### ISSUE TITLE
在编译项目时，由于定制化的setting.gradle导致了编译的失败

### ISSUE THREAD

**Issue by Jacksgong** [alibaba/freeline#1]
#### 感谢你们的开源，很赞的项目~ 👍 

我们项目中对`setting.gradle`进行了定制，因此里面并非是一系列的`module`名，而是`groovy`代码，通过`groovy`代码加载出需要引入项目的module。因此在使用freeline编译项目的时候出现了错误。

错误日志: 
[16-08-12 13:42:16.log.zip](https://github.com/alibaba/freeline/files/415229/16-08-12.13.42.16.log.zip)

> P.S: 希望能够有一个解决方案，或者是有接口或命令参数能够给freeline指定提供直接包含module的文件也行。

**Comment by lomanyong** [comment]
Thanks for your feedback, we will support this feature soon.

**Comment by lomanyong** [comment]
@Jacksgong 可以更新下gradle插件版本：

````gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.antfortune.freeline:gradle:0.5.1'
    }
}
````

重新执行：`./gradlew initFreeline`

验证下是否还会存在以上问题

**Comment by Jacksgong** [comment]
恩。好的。谢谢啦。

**Comment by Jacksgong** [comment]
我这边测试，0.5.1 这个问题确实已经解决了~。多谢啦！
