### ISSUE TITLE
执行完./gradlew initFreeline 在执行python freeline.py -f （mac）

### ISSUE THREAD

**Issue by fearlesstrek** [alibaba/freeline#100]
<img width="307" alt="1" src="https://cloud.githubusercontent.com/assets/12731121/18307478/461cb436-7523-11e6-83b8-fbaea4bdba1e.png">

一直这样准备不动

**Comment by fearlesstrek** [comment]
在as上打开一个bat文件，提示我缺少plugin，然后装完这个plugin，重新执行上面两行命令又跑成功了

**Comment by charvenhe** [comment]
@fearlesstrek 好的，可以多在你们项目试试
