### ISSUE TITLE
minifyEnabled=true 时获取不到依赖

### ISSUE THREAD

**Issue by muyiou** [alibaba/freeline#102]
jar_dependencies依赖JarMergingTransform，JarMergingTransform依赖 minifyEnabled=false，所以如果配置了minifyEnabled=true，hack class和jar_dep都会获取失败

**Comment by lomanyong** [comment]
@muyiou  freeline需要`minifyEnabled=false`的，混淆这些都需要关掉。我们之后也在文档中具体体现吧~
