### ISSUE TITLE
ReactNative跑一下87秒, 算快么?

### ISSUE THREAD

**Issue by wv1124** [alibaba/freeline#104]
> python freeline.py
[WARNING] NoInstallationException occurs, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 12.3s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] finished. in 56.8s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 5.4s
[-][build_base_resource_task] finished. in 4.6s
[-][generate_project_info_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 12.9s
[DEBUG] Task engine running time: 74.5s
[DEBUG] Total time: 87.4s
[DEBUG] --------------------------------------------------------

**Comment by charvenhe** [comment]
@wv1124 这个是首次全量编译，改个文件再运行一次python freeline.py试试

**Comment by wv1124** [comment]
wv@iMac-WV  ~/work/d2papp/src/master/android   master ●  python freeline.py
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.2s
[-][gradle_aapt_task] finished. in 0.0s
[-][react-native-image-picker] finished. in 0.0s
[-][ReactAndroid] finished. in 0.0s
[-][react-native-code-push] finished. in 0.0s
[-][ReactNativeBarcodescanner] finished. in 0.0s
[-][app] finished. in 1.5s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] finished. in 0.0s
[-][clean_cache_task] finished. in 0.0s
[-][update_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 1.6s
[DEBUG] Total time: 1.7s
[DEBUG] --------------------------------------------------------


嗯, 搞错了, 以为initFreeLine是第一次
