### ISSUE TITLE
可以打Release包么?

### ISSUE THREAD

**Issue by wv1124** [alibaba/freeline#105]
可以打Release包么?

**Comment by lomanyong** [comment]
可以的，之后我们会加入到README中：

````gradle
debugCompile 'com.antfortune.freeline:runtime:0.6.0'
releaseCompile 'com.antfortune.freeline:runtime-no-op:0.6.0'
````

这个可以不影响你们打release包。

**Comment by wv1124** [comment]
`
dependencies {
    ...
    debugCompile 'com.antfortune.freeline:runtime:0.6.0'
    releaseCompile 'com.antfortune.freeline:runtime-no-op:0.6.0'
}
`

加了, 还是只有Debug包, 打Release还是只能用原来的方式么? 不能python freeline.py

**Comment by lomanyong** [comment]
@wv1124 打release包当然用你们原来的方式啦~`releaseCompile 'com.antfortune.freeline:runtime-no-op:0.6.0'`，主要是不影响你们原本app的运行，不影响你们打出的release包的使用。

**Comment by wv1124** [comment]
谢谢!
