### ISSUE TITLE
运行python freeline.py的时候报错： Freeline ERROR,  Please make sure your application is properly running in your device.

### ISSUE THREAD

**Issue by BlackMagicHappy** [alibaba/freeline#108]
在运行脚本 python freeline.py的时候，命令行重试了24秒，之后报错：

[DEBUG] [sync_client] apktime path: F:\17.MusicClient\Android\Music\MusicUI\Music_MTN\MusicUI_MTN\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 960000
[DEBUG] [sync_client] your local uuid value is: d4e0402209cd5cc4bd00c0e2b99116cf
[DEBUG] [sync_client] try to connect device 23 times...
[DEBUG] [sync_client] apktime path: F:\17.MusicClient\Android\Music\MusicUI\Music_MTN\MusicUI_MTN\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 960000
[DEBUG] [sync_client] your local uuid value is: d4e0402209cd5cc4bd00c0e2b99116cf
[DEBUG] [sync_client] try to connect device 24 times...
[DEBUG] [sync_client] package com.mtn.softclient.music.baseline not found. Please make sure your application is properly running in your device, freeline will start a clean build
[DEBUG] [connect_device_task] connect_device_task finish in 40.5s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 40.5s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 40.5s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 40.5s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 40.52s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package com.mtn.softclient.music.baseline is not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 5.3s
[DEBUG] Task engine running time: 40.5s
[DEBUG] Total time: 45.9s

—————————————————————————————————————————————

但是我运行adb shell pm list packages com.mtn.softclient.music.baseline的时候是有这个程序的：
F:\17.MusicClient\Android\Music\MusicUI\Music_MTN>adb shell pm list packages com.mtn.softclient.music.baseline
adb server is out of date.  killing...
* daemon started successfully *
package:com.mtn.softclient.music.baseline

_____________________________________________________________________________________________________________
此问题困扰了我很久，请帮忙看一下，非常感谢@！！

**Comment by lomanyong** [comment]
@BlackMagicHappy Application类中是否`FreelineCore.init(this);`执行了呢？以及可以看下，logcat里是否有freeline相关的日志输出。

**Comment by BlackMagicHappy** [comment]
Search "freeline" (24 hits in 1 file)
  new  12 (24 hits)
	Line 959: 09-08 17:49:55.903: I/Freeline(13319): freeline start initial process...
	Line 959: 09-08 17:49:55.903: I/Freeline(13319): freeline start initial process...
	Line 960: 09-08 17:49:55.913: I/Freeline(13319): freeline init application
	Line 960: 09-08 17:49:55.913: I/Freeline(13319): freeline init application
	Line 961: 09-08 17:49:55.913: I/Freeline(13319): start to inject dex...
	Line 962: 09-08 17:49:55.913: I/Freeline(13319): start to inject resources...
	Line 963: 09-08 17:49:55.913: I/Freeline(13319): dynamicInfoSp: {}
	Line 964: 09-08 17:49:55.913: I/Freeline(13319): resMap: {}
	Line 965: 09-08 17:49:55.913: I/Freeline(13319): start to load hackload.dex...
	Line 966: 09-08 17:49:55.913: I/Freeline.hackDex(13319): /data/data/com.mtn.softclient.music.baseline/cache/hack/hackload.dex dex length: 848
	Line 967: 09-08 17:49:55.913: I/Freeline.hackDex(13319): /data/data/com.mtn.softclient.music.baseline/cache/hack/opt opt length: 4096
	Line 968: 09-08 17:49:55.923: I/Freeline.hackDex(13319): after opt, dex len:848; opt len:4096
	Line 969: 09-08 17:49:55.923: I/Freeline(13319): load hackload，dex size:848
	Line 970: 09-08 17:49:55.923: I/Freeline(13319): start to inject native lib...
	Line 971: 09-08 17:49:55.923: I/Freeline.hackNative(13319): native lib inject process start...
	Line 972: 09-08 17:49:55.923: I/Freeline.hackNative(13319): inject native lib success [Ljava.io.File;@194aef50
	Line 973: 09-08 17:49:55.923: I/Freeline(13319): freeline init server
	Line 973: 09-08 17:49:55.923: I/Freeline(13319): freeline init server
	Line 976: 09-08 17:49:55.963: I/ActivityManager(1037): Start proc com.mtn.softclient.music.baseline:freeline for service com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService: pid=13406 uid=11186 gids={51186, 9997, 1028, 1015, 3003} abi=armeabi
	Line 976: 09-08 17:49:55.963: I/ActivityManager(1037): Start proc com.mtn.softclient.music.baseline:freeline for service com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService: pid=13406 uid=11186 gids={51186, 9997, 1028, 1015, 3003} abi=armeabi
	Line 976: 09-08 17:49:55.963: I/ActivityManager(1037): Start proc com.mtn.softclient.music.baseline:freeline for service com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService: pid=13406 uid=11186 gids={51186, 9997, 1028, 1015, 3003} abi=armeabi
	Line 983: 09-08 17:49:56.023: I/Freeline(13373): freeline start initial process...
	Line 983: 09-08 17:49:56.023: I/Freeline(13373): freeline start initial process...
	Line 1011: 09-08 17:49:56.123: D/MusicApplication(13406): isBaiduPushProcess processName:com.mtn.softclient.music.baseline:freeline

**Comment by BlackMagicHappy** [comment]
我重新运行了python freeline.py, 把日志过滤“freeline”的地方，显示如上。

**Comment by lomanyong** [comment]
@BlackMagicHappy 手机或者电脑上是否开了全局代理呢？

或者手动执行一下`adb shell am startservice -n com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService`，然后再`python freeline.py`，看下是否正常。

**Comment by lomanyong** [comment]
@BlackMagicHappy 日志中似乎还少了一句`Freeline.increment server running on port xxxx`，这句日志是说明socket server已经启动的。

**Comment by charvenhe** [comment]
@BlackMagicHappy 尝试下0.6.1版本，更换版本后，重新./gradlew initFreeline，再试试

**Comment by BlackMagicHappy** [comment]
@lomanyong ，手动执行一下adb shell am startservice -n com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService的时候报错：


F:\17.MusicClient\Android\Music\MusicUI\Music_MTN>adb shell am startservice -n com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService
adb server is out of date.  killing...
* daemon started successfully *
Starting service: Intent { cmp=com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService }
Error: Requires permission not exported from uid 10737

**Comment by BlackMagicHappy** [comment]
@charvenhe 我升级了0.6.1版本，运行脚本：python freeline.py -f 是可以的。但是运行python freeline.py还是不行，好像重试24秒之后报错：

————————————————————————————————————————————

[DEBUG] [sync_client] apktime path: F:\17.MusicClient\Android\Music\MusicUI\Music_MTN\MusicUI_MTN\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 451000
[DEBUG] [sync_client] your local uuid value is: 451000
[DEBUG] [sync_client] try to connect device 20 times...
[DEBUG] [sync_client] wake up Service: E:\88.AndoirdStudio\Android_SDK\platform-tools\adb.exe shell am startservice -n com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: F:\17.MusicClient\Android\Music\MusicUI\Music_MTN\MusicUI_MTN\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 451000
[DEBUG] [sync_client] your local uuid value is: 451000
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 52.6s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 52.6s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 52.64s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package com.mtn.softclient.music.baseline is not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 52.6s
[DEBUG] Total time: 52.9s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@BlackMagicHappy 手动执行`E:\88.AndoirdStudio\Android_SDK\platform-tools\adb.exe shell am startservice -n com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService -e wakeup marker`会报错对吧？

这个我再打个版本出来，看下是否能解决这个问题。

@BlackMagicHappy logcat中是否有`Freeline.increment server running on port xxxx`类似这句的日志呢？

**Comment by BlackMagicHappy** [comment]
@lomanyong 

我运行脚本：python freeline.py -f的时候提取了相关freeline的日志如下：

里面是有running on port的日志的：
Freeline.increment server running on port 41128

——————————————————————————————————————
Line 2013: 09-09 10:31:39.441: I/Freeline(21351): freeline start initial process...
	Line 2013: 09-09 10:31:39.441: I/Freeline(21351): freeline start initial process...
	Line 2014: 09-09 10:31:39.441: I/Freeline(21351): freeline init application
	Line 2014: 09-09 10:31:39.441: I/Freeline(21351): freeline init application
	Line 2019: 09-09 10:31:39.441: I/Freeline(21351): start to inject dex...
	Line 2020: 09-09 10:31:39.441: I/Freeline(21351): start to inject resources...
	Line 2021: 09-09 10:31:39.441: I/Freeline(21351): dynamicInfoSp: {}
	Line 2022: 09-09 10:31:39.441: I/Freeline(21351): resMap: {}
	Line 2023: 09-09 10:31:39.441: I/Freeline(21351): start to load hackload.dex...
	Line 2024: 09-09 10:31:39.441: I/Freeline.hackDex(21351): /data/data/com.mtn.softclient.music.baseline/cache/hack/hackload.dex dex length: 848
	Line 2025: 09-09 10:31:39.441: I/Freeline.hackDex(21351): /data/data/com.mtn.softclient.music.baseline/cache/hack/opt opt length: 4096
	Line 2027: 09-09 10:31:39.451: I/Freeline.hackDex(21351): after opt, dex len:848; opt len:4096
	Line 2028: 09-09 10:31:39.451: I/Freeline(21351): load hackload，dex size:848
	Line 2029: 09-09 10:31:39.451: I/Freeline(21351): start to inject native lib...
	Line 2030: 09-09 10:31:39.451: I/Freeline.hackNative(21351): native lib inject process start...
	Line 2031: 09-09 10:31:39.451: I/Freeline.hackNative(21351): inject native lib success [Ljava.io.File;@2ce8612f
	Line 2032: 09-09 10:31:39.451: I/Freeline(21351): freeline init server
	Line 2032: 09-09 10:31:39.451: I/Freeline(21351): freeline init server
	Line 2037: 09-09 10:31:39.461: D/ActivityManager(3797): retrieveServiceLocked(): component = com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService; callingUser = 0; userId(target) = 0
	Line 2037: 09-09 10:31:39.461: D/ActivityManager(3797): retrieveServiceLocked(): component = com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService; callingUser = 0; userId(target) = 0
	Line 2056: 09-09 10:31:39.491: I/ActivityManager(3797): Start proc com.mtn.softclient.music.baseline:freeline for service com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService: pid=21636 uid=10737 gids={50737, 9997, 1028, 1015, 3003} abi=armeabi
	Line 2056: 09-09 10:31:39.491: I/ActivityManager(3797): Start proc com.mtn.softclient.music.baseline:freeline for service com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService: pid=21636 uid=10737 gids={50737, 9997, 1028, 1015, 3003} abi=armeabi
	Line 2056: 09-09 10:31:39.491: I/ActivityManager(3797): Start proc com.mtn.softclient.music.baseline:freeline for service com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService: pid=21636 uid=10737 gids={50737, 9997, 1028, 1015, 3003} abi=armeabi
	Line 2084: 09-09 10:31:39.541: I/Freeline(21549): freeline start initial process...
	Line 2084: 09-09 10:31:39.541: I/Freeline(21549): freeline start initial process...
	Line 2218: 09-09 10:31:39.701: D/MusicApplication(21636): isBaiduPushProcess processName:com.mtn.softclient.music.baseline:freeline
	Line 2680: 09-09 10:31:40.081: I/Freeline(21636): freeline start initial process...
	Line 2680: 09-09 10:31:40.081: I/Freeline(21636): freeline start initial process...
	Line 2688: 09-09 10:31:40.081: I/Freeline.Service(21636): onStartCommand Received start id 1, intent: Intent { cmp=com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService }
	Line 2688: 09-09 10:31:40.081: I/Freeline.Service(21636): onStartCommand Received start id 1, intent: Intent { cmp=com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService }
	Line 2688: 09-09 10:31:40.081: I/Freeline.Service(21636): onStartCommand Received start id 1, intent: Intent { cmp=com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService }
	Line 2689: 09-09 10:31:40.081: D/Freeline.LongLinkServer(21636): Freeline.increment server running on port 41128
	Line 2689: 09-09 10:31:40.081: D/Freeline.LongLinkServer(21636): Freeline.increment server running on port 41128

**Comment by BlackMagicHappy** [comment]
@lomanyong 

手动执行E:\88.AndoirdStudio\Android_SDK\platform-tools\adb.exe shell am startservice -n com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService -e wakeup marker确实也会报错：
——————————————————————————————————————————————

F:\17.MusicClient\Android\Music\MusicUI\Music_MTN>E:\88.AndoirdStudio\Android_SDK\platform-tools\adb.exe shell am startservice -n com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService -e wakeup marker
Starting service: Intent { cmp=com.mtn.softclient.music.baseline/com.antfortune.freeline.FreelineService (has extras) }
Error: Requires permission not exported from uid 10737

**Comment by lomanyong** [comment]
@BlackMagicHappy 收到。可以麻烦检查一下是否在电脑上/手机上开了全局代理吗？

那个报错的问题，我下午打个版本可以再试试看。

**Comment by BlackMagicHappy** [comment]
@lomanyong 
全局代理?  这个怎么开？或者怎么检查呢？我一般都没有用过这个，手机Wifi里面可以配置代理，我确定里面已经被关掉了。

**Comment by lomanyong** [comment]
@BlackMagicHappy 比如shadowsocks的全局代理，会导致`127.0.0.1`这个ip无法被正常当做local ip来使用。

**Comment by shenquan** [comment]
和他遇到了相同的问题

**Comment by BlackMagicHappy** [comment]
@lomanyong 我这边没有使用代理

@shenquan 你那边问题有进展跟我说说吧，非常感谢了！

**Comment by chris-sharl** [comment]
同样的问题了。。
我这边是第一次运行python freeline.py可以正常编译以及安装，之后再运行python freeline.py会长时间执行connect_device_task，然后过会报这个错

**Comment by chris-sharl** [comment]
这个问题在我这边已经解决了。。
在我们的app里可能会有多个进程，所以我们有多个初始化方法，分别是initMainProcess,initOtherProcess,initAlways。。
我之前是在initMainProcess里执行的freeline的初始化，状况就是一直失败。。
后来改在initOtherProcess执行，一样。。
最后改在initAlways里执行，然后就ok了。。

**Comment by charvenhe** [comment]
@chris-sharl 你这边的问题是指的是所有进程都调用一次Freeline.init就成功了吗

**Comment by gitsteven** [comment]
我也遇到了相同的问题。 解决如下：
1， 没有vpn 什么的设置。手机与电脑都没有。
2， 我执行：adb shell am startservice -n  scadaems.pilot.com.testsimplehello/com.antfortune.freeline.FreelineService -e wakeup marker 

在logcat 中看到 ： Starting service: Intent { cmp=scadaems.pilot.com.testsimplehello/com.antfortune.freeline.FreelineService (has extras) }
Error: Requires permission not exported from uid 10255

所以在 androidmanifest.xml 中加入这个 ：  <service android:name="com.antfortune.freeline.FreelineService" android:exported="true"></service>

3，然后继续logcat 看到 FreelineService port 启动了。

4， 继续python freeline。py ，还是不行。

继续查看logcat 日志如下： 09-09 22:25:16.950 10105-10131/scadaems.pilot.com.testsimplehello:freeline I/Freeline.CheckSync: check uuid failed, skip check sync.
直接继续看源代码
 定位到 FreelineCore.getUuid(); 这个方法 ，发现返回的是 “dfsfsfxx”的 字符串，但是了，继续看
python 文件 sync_client.py  103 ,发现他 的请求地址为： 
  url = 'http://127.0.0.1:{}/checkSync?sync={}&uuid={}'.format(41128 + i, sync_value, uuid) 但是这个uuid 为 整形的。 所以直接改这样的代码 ，  url = 'http://127.0.0.1:{}/checkSync?sync={}&uuid={}'.format(41128 + i, sync_value, '465d21524f1a230ea2286e4ffca837bf')
就可以了。

5， 原因就是这样了。看了下代码提交记录，感觉是版本混淆了。因为看到有些 java 是把整形md5了一下，但是python 端的代码就是 整形，没有md5吗 ？

**Comment by lomanyong** [comment]
@gitsteven `python freeline.py -v`看下版本，以及跟你在build.gradle中引入的版本是否一致？

**Comment by gitsteven** [comment]
是0.6.2 ，奇怪了，昨天电脑上就可以运行，今天就不行。看了下 android 代码配置是0.6.0 。 昨天可以运行，今天就不行了。 直接翻代码，看了一遍。也算是了解了一下代码，感觉代码不错。学了很多东西，但是没有注释，看着很吃力。 就楞不明白这个  http://127.0.0.1:{}/checkSync?sync={}&uuid={}'. 这个是干什么的？

**Comment by charvenhe** [comment]
@gitsteven 把运行期build.gradle更新到0.6.2再试试，这个版本号是要配套使用的

**Comment by lomanyong** [comment]
@gitsteven checkSync这个是freeline的基线对齐机制使用的。每次socket连接都会先进行基线校验，保证手机上的apk与本地的代码是基于同一份改动的。如果校验失败，就会自动重新打全量。

**Comment by gitsteven** [comment]
@lomanyong , 看了下代码，就是说 apps 和 pc 端简历一个http 连接，可以通过这个连接来增量 打包，速度确实快。 这个东西很好用。有没有机会pull request 一下？ 或者 参与进来你们的开发的要什么要求？

**Comment by lomanyong** [comment]
@gitsteven 恩，差不多是这么理解的。

非常欢迎提交pr~如果你有什么想法或者改进的话都可以修改了，然后给我们提pr。如果有大feature的话，也欢迎提出issue来一起交流~

**Comment by BlackMagicHappy** [comment]
@lomanyong 我今天更新0.6.3版本之后就好了，能够不报重试的错误，问题可以关闭了。

**Comment by ohmerhe** [comment]
[DEBUG] [sync_client] your local sync value is: 245283
[DEBUG] [sync_client] your local uuid value is: 245283
[DEBUG] [sync_client] try to connect device 21 times...
[DEBUG] [sync_client] wake up Service: /Users/ohmer/sdk/platform-tools/adb shell am startservice -n com.hujiang.normandy/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: /Users/ohmer/Projects/Android/android_study/normandy/build/freeline/freeline-assets/apktime

我用的 0.6.3 的版本，添加 -f 能够正常运行，python freeline.py 运行连接不上，我这里应该没有走代理

**Comment by lomanyong** [comment]
@ohmerhe 看下logcat的日志，是否有freeline的日志呢？

**Comment by 390467556** [comment]
@lomanyong 我这边现在也是这个问题
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] try to connect device 1 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 2 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 3 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 4 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 5 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 6 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 7 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 8 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 9 times...
[DEBUG] [sync_client] wake up Service: /Users/wangzhe/Library/Android/sdk/platform-tools/adb shell am startservice -n com.sdu.didi.psnger/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 10 times...
[DEBUG] [sync_client] Freeline server in app com.sdu.didi.psnger not found. Please make sure your application is properly running in your device.


手动adb shell start service，是成功的，但是再用python去执行，还是一样连接不上设备
