### ISSUE TITLE
修改项目project.buildDir导致file not found问题

### ISSUE THREAD

**Issue by weiyixiong** [alibaba/freeline#11]
因为我们的项目修改了project.buildDir，导致freeline读取module下的build文件夹发生找不到的异常

**Comment by lomanyong** [comment]
@weiyixiong 可以贴一下报错的日志吗？可以`python freeline.py -d`输出更详细的日志看看

**Comment by weiyixiong** [comment]
[DEBUG] [install_apk_task] install_apk_task finish in 15.5s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 130.71s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

-resoucres-md5-cache-path = /Users/winney/Documents/Tiger/android/build/myapp/freeline/arsc_cache.dat
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
/Users/winney/Documents/Tiger/android/modules/myapp/build/intermediates/manifests/full/dev/debug/AndroidManifest.xml: error: Unable to open file for read: No such file or directory

谢谢

**Comment by lomanyong** [comment]
@weiyixiong 修改`project.buildDir`导致的这个问题确实是兼容性问题，这周会解决这个兼容性bug，多谢提出问题~
