### ISSUE TITLE
databinding支持

### ISSUE THREAD

**Issue by yangwuan55** [alibaba/freeline#110]
之前的issues为何都关了啊？希望尽快支持databinding。

**Comment by lomanyong** [comment]
@yangwuan55 当时应该是当做编译错误关掉了，我加个`enhancement`的label。

**Comment by yangwuan55** [comment]
QQQ

**Comment by kexuejin** [comment]
到现在还没支持啊？？？

**Comment by lomanyong** [comment]
@kexuejin 最近已经支持了lambda跟注解了。databinding还比较复杂，正在研究增量编译的思路中。

**Comment by yangwuan55** [comment]
遥遥无期了

**Comment by lomanyong** [comment]
@yangwuan55 @kexuejin 0.8.0将会支持DataBinding，再经过一些测试和bug修复后，预计下周正式升级。

See PR #246 for more details.

**Comment by yangwuan55** [comment]
喜大普奔

**Comment by lomanyong** [comment]
@yangwuan55 @kexuejin 已经升级0.8.0，可以使用试试看了。

由于DataBinding本身编译实现的限制，编译的时候速度会比非DataBinding的工程来的慢点。后面我们会考虑改造一下compiler。
