### ISSUE TITLE
使用0.6.1版本出现了这个pyhon freeline.py报错

### ISSUE THREAD

**Issue by q624228096** [alibaba/freeline#111]
````
Caused by: org.gradle.api.GradleException: F:\daima\6.20.c\android_2\CtripMain\b
uild\intermediates\assets\debug\apktime file not found.
Missing the `productFlavor` configuration?
You can try to add `productFlavor` to freeline DSL, for example:

  freeline {
      hack true
      productFlavor 'your-flavor'
  }

Then re-run `python freeline.py` again.

        at com.antfortune.freeline.FreelinePlugin$_addFreelineGeneratedFiles_clo
sure4.doCall(FreelinePlugin.groovy:244)
        at com.antfortune.freeline.FreelinePlugin.addFreelineGeneratedFiles(Free
linePlugin.groovy:239)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure3_closure7_closu
re10.doCall(FreelinePlugin.groovy:86)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:535)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
````

**Comment by lomanyong** [comment]
````
Missing the `productFlavor` configuration?
You can try to add `productFlavor` to freeline DSL, for example:

  freeline {
      hack true
      productFlavor 'your-flavor'
  }

Then re-run `python freeline.py` again.
````

@q624228096 已经给了提示了呀，照着提示修改一下freeline DSL，增加一下配置项就行了~

**Comment by smallobserver** [comment]
我也遇到了同样的问题   freeline dsl 在哪修改 这段代码 放在哪里呀

**Comment by lomanyong** [comment]
@smallobserver README里有，在 application module 的build.gradle里：

````gradle
android {
    ...
    freeline {
        hack true
        productFlavor 'your-flavor'
    }
}
````

**Comment by smallobserver** [comment]
@lomanyong   我尝试过的哦   一开始就尝试过  然后除了这个错
* What went wrong:
Execution failed for task ':checkBeforeCleanBuild'.
>  invalid productFlavor : your-flavor

更改 your-flavor之后
* What went wrong:
Execution failed for task ':checkBeforeCleanBuild'.
>  invalid productFlavor : productFlavors

**Comment by lomanyong** [comment]
额，`your-flavor`要替换成你真正的flavor...

**Comment by smallobserver** [comment]
@lomanyong  我换成了 debug上使用的渠道    没有报错了  但是 一直在 执行
[+][gradle_clean_build_task] running... 
已经700多s了

**Comment by lomanyong** [comment]
@smallobserver 第一次编译其实际上调用的就是你们的 gradle 编译命令...耗时跟你们全量编译耗时差不多...

如果你想看下为什么耗时这么久的话，可以手动执行一下：`gradlew assemble{your-flavor}Debug -PfreelineBuild=true`，跟freeline全量打包的命令一致。

**Comment by smallobserver** [comment]
@lomanyong 谢谢 麻烦了

**Comment by Huyamin150** [comment]
@smallobserver我也是十分钟停不下来，请问你怎么解决的

**Comment by Huyamin150** [comment]
@lomanyong  0.81的版本跑了十几分钟了还是在build，也不报错

**Comment by lomanyong** [comment]
@Huyamin150 上文已经有提到排查方法，你可以自己先试试看

**Comment by weiyanjie** [comment]
@lomanyong 不知道flavor是什么是不是太low了

**Comment by lomanyong** [comment]
@weiyanjie google一下就知道了..

**Comment by binqiangsun** [comment]
加了productFlavors 提示错误： 

 invalid productFlavor : lk

**Comment by binqiangsun** [comment]
* What went wrong:
Execution failed for task ':checkBeforeCleanBuild'.
>  invalid productFlavor : your-flavor

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
