### ISSUE TITLE
能不能只做编译打包，不在手机上运行呢？

### ISSUE THREAD

**Issue by BlackMagicHappy** [alibaba/freeline#112]
我想把freeline集成到持续集成里去，我们的持续集成环境不连手机，只做编译打包，请问freeline是否可以支持这个需求呢？

**Comment by lomanyong** [comment]
````gradle
dependencies {
    debugCompile 'com.antfortune.freeline:runtime:0.6.1'
    releaseCompile 'com.antfortune.freeline:runtime-no-op:0.6.1'
    testCompile 'com.antfortune.freeline:runtime-no-op:0.6.1'
}
````

**Comment by lomanyong** [comment]
@BlackMagicHappy 可以这样做，有`runtime-no-op`可以完成你的这个需求。

**Comment by BlackMagicHappy** [comment]
@lomanyong  脚本还是python freeline.py -f？
我运行python freeline.py -f 报错：
——————————————————————————————————————
[DEBUG] [build_base_resource_task] build_base_resource_task finish in 4.2s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 71.36s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Use `adb devices` to check your device connection
[ERROR] --------------------------------------------------------
[ERROR] No device's connection found
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 71.4s
[DEBUG] Total time: 71.5s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@BlackMagicHappy 手机没有连接到笔记本上吧？

**Comment by BlackMagicHappy** [comment]
@lomanyong 是的，持续集成的环境只做编译打包，也无法连接手机的。freeline是否支持这种不连接手机的情况下，进行编译打包呢？

**Comment by lomanyong** [comment]
@BlackMagicHappy 你是指在集成环境使用`python freeline.py -f`吗？

**Comment by BlackMagicHappy** [comment]
@lomanyong  是的，想把freeline集成到持续集成环境，在持续集成环境上实现快速出包，持续集成环境没法连接手机，freeline是否支持这种不连接手机的情况下，进行编译打包呢？

**Comment by lomanyong** [comment]
@BlackMagicHappy `python freeline.py -f`这个指令本质上只是使用了`./gradlew assemblexxx`的命令而已，跟你们集成环境打包没有太大的差异。最好不要集成到集成环境中，集成环境仍旧使用你们自己的打包指令即可。

**Comment by BlackMagicHappy** [comment]
@lomanyong 就是说暂时freeline不支持在没有连接手机的环境跑了？我很想把这种快速编译打包的好东西用到持续集成里去。

**Comment by lomanyong** [comment]
@BlackMagicHappy 额，freeline对于全量打包并没有很好的加速作用的，他的主要加速在于增量编译的时候。集成环境下的打包，最好还是使用你们日常的打包命令，可以保证freeline的相关生成产物，不影响你们最终的打包结果。

**Comment by BlackMagicHappy** [comment]
@lomanyong 我看https://yq.aliyun.com/articles/59122这里介绍了有多任务并发的功能，而我实际运行来看，也能把打包时间缩短一倍: 采用gradle build脚本跑需要3分钟才能把包出出来，但是使用python freeline.py的时候只需要1分多钟，所以我才有把freeline集成到持续集成的想法，但是目前来看阻塞在必须连接手机这里。
