### ISSUE TITLE
代码中aapt实现的几个问题

### ISSUE THREAD

**Issue by muyiou** [alibaba/freeline#113]
在aapt的处理过程中并没有看到对ids.xml的使用，这个文件是用来干嘛的？

另外，res的增量编译是不是只在art下面才能使用？

**Comment by charvenhe** [comment]
@muyiou 1.ids.xml 主要用于与public.xml配合固定运行期id
2.res 在4.x是全量替换，速度会比5.x慢些

**Comment by muyiou** [comment]
没有太明白为什么还需要ids.xml来确定运行时id，public.xml不就可以了吗？
是为了提高速度吗？

另外好像没有看到直接处理ids.xml的逻辑

**Comment by charvenhe** [comment]
public.xml里面的id，不一定全来自开发环境的res，如果没有导出一份ids.xml，则aapt编译会报id not found的问题

**Comment by muyiou** [comment]
aapt怎么知道ids的文件在哪里？

**Comment by charvenhe** [comment]
@muyiou给aapt入参里面有带上ids所在目录

**Comment by muyiou** [comment]
@charvenhe 貌似在5.0以下aapt执行的时候并没有把ids传递进去

**Comment by charvenhe** [comment]
你指的是buildIncrement后面的参数吧，这个是在5.x之后做资源增量才会用到，ids所在的目录是在buckup目录，都有传进去的

**Comment by muyiou** [comment]
sorry 看到了
