### ISSUE TITLE
jar包冲突

### ISSUE THREAD

**Issue by StriverYong** [alibaba/freeline#114]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/android/tools/fd/runtime/MonkeyPatcher;

**Comment by lomanyong** [comment]
@StriverYong 你们应用中引入了同样的类吗？麻烦看下？

**Comment by lomanyong** [comment]
@StriverYong 可以将runtime使用这个版本：`com.antfortune.freeline:runtime:0.6.1.1609091717`，然后重新编译试试看，是否还会出现这个报错。

**Comment by lomanyong** [comment]
@StriverYong runtime版本`com.antfortune.freeline:runtime:0.6.2`已经修复了这个问题，欢迎尝试~
