### ISSUE TITLE
首次运行报 [build_base_resource_task] failed. 错误

### ISSUE THREAD

**Issue by victorygao** [alibaba/freeline#115]
首次运行时报错了，出现很多的 invalid resource directory 日志输出，例如：

invalid resource directory name: /Users/user/Android/studio-workspace/project/app/src/main/res/drawable-xhdpi header_bg_left_night_n.9.png

接着的日志输出如下：

[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/xxx/Library/Android/sdk/platforms/android-23/android.jar -M /Users/xxx/Android/studio-workspace/project/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/xxx/Android/studio-workspace/project/app/src/main/res -S /Users/xxx/Android/studio-workspace/project/app/src/main/res/drawable-xhdpi -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.6.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android/1.4-beta2/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.android.support/support-v4/23.1.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.github.chrisbanes.photoview/library/1.2.4/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.android.support/cardview-v7/23.1.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.1.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.1.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.android.support/design/23.1.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.third/baidu-tongji-user-profile/3.7.4.2-1.5/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.third/ali-push/2.2.0/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.third/mi-push/2.2.18/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.third/share-sdk/2.7.4.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-core-jni/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.mucang.framework/core/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.mucang.framework/android-pay/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.andreabaccega/android-form-edittext/1.2.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.mucang.business/wallet/1.0-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.tencent.bugly/crashreport/2.2.2/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.github.itsmechlark/android-sliding-menu/1.0.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.makeramen/roundedimageview/2.2.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-jifen/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.felipecsl/gifimageview/2.0.0/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/moon/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-advert/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/it.sephiroth.android.library.easing/android-easing/1.0.3/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-select-car/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.third/baidu-maps-location/3.6.0-6a/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-im/6.5-refactor-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.aigestudio.wheelpicker/WheelPicker/1.0.3/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-ffmpeg/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-media/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.third/percent/23.0.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/saturn-core/6.5-refactor-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/saturn-baojiazhijia/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.maichebaodian/libapi-mcbd/6.5.2-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-optimuslib/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-optimus/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/comment-core/6.5-anonymous-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/qichetoutiao-lib-ui/6.5.2-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/qichetoutiao-lib-video/6.5.2-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/saturn-venus/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-qichetoutiao/6.5.2-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.maichebaodian/lib-mcbd/6.5.2-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-feedback/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/tufumall-api/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/tufumall/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.qichebaojia/bitauto-core/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/android-busybox/6.5-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/cn.mucang.android.framework/saturn-jiakao/6.5-refactor-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.sothree.slidinguppanel/library/3.2.0/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.handsgo.jiakao.android/jiakao-db/201608161428-SNAPSHOT/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.bartoszlipinski.recyclerviewheader/library/1.2.0/res -S /Users/xxx/Android/studio-workspace/project/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/xxx/Android/studio-workspace/project/app/build/generated/res/rs/debug -S /Users/xxx/Android/studio-workspace/project/app/build/generated/res/resValues/debug -S /Users/xxx/Android/studio-workspace/project/app/build/freeline/app/backup/res -A /Users/xxx/Android/studio-workspace/project/app/build/freeline/freeline-assets -A /Users/xxx/Android/studio-workspace/project/app/src/main/assets -m -J /Users/xxx/Android/studio-workspace/project/app/build/freeline/app/backup --auto-add-overlay -F /Users/xxx/Android/studio-workspace/project/app/build/freeline/base-res.so --debug-mode --resoucres-md5-cache-path /Users/xxx/Android/studio-workspace/project/app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*

求大神帮解决~

**Comment by charvenhe** [comment]
@victorygao 麻烦把invalid resource directory相关的都贴出来看看。

**Comment by lomanyong** [comment]
@victorygao 可以升级freeline到`0.6.3`，然后执行`./gradlew initFreeline -PfreelineVersion=0.6.3.1609131546`。然后再看下是否还有这个问题。

**Comment by charvenhe** [comment]
@victorygao 你好，我们针对这个情况进行了优化，像@lomanyong上面说的

如果还有问题，加我们微信群我们单独跟进看看
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)
