### ISSUE TITLE
不支持断点？

### ISSUE THREAD

**Issue by qq1728744610** [alibaba/freeline#128]
打了断点，运行到断点处没停下来

**Comment by lomanyong** [comment]
@qq1728744610 freeline支持断点的。我这边重新测了一遍，这些都没有问题，可以再试试看？

**Comment by qq1728744610** [comment]
@lomanyong 打了断点后，运行python freeline.py, 需要加其他参数吗？

**Comment by lomanyong** [comment]
@qq1728744610 不需要的，正常执行就行了。

**Comment by zxsr20** [comment]
attach device 即可
