### ISSUE TITLE
希望freeline可以增加参数使得不影响正常的debug编译

### ISSUE THREAD

**Issue by zzz40500** [alibaba/freeline#13]
当使用as直接run的时候 freeline 不会对我的生成物有影响, 只有使用python 命令的时候才会对我的生成物有影响，因为有时候用户的环境是比较复杂的，当出现一个bug 的时候， 他可以直接用run编译项目， 排除所有freeline 可能对项目的影响。而不需要编辑 build.gradle里面的内容。

**Comment by charvenhe** [comment]
感谢提议，我们尽快完善

**Comment by zzz40500** [comment]
我的想法是在python 的执行 build_script 的时候携带一个参数freeline ， 如果gradle插件中获取这个属性为true 并且freeline 中的hack也为true，才会执行才会执行一系列动作。

**Comment by lomanyong** [comment]
@zzz40500 恩，我review了一下代码，之前觉得可能影响不大， 不过还是插入了一些额外的assets文件。确实可以直接return掉，如果没有带参数的话。

期待你的pr~
