### ISSUE TITLE
FreelinePlugin获取jar-deps的问题

### ISSUE THREAD

**Issue by muyiou** [alibaba/freeline#134]
classesProcessTask.inputs.files.files.each { f ->
                        if (f.isDirectory()) {
                            f.eachFileRecurse(FileType.FILES) { file ->
                                backUpClass(file, backUpDirPath)
                                FreelineInjector.inject(excludeHackClasses, file, modules)
                            }
                            if (f.path.endsWith(".jar")) {
                                jarDependencies.add(f.path)
                            }
                        } else {
                            backUpClass(f, backUpDirPath)
                            FreelineInjector.inject(excludeHackClasses, f, modules)
                            if (f.path.endsWith(".jar")) {
                                jarDependencies.add(f.path)
                            }
                        }
                    }

如果一个classesProcessTask对应的transform得到的input是多级目录，这里就获取不到jar了吧，为什么不把     jarDependencies.add(f.path)放到递归操作里？

**Comment by lomanyong** [comment]
@muyiou 这个函数是groovy下的递归遍历文件的函数哈~效果是一样的

````groovy
f.eachFileRecurse(FileType.FILES) { file ->
    backUpClass(file, backUpDirPath)
    FreelineInjector.inject(excludeHackClasses, file, modules)
}
````

**Comment by muyiou** [comment]
@lomanyong 递归的以后会把file加到jarDependencies里吗？

**Comment by lomanyong** [comment]
@muyiou 恩，只有`.jar`结尾的会加入

**Comment by muyiou** [comment]
@lomanyong 
这段逻辑不应该是：
  classesProcessTask.inputs.files.files.each { f ->
                    if (f.isDirectory()) {
                        f.eachFileRecurse(FileType.FILES) { file ->
                            backUpClass(file, backUpDirPath)
                            FreelineInjector.inject(excludeHackClasses, file, modules)
                            if (file.path.endsWith(".jar")) {
                                 jarDependencies.add(f.path)
                            }
                        }
                      
                    } else {
                        backUpClass(f, backUpDirPath)
                        FreelineInjector.inject(excludeHackClasses, f, modules)
                        if (f.path.endsWith(".jar")) {
                            jarDependencies.add(f.path)
                        }
                    }
                }
？之前只把input里一级jar文件到到了jar-dep里

**Comment by lomanyong** [comment]
@muyiou 恩，这里确实是遗漏了的，下个版本修复，多谢指正。

**Comment by muyiou** [comment]
OK 我们其实不确定transform 拿到的input到底是个dir还是file

**Comment by lomanyong** [comment]
@muyiou 就目前的各种日志来看，基本都是一级目录，暂时还没有发现二级目录的情况，在这个循环里。

**Comment by muyiou** [comment]
@lomanyong 你试一下执行这个逻辑的时候：
                        classesProcessTask = project.tasks.findByName("transformClassesWithDexFor${variant.name.capitalize()}")

transform的input？

**Comment by lomanyong** [comment]
@muyiou 什么意思呢？

**Comment by muyiou** [comment]
比如修改成下面这样                    
f (getMinSdkVersion(variant.mergedFlavor, manifest_path) < 21 && variant.mergedFlavor.multiDexEnabled) {
                        classesProcessTask = project.tasks.findByName("transformClassesWithDexFor${variant.name.capitalize()}")
                    } else {
                        classesProcessTask = project.tasks.findByName("transformClassesWithDexFor${variant.name.capitalize()}")
                    }

**Comment by muyiou** [comment]
得到的应该是jarMergingTransform的结果

**Comment by lomanyong** [comment]
@muyiou 有点忘了，这段逻辑的input/output之前应该都有测试过。印象中是还有一些问题。

**Comment by lomanyong** [comment]
@muyiou 也欢迎加入我们的交流群一起来讨论哈

![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)

**Comment by muyiou** [comment]
恩，我感觉的实现兼容性不太强，比如开启proguard的时候都没有jarMerging这个transform（虽然freeline不允许开启proguard）

**Comment by lomanyong** [comment]
@muyiou 是的，默认debug状态下认为不开启proguard，proguard本身也影响编译速度..

**Comment by muyiou** [comment]
@lomanyong 感觉这里改成transform的实现要好一些，本来transform的作用就是在dex之前修改class的，至于jar-dep和res-dep放到配置结束那个阶段获取就行

**Comment by lomanyong** [comment]
@muyiou 现在的实现其实就是类似hook的机制，jar-dep是去hook到dex task的入口，res-dep是去hook到res merge的入口。要修改为transform其实也类似，instant-run就是通过transform来实现的，机制变更了，但是本质上还是没有区别的。

**Comment by muyiou** [comment]
@muyiou 恩

**Comment by muyiou** [comment]
@lomanyong 恩，本质没有区别

**Comment by muyiou** [comment]
恩

**Comment by lomanyong** [comment]
@muyiou 你们的应用可以正常接入freeline吗？

**Comment by muyiou** [comment]
@lomanyong 除了jar-dep那个问题，还没有深入使用
