### ISSUE TITLE
连接不上设备

### ISSUE THREAD

**Issue by chaunmi** [alibaba/freeline#135]
python freeline.py -f
上面这要运行无问题，修改代码之后
python freeline.py
这样运行就出现这个，但是系统环境是已经配置了的

**Comment by lomanyong** [comment]
@chaunmi 使用的freeline版本是多少呢？是最新的0.6.3吗？

可以看下`~/.freeline/cache/xxxxx/project_description.json`这个文件，应该会有一个`java_home`字段的

**Comment by chaunmi** [comment]
@lomanyong 嗯，就是最新的，java_home那里面写入有问题

**Comment by lomanyong** [comment]
@chaunmi 指的是java_home不对吗？想问下环境变量中的`JAVA_HOME`是否设置正确呢？默认去读取的是环境变量配置的地址的。

**Comment by chaunmi** [comment]
@lomanyong 环境变了最开始未设置，后面提示错误才设置的，但设置了还是无用，手动改了project_description里面的配置才OK了

**Comment by chaunmi** [comment]
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 14 times...
@lomanyong 顺便问下这个又是什么情况呢？Android studio monitor logcat都是可以连接的

**Comment by lomanyong** [comment]
@chaunmi `FreelineCore.init(this);`在application类中调用了吗？

**Comment by chaunmi** [comment]
@lomanyong 调用了的

**Comment by lomanyong** [comment]
@chaunmi logcat的日志能发下吗？以及python的完整的日志？

**Comment by chaunmi** [comment]
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 24 times...
[DEBUG] [sync_client] package com.codemonkeylabs.fpslibrary.sample not found. Please make sure your application is properly running in your device, freeline wi
ll start a clean build
[DEBUG] [connect_device_task] connect_device_task finish in 300.9s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 300.9s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 300.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 300.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 300.96s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package com.codemonkeylabs.fpslibrary.sample is not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 301.0s
[DEBUG] Total time: 301.2s
[DEBUG] --------------------------------------------------------





D:\github\TinyDancer>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False)
[DEBUG] [scan_changed_files_command] find D:\github\TinyDancer\app\src\main\res\layout\activity_main.xml has modification.
[DEBUG] [scan_changed_files_command] find D:\github\TinyDancer\app\src\main\java\com\codemonkeylabs\fpslibrary\sample\UI\MainActivity.java has modification.
[DEBUG] find app has 1 java files modified.
[DEBUG] find library has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1473752359.0242996,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [
                "D:\\github\\TinyDancer\\app\\src\\main\\java\\com\\codemonkeylabs\\fpslibrary\\sample\\UI\\MainActivity.java"
            ],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [
                "D:\\github\\TinyDancer\\app\\src\\main\\res\\layout\\activity_main.xml"
            ],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "library": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [gradle_inc_builder] find app modules have res changed
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [library]
[DEBUG] [task_engine] depth: 3, task: [app]
[DEBUG] [task_engine] depth: 4, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 6, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 7, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 8, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [app_inc_invoker] find app has resource files modification.
[DEBUG] [gradle_aapt_task] start to execute aapt command...
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [tracing] generate_id_keeper_files: 0.0ms
[DEBUG] [app_inc_invoker] find relative path: res\layout\activity_main.xml
[DEBUG] [app_inc_invoker] find relative path: res\values\freeline_id_keeper_public.xml
[DEBUG] [app_inc_invoker] find relative path: res\values\freeline_id_keeper_ids.xml
[DEBUG] [app_inc_invoker] aapt exec: freeline\release-tools\FreelineAapt.exe package -f -I D:\AndroidDevEvn\Android\android-sdk\platforms\android-23\android.ja
r -M D:\github\TinyDancer\app\build\intermediates\manifests\full\debug\AndroidManifest.xml -S D:\github\TinyDancer\app\src\main\res -S D:\github\TinyDancer\lib
rary\src\main\res -S D:\github\TinyDancer\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.6.3\res -S D:\github\TinyDancer\app\build\inte
rmediates\exploded-aar\com.android.support\support-v4\23.2.0\res -S D:\github\TinyDancer\app\build\intermediates\exploded-aar\com.android.support\recyclerview-
v7\23.2.0\res -S D:\github\TinyDancer\app\build\intermediates\exploded-aar\com.android.support\support-vector-drawable\23.2.0\res -S D:\github\TinyDancer\app\b
uild\intermediates\exploded-aar\com.android.support\animated-vector-drawable\23.2.0\res -S D:\github\TinyDancer\app\build\intermediates\exploded-aar\com.androi
d.support\appcompat-v7\23.2.0\res -S D:\github\TinyDancer\app\build\generated\res\rs\debug -S D:\github\TinyDancer\app\build\generated\res\resValues\debug -S D
:\github\TinyDancer\app\build\freeline\app\backup\res -A D:\github\TinyDancer\app\build\freeline\freeline-assets --custom-package com.codemonkeylabs.fpslibrary
.sample -m -J D:\github\TinyDancer\app\build\freeline\app\backup --auto-add-overlay -P D:\github\TinyDancer\app\build\freeline\app\backup\res\values\freeline_i
d_keeper_public.xml -F D:\github\TinyDancer\app\build\freeline\app\respack\app.pack --debug-mode --auto-add-overlay --no-version-vectors --ignore-assets public
_id.xml:public.xml:*.bak:.*
[DEBUG] [app_inc_invoker] aapt use time: 566.999912262ms
[DEBUG] [app_inc_invoker] merged_changed_list:
[DEBUG] [app_inc_invoker] [u'res/layout/activity_main.xml', u'res/values/freeline_id_keeper_public.xml', u'res/values/freeline_id_keeper_ids.xml']
[DEBUG] [tracing] run_incremental_aapt_task: 614.000082016ms
[DEBUG] [app_inc_invoker] modify D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] avoid windows unicode error for D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] [app_inc_invoker] copy D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeylabs\fpslibrary\sample\R.java to D:\github\TinyDancer\app\build
\freeline\freeline-backup-r\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] [app_inc_invoker] modify D:\github\TinyDancer\app\build\freeline\freeline-backup-r\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] [tracing] check_other_modules_resources: 6.99996948242ms
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.6s
[DEBUG] [library] library start to run after waiting 0.6s
[DEBUG] [library_inc_invoker] library old R.java path: D:\github\TinyDancer\library\build\generated\source\r\androidTest\debug\com\codemonkeylabs\fpslibrary\R.
java
[DEBUG] [library_inc_invoker] library new R.java path: None
[DEBUG] [library_inc_invoker] src changed files:
[DEBUG] [library_inc_invoker] []
[DEBUG] [library_inc_invoker] library project has no change, need not go ahead
[DEBUG] [library_inc_invoker] library code only change R.java, need not go ahead
[DEBUG] [library_inc_javac_compile] no need to execute
[DEBUG] [library_inc_dex_compile] no need to execute
[DEBUG] [library] library finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.6s
[DEBUG] [app_inc_invoker] app old R.java path: D:\github\TinyDancer\app\build\generated\source\r\debug\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] [app_inc_invoker] app new R.java path: D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] avoid windows unicode error for D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'D:\\github\\TinyDancer\\app\\src\\main\\java\\com\\codemonkeylabs\\fpslibrary\\sample\\UI\\MainActivity.java', u'D:\\github\\TinyD
ancer\\app\\build\\freeline\\app\\backup\\com\\codemonkeylabs\\fpslibrary\\sample\\R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_javac_compile] start to execute javac command...
[DEBUG] avoid windows unicode error for D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] [app_inc_invoker] javac exec: D:\AndroidDevEvn\Java\jdk1.8.0_20\bin\javac.exe -target 1.7 -source 1.7 -encoding UTF-8 -g -cp D:\github\TinyDancer\app\b
uild\freeline\app\classes;D:\github\TinyDancer\app\build\intermediates\classes\debug;D:\github\TinyDancer\app\build\freeline\library\classes;D:\AndroidDevEvn\A
ndroid\android-sdk\platforms\android-23\android.jar;D:\github\TinyDancer\app\build\intermediates\exploded-aar\com.android.support\recyclerview-v7\23.2.0\jars\c
lasses.jar;C:\Users\xxxxx\.gradle\caches\modules-2\files-2.1\com.google.dagger\dagger\2.0.2\de8416eda7b2fd7c25836b140c39e1cbf10542f6\dagger-2.0.2.jar;D:\
github\TinyDancer\app\build\intermediates\exploded-aar\com.android.support\animated-vector-drawable\23.2.0\jars\classes.jar;D:\github\TinyDancer\app\build\inte
rmediates\exploded-aar\com.android.support\support-vector-drawable\23.2.0\jars\classes.jar;C:\Users\xxxx\.gradle\caches\modules-2\files-2.1\com.jakewhar
ton\butterknife\7.0.1\d5d13ea991eab0252e3710e5df3d6a9d4b21d461\butterknife-7.0.1.jar;D:\github\TinyDancer\app\build\intermediates\exploded-aar\com.android.supp
ort\appcompat-v7\23.2.0\jars\classes.jar;D:\github\TinyDancer\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.2.0\jars\libs\internal_imp
l-23.2.0.jar;D:\AndroidDevEvn\Android\android-sdk\extras\android\m2repository\com\android\support\support-annotations\23.2.0\support-annotations-23.2.0.jar;D:\
github\TinyDancer\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.6.3\jars\classes.jar;D:\github\TinyDancer\app\build\intermediates\expl
oded-aar\com.android.support\support-v4\23.2.0\jars\classes.jar;C:\Users\xxxxx\.gradle\caches\modules-2\files-2.1\javax.inject\javax.inject\1\6975da39a70
40257bd51d21a231b76c915872d38\javax.inject-1.jar;D:\github\TinyDancer\app\build\intermediates\exploded-aar\TinyDancer\library\unspecified\jars\classes.jar D:\g
ithub\TinyDancer\app\src\main\java\com\codemonkeylabs\fpslibrary\sample\UI\MainActivity.java D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeyl
abs\fpslibrary\sample\R.java -d D:\github\TinyDancer\app\build\freeline\app\classes
[DEBUG] [app_inc_invoker] copy D:\github\TinyDancer\app\build\freeline\app\backup\com\codemonkeylabs\fpslibrary\sample\R.java to D:\github\TinyDancer\app\build
\generated\source\r\debug\com\codemonkeylabs\fpslibrary\sample\R.java
[DEBUG] [app_inc_dex_compile] start to execute dex command...
[DEBUG] [app_inc_invoker] dex exec: D:\AndroidDevEvn\Android\android-sdk\build-tools\23.0.2\dx.bat --dex --output=D:\github\TinyDancer\app\build\freeline\app\d
ex\app.dex D:\github\TinyDancer\app\build\freeline\app\classes
[DEBUG] [app] app finish in 2.9s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 3.5s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy D:\github\TinyDancer\app\build\freeline\app\dex\app.dex to D:\github\TinyDancer\app\build\freeline\incre
ment.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 1 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 2 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 3 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 4 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 5 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 6 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 7 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000
[DEBUG] [sync_client] try to connect device 8 times...
[DEBUG] [sync_client] wake up Service: D:\AndroidDevEvn\Android\android-sdk\platform-tools\adb.exe shell am startservice -n com.codemonkeylabs.fpslibrary.sampl
e/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] apktime path: D:\github\TinyDancer\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 704000
[DEBUG] [sync_client] your local uuid value is: 704000

**Comment by chaunmi** [comment]
@lomanyong python日志在哪儿？

**Comment by lomanyong** [comment]
@chaunmi 你发的就是python的日志了， 可以把Logcat里跟freeline相关的日志也发一下

**Comment by yinduo527** [comment]
我跟他遇到的问题貌似是一样的，这是我的logcat日志，类型转换错误，看看有没有帮助
E/Freeline: java.lang.NumberFormatException: Invalid long: "${placeholder}"
                                                                            at java.lang.Long.invalidLong(Long.java:124)
                                                                            at java.lang.Long.parse(Long.java:361)
                                                                            at java.lang.Long.parseLong(Long.java:352)
                                                                            at java.lang.Long.parseLong(Long.java:318)
                                                                            at com.antfortune.freeline.FreelineCore.getApkBuildFlag(FreelineCore.java:146)
                                                                            at com.antfortune.freeline.router.schema.CheckSyncSchema.handle(CheckSyncSchema.java:28)
                                                                            at com.antfortune.freeline.router.Router.dispatch(Router.java:48)
                                                                            at com.antfortune.freeline.server.LongLinkServer.handle(LongLinkServer.java:55)
                                                                            at com.antfortune.freeline.server.EmbedHttpServer.run(EmbedHttpServer.java:95)
                                                                            at java.lang.Thread.run(Thread.java:841)

**Comment by chaunmi** [comment]
09-13 17:18:04.970 1509-1509/com.codemonkeylabs.fpslibrary.sample:freeline I/Freeline.Service: onStartCommand Received start id 123, intent: Intent { cmp=com.codemonkeylabs.fpslibrary.sample/com.antfortune.freeline.FreelineService }
09-13 17:18:04.970 1509-1509/com.codemonkeylabs.fpslibrary.sample:freeline D/Freeline.LongLinkServer: Freeline.increment server is already running
09-13 17:18:05.010 1509-1509/com.codemonkeylabs.fpslibrary.sample:freeline I/Freeline.Service$Inner: onStartCommand Received start id 1, intent: Intent { cmp=com.codemonkeylabs.fpslibrary.sample/com.antfortune.freeline.FreelineService$InnerService }
09-13 17:18:17.000 1509-1509/com.codemonkeylabs.fpslibrary.sample:freeline I/Freeline.Service: onStartCommand Received start id 124, intent: Intent { cmp=com.codemonkeylabs.fpslibrary.sample/com.antfortune.freeline.FreelineService (has extras) }
09-13 17:18:17.000 1509-1509/com.codemonkeylabs.fpslibrary.sample:freeline D/Freeline.LongLinkServer: Freeline.increment server is already running
09-13 17:18:28.890 1509-1509/com.codemonkeylabs.fpslibrary.sample:freeline I/Freeline.Service: onStartCommand Received start id 125, intent: Intent { cmp=com.codemonkeylabs.fpslibrary.sample/com.antfortune.freeline.FreelineService (has extras) }
09-13 17:18:28.890 1509-1509/com.codemonkeylabs.fpslibrary.sample:freeline D/Freeline.LongLinkServer: Freeline.increment server is already running

@lomanyong

**Comment by lomanyong** [comment]
@chaunmi 看了下日志貌似是因为代理的问题导致的。可以检查下是否安装了网络代理...

（还有一个终极解决方案...重启试试...解决了不少人连接不上的问题...

**Comment by chaunmi** [comment]
@lomanyong 这和代理有什么关系呢

**Comment by lomanyong** [comment]
@chaunmi 代理会导致`127.0.0.1`这个IP的访问被重定向...导致无法连接上的问题。

**Comment by charvenhe** [comment]
@chaunmi 问题解决了没呢，没有的话

加我们微信群我们单独跟进看看
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)

**Comment by charvenhe** [comment]
0.7已经进行专门处理，后续有类似问题移步这里讨论 #152
