### ISSUE TITLE
提示错误，现在我每次都要用python freeline.py -f 跑，用python freeline.py跑就提示下面错误

### ISSUE THREAD

**Issue by fearlesstrek** [alibaba/freeline#136]
![image](https://cloud.githubusercontent.com/assets/12731121/18469062/36498e70-79d9-11e6-898b-b532e250c940.png)

**Comment by charvenhe** [comment]
@fearlesstrek 加我们微信群我们单独跟进看看
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)
