### ISSUE TITLE
[WARNING] NoInstallationException occurs, a clean build will be automatically executed.

### ISSUE THREAD

**Issue by guxun12** [alibaba/freeline#139]
项目每次运行freeline.py都会提示这个[WARNING] ，然后每次都执行[gradle_clean_build_task]，
构建的LOG如下：
[WARNING] NoInstallationException occurs, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 9.1s
[-][generate_file_stat_task] finished. in 0.5s
[-][gradle_clean_build_task] finished. in 246.5s
[-][clean_all_cache_task] finished. in 0.1s
[-][install_apk_task] finished. in 39.7s
[-][build_base_resource_task] finished. in 22.3s
[-][generate_project_info_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 39.3s
[DEBUG] Task engine running time: 295.3s
[DEBUG] Total time: 334.6s
[DEBUG] --------------------------------------------------------

但是DEMO没这个[WARNING] ，请问哪里姿势错了么？

**Comment by lomanyong** [comment]
@guxun12 你自己的app有添加freeline的`FreelineCore.init(this);`到application类中吗？

**Comment by guxun12** [comment]
@lomanyong  Application的onCreat里有初始化的。
我对着[Issues35](https://github.com/alibaba/freeline/issues/35)的姿势确认了一把：
1、project_description.json中的package字段不为null 
2、app中build.gradle设置了hack true
3、adb shell pm list package {your package} 输出列表中有信息
4、手机中依赖Freeline的其他app已删除
ps : 项目中的 gradle版本1.3.0/ jdk 1.7 / compileSdkVersion 22

**Comment by guxun12** [comment]
执行 freeline.py -f 成功后再执行 freelance.py会报如下错误
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package myPackageName is not found.
[ERROR] --------------------------------------------------------

**Comment by charvenhe** [comment]
@guxun12 加我们微信群我们单独跟进看看
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)

**Comment by guxun12** [comment]
@lomanyong @charvenhe 我对着[常见问题](https://github.com/alibaba/freeline/wiki/常见问题) 找到我这边问题所在了：测试更改的代码被Application引用到了，所以每次都是全量编译。
更改普通layout后增量编译效果很明显。
Freeline 非常赞，谢谢！
