### ISSUE TITLE
That'd be wonderful if Freeline can support change BuildType

### ISSUE THREAD

**Issue by xiongwei-git** [alibaba/freeline#14]
That'd be wonderful if Freeline can support change BuildType

**Comment by charvenhe** [comment]
thanks for your issues ，we will improve as soon as possible

**Comment by lomanyong** [comment]
@xiongwei-git 最近思考了一下freeline对多buildType支持的这个问题，之前一直没有做修改是因为这个改动涉及到的地方挺多的。之前按照你们项目的做法，应该是在buildType中对应了不同的网关，来做网络环境的隔离。其实我觉得这种场景更应该通过配置的方式，来做动态切换，比如一个debug包可以通过配置切换，快速地在release网关环境下进行测试，而不是跟buildType进行强耦合。

freeline如果加入对多个buildType的支持的话，意味着也有可能在用户不经意地操作下对test/release等，有特定作用的包造成污染，造成不好的影响，这也是我们不希望看到的，我们仍然是希望freeline能够足够的简单，容易集成，不对用户的正式发版造成影响。

所以，freeline对多buildType的支持这个feature暂时应该是不会做处理了，如果你有什么想法的话，欢迎在issue中跟我们进行交流哈。
