### ISSUE TITLE
when to release v1.0?

### ISSUE THREAD

**Issue by gao746700783** [alibaba/freeline#141]
have so many errors?want to know when to release v1.0?

**Comment by lomanyong** [comment]
Yep, we are keeping on working to make freeline a better tool for android. We still have some problems when developers used freeline in the first time and we are making progress with this to help developers to integrate with freeline more easier.

There is no a specific time schedule for the v1.0 releasing. But we are working on more features, such as application proxy, annotation support and so on. Hope the version 1.0 can come soon.
