### ISSUE TITLE
升级AS2.2后遇到问题，read_project_info_task过不去

### ISSUE THREAD

**Issue by zx810506** [alibaba/freeline#144]
![88c6c049-7060-4022-968c-6f4e4502d9dd](https://cloud.githubusercontent.com/assets/3293075/18656710/19a15df0-7f26-11e6-841a-edec83e03904.png)
请问如何解决？

**Comment by lomanyong** [comment]
@zx810506 应该是卡在下载gradle上了，你可以直接实行`./gradlew checkBeforeCleanBuild`看下。

**Comment by zx810506** [comment]
好的，我试试
