### ISSUE TITLE
python freeline.py 在build时没有merge manifest文件

### ISSUE THREAD

**Issue by act262** [alibaba/freeline#146]
v0.6.3 中
python freeline.py 在build过程中没有合并freeline相关的组件，导致 唤醒不了FreelineService,所以会一直连接设备，直到失败。

**Comment by act262** [comment]
在app的manifest中使用了`tools:node="replace"`导致没有合并freeline的`manifest`，
临时解决方案：
方案1，直接复制freeline的`manifest`代码到app的`manifest`中去;
方案2，移除`tools:node="replace"` 这个功能;

**Comment by lomanyong** [comment]
@act262 `tools:node="replace"`，这个是在manifest的哪个节点中呢？

**Comment by act262** [comment]
我是放在application节点的，用于替换library中的supportRTL属性

**Comment by lomanyong** [comment]
@act262 应该是可以使用`tools:overrideLibrary="com.antfortune.freeline"`来替换属性的。`tools:node="replace"`估计直接全局禁止了...

**Comment by lomanyong** [comment]
@act262 看了下[官方文档](http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger)，写的也不是很清楚。我找时间来试验下这个属性为啥不能正常merge...
