### ISSUE TITLE
修改布局文件，增量编译后出现 ClassCastException

### ISSUE THREAD

**Issue by reondz** [alibaba/freeline#15]
修改布局文件中的控件，从父类改为其某个子类，并在代码中做了相应修改。增量编译正常，运行时在findViewById的过程中出现了 ClassCastException，即父类无法 cast 为子类的错误。

**Comment by lomanyong** [comment]
@reondz 这个问题应该还是偶现的，可能是runtime加载依赖的时序有问题导致的。现在可以更新到`0.5.3`版本，看下是否还会经常出现。

注意，需要同时更新gradle与runtime的版本号到`0.5.3`，然后重新执行一下`./gradlew initFreeline`，然后就可以正常使用了。
