### ISSUE TITLE
工程中使用了 me.tatarka:gradle-retrolambda，增量编译时报错

### ISSUE THREAD

**Issue by spysoos** [alibaba/freeline#150]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

警警告告: [options] 未未与与 -source 1.7 一一起起设设置置引引导导类类路路径径
        lvMessage.setOnRefreshListener(refreshView -> {

  (请请使使用用 -source 8 或或更更高高版版本本以以启启用用 lambda 表表达达式式)
1 个个错错误误
1 个个警警告告

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.5s
[DEBUG] Total time: 0.7s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@spysoos 目前不支持lambda，不过已经在我们的待支持feature中了，会陆续支持上~

**Comment by acilgit** [comment]
什么时候可以支付Lambda表达式？
