### ISSUE TITLE
一直停在Building 0% > :initFreeline 这个状态中

### ISSUE THREAD

**Issue by jiantao88** [alibaba/freeline#16]
![image](https://cloud.githubusercontent.com/assets/7411102/17916787/00b3cdf2-69e9-11e6-90ff-fb7dab3c746c.png)

**Comment by lomanyong** [comment]
@jiantao88 有可能是因为卡在下载gradle包上，你可以挂个代理，或者修改`gradle/wrapper/gradle-wrapper.properties`的`distributionUrl`属性，改为国内的gradle镜像

**Comment by lomanyong** [comment]
@jiantao88 问题解决了吗？

**Comment by jiantao88** [comment]
还是没有

**Comment by lomanyong** [comment]
会卡在0%主要还是网络的问题... 可以直接在命令行执行`./gradlew assembleDebug`，看是否可以正常运行.

**Comment by lomanyong** [comment]
@jiantao88 可以根据我上面提供的方法配置一下，看是否可以正常下载。现在如何了呢？

**Comment by gushoubang** [comment]
我今天也遇到这个问题了

**Comment by jiantao88** [comment]
使用 ./gradlew assembleDebug --stacktrace 这个命令可以编译

**Comment by gushoubang** [comment]
我的是windows，可以啦

**Comment by jiantao88** [comment]
![image](https://cloud.githubusercontent.com/assets/7411102/17959500/566786e0-6ad3-11e6-8304-549e86eaa59f.png)
运行./gradlew initFreeline --stacktrace 就这样

**Comment by lomanyong** [comment]
@jiantao88 截图似乎有问题？在我这边看基本都是黑色的...没有内容...

**Comment by jiantao88** [comment]
@lomanyong 我重新发了一个

**Comment by gushoubang** [comment]
直接运行   gradlew assembleDebug --stacktrace   

直截了最后一部分


warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.umeng.socialize.view.h) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
:app:vdsDeinstrumentTask                                   
[vds.info] Rewriter jar path: C:\Users\xg\.gradle\caches\modules-2\files-2.1\com.growingio.android\vds-class-rewriter\0.9.90\1d82021fe529aac77292258d134d359d5ca3095f\vds-class-rewriter-0.9.90.jar
:app:mergeXiaomiDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForXiaomiDebug UP-TO-DATE
:app:processXiaomiDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForXiaomiDebug
:app:validateDebugSigning
:app:packageXiaomiDebug                 
:app:zipalignXiaomiDebug
[vds.info] Instrumentation disabled, no agent present.  Command: zipalign.exe
:app:assembleXiaomiDebug                 
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 2 mins 1.727 secs

**Comment by lomanyong** [comment]
@jiantao88 应该是你网络的问题..你可以使用国内镜像地址下载，执行`./gradlew initFreeline -Pmirror`

**Comment by lomanyong** [comment]
@gushoubang 现在initFreeline还有什么问题呢？

**Comment by jiantao88** [comment]
@lomanyong 可以了 多谢，希望能有个讨论组之类的

**Comment by lomanyong** [comment]
@jiantao88 可以扫二维码加入我们的微信群讨论，群里有不少已经将freeline用于团队开发中了。

![](http://ww2.sinaimg.cn/large/006tKfTcgw1f760b2tzn5j30ny0zk0tm.jpg)

**Comment by gdky005** [comment]
对于第一次遇见的网络问题，我也是醉了，一直卡在0%。当挂代理后，也是0%，但是最后也会下载成功，只是没有界面更新而已，希望能修正下。 网速还好的话，基本等2分钟左右差不多。

**Comment by lomanyong** [comment]
@gdky005 我们在README中有提到，对于国内网络下载问题的话，可以使用`./gradlew initFreeline -Pmirror`，速度回快一点的。很抱歉造成困扰哈~
