### ISSUE TITLE
总是报错：only 1 device allwoed;

### ISSUE THREAD

**Issue by WQLhub** [alibaba/freeline#162]
[DEBUG] [task_engine] it takes task engine 382.52s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Only 1 device allowed, use `adb devices` to check your devices' connection
[ERROR] --------------------------------------------------------
[ERROR] More than 1 device connect
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 2.4s
[DEBUG] Task engine running time: 382.5s
[DEBUG] Total time: 384.9s
[DEBUG] --------------------------------------------------------

C:\asproject\XXX>adb devices
List of devices attached
c9ed3f6f        device

实际上只有一台设备连接，并adb devices 也只看到一台设备，为什么总是报错说： Only 1 device allowed, use `adb devices` to check your devices' connection？

**Comment by charvenhe** [comment]
@WQLhub 这个现象能否稳定复现呢？我们这边检查过没出问题

**Comment by WQLhub** [comment]
已经发现问题了，是我这边装了两个手机助手导致的，关闭其中一个就没这个问题了，谢谢。



ds0qiao@163.com
 
发件人： xianying
发送时间： 2016-09-26 20:47
收件人： alibaba/freeline
抄送： WQLhub; Mention
主题： Re: [alibaba/freeline] 总是报错：only 1 device allwoed; (#162)
@WQLhub 这个现象能否稳定复现呢？我们这边检查过没出问题

**Comment by charvenhe** [comment]
@WQLhub   好的，可以多在你项目中使用，有问题及时反馈

**Comment by WQLhub** [comment]
嗯嗯，好的，目前来看挺好用，谢谢你们的努力付出；



ds0qiao@163.com
 
发件人： xianying
发送时间： 2016-09-26 20:59
收件人： alibaba/freeline
抄送： WQLhub; Mention
主题： Re: [alibaba/freeline] 总是报错：only 1 device allwoed; (#162)
@WQLhub 好的，可以多在你项目中使用，有问题及时反馈
