### ISSUE TITLE
as安装freeline plugin后，无法启动，

### ISSUE THREAD

**Issue by huangying812** [alibaba/freeline#163]
Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: views/FreelineTerminal : Unsupported major.minor version 52.0 [Plugin: com.apkfuns.plugin.freeline] [Plugin: com.apkfuns.plugin.freeline]

报这个异常，阻止as启动

**Comment by lomanyong** [comment]
@pengwei1024 插件编译的时候JDK版本是不是比较高呢？

**Comment by pengwei1024** [comment]
@huangying812 你好，你可以暂时先修改android studio  应用程序 -> 右键显示包内容 -> Contents -> Info.plist ->  JVMVersion 版本改成1.8*,1.8+，或者条件允许的话升级到android studio2.2也可以解决这个问题。这个问题我后续看看怎么修改。

**Comment by lomanyong** [comment]
@pengwei1024 编译的时候Target使用1.7的应该可以解决吧。

**Comment by act262** [comment]
@huangying812 需要看下你当前的环境信息，jdk，AS版本，gradle版本，android plugin 版本==

**Comment by pengwei1024** [comment]
@huangying812 麻烦你再试试这个jar包，intellij IDEA16以后已经不支持jdk 1.7
[freeline-plugin-1.0.9.1.jar.zip](https://github.com/alibaba/freeline/files/489334/freeline-plugin-1.0.9.1.jar.zip)

**Comment by huangying812** [comment]
多谢！我试试先

**Comment by pengwei1024** [comment]
好的，非常感谢你的反馈。以后都用intellij IDEA 15打包，尽量兼容到JDK 1.7

**Comment by ftc300** [comment]
![image](https://cloud.githubusercontent.com/assets/12816061/20952857/5e89052c-bc6a-11e6-9eb4-6490af7093ff.png)

**Comment by pengwei1024** [comment]
@ftc300 请问你的插件版本是最新版吗？你本地用的jdk版本是多少？

**Comment by ftc300** [comment]
@pengwei1024
java version "1.8.0_101"
![image](https://cloud.githubusercontent.com/assets/12816061/20953177/82afec8e-bc6c-11e6-8e91-9e1c3f85803c.png)
我用的是AndroidStudio2.1.1

**Comment by pengwei1024** [comment]
@ftc300  你可以暂时先修改android studio 应用程序 -> 右键显示包内容 -> Contents -> Info.plist -> JVMVersion 版本改成1.8*,1.8+，或者条件允许的话升级到android studio2.2 或者2.3。

**Comment by ftc300** [comment]
@pengwei1024  采用第一种方式 没有异常了 谢谢
