### ISSUE TITLE
app\build\intermediates\assets\debug\apktime (系统找不到指定的路径。)

### ISSUE THREAD

**Issue by hzy82218052** [alibaba/freeline#165]
在android中配置productFlavors{ xxx {} }渠道打包后，出现bug如下：
Execution failed for task ':app:mergexxxDebugAssets'.
> D:\AndroidStudioProjects\myapplication\app\build\intermediates\assets\debug\apktime (系统找不到指定的路径。)

**Comment by lomanyong** [comment]
@hzy82218052 用的是哪个版本呢？应该会提示说需要加配置项，加完即可正常编译。如下：

````gradle
freeline {
    ....
    productFlavor "your-flavor"
}
````

**Comment by hzy82218052** [comment]
在freeline中我也加入了productFlavor 属性的，不过上周还有这个问题，今天放假回来后好像就没这个问题了，不过还是谢谢解答
