### ISSUE TITLE
不设置JAVA_HOME环境变量

### ISSUE THREAD

**Issue by coolfile** [alibaba/freeline#17]
由于特殊原因，机子不能设置JAVA_HOME这个环境变量，有办法不设置此变量运行吗？

**Comment by lomanyong** [comment]
@coolfile 恩，下一个插件版本我们来支持这个feature

**Comment by ImKarl** [comment]
类似的，我的Mac命令行已经支持 `java` 命令。但还是需要设置 `JAVA_HOME` 变量
我都是在每次开 终端 后设置变量，以保证可用。 @coolfile 你也可以试试
> export JAVA_HOME=my_java_home

**Comment by lomanyong** [comment]
@coolfile 可以更新freeline版本到`0.5.3`试试看，修改一下gradle插件与runtime的版本号，然后执行`./gradlew initFreeline`，试试看是否解决了不设置`JAVA_HOME`环境变量也能运行的问题

**Comment by coolfile** [comment]
我的windows 环境有点问题。报这个错。
Execution failed for task ':x1:compileDeveloperDebugJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_101 contains a valid JDK installation.
好像读成了jre的路径。

**Comment by coolfile** [comment]
linux问题不大，我已经通过改gradlew脚本的方式解决。

**Comment by coolfile** [comment]
@ImKarl 我在linux下是改了gradlew的脚本。在里面加入了JAVA_HOME，不用每次开终端设置。

**Comment by lomanyong** [comment]
@coolfile win下的这个报错，看着像是你本地环境的问题，应该不是freeline引起的

**Comment by coolfile** [comment]
@lomanyong 我的问题，已经修改好了。
