### ISSUE TITLE
使用python freeline.py可以打包成功，但是使用原始gradle build打包出错

### ISSUE THREAD

**Issue by hzy82218052** [alibaba/freeline#170]
Execution failed for task ':app:transformClassesWithDexForTempusRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/antfortune/freeline/Buil
dConfig;

**Comment by lomanyong** [comment]
@hzy82218052 是否使用了`0.6.3`以上的版本呢？是的话可以移除在build.gradle中`com.antfortune.freeline:runtime:xxx`的依赖，然后clean一下，重新编译。

**Comment by hzy82218052** [comment]
是的确实，我一直在想哪里冲突了，原来是以前用module中引用的com.antfortune.freeline:runtime没去掉，已经完美解决了
