### ISSUE TITLE
flavor dimension支持

### ISSUE THREAD

**Issue by whistlexie** [alibaba/freeline#176]
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [react_native]
[DEBUG] [task_engine] depth: 3, task: [app_fanxingv2]
[DEBUG] [task_engine] depth: 4, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 6, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 7, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 8, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\freeline-assets\apktime
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [sync_client] your local sync value is: 666000
[DEBUG] [react_native] react_native start to run after waiting 0.0s
[DEBUG] [sync_client] your local uuid value is: 666000
[DEBUG] [react_native_inc_invoker] react_native old R.java path: E:\LocalRepository\fanxing\react_native\build\generated\source\r\androidTest\debug\com\kugou\reactnative\R.java
[DEBUG] [react_native_inc_invoker] react_native new R.java path: None
[DEBUG] [react_native_inc_invoker] src changed files:
[DEBUG] [react_native_inc_invoker] []
[DEBUG] [react_native_inc_invoker] react_native project has no change, need not go ahead
[DEBUG] [react_native_inc_invoker] react_native code only change R.java, need not go ahead
[DEBUG] [react_native_inc_javac_compile] no need to execute
[DEBUG] [react_native_inc_dex_compile] no need to execute
[DEBUG] [react_native] react_native finish in 0.0s
[DEBUG] [app_fanxingv2] app_fanxingv2 start to run after waiting 0.0s
[DEBUG] [app_fanxingv2_inc_invoker] app_fanxingv2 old R.java path: E:\LocalRepository\fanxing\app_fanxingv2\build\generated\source\r\devFanxing\debug\com\kugou\fanxing\R.java
[DEBUG] [app_fanxingv2_inc_invoker] app_fanxingv2 new R.java path: E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\app_fanxingv2\backup\com\kugou\fanxing\R.java
[DEBUG] avoid windows unicode error for E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\app_fanxingv2\backup\com\kugou\fanxing\R.java
[DEBUG] [sync_client] server result is 1
[DEBUG] [app_fanxingv2_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_fanxingv2_inc_invoker] src changed files:
[DEBUG] [app_fanxingv2_inc_invoker] [u'E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\app_fanxingv2\backup\com\kugou\fanxing\R.java']
[DEBUG] [app_fanxingv2_inc_invoker] find R.java modified in src list
[DEBUG] [app_fanxingv2_inc_invoker] app_fanxingv2 code only change R.java, need not go ahead
[DEBUG] [app_fanxingv2_inc_javac_compile] no need to execute
[DEBUG] [app_fanxingv2_inc_dex_compile] no need to execute
[DEBUG] [app_fanxingv2] app_fanxingv2 finish in 0.1s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.1s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.2s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.2s
[DEBUG] [sync_client] react_native has no need to sync inc res pack.
[DEBUG] [sync_client] app_fanxingv2 has no need to sync inc res pack.
[DEBUG] [sync_client] no E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\increment.dex exists.
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.0s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.3s
[DEBUG] [clean_cache_task] remove cache: E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\app_fanxingv2\respack\app_fanxingv2.rflag
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.2s
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 0.3s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 0.3s
[DEBUG] Total time: 0.6s
[DEBUG] --------------------------------------------------------

---------------------------------------分割线---------------------------------------

修改资源文件后，可以看到 R 文件有修改的log，然后 manifest 文件merge也成功了。是不是 tcp 连接失败了？不是手机或者代理的问题，自己之前测试的项目比较简单，可以成功，所以不是手机或者代理的问题。后来进入 values 文件夹查看，发现 ids.xml 和 public.xml，在修改资源文件后不会更新，仔细看了下 freeline 日志。 发现没有 [DEBUG] [sync_client] checkresource: http://127.0.0.1:41129/checkResource   和  [DEBUG] [clean_cache_task] refresh app ids.xml
 类似的输出，请问是 tcp 没连接上吗？我这里没有设置 debuggable 属性，直接在 manifst 设置debuggable = true，会提示报错，不允许硬编码设置debuggable。麻烦大神再次看一下，不胜感激！！！

**Comment by lomanyong** [comment]
@whistlexie 这个日志看着就是没有改动的空跑呀....可以修改下文件，然后如果还是这样的话，发个完整一点的日志把。

**Comment by whistlexie** [comment]
@lomanyong  下面是完整log，确实是修改了资源文件和代码的。

E:\LocalRepository\fanxing>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False)
[DEBUG] find react_native has 0 java files modified.
[DEBUG] find app_fanxingv2 has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1475054004.842322,
        "is_root_config_changed": false
    },
    "projects": {
        "react_native": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "app_fanxingv2": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [react_native]
[DEBUG] [task_engine] depth: 3, task: [app_fanxingv2]
[DEBUG] [task_engine] depth: 4, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 6, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 7, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 8, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [sync_client] apktime path: E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\freeline-assets\apktime
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [react_native] react_native start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 964000
[DEBUG] [sync_client] your local uuid value is: 964000
[DEBUG] [react_native_inc_invoker] react_native old R.java path: E:\LocalRepository\fanxing\react_native\build\generated\source\r\androidTest\debug\com\kugou\reactnative\R.java
[DEBUG] [react_native_inc_invoker] react_native new R.java path: None
[DEBUG] [react_native_inc_invoker] src changed files:
[DEBUG] [react_native_inc_invoker] []
[DEBUG] [react_native_inc_invoker] react_native project has no change, need not go ahead
[DEBUG] [react_native_inc_invoker] react_native code only change R.java, need not go ahead
[DEBUG] [react_native_inc_javac_compile] no need to execute
[DEBUG] [react_native_inc_dex_compile] no need to execute
[DEBUG] [react_native] react_native finish in 0.0s
[DEBUG] [app_fanxingv2] app_fanxingv2 start to run after waiting 0.0s
[DEBUG] [app_fanxingv2_inc_invoker] app_fanxingv2 old R.java path: E:\LocalRepository\fanxing\app_fanxingv2\build\generated\source\r\devFanxing\debug\com\kugou\fanxing\R.java
[DEBUG] [app_fanxingv2_inc_invoker] app_fanxingv2 new R.java path: E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\app_fanxingv2\backup\com\kugou\fanxing\R.java
[DEBUG] avoid windows unicode error for E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\app_fanxingv2\backup\com\kugou\fanxing\R.java
[DEBUG] [sync_client] server result is 1
[DEBUG] [app_fanxingv2_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_fanxingv2_inc_invoker] src changed files:
[DEBUG] [app_fanxingv2_inc_invoker] [u'E:\\LocalRepository\\fanxing\\app_fanxingv2\\build\\freeline\\app_fanxingv2\\backup\\com\\kugou\\fanxing\\R.java']
[DEBUG] [app_fanxingv2_inc_invoker] find R.java modified in src list
[DEBUG] [app_fanxingv2_inc_invoker] app_fanxingv2 code only change R.java, need not go ahead
[DEBUG] [app_fanxingv2_inc_javac_compile] no need to execute
[DEBUG] [app_fanxingv2_inc_dex_compile] no need to execute
[DEBUG] [app_fanxingv2] app_fanxingv2 finish in 0.2s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.2s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.9s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.9s
[DEBUG] [sync_client] react_native has no need to sync inc res pack.
[DEBUG] [sync_client] app_fanxingv2 has no need to sync inc res pack.
[DEBUG] [sync_client] no E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\increment.dex exists.
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.0s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.9s
[DEBUG] [clean_cache_task] remove cache: E:\LocalRepository\fanxing\app_fanxingv2\build\freeline\app_fanxingv2\respack\app_fanxingv2.rflag
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.9s
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 0.95s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 1.0s
[DEBUG] Total time: 1.2s
[DEBUG] --------------------------------------------------------

**Comment by whistlexie** [comment]
@lomanyong  谢谢呀

**Comment by whistlexie** [comment]
@lomanyong  找到问题了，是代码文件件结构的问题。打开了 project_descript.json。发现代码文件夹根本不在这里面。

**Comment by lomanyong** [comment]
@whistlexie  工程除了`react_native`和`app_fanxingv2 `还有其他的module吗？

意思是有module没有找到吗？

**Comment by whistlexie** [comment]
@lomanyong  大神，是这样的。我这边只有两个module，但是我的代码和资源是放在 app_fanxingv2/src下的文件夹，而不是 app_fanxingv2/src/main。所以，就导致有冲突了。

**Comment by lomanyong** [comment]
@whistlexie build.gralde中有对`sourceSets`做过设置吗？

**Comment by charvenhe** [comment]
@whistlexie 请问下你的工程是否从eclipse迁移过来的呢

**Comment by whistlexie** [comment]
@lomanyong  SourceSet 设置没问题，只不过是我在其他 SourceSet 也包含了 manifest 文件

**Comment by whistlexie** [comment]
@charvenhe @lomanyong   不是的，是 gradle 项目来的。只不过，我的其他 SourceSet 下也含有 manifest 文件，但是 freeline 只读取了 src/main/ 下的 manifest 文件。按照 gradle 实际打包情况是会把这个 manifest 合并的，freeline 好像没有这样做。

**Comment by lomanyong** [comment]
@whistlexie 能麻烦截个图看下工程结构吗？

**Comment by whistlexie** [comment]
@lomanyong  我的项目结构正常。就是 productFlavors 里面用了 dimension.
![image](https://cloud.githubusercontent.com/assets/10007354/19225805/fbdca518-8ed4-11e6-9923-6eb32287ced4.png)
然后 productFlavors 如下：
![image](https://cloud.githubusercontent.com/assets/10007354/19225815/244f0ea0-8ed5-11e6-93fb-119c5a63a2af.png)
如果你们新版支持 dimension 请告知一下，不胜感激！！！

**Comment by lomanyong** [comment]
@whistlexie 能够再提供一下你们`sourceSets`的配置吗？看样子你们对每个flavor都设置了单独的manifest之类的内容？

**Comment by whistlexie** [comment]
@lomanyong  抱歉，回复晚了。下面是我的 productFlavors 和 sourceSets 的配置：
 flavorDimensions "channel", "type"
    productFlavors {
        dev {
            dimension "channel"
            dependencies {
			........
            }
        }
        c_normal {
            dimension "channel"
        }
        fast {
            dimension "channel"
            minSdkVersion 21

            dependencies {
			........
            }
        }
        fanxing {
            dimension "type"
            dependencies {
			........
            }
        }
    }
    sourceSets {
        dev_test {
            manifest.srcFile './src/dev/AndroidManifest.xml'
            java.srcDirs = ['./src/dev/java']
            res.srcDirs = ['./src/dev/res']
        }
        fast {
            manifest.srcFile './src/dev/AndroidManifest.xml'
            java.srcDirs = ['./src/dev/java']
            res.srcDirs = ['./src/dev/res']
        }
    }
![image](https://cloud.githubusercontent.com/assets/10007354/19841824/4c6fc0e6-9f4c-11e6-8814-0bdb8ff1323a.png)
我删了了一些无关的信息。

再次感谢你们的帮助！！！！！

**Comment by captain-miao** [comment]
+1

**Comment by lomanyong** [comment]
@captain-miao @whistlexie flavorDimensions 应该是支持了的，之前的一个版本有做了兼容。你们可以使用正确的 productFlavor 配置进去然后再试试看
