### ISSUE TITLE
FreeLine plugin

### ISSUE THREAD

**Issue by JakeyYe** [alibaba/freeline#177]
为什么FreeLine plugin已经安装了，却还提示错误要求安装FreeLine
![qq 20160929112743](https://cloud.githubusercontent.com/assets/20735044/18940070/1e5aa7c0-8638-11e6-8712-979459879961.png)
![qq 20160929112023](https://cloud.githubusercontent.com/assets/20735044/18940072/1e8deaf4-8638-11e6-976d-b93d0d19e667.png)
![qq 20160929112013](https://cloud.githubusercontent.com/assets/20735044/18940073/20478b20-8638-11e6-9862-30072cd646fb.png)
使用的是AS 2.2,系统Windows10

**Comment by lomanyong** [comment]
@JakeyYe 手动在命令行执行一下`gradlew initFreeline -Pmirror`，然后再使用插件看看。

@pengwei1024 估计是插件在初始化的时候有问题。

**Comment by JakeyYe** [comment]
BUILD FAILED , 和#86的结果一样

**Comment by lomanyong** [comment]
@JakeyYe 没有添加`apply plugin: 'com.antfortune.freeline'`？

**Comment by JakeyYe** [comment]
这个不是直接安装在AS上的插件吗？直接安装，直接使用？

**Comment by JakeyYe** [comment]
加上classpath和apply plugin可以使用了，但那个按钮Run Freeline一直没用啊

**Comment by lomanyong** [comment]
@JakeyYe 一直没用的意思是什么呢？

freeline原本是个terminal工具，第三方开发来插件来辅助使用。相关的配置还是需要添加的。

**Comment by JakeyYe** [comment]
那要配置的就是classpath和apply plugin吧，配置了这些是可以使用了，但点击那Run Freeline按钮还是没用，错误提示还是这个
![1e8deaf4-8638-11e6-976d-b93d0d19e667](https://cloud.githubusercontent.com/assets/20735044/18944994/eed87e28-865a-11e6-9775-b892b139fc87.png)

**Comment by lomanyong** [comment]
@JakeyYe 项目目录下没有`freeline.py`这个文件吗？

**Comment by JakeyYe** [comment]
没有

**Comment by lomanyong** [comment]
@JakeyYe 那样的话freeline并没有用起来，加入后执行`gradlew initFreeline -Pmirror`，然后插件应该就可以使用了。

**Comment by JakeyYe** [comment]
你的意思是要先配置好classpath和apply plugin，再在Terminal执行gradlew initFreeline -Pmirror,就可以使用那按钮Run Freeline了？

**Comment by lomanyong** [comment]
@JakeyYe 恩，后面README我再更新一下吧。有点说的不清楚，插件看上去也有点bug，我们尽快修复。按理说插件会自动给你安装freeline的依赖的。

**Comment by JakeyYe** [comment]
嗯好，谢谢
