### ISSUE TITLE
不支持lambda、kotlin

### ISSUE THREAD

**Issue by ImKarl** [alibaba/freeline#18]
经过简单测试，freeline 不支持 `gradle-retrolambda`、`kotlin`

并且，在每次执行`python freeline.py`后，撤回代码修改会有警告：
> Undo Reload from Disk?

**Comment by lomanyong** [comment]
@ImKarl 现在暂时确实还不支持任何需要apt插件的库，包括butterknife这些。但是主流的注解库以及apt插件库我们都会在后面陆续支持的，欢迎贾诩关注~

关于`Undo Reload from Disk`这个问题，这个应该不会影响开发。主要是freeline没有执行完之后会更新文件的mtime，IDE会认为文件在IDE之外被修改了触发`Undo Reload from Disk`的提示。对实际开发不会有太大影响的

**Comment by ImKarl** [comment]
期待ing…… ╰（￣▽￣）╭

**Comment by ohmerhe** [comment]
kotlin 文件发生变化以后，没有检测到修改

**Comment by lomanyong** [comment]
@ohmerhe 目前不支持kotlin..
