### ISSUE TITLE
这个错误是怎么引起的:Execution failed for task ':Client:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by smoothdvd** [alibaba/freeline#182]
Client:transformClassesWithDexForDebug'.
21:48:30.193 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 66796 into a non-jumbo instruction!

**Comment by lomanyong** [comment]
@smoothdvd 麻烦确认一下是否是因为freeline引起的呢？看着是你们自己工程的问题？

**Comment by smoothdvd** [comment]
@lomanyong 好象是Dex超过上限的错误，移掉了几个库之后可以了。但是直接用Android Studio的默认gradle是不会报Dex错误。

**Comment by lomanyong** [comment]
@smoothdvd freeline本身也有method数量...加上multiDex的话应该就没问题了。
