### ISSUE TITLE
python freeline.py 不通过

### ISSUE THREAD

**Issue by evan0502** [alibaba/freeline#184]
所有都配置好了，但是执行脚本的时候则出现以下错误，但是Demo又是没问题的，需要帮助，谢谢！

Evan:Welltang Evan$ python freeline.py 
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.0s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Evan/AndroidStudioProjects/Welltang/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/Evan/AndroidStudioProjects/Welltang/freeline/freeline_core/gradle_clean_build.py", line 71, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/Evan/AndroidStudioProjects/Welltang/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@evan0502 `python freeline.py -d`，然后发下详细的日志看下？

目测是参数格式的问题导致的，可能跟你本地的一些环境有关。

**Comment by zjc** [comment]
localhost:welltang mark$ python freeline.py -d 
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False)
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /Users/mark/git/welltang/welltang_patient/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 627987
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save welltang_patient module file stat
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save welltang_patient_yidu_library module file stat
[DEBUG] [generate_file_stat_task] save welltang_patient_doctor_library module file stat
[DEBUG] [generate_file_stat_task] save welltang_bluetooth_device_library module file stat
[DEBUG] [generate_file_stat_task] save welltang_share_library module file stat
[DEBUG] [generate_file_stat_task] save welltang_report_library module file stat
[DEBUG] [generate_file_stat_task] save welltang_zxing_library module file stat
[DEBUG] [generate_file_stat_task] save welltang_multi_image_library module file stat
[DEBUG] [generate_file_stat_task] save welltang_common_library module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.1s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.15s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mark/git/welltang/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/mark/git/welltang/freeline/freeline_core/gradle_clean_build.py", line 71, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/mark/git/welltang/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.1s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------
错误应该大同小异，我和evan0502是同一个工程

**Comment by evan0502** [comment]
@lomanyong 麻烦请参考 @zjc 贴出的日志，谢谢！

**Comment by lomanyong** [comment]
@evan0502 @zjc 在terminal手动执行`./gradlew -q checkBeforeCleanBuild`，会报错吗？

**Comment by evan0502** [comment]
@lomanyong 参考下面log

No such file or directory
freeline auto add runtime dependencies: 0.7.2
variant normalDebug is not develop, skip hack process.
variant normalStage is not debug, skip hack process.
variant normalRelease is not debug, skip hack process.
find variant developDebug start hack process...
variant developStage is not debug, skip hack process.
variant developRelease is not debug, skip hack process.
{
    "project_type": "gradle",
    "java_home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home",
    "freeline_cache_dir": "/Users/Evan/.freeline/cache/a4f00cdd279ce04f5326b38c3013d35a",
    "auto_dependency": true,
    "product_flavor": "develop",
    "build_script": "./gradlew assembleDevelopDebug",
    "build_script_work_directory": "",
    "root_dir": "/Users/Evan/AndroidStudioProjects/Welltang",
    "main_project_name": "welltang_patient",
    "main_project_dir": "welltang_patient",
    "build_directory": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/build",
    "build_cache_dir": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/build/freeline",
    "build_tools_version": "24.0.0",
    "sdk_directory": "/Users/Evan/Develop/sdk",
    "build_tools_directory": "/Users/Evan/Develop/sdk/build-tools/24.0.0",
    "compile_sdk_version": "android-24",
    "compile_sdk_directory": "/Users/Evan/Develop/sdk/platforms/android-24",
    "package": "com.byb.patient",
    "debug_package": "com.byb.patient",
    "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/AndroidManifest.xml",
    "launcher": "com.byb.patient.StartPageActivity_",
    "apk_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/build/outputs/apk/welltang_patient-develop-debug.apk",
    "extra_dep_res_paths": [
        
    ],
    "exclude_dep_res_paths": [
        
    ],
    "main_r_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/build/generated/source/r/develop/debug/R.java",
    "main_src_directory": [
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/java",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/java",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/java",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/java"
    ],
    "main_res_directory": [
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/res",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/res",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/res",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/res"
    ],
    "main_assets_directory": [
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/assets",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/assets",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/assets",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/assets"
    ],
    "main_jni_directory": [
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/jni",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/jni",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/jni",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/jni"
    ],
    "main_jniLibs_directory": [
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/jniLibs",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/jniLibs",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/jniLibs",
        "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/jniLibs"
    ],
    "project_source_sets": {
        "welltang_patient": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/developDebug/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/buildType/debug/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/develop/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient/src/main/AndroidManifest.xml"
        },
        "welltang_patient_yidu_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library/src/main/AndroidManifest.xml"
        },
        "welltang_patient_doctor_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library/src/main/AndroidManifest.xml"
        },
        "welltang_bluetooth_device_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library/src/main/AndroidManifest.xml"
        },
        "welltang_share_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library/src/main/AndroidManifest.xml"
        },
        "welltang_report_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library/src/main/AndroidManifest.xml"
        },
        "welltang_zxing_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library/src/main/AndroidManifest.xml"
        },
        "welltang_multi_image_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library/src/main/AndroidManifest.xml"
        },
        "welltang_common_library": {
            "main_src_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/release/java",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/main/java"
            ],
            "main_res_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/release/res",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/main/res"
            ],
            "main_assets_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/release/assets",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/main/assets"
            ],
            "main_jni_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/release/jni",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/release/jniLibs",
                "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/main/jniLibs"
            ],
            "main_manifest_path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library/src/main/AndroidManifest.xml"
        }
    },
    "modules": [
        {
            "name": "welltang_patient",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient"
        },
        {
            "name": "welltang_patient_yidu_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_yidu_library"
        },
        {
            "name": "welltang_patient_doctor_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_patient_doctor_library"
        },
        {
            "name": "welltang_bluetooth_device_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_bluetooth_device_library"
        },
        {
            "name": "welltang_share_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_share_library"
        },
        {
            "name": "welltang_report_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_report_library"
        },
        {
            "name": "welltang_zxing_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_zxing_library"
        },
        {
            "name": "welltang_multi_image_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_multi_image_library"
        },
        {
            "name": "welltang_common_library",
            "path": "/Users/Evan/AndroidStudioProjects/Welltang/welltang_common_library"
        }
    ],
    "module_dependencies": {
        "welltang_patient": [
            "welltang_patient_yidu_library"
        ],
        "welltang_patient_yidu_library": [
            "welltang_patient_doctor_library",
            "welltang_bluetooth_device_library"
        ],
        "welltang_patient_doctor_library": [
            "welltang_share_library",
            "welltang_report_library",
            "welltang_zxing_library",
            "welltang_multi_image_library"
        ],
        "welltang_share_library": [
            "welltang_common_library"
        ],
        "welltang_common_library": [
            
        ],
        "welltang_report_library": [
            "welltang_common_library"
        ],
        "welltang_zxing_library": [
            "welltang_common_library"
        ],
        "welltang_multi_image_library": [
            "welltang_common_library"
        ],
        "welltang_bluetooth_device_library": [
            
        ]
    }
}
Old file /Users/Evan/.freeline/cache/a4f00cdd279ce04f5326b38c3013d35a/project_description.json removed.
Save to /Users/Evan/.freeline/cache/a4f00cdd279ce04f5326b38c3013d35a/project_description.json

**Comment by lomanyong** [comment]
@evan0502 `gradlew`这个文件打开，第一行是`#!/usr/bin/env bash`吗？如果不是的话，把`#!/usr/bin/env bash`加入到第一行，然后重新执行freeline看看。

**Comment by evan0502** [comment]
@lomanyong 问题解决了，确实是因为第一行错误的原因，谢谢！
