### ISSUE TITLE
如何构建我想要的buildType

### ISSUE THREAD

**Issue by evan0502** [alibaba/freeline#187]
我的build.gradle 的buildTypes如下
buildTypes {
        release {
        }
        stage {
        }
        debug {
        }
}

而我此时想构建release的版本，如下图
![image](https://cloud.githubusercontent.com/assets/8966069/19218843/03b542b6-8e37-11e6-802d-f2547ba61c01.png)

执行python freeline.py 后，仍然是debug版本。
请问怎么才能构建出release的版本？

**Comment by lomanyong** [comment]
@evan0502 freeline主要用于开发时的加速编译~如果想要打release包的话，推荐直接使用assembleRelease来打，freeline不负责这个的~

**Comment by evan0502** [comment]
OK,  Thanks a lot !

**Comment by BigOcto** [comment]
你好，可能存在一种情况，
buildTypes {
release {
}
debug {
}
debug_99{
}
}

现在我构建时候，执行
   freeline {
        hack true
        buildScript "./gradlew assembleDebug_99"
    }
发现构建的结果，还是debug的

**Comment by lomanyong** [comment]
@BigOcto freeline目前默认只构建debug版本的包...
