### ISSUE TITLE
python freeline.py 应用无法启动

### ISSUE THREAD

**Issue by tengbinlive** [alibaba/freeline#189]
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.3s
[-][gradle_aapt_task] finished. in 0.0s
[-][app] finished. in 2.1s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] finished. in 0.3s
[-][clean_cache_task] finished. in 0.0s
[-][update_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 2.3s
[DEBUG] Total time: 2.5s
[DEBUG] --------------------------------------------------------

配置:
 
        classpath 'com.antfortune.freeline:gradle:0.7.2'
 
app:
freeline {
        hack true
        productFlavor "dev"
        autoDependency false
        applicationProxy false
    }

    debugCompile 'com.antfortune.freeline:runtime:0.7.2'
    alphaCompile 'com.antfortune.freeline:runtime:0.7.2'
    stagingCompile 'com.antfortune.freeline:runtime:0.7.2'
    releaseCompile 'com.antfortune.freeline:runtime-no-op:0.7.2'
    testCompile 'com.antfortune.freeline:runtime-no-op:0.7.2'

clean 再编译 第一次 正常启动. 随意修改再运行异常.

手机:
nexus 5
android 6.0.1

android studio 2.2
![screenshot_20161010-170702](https://cloud.githubusercontent.com/assets/6283933/19231931/659012c6-8f0f-11e6-8b60-022fd13ccb25.png)

**Comment by lomanyong** [comment]
@tengbinlive 启动异常的log是什么呢？

**Comment by tengbinlive** [comment]
@lomanyong  可能是跟我项目结构有关. 
其中有view做了缓存处理. 
freeline 启动的时候 造成了:
Make sure other views do not use the same id

**Comment by lomanyong** [comment]
@tengbinlive 恩，麻烦你可以再处理一下你们项目的情况，有什么都可以在issue里反馈..

**Comment by tengbinlive** [comment]
@lomanyong  好的.  谢谢了.
