### ISSUE TITLE
开发时用了android-iconify，似乎freeline不会自动加入这个库的asset目录里的字体（freeline是不是默认扫描res目录？）。

### ISSUE THREAD

**Issue by smoothdvd** [alibaba/freeline#191]
如何手动加入？
找到文件在`./app/build/intermediates/assets/develop/debug/iconify`这个目录下，试着在extraResourceDependencyPaths里加入，没有起作用。

**Comment by lomanyong** [comment]
@smoothdvd freeline目前没有自动去import额外的assets目录，`extraResourceDependencyPaths`这个路径是添加resources的，这个后面支持吧，我加入enhancement标签。

**Comment by smoothdvd** [comment]
我现在手动加到了resources_dependencies.json里，修改layout res文件后倒是可以增量编译了，这么做不知道对不对。

**Comment by lomanyong** [comment]
@smoothdvd 你`extraResourceDependencyPaths `使用得对吗？

类似这样：
````gradle
freeline {
    extraResourceDependencyPaths = ["your-res-path"]
}
````

**Comment by smoothdvd** [comment]
@lomanyong 试过了，
```
extraResourceDependencyPaths = ["/Users/alexgao/Dev/dszhclient-android/app/build/intermediates/exploded-aar/com.joanzapata.iconify/android-iconify-ionicons/2.2.2/assets"]

java.lang.RuntimeException: Font asset not found iconify/android-iconify-ionicons.ttf
```

**Comment by lomanyong** [comment]
@smoothdvd 恩，assets还是不会被加入，只有resource可以。这个需要后面更新来支持了。

**Comment by smoothdvd** [comment]
@lomanyong 期待

**Comment by lomanyong** [comment]
@smoothdvd 前几天业务有点忙，开发delay了一些，大概今晚或者明天会发布 0.7.4 版本，你的这个问题就能够解决了。
