### ISSUE TITLE
无法使用自定义的Application，会出现Caused by: java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to 错误

### ISSUE THREAD

**Issue by littleGnAl** [alibaba/freeline#192]
使用freeline 会出现以下错误 Caused by: java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to 自定义Application<br/>
已经在app/build.gradle下添加
```groovy
freeline {
    hack true
    applicationProxy false
  }
```

**Comment by lomanyong** [comment]
@littleGnAl 先clean一下，再重新build呢？

有可能是因为缓存没有清楚，仍然使用之前的配置导致的。
