### ISSUE TITLE
运行python freeline.py时报错，提示productFlavor未设置。

### ISSUE THREAD

**Issue by Dwan-xie** [alibaba/freeline#194]
运行python freeline.py时报错，提示productFlavor未设置。
在build.gradle我做了如下的设置：
freeline {
        hack true
        productFlavor "babytree"
        autoDependency false
}
但还是没有会提示没有找到productFlavor

**Comment by lomanyong** [comment]
@Dwan-xie 能贴下详细的日志吗？

**Comment by lomanyong** [comment]
经过交流，主要是eclipse迁移过来的工程结构引起的各种问题...暂时won't fix..
