### ISSUE TITLE
freeline.py 能不能加一个参数可以让debugger连接上后再让app继续运行

### ISSUE THREAD

**Issue by smoothdvd** [alibaba/freeline#195]
我现在是每次手动adb shell am set-debug-app -w packagename

**Comment by lomanyong** [comment]
@smoothdvd 不能运行之后在IDE使用attach debugger吗？直接使用debugger来编译的话，freeline的功能是无法生效的。

**Comment by smoothdvd** [comment]
@lomanyong 我的意思是能不能让freeline去执行adb shell am set-debug-app -w packagename，这样app就是一直等待直到debugger attach上之后才开始真正执行。运行之后在IDE使用attach debugge的话有些代码民已经执行了。

**Comment by lomanyong** [comment]
@smoothdvd 了解，也可以解决。还有，其实现在最简单实现的方法是，你可以在启动的时候加个Thread.sleep(5000);，也能够暂时解决你要的问题。

**Comment by smoothdvd** [comment]
@lomanyong OK。这个问题不急。

**Comment by lomanyong** [comment]
@smoothdvd 全量编译启动的时候加入了`wait for debugger`的功能使用`python freeline.py -f -w`即可。增量的时候`wait for debugger`会在后面加入，目前也可以直接在AS中使用`attach debugger`
