### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.abcd.app.base.MyApplication"

### ISSUE THREAD

**Issue by eritpchy** [alibaba/freeline#196]
正确的路径为com.abc.base.MyApplication
freeline中识别成com.abcd.app.base.MyApplication
暂时把 android:name=".base.MyApplication"改成 android:name="com.abc.base.MyApplication" 解决了

<manifest package="com.abc"

    <application
        android:name=".base.MyApplication"
    </application>

</manifest>

gradle中指定为
applicationId "com.abcd.app"

**Comment by lomanyong** [comment]
@eritpchy 恩，了解。Freeline优先认为packageName是applicationId导致的这个问题。
