### ISSUE TITLE
在python v3.6版本上，出现语法不兼容情况

### ISSUE THREAD

**Issue by XeoOuYang** [alibaba/freeline#197]
![35517-ef6e5d99d7b4ef1f341a0bc7815183f9](https://cloud.githubusercontent.com/assets/22720355/19373548/59b65222-91f7-11e6-9462-1c3d8f95615a.jpg)

python语法说明
![30175-c4c9620479034d3dd3bd1f6c05254b4d](https://cloud.githubusercontent.com/assets/22720355/19373553/6ebf20e0-91f7-11e6-90ac-e6e2ffe617b2.jpg)

自行解决

**Comment by lomanyong** [comment]
@XeoOuYang freeline不支持Python 3+的，麻烦切换一下Python版本。
