### ISSUE TITLE
资源文件的奇葩注解引起的问题

### ISSUE THREAD

**Issue by XeoOuYang** [alibaba/freeline#198]
当资源文件出现的注解，会生成错误的缓存R文件。

R文件会生成一段新的注解为
/**
/*** 我是例子 **/
*/

从而导致资源重编的时候，出现语法错误

**Comment by lomanyong** [comment]
@XeoOuYang 额，这个是不规范用法导致的，目前没有修复这个问题的打算，麻烦自己处理一下这样的注释吧。
