### ISSUE TITLE
为什么测试demo 构建时间并没有提升呢

### ISSUE THREAD

**Issue by zhuldu** [alibaba/freeline#2]
python freeline.py -f
执行这个命令后还是要36s以上

**Comment by charvenhe** [comment]
@zhuldu -f是走的强制全量构建，涉及到把缓存清除，增量模式是直接通过 ”python freeline.py“ 不带“-f”，是在第二次执行时候开始进入增量模式

**Comment by zhuldu** [comment]
@charvenhe 3q,原来我搞错了。请教一下：build base resources failed with: 后面很多得错误这个要怎么解决呢？您知道大概是哪里出问题了么？`[ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/zhujj/Library/Android/sdk/platforms/android-23/android.jar -M /Users/zhujj/AndroidStudioProjects/******/app/src/main/AndroidManifest.xml -S /Users/zhujj/AndroidStudioProjects/******/app/src/main/res -S /Users/zhujj/AndroidStudioProjects/Momo/android_hanisdk/hanisdk/src/main/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android/1.3.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.5.0/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.android.support/cardview-v7/23.0.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.0.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/io.fabric.sdk.android/fabric/1.3.10/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/answers/1.3.6/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/crashlytics-core/2.3.8/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/crashlytics-ndk/1.1.2/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/localyticsintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/amplitudeintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/optimizely-editor/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/optimizely-view/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/universalanalyticsintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/optimizely-core/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/mixpanelintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.optimizely/optimizely/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.twitter.sdk.android/twitter-core/1.6.3/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.digits.sdk.android/digits/1.9.3/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/beta/1.1.4/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/crashlytics/2.5.5/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/okhttputils-release/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/player-java-release/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/it.sephiroth.android.library.easing/android-easing/1.0.3/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.bignerdranch.android/recyclerview-multiselect/0.2/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/zhujj/AndroidStudioProjects/******/app/build/freeline/app/backup/res -A /Users/zhujj/AndroidStudioProjects/******/app/build/freeline/freeline-assets -A /Users/zhujj/AndroidStudioProjects/******/app/src/main/assets -m -J /Users/zhujj/AndroidStudioProjects/******/app/build/freeline/app/backup --auto-add-overlay -F /Users/zhujj/AndroidStudioProjects/******/app/build/freeline/base-res.so --debug-mode --resoucres-md5-cache-path /Users/zhujj/AndroidStudioProjects/******/app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[ERROR] --------------------------------------------------------`


*****的地方是app的目录

**Comment by lomanyong** [comment]
@zhuldu 可以贴下完整的保存日志吗？不只是最后这行命令的

**Comment by zhuldu** [comment]
@lomanyong 下面是全部的日志，是不是前面的错误导致的，我正在处理这些问题
python freeline.py
[WARNING] NoInstallationException occurs, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 6.5s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] finished. in 113.2s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 22.4s
[-][build_base_resource_task] failed. in 7.6s
[-][generate_project_info_task] finished. in 0.0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Freeline trace:: makeFileResources all resource. Time Elapsed: 19015.082000 ms 
Freeline trace:: compile values. Time Elapsed: 665.780000 ms 
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 1.017000 ms 

-resoucres-md5-cache-path = /Users/zhujj/AndroidStudioProjects/********/app/build/freeline/arsc_cache.dat
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
/Users/zhujj/AndroidStudioProjects/Momo/android_hanisdk/hanisdk/src/main/res/drawable-xhdpi/hani_null_placeholder_image.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/zhujj/AndroidStudioProjects/********/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:8656: error: Public symbol string/com.crashlytics.android.build_id declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/zhujj/Library/Android/sdk/platforms/android-23/android.jar -M /Users/zhujj/AndroidStudioProjects/********/app/src/main/AndroidManifest.xml -S /Users/zhujj/AndroidStudioProjects/********/app/src/main/res -S /Users/zhujj/AndroidStudioProjects/Momo/android_hanisdk/hanisdk/src/main/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android/1.3.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.5.0/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.android.support/cardview-v7/23.0.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.0.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/io.fabric.sdk.android/fabric/1.3.10/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/answers/1.3.6/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/crashlytics-core/2.3.8/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/crashlytics-ndk/1.1.2/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/localyticsintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/amplitudeintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/optimizely-editor/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/optimizely-view/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/universalanalyticsintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/optimizely-core/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/mixpanelintegration/1.5.0/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.optimizely/optimizely/1.6.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.twitter.sdk.android/twitter-core/1.6.3/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.digits.sdk.android/digits/1.9.3/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/beta/1.1.4/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.crashlytics.sdk.android/crashlytics/2.5.5/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/okhttputils-release/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/player-java-release/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/it.sephiroth.android.library.easing/android-easing/1.0.3/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.bignerdranch.android/recyclerview-multiselect/0.2/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/zhujj/AndroidStudioProjects/********/app/build/freeline/app/backup/res -A /Users/zhujj/AndroidStudioProjects/********/app/build/freeline/freeline-assets -A /Users/zhujj/AndroidStudioProjects/********/app/src/main/assets -m -J /Users/zhujj/AndroidStudioProjects/********/app/build/freeline/app/backup --auto-add-overlay -F /Users/zhujj/AndroidStudioProjects/********/app/build/freeline/base-res.so --debug-mode --resoucres-md5-cache-path /Users/zhujj/AndroidStudioProjects/********/app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 13.7s
[DEBUG] Task engine running time: 142.1s
[DEBUG] Total time: 155.8s
[DEBUG] --------------------------------------------------------

**Comment by charvenhe** [comment]
@zhuldu "com.crashlytics.android.build_id"排查下所在的资料路径是否在上面的-S 参数里面没出现，是的话，可以通过DSL 补充一下：

Exception: Public symbol xxxx declared here is not defined.

Aapt 打资源包报错。在aapt的参数中，缺少某些未被freeline自动识别的资源路径，导致部分资源id没有被找到。将缺少的资源路径，在build.gradle的freeline DSL中加入配置项：extraResourceDependencyPaths = ['com.crashlytics.android.build_id 所在资源的目录路径（res的上一级）']

https://github.com/alibaba/freeline/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by zhuldu** [comment]
@charvenhe 谢谢了，那个问题是fabric会在build过程中生成一个xml文件，里面有这么一个string，我在资源文件里写了个相同名字的string，目前没有出问题，现在成功编译完后，做出修改增量更新，会报一下错误，不知道您这边有没有遇到过。
python freeline.py
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.2s
[-][gradle_aapt_task] finished. in 0.0s
[-][uil-library] finished. in 0.0s
[-][app] failed. in 0.0s
[-][merge_dex_task] failed. in 0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhujj/AndroidStudioProjects/*******/freeline/freeline_core/android_tools.py", line 296, in execute
    self._command.execute()
  File "/Users/zhujj/AndroidStudioProjects/*******/freeline/freeline_core/gradle_inc_build.py", line 144, in execute
    map(lambda command: command.execute(), self.command_list)
  File "/Users/zhujj/AndroidStudioProjects/*******/freeline/freeline_core/gradle_inc_build.py", line 144, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "/Users/zhujj/AndroidStudioProjects/*******/freeline/freeline_core/gradle_inc_build.py", line 181, in execute
    self._invoker.run_javac_task()
  File "/Users/zhujj/AndroidStudioProjects/*******/freeline/freeline_core/android_tools.py", line 524, in run_javac_task
    self.debug('javac exec: ' + ' '.join(javacargs))
TypeError: sequence item 0: expected string, NoneType found

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.3s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zhuldu 是否有在环境变量中配置$JAVA_HOME呢？

**Comment by zhuldu** [comment]
@lomanyong  太感谢了，是这个环境变量的问题，现在可以增量编译了，3q，很棒的项目哦

**Comment by charvenhe** [comment]
@zhuldu 不客气，ps，增量前后的数据可以发我们看看吗，另外，你们是什么项目方便说下吗

**Comment by zhuldu** [comment]
@charvenhe 增量的数据怎么发给你们呢？可以私聊么？

**Comment by charvenhe** [comment]
@zhuldu 像上面那样，截图贴一下就好了，github上好像私聊不了..

**Comment by zhuldu** [comment]
@charvenhe 
同样clean后，正常运行三次分为5 mins 1.176 secs，4mins 42.446 secs，4mins 31.257 secs
freeline时间为：100.3s，148.3s，131.4

增量编译，添加删除一行代码：instant-run 为23.235，17.308 secs
freeline时间 基本都在5s以内....

ps，我上面说得我们项目的情况，有解决思路么...3q3q3q

**Comment by charvenhe** [comment]
@zhuldu 好的，资源增量的有时间对比吗，除去首次增量资源增量外的时间。建议用5.x以上的机器多测几次看看

**Comment by lomanyong** [comment]
@zhuldu 可以更新下gradle插件版本：

````gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.antfortune.freeline:gradle:0.5.1'
    }
}
````
重新执行：`./gradlew initFreeline`

验证下是否还会存在子模块修改后无法增量的问题

**Comment by lxxself** [comment]
@charvenhe 二维码失效了，话说freeline编译云信SDK好像有问题，是云信的问题还是freeline哪里需要配置
