### ISSUE TITLE
Freeline开发帮助

### ISSUE THREAD

**Issue by fangkyi02** [alibaba/freeline#200]
首先说一下 不是特别的明白 为啥Freeline是阿里云那边开发的 为啥连个中文文档都没有 所有问题都得自己摸索 今天在window平台上 好不容易运行起来了 也编译出来了 我对gradle这种语法什么的 其实一点都不了解 我主要就是想找一个编译速度快 编译的体积也比较小的工具 这样我就不用考虑编译方面的事情 直接关注代码的开发就可以了 但是freeline真心有点玩不转 我其实就想先一点点了解一下 先从编译一个最简单的helloworld开始 但是freeline带了一大堆的文件 对于新手来说 表示真心不是很懂 这些文件 相互之间的关联是如何进行的 麻烦 大神 能不能搞一个就只编译main下面源码的一个模板出来呢 谢谢了~~~

**Comment by fangkyi02** [comment]
还有一点 我不是特别明白 我其实只想要让他能编译出来apk而已 为啥我直接Python freeline 以后 到最后 还会执行adb呢？然后就一直卡死在那边 要等好久才能过去
如果我用python freeline -f 以后 就卡死在[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
到底这么编译才是单独只进行编译 而不会执行其他的

**Comment by fangkyi02** [comment]
我想说作者在后面加上adb是为了能调试方便点 而且还加上了多次重连 
虽然不错 但是 你也得看一下 我有没有插手机嘛 我没插手机 你一直不停的去尝试连接手机设备 这不是浪费时间嘛 本来几秒能编译出来了 你加上这个 有可能要几分钟才能执行完 

就不能再执行之前先判断一下 有没有手机 或者有没有装过手机驱动吗 不然这样很浪费时间

**Comment by lomanyong** [comment]
@fangkyi02 

1. 中文文档最近几天就会上线到wiki，首页README也会有相关的链接，之前一直都在开发迭代的阶段，所以相关的文档来的慢了点；
2. 我们提供的sample工程其实就是一个简单的hello world的模板；
3. 关于freeline各个模块的关系，最近这段时间我们也终于有时间沉淀一部分的内容了，下周开始应该就可以在社区上陆续看到相关的文章发出了，freeline的Github Repo也会有相关技术文章的链接的；
4. freeline不是一个编译出apk的工具，而是一个帮助你将你的修改快速部署到你的手机上的工具，所以最后还是会执行adb命令去安装，而不是你想的只是编译出一个apk；
5. freeline没有提供单独编译而不执行其他操作的命令，如果你想要单独编译的话，你可以执行gradle的编译命令，这样更能满足你的需求；
6. 不知道你是运行了哪个case导致了adb连接了十几分钟呢？据测试的情况，重连10次的话应该是不会超过20s的。我们默认用户是会连接手机或者打开模拟器来调试的，重连失败的原因不只是只有一个手机没连接，还有其他多种原因。如果重连失败的话，最终会去检查是否有手机连接，以及apk是否安装到手机上的

现在freeline在你们的工程上应用是遇见了什么问题了呢？麻烦写出具体的问题，然后我们帮你解决一下吧。

**Comment by fangkyi02** [comment]
我对这一块是完全小白的 说的不对不要见怪 因为我只想找一个能帮助我编译开发的工具 只要能做饭几点 编译速度快 体积小 一键自动化那种 因为小成本投资的关系 所以实在没有太多的时间 把所有相关的文档跟代码全部看一遍 从而把整个开发周期都花在如何编译上 而不去项目本身的代码编译上 ant gradle buck 我都有去了解过 各有各的优势 然后看到了freeline 原本我以为是集合家之所长的 不管是编译体积或者速度 都是领先的 但是现在来看的话 不仅文档少的可怜 而且入门也不容易啊 而且如果想要另立一个文件夹放项目的话 还需要复制很多东西过去才可以 我就想 为啥不能支持python freeline.py -path 项目路径 -outpath 输出路径 这样的方式来么？一定要复制一大堆的东西 然后每个项目配置一下环境才可以 why? 还有 你说的是快速部署到手机上 但是其实我就想找一个跟buck差不多编译速度 而且有非常全的中文文档 不用老是去国外找资料的那种 不过看样子 现在的期望有点太过遥远 如果我把这个freeline放到服务器上让他自动部署 还不得一直卡在adb那边啊 就算你速度快 也体现不出来了吧

**Comment by fangkyi02** [comment]
还有 我上面的评论 可从来没说连接adb能连接10几分钟 不要臆想好吗？

**Comment by fangkyi02** [comment]
还有 我知道你sample下面就是一个简单例子 但是 貌似 你附带的东西太多了吧 我表示真心没时间 把你的东西一个个都去看一遍 buck的例子也没你这个文件复杂吧 表示小白言论 因为对于我来说 我连一个我所要达到的效果都没看到 就想让别人把你所有源码都看一遍去做深入研究 你觉得可能吗？也没这个时间啊

**Comment by lomanyong** [comment]
@fangkyi02 嗯，之前的回复已经大概说明了，我们之前的各种开发阶段变动比较多，所以中文文档确实不全。所以，你现在是遇见了什么问题导致编译不过？

**Comment by fangkyi02** [comment]
我想问一下 如果想在其他目录下编译 是不是一定要复制相关的文件过去然后重新执行一下gradlew initFreeline这样来的么？ 不能直接像buck一样 命令行直接指定一个路径来进行编译吗？

**Comment by lomanyong** [comment]
@fangkyi02 freeline目前不支持全局安装，以及指定cwd。

不知道你指的跟buck一样，是说像buck一样只编译指定的module吗？如果是的话，freeline设计的目的并不是为了支持这个的。

Freeline做的是先做一次全量编译，然后基于全量编译的apk进行增量编译。
