### ISSUE TITLE
增量编译完成安装包也进入手机了,就是不能自己启动,需要手点击

### ISSUE THREAD

**Issue by vipheyue** [alibaba/freeline#201]
heyuedeMacBook-Pro:Feeling-Android-2.0 heyue$ python freeline.py  

[WARNING] some important file missed, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 14.0s
[-][generate_file_stat_task] finished. in 0.3s
[-][gradle_clean_build_task] finished. in 141.8s
[-][clean_all_cache_task] finished. in 0.1s
[-][install_apk_task] finished. in 23.6s
[-][build_base_resource_task] finished. in 15.0s
[-][generate_project_info_task] finished. in 0.0s
[-][append_file_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 179.3s
[DEBUG] Total time: 179.5s
[DEBUG] --------------------------------------------------------
heyuedeMacBook-Pro:Feeling-Android-2.0 heyue$

**Comment by lomanyong** [comment]
@vipheyue 麻烦执行`python freeline.py -d`看看，是否是全量安装完，执行adb install的时候，命令有错误导致的呢？或者是设备offline了的问题？
