### ISSUE TITLE
应用奔溃后不关掉已停止的窗口 会造成热部署失效

### ISSUE THREAD

**Issue by eritpchy** [alibaba/freeline#202]
然后关了再次热部署, freeline 会发现代码没变 再次失效..

**Comment by lomanyong** [comment]
@eritpchy 不是很明白这里所指的case，如果关掉已停止的窗口呢？是否还会出现这个问题？

**Comment by lomanyong** [comment]
大概复现了一下，应该是使用方法的问题，只需要对原有的代码简单敲下回车其实还是可以继续重新增量编译过去的。
