### ISSUE TITLE
Gradle成功。但是用Freeline时报出* Where: Build file 'D:\Downloads\freeline-master\sample\app\build.gradle' line: 1  * What went wrong: A problem occurred evaluating project ':app'. > java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by deepsadness11** [alibaba/freeline#206]
下载Sample.在Gradle下面能够编译成功。但是执行 initFreeline时，一直报出这个* Where:
Build file 'D:\Downloads\freeline-master\sample\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

无从下手。是因为我用的是JDK8吗？Android Studio2.2强制使用jdk8了。

**Comment by lomanyong** [comment]
@deepsadness11 麻烦给出更详细的信息，比如是否是master分支的最新代码，依赖的是哪个版本的？也可以在命令行使用`java -version`确认下Java版本。

我这样用同样的master分支的最新代码，使用`initFreeline`命令没有报错...

**Comment by deepsadness11** [comment]
1. 用的是Studio2.2 内嵌的JRe。应该是1.8 。因为之前修改必须让我改成1.8以上的版本。
2. 是用的最新的master下面的sample。gradle的配置文件，我都没有修改过。

麻烦能告知对比一下，你用的studio版本和配置的java版本吗？我这里再改一下。
我配置了好久，一直都是这个Unsupported major.minor version 52.0的错误。

**Comment by lomanyong** [comment]
@deepsadness11 恩，因为你用的内置的JRE，所以肯定是1.8的。但是你在命令行执行一下`java -veresion`看下，估计会是1.7的。因为JDK8没有配置到环境变量里。

我的就是AS 2.2 + Java 8。

**Comment by lomanyong** [comment]
@deepsadness11 IDE里使用的JDK，跟你在命令行里使用的不是同一个。

**Comment by deepsadness11** [comment]
恩恩。太感谢了。是我电脑的jdk和IDE里面的不一样导致的原因。我卸载JDK1.7，重新安装JDK1.8之后，这个问题就解决了。谢谢！！
可是还是有点问题。出现Task 'initFreeline' not found in project 'app'.了。我去找找解决方案。

**Comment by lomanyong** [comment]
@deepsadness11 sample的话应该都配置好了，不会出现太多问题的。直接执行`gradlew initFreeline -Pmirror`就可以了（-Pmirror是指下载国内镜像路径）

**Comment by deepsadness11** [comment]
sample不知道为什么没跑成功。我重新创建了一个Project，然后配置成功了。
感谢你的帮助。:)

**Comment by connonfodder** [comment]
这里补充我的坑，如果你在IDE里面输入java -version 和  javac -version都是1.8+的话才是正确的，之前安装了1.7后来又安装了1.8，在环境变量设置中c:\Windows\System32放到JAVA_HOME后面去，不然c:\Windows\System32\java.exe 会被调用，那是之前java7设置时放的。参考
http://stackoverflow.com/questions/9609139/javac-and-java-pointing-to-different-environments
