### ISSUE TITLE
增量编译报错:java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by diql** [alibaba/freeline#207]
使用增量编译时, 多次报过java.lang.IncompatibleClassChangeError;错误发生后,只能重新进行一次全量编译才能够解决,比较费时.

**Comment by lomanyong** [comment]
@diql 麻烦问下，修改的类有什么特征吗？是否是抽象类？

**Comment by diql** [comment]
@lomanyong 没有这种特征的.

**Comment by lomanyong** [comment]
@diql 能否提供下使用的设备的系统版本，以及修改的类的相关呢？如果有稳定的复现的路径的话，也麻烦一并提供一下。

这个问题之前只在freeline早期会频繁出现过，没有对inject class导致的问题。

**Comment by diql** [comment]
@lomanyong android6.0, 复现没有尝试过.

**Comment by lomanyong** [comment]
@diql 所以这个问题是偶现吗？

麻烦之后出现这个问题的时候可以截获下更详细的日志发给我们哈。我这里也多找下复现的路径。

**Comment by diql** [comment]
@lomanyong 问题本来就不是必现的,但是出现频率比较高,跟具体修改的地方没有必然的联系.

**Comment by WelliJohn** [comment]
我也出现这个问题了，不过出现的问题类是继承了一个抽象类，但是我增量编译的时候，是没有更改这个类的

**Comment by lomanyong** [comment]
@WelliJohn get，抽象类的问题我争取最近给解决了，应该可以减少这个问题出现的几率。

**Comment by naixx** [comment]
Having the same issue with modifying lambda in Fragment annotated with `@EFragment` from AndroidAnnotations. If you need any particular details, please tell

**Comment by charvenhe** [comment]
该情况需要连同引用抽象类的类一并修改，暂时没有更好办法能解决该问题

**Comment by leoleohan** [comment]
修改抽象类会出现此issue

**Comment by a3349384** [comment]
我也出现了这个问题。在抽象类中新增了一个变量。
