### ISSUE TITLE
incremental build task failed.

### ISSUE THREAD

**Issue by junjle** [alibaba/freeline#208]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\trunk\freeline_core\android_tools.py", line 307, in execute
    self._command.execute()
  File "C:\code\trunk\freeline_core\gradle_inc_build.py", line 176, in execute
    map(lambda command: command.execute(), self.command_list)
  File "C:\code\trunk\freeline_core\gradle_inc_build.py", line 176, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "C:\code\trunk\freeline_core\gradle_inc_build.py", line 214, in execute
    self._invoker.run_javac_task()
  File "C:\code\trunk\freeline_core\gradle_inc_build.py", line 471, in run_javac_task
    output, err, code = cexec(javacargs, callback=None)
  File "C:\code\trunk\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 87]

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------

[DEBUG] [hg] hg finish in 0.1s[DEBUG] Prepare tasks time: 0.6s
[DEBUG] Task engine running time: 0.3s
[DEBUG] Total time: 0.9s
[DEBUG] --------------------------------------------------------

[DEBUG] [account] account start to run after waiting 0.1s
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
第一次-f编译完没问题，修改代码之后python freeline.py
就报这个问题，而且错误日志无法看出来是哪里的问题

**Comment by lomanyong** [comment]
@junjle 能麻烦贴下完整的日志吗？这个看着应该是你系统环境的问题导致的，报的是`WindowsError `

**Comment by junjle** [comment]
都是一些文件的名称和修改日志，没有什么有用的信息，我看同事的MAC增量编译出错了会有详细的文字日志输出我的不知道为什么没有

**Comment by lomanyong** [comment]
@junjle 还是有用的...在报错的日志前应该还有一句`'javac exec: xxxx`的日志..你可以看下打出来的命令行是什么。实际上就是执行这个命令的时候报错的，需要看下这个命令有什么问题。

**Comment by junjle** [comment]
方便留个QQ吗，我把完整的日志给你发过去

**Comment by junjle** [comment]
我把日志给你gmail的邮箱了

**Comment by lomanyong** [comment]
@junjle 收到，我看下

**Comment by lomanyong** [comment]
@junjle 问题应该是出在这里`javac exec: C:\Program Files\Java\jdk1.8.0_31\bin\javac.exe -encoding`，jdk的路径里含有一个空格没有转义，导致`C:\Program Files\Java\jdk1.8.0_31\bin\javac.exe`命令行执行时报错...

一个快速的解决办法，简单地挪一下jdk的位置，然后修改下环境变量看看...

**Comment by junjle** [comment]
你的意思是Program Files这个文件的空格吗

**Comment by lomanyong** [comment]
@junjle 是的..你可以在命令行执行一下`C:\Program Files\Java\jdk1.8.0_31\bin\javac.exe -version`，应该也是会报错...

**Comment by junjle** [comment]
确实报错，哎，这是jdk默认的路径...我换了个路径，重新编译一下试试

**Comment by lomanyong** [comment]
@junjle 好的~
