### ISSUE TITLE
[ERROR] merge dex failed: ['java', '-jar', 'freeline\\release- tools\\DexMerge.jar'报错问题的解决

### ISSUE THREAD

**Issue by WelliJohn** [alibaba/freeline#210]
请问下，重新全量编译安装了程序，在用freeline增量编译，在一段时间是可以的，但是好景不长，过一段时间，再修改了代码，再运行，每次都会报[ERROR] merge dex failed: ['java', '-jar', 'freeline\\release-tools\\DexMerge.jar', u'D:\\work\\business\\app\\build\\freeline\\increment.dex',

**Comment by lomanyong** [comment]
@WelliJohn 有这段错误更详细的日志输出吗？merge dex出错的上面应该还有一个错误栈的...

**Comment by WelliJohn** [comment]
不支持1.8的jre吗

**Comment by WelliJohn** [comment]
![image](https://cloud.githubusercontent.com/assets/22828971/19544507/08e296f2-96b2-11e6-8db5-05ccc70d7a48.png)

**Comment by lomanyong** [comment]
@WelliJohn 必然支持的，因为都已经能够支持retrolambda了。这个报错是怎么出现的？不像是freeline导致的报错。

**Comment by WelliJohn** [comment]
sorry,是我本地的原因，我的注册表，中有1.7版本的jre和1.8版本的jre。
