### ISSUE TITLE
修改layout文件后，freeline提示资源ID找不到

### ISSUE THREAD

**Issue by lichangadd** [alibaba/freeline#212]
我们的项目结构是把layout拆分成多个来管理的，但是每次修改layout文件后，freeline都会报错：
```java
 Caused by: android.content.res.Resources$NotFoundException: File res/layout/setting_aty.xml from xml type layout resource ID #0x7f0401c4
```

![image](https://cloud.githubusercontent.com/assets/8686438/19543321/32b21b1e-96a9-11e6-8c02-10a94acaf8c6.png)
![image](https://cloud.githubusercontent.com/assets/8686438/19543329/45e43eb0-96a9-11e6-9fc8-6cb612dd0fc8.png)

**Comment by lomanyong** [comment]
@lichangadd freeline目前不支持二级layout目录的资源编译...其实这也是不规范用法，正确地使用的话，应该还是要放在res/目录下的一级目录使用。这样的资源因为 Gradle 会做 merge 处理，所以用 Gradle 编译能够正常出包，Freeline 编译资源相当于使用 aapt 直接打包，所以会存在一定的差异。

这个问题我本地模拟一下环境看看，看是否可以简单解决。

**Comment by lichangadd** [comment]
后续我们会按照module来进行项目拆分，但是应该有不少友商也会遇到次问题。辛苦了

**Comment by CJWaitFor** [comment]
请问这个问题有没有workaround方案？

**Comment by lomanyong** [comment]
@CJWaitFor 你也是类似的项目结构吗？

**Comment by CJWaitFor** [comment]
对的。可以在编译前手动merge吗？或者有其他什么办法吗
