### ISSUE TITLE
正式签名时会导致失败

### ISSUE THREAD

**Issue by xiaotianyilang** [alibaba/freeline#222]
java.io.IOException: Can't write [/Users/tianshutong/Desktop/xidi-android/build/intermediates/transforms/proguard/xidibuy/release/jars/3/1f/main.jar] (Can't read [/Users/tianshutong/Desktop/xidi-android/build/intermediates/exploded-aar/com.antfortune.freeline/runtime-no-op/0.7.3.1/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:com/antfortune/freeline/FreelineCore.class]))

**Comment by xiaotianyilang** [comment]
debug是没有问题的，但正式打包签名时就出现了这个问题

**Comment by lomanyong** [comment]
@xiaotianyilang 有更详细的报错吗？或者可以先clean一下再来build。这段日志看不出来是freeline在哪里导致了这个问题。

**Comment by xiaotianyilang** [comment]
(Duplicate zip entry [classes.jar:com/antfortune/freeline/FreelineCore.class]))

**Comment by xiaotianyilang** [comment]
(Duplicate zip entry [classes.jar:com/antfortune/freeline/FreelineCore.class]))

**Comment by lomanyong** [comment]
@xiaotianyilang 可以看下你们是否单独在dependency里添加了freeline runtime的依赖了呢？
freeline默认加载的依赖是：

```gradle
dependencies {
        debugCompile "com.antfortune.freeline:runtime:${freelineVersion}"
        releaseCompile "com.antfortune.freeline:runtime-no-op:${freelineVersion}"
        testCompile "com.antfortune.freeline:runtime-no-op:${freelineVersion}"
}
```

**Comment by xiaotianyilang** [comment]
添加了
compile 'com.antfortune.freeline:runtime:0.7.3.1'

**Comment by lomanyong** [comment]
@xiaotianyilang 不是，把那个compile这行去掉应该就好了，其实runtime的依赖，freeline自动给你添加了。
