### ISSUE TITLE
关于 webview loadurl 时，freeline 不起作用的问题

### ISSUE THREAD

**Issue by BruceHurrican** [alibaba/freeline#225]
我的 app 中有个用 webview loadurl 全量编译后，app 部署到终端，修改 url，增量编译成功，但是打开的 app 的界面中的 url 还是原来的url，这个怎样解决？谢谢

**Comment by lomanyong** [comment]
@BruceHurrican 我这边测试时可以加载新的url的，你可以把你的那段代码贴出来看看。

**Comment by BruceHurrican** [comment]
嗯，我用原生 webview 试了下可以的，可能和我们项目自己封装的 webview 中的某些设置有关，我再看下，谢谢啦

**Comment by lomanyong** [comment]
@BruceHurrican 是的，可能是有某些特殊的声明之类导致的，找到原因的话，也可以在issue中分享一下。
