### ISSUE TITLE
initFreeline 后在文件夹根目录下生成的 freeline 文件夹不能使用 AS freeline插件

### ISSUE THREAD

**Issue by BruceHurrican** [alibaba/freeline#226]
工程根目录下有 freeline 文件夹。

- 通过命令行方式 python freeline/freeline.py 可以实现全量编译和增量编译,此时 AS 插件点击会提示“please install Freeline first”的错误信息。

- 我将 freeline 文件夹下的两个文件夹和 freeline.py 文件考到工程根目录下，此时 AS 插件可以正常使用，但是只能做全量编译，不能作增量编译。报错信息同 [#224](https://github.com/alibaba/freeline/issues/224)

**Comment by lomanyong** [comment]
@BruceHurrican 从昨天你报的issue的现象来看，似乎在你的机器上使用`./gradlew initFreeline`表现出来的现象不对。(你那里好像是Mac？)

如果你删掉目录下的所有freeline相关的文件的话，执行完`initFreeline`，你的目录下应该是只有一个`freeline`文件夹，然后有一个`freeline.py`的文件，软链到`freeline/freeline.py`。不需要进行手动拷贝的。执行命令的时候直接`python freeline.py`即可，而不是`python freeline/freeline.py`。

AS提示“please install Freeline first”应该是目录下没有`freeline`文件夹的原因。

麻烦再确认一下现象...

**Comment by BruceHurrican** [comment]
我用的是 mac，这个 freeline 文件夹是我从 dowloading 日志中重新下载下来再考入的，从命令行输入 ./gradlew initFreeline， ./gradlew initFreeline -Pmirror 这两个命令都会卡在 building 0% 这个地方，（所处网络下载电影速度有1M/s）只能通过下载再考入的方法来使用 freeline

**Comment by lomanyong** [comment]
@BruceHurrican 如果加上`-Pmirror`都会卡住的话，很可能的原因是你的terminal访问github的网络有点问题。一个简单的方法，你可以指定你要下载的版本` ./gradlew initFreeline -PfreelineVersion=0.7.3.1`，这样可以绕过对github api的访问。

你可以尝试一下上面提供的方法。

**Comment by BruceHurrican** [comment]
我是通过查看日志中有个 Download  后面有个下载连接，下载下对应的0.7.3这个版本的，然后考入的。我再试下你说的方法，谢谢
