### ISSUE TITLE
修改layout后，报资源文件未定义错误

### ISSUE THREAD

**Issue by lovexujh** [alibaba/freeline#227]
我在layout中为一个控件添加了onClick方法，编译执行报错，修改了layout后很大几率出现,需要重新全部编译。
freeline 0.7.3.1;AS 2.2;MAC
Log:
````
/Users/..../Desktop/workspace/.../build/freeline/.../backup/res/values/freeline_id_keeper_public.xml:21744: error: Public symbol string/notify_no_network declared here is not defined.
````

**Comment by lomanyong** [comment]
@lovexujh 这个log看着是因为删除了string才出现的...freeline目前不支持删除带id的资源...

有其他的日志吗？

**Comment by lovexujh** [comment]
@lomanyong 没有删除任何文件 只是为一个控件添加了onClick方法，然后就报上面的错误，把所有的资源文件都报错了一遍，均是上面同样的错误。

**Comment by lomanyong** [comment]
@lovexujh 一个简单的处理方法可以先试试看`/Users/..../Desktop/workspace/.../build/freeline/.../backup/res/values/freeline_id_keeper_public.xml`，打开这个文件，删除掉`string/notify_no_network`这个声明。然后重新增量试试看。

或者，clean一下，重新全量编译后增量编译。

**Comment by lovexujh** [comment]
@lomanyong 我这里有2W多的同样报错。。。。

**Comment by lomanyong** [comment]
@lovexujh 2w多的报错...？可以把详细的aapt出错的日志包括命令发出来看下...应该会有一个比较明显的地方导致出错的。

**Comment by lovexujh** [comment]
@lomanyong 2W多的报错跟上面的error是一样的，只不过把上面的string后面的名称换成其他的名称，还有drawable/icon_a类似的。

**Comment by lomanyong** [comment]
@lovexujh 这部分日志没办法定位问题的...可以把日志放在txt里发我邮箱一份吧。

我这里需要关注的主要就是aapt命令和aapt报错的日志...按照你的描述，现在应该是任何资源增量编译都会无效...

**Comment by lovexujh** [comment]
@lomanyong 是的，资源文件不能修改，一旦修改就会出这个问题。之前还好的，现在不行了， 重新check的代码重新导入AS还是不行。

**Comment by lomanyong** [comment]
@lovexujh 可以看下这个路径的文件`${main_module}/build/freeline/${main_module}/resources_dependencies.json`，文件的内容是不是空的json...

你日志里的`aapt`命令应该是会比较短，少了很多的资源依赖路径。

**Comment by lovexujh** [comment]
@lomanyong 好吧，把同事的项目拷贝过来好了，哎。。。辛苦你了 @lomanyong

**Comment by lomanyong** [comment]
@lovexujh 好吧= =...
