### ISSUE TITLE
webview load url 时全量编译通过，修改 url增量编译通过，但是 app 没有体现

### ISSUE THREAD

**Issue by BruceHurrican** [alibaba/freeline#228]
我用原生 webview loadurl 时发现如下几种场景freeline 未能正确编译（编译不报错）,为方便描述，设置伪代码如下

```

public class A extends Activity{
    protected void onCreate(Bundle savedInstanceState) {
        webview.loadurl(param);
    }
}

```

操作步骤  
B1: param="http://www.taobao.com"; 全量编译-部署-app, app理论显示结果 R1: 显示http://www.taobao.com页面。
B2: param="http://www.tao2bao.com"; 增量编译-部署-app, app理论显示结果 R2:  显示的是http://www.tao2bao.com页面
- 场景1: param 是局部变量 执行 B1,B2对应R1,R2实际结果和理论结果相同。
- 场景2: param 是全局变量 执行B1,B2对应R1,R2陆陆结果和理论结果相同。
- 场景3: param 是 A 内静态常量即 private/public static final String param=“”；执行 B1,B2对应 R1,R2实际结果和理论结果相同。
- 场景4: param 为 A2中的全局静态常量， 

```

public class A2{
    public static final String param = "";
}

```

执行 B1,B2,对应 R1结果和理论结果相同，但是 R2实际结果显示的是http://www.taobao.com，非 R2理论结果，此时重启 APP 显示的依然是http://www.taobao.com非 R2理论结果，但是可以通过修改其他 java 文件或者loadurl 所在同 java 文件中其他非 String 类型的变量，再执行 B2， R2得到实际结果和理论结果相同，简言之，将 loadurl 中，int a=3;改为 a=4;或者将一行代码注释/反注释这种操作都可以使得 R2的实际结果同理论结果。
- 场景5: param 为 A2中的全局变量，

```

public class A2{
    public String param = "";
}

```

执行B1,B2对应 R1,R2实际结果和理论结果相同。

请问,当前版本的 freeline(0.7.3.1) 是不是对全局静态常量的跨类访问在增量编译时有问题？如上述场景5所述，增量编译通过正常部署 app，但是新的改动并没有在增量编译后体现出来。

**Comment by lomanyong** [comment]
@BruceHurrican 感谢提供case！我在本地再重新验证一下看看。

**Comment by lomanyong** [comment]
@BruceHurrican 我这边测试了，全局静态常量其实在增量编译的时候是生效了，只是没有被重新加载，原因是final修饰了常量。

要让这个类可以增量生效也很简单，在修改全局静态常量的同时，也修改一下你使用这个常量的类即可。比如你修改的全局静态常量URL，同时也在你将要加载这个变更变量的类（比如WebViewActivity），多加一个空行（让freeline检测到这个类存在修改）。两个变更的class同时重新加载，你所做的变更即可生效。目前你可以这么处理。

**Comment by BruceHurrican** [comment]
@lomanyong 你说的方法和上述的场景4提供的解决方案是一样的，A2中的常量发生改变，则调用它的 A 也要做相应的改变，否则增量编译没有效果
