### ISSUE TITLE
运行时提示插件未安装，实际已经安装好了

### ISSUE THREAD

**Issue by ouyangzn** [alibaba/freeline#229]
环境：win10
Android studio：2.2
![error](https://cloud.githubusercontent.com/assets/8808376/19711783/bc7dc738-9b6a-11e6-8f15-cf338bdb9c2c.png)
![plugin](https://cloud.githubusercontent.com/assets/8808376/19711786/c40b75ae-9b6a-11e6-92f9-820775a2aad2.png)

**Comment by sivan67** [comment]
这个是提示你 Freeline 没有初始化，而不是未安装插件


最后，在命令行执行以下命令来下载 freeline 的 python 和二进制依赖。

Windows[CMD]: gradlew initFreeline
Linux/Mac: ./gradlew initFreeline

**Comment by lomanyong** [comment]
@ouyangzn 如 @sivan67 所说，执行一下命令即可，这个问题我近期会优化掉...

**Comment by ouyangzn** [comment]
初始化后还是有问题，说Python没找到，难道还要安装Python环境？
![0](https://cloud.githubusercontent.com/assets/8808376/19756685/02082898-9c51-11e6-8d36-0dcdae310fd9.png)
![1](https://cloud.githubusercontent.com/assets/8808376/19756690/053b7d6c-9c51-11e6-9d88-f5a58648b91a.png)
![2](https://cloud.githubusercontent.com/assets/8808376/19756694/089327c6-9c51-11e6-8b1c-ea3e803288f6.png)
![3](https://cloud.githubusercontent.com/assets/8808376/19756696/0c83c48a-9c51-11e6-8132-b07dde89c56e.png)
![4](https://cloud.githubusercontent.com/assets/8808376/19756703/101a2454-9c51-11e6-87b7-654e42a2ae8d.png)

**Comment by lomanyong** [comment]
@ouyangzn 必然额...freeline能跨平台主要原因是基于python写的...专门为Windows考虑了兼容新问题。需要安装python 2.7版本..

**Comment by ouyangzn** [comment]
好吧，谢啦

**Comment by ouyangzn** [comment]
再问一下，我装好了Python，还是说没找到Python，还要做什么吗？
![python](https://cloud.githubusercontent.com/assets/8808376/19758634/8d2793b4-9c5b-11e6-8ec7-8a05423c870b.png)

**Comment by lomanyong** [comment]
@ouyangzn 有配置到环境变量中吗？检查下安装Python的姿势是否正确吧~或者重启下Android Studio说不定可以解决。
