### ISSUE TITLE
常量修改不生效

### ISSUE THREAD

**Issue by msdx** [alibaba/freeline#235]
发现一个问题。
假如A用到了B的一个常量，那么当只修改B里的这一个常量的时候，运行之后A的值还是之前的，除非修改A文件（譬如加个空行或删个空行的）A才会跟着改。
目测这和Java及Buck同样原理的编译机制有关（把常量直接编译到A里面，而A文件又没有检测到修改所以没有重新编译）。

**Comment by lomanyong** [comment]
@msdx 跟#228 提到的类似，通过反编译可以看到实际上还是修改了，应该是因为final修饰了常量，导致的在运行期没有重新加载...

**Comment by msdx** [comment]
@lomanyong 如果我在A加个空行之类的，再编译一下，则能够生效。

**Comment by msdx** [comment]
能否做到对于这种情况，也检测到A也应该被重新编译和加载？

**Comment by lomanyong** [comment]
@msdx 不好检测其实，这里涉及到freeline现在也存在的一个问题，抽象类的改动容易触发运行期出错。抽象类的变更跟final field类似，重新编译的时候需要把引用或者继承的类一起重新编译。

带来的问题是我们需要在编译期收集抽象类与继承类的关系、final class以及final field与引用类的关系，并在增量编译时做判断是否需要将引用类一起进入重新编译的流程...

如果做到上面这一步的话，就可以解决抽象类/final field or class在增量编译时报错或者不生效的问题了...

抽象类的问题在规划中，之后会去看下怎么处理比较好...

**Comment by msdx** [comment]
@lomanyong 感谢释疑，明白。我没疑问了。这个issue 你可以选择关闭了。
