### ISSUE TITLE
Public symbol id /btn_crash declared here is not defined.

### ISSUE THREAD

**Issue by Lonecy** [alibaba/freeline#236]
我在一个xml文件里加了个按钮btn_crash 然后运行不通过。 报这个错误. 用的是freeline 0.7.3.1版本

app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:6793: error: Public symbol id
/btn_crash declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 1.0s
[DEBUG] Total time: 1.3s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@Lonecy 增加id是没有问题的，可以重新编译试试看，有可能是中间有一些删除之类的操作导致了这个问题。

**Comment by tlrkboy** [comment]
有同样的错误，场景是这样的：
全编通过，我修改了一些layout文件，增量编译，出现declared here is not defined.
查看这些文件的特点，代码中有出现resId = R.id.some_res（其中some_res会出现drawable/some_res declared here is not defined 错误）这样的代码，
我猜测是增量编译的时候，类似于这样的id没有找到

**Comment by lomanyong** [comment]
@tlrkboy 修改的时候是否删除了相关的 id？
