### ISSUE TITLE
请问下什么情况下，freeline重新全量编译完成后，不会自动安装app呢

### ISSUE THREAD

**Issue by WelliJohn** [alibaba/freeline#237]

**Comment by lomanyong** [comment]
@WelliJohn  通常是会自动安装上的。`python freeline.py -d`可以看到日志中有个`adb install`的命令，可以对比一下apk路径、包名、Launcher Activity是否正确，错误的话无法安装上。也可以用命令`adb devices`看下设备是否offline了，如果offline了的话，也无法安装上...

**Comment by WelliJohn** [comment]
另外NoInstallationException occurs, a clean build will be automatically executed.怎么解决

**Comment by lomanyong** [comment]
@WelliJohn 可以参考一下 #152 这个issue哈，如果你声明了`applicationProxy false`，则需要加上`FreelineCore.init(this);`

**Comment by WelliJohn** [comment]
![image](https://cloud.githubusercontent.com/assets/22828971/19760358/037903f6-9c64-11e6-8359-b774e4a7cbbe.png)
我的版本是0.7.3.1现在还是需要增加的是吧

**Comment by lomanyong** [comment]
@WelliJohn 不是，如果声明了`applicationProxy false`的话，是需要增加的`FreelineCore.init(this);`的。默认`applicationProxy true`，所以是不用加的。直接用那个标记`deprecated`的方法就可以了，只含一个参数的~
