### ISSUE TITLE
mac下面运行python freeline.py一直停在下面的页面，是怎么回事啊

### ISSUE THREAD

**Issue by WelliJohn** [alibaba/freeline#241]
![image](https://cloud.githubusercontent.com/assets/22828971/19793423/1f347012-9cff-11e6-9aa3-a83fe054e78f.png)

**Comment by lomanyong** [comment]
@WelliJohn 通常是卡在下载上的。具体可以直接手动运行`./gradlew checkBeforeCleanBuild`来查看为什么这么久。
