### ISSUE TITLE
下面这样的问题，怎么解决呢，我只要一改资源文件，然后增量编译就会出这样的问题，全量编译是ok的

### ISSUE THREAD

**Issue by WelliJohn** [alibaba/freeline#243]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
nothing matches overlay file nav_back.png, for flavor xhdpi-v4
Freeline trace:: makeFileResources all resource. Time Elapsed: 21083.826000 ms 
Freeline trace:: compile values. Time Elapsed: 1005.172000 ms 
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.555000 ms

**Comment by lomanyong** [comment]
@WelliJohn 需要这部分更完整一点的日志才能分析原因..

**Comment by WelliJohn** [comment]
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.4s
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 1.7s
[DEBUG] [qicheChaoren] qicheChaoren start to run after waiting 1.7s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 1.7s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 1.7s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 1.7s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 1.3s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 1.73s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
nothing matches overlay file nav_back.png, for flavor xhdpi-v4
Freeline trace:: makeFileResources all resource. Time Elapsed: 0.056000 ms
Freeline trace:: compile values. Time Elapsed: 0.994000 ms
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.001000 ms

gChangeList = res/layout/activity_store_show_detail.xml:resalues/freeline_id_keeper_public.xml:resalues/freeline_id_keeper_ids.xml
-resoucres-md5-cache-path = D:\work\qccr_git\client\qicheChaoren\build\freeline\arsc_cache.dat
warning: overwriting 'D:\work\qccr_git\client\qicheChaoren\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.7.3.1\assets\apktime' with 'D:\work\qccr_git\client\qicheChaoren\build\freeline\freeline-assets\apktim
e'
D:\work\qccr_git\client\qicheChaoren\build\freeline\qicheChaoren\backup\res\values\freeline_id_keeper_public.xml:7231: error: Public symbol string/growingio_project_id declared here is not defined.
D:\work\qccr_git\client\qicheChaoren\build\freeline\qicheChaoren\backup\res\values\freeline_id_keeper_public.xml:7233: error: Public symbol string/growingio_url_scheme declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------

**Comment by WelliJohn** [comment]
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.4s
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 1.7s
[DEBUG] [testApplication] testApplication start to run after waiting 1.7s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 1.7s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 1.7s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 1.7s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 1.3s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 1.73s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
nothing matches overlay file nav_back.png, for flavor xhdpi-v4
Freeline trace:: makeFileResources all resource. Time Elapsed: 0.056000 ms
Freeline trace:: compile values. Time Elapsed: 0.994000 ms
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.001000 ms

gChangeList = res/layout/store.xml:res alues/freeline_id_keeper_public.xml:res alues/freeline_id_keeper_ids.xml
-resoucres-md5-cache-path = D:\work\qccr_git\client\testApplication\build\freeline\arsc_cache.dat
warning: overwriting 'D:\work\qccr_git\client\testApplication\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.7.3.1\assets\apktime' with 'D:\work\qccr_git\client\testApplication\build\freeline\freeline-assets\apktim
e'
D:\work\qccr_git\client\Test\build\freeline\testApplication\backup\res\values\freeline_id_keeper_public.xml:7231: error: Public symbol string/growingio_project_id declared here is not defined.
D:\work\qccr_git\client\testApplication\build\freeline\testApplication\backup\res\values\freeline_id_keeper_public.xml:7233: error: Public symbol string/growingio_url_scheme declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------

**Comment by WelliJohn** [comment]
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.4s
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 1.7s
[DEBUG] [testApplication] testApplication start to run after waiting 1.7s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 1.7s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 1.7s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 1.7s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 1.3s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 1.73s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
nothing matches overlay file ic_back.png, for flavor xhdpi-v4
Freeline trace:: makeFileResources all resource. Time Elapsed: 0.056000 ms
Freeline trace:: compile values. Time Elapsed: 0.994000 ms
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.001000 ms

gChangeList = res/layout/store.xml:res alues/freeline_id_keeper_public.xml:res alues/freeline_id_keeper_ids.xml
-resoucres-md5-cache-path = D:\work\test_git\client\testApplication\build\freeline\arsc_cache.dat
warning: overwriting 'D:\work\test_git\client\testApplication\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.7.3.1\assets\apktime' with 'D:\work\test_git\client\testApplication\build\freeline\freeline-assets\apktim
e'
D:\work\test_git\client\Test\build\freeline\testApplication\backup\res\values\freeline_id_keeper_public.xml:7231: error: Public symbol string/growingio_project_id declared here is not defined.
D:\work\test_git\client\testApplication\build\freeline\testApplication\backup\res\values\freeline_id_keeper_public.xml:7233: error: Public symbol string/growingio_url_scheme declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------

**Comment by lomanyong** [comment]
@WelliJohn 这个是bug，在0.7.3.1引入的...明天发布0.8.0会修复这个问题..想尽快使用的话可以暂时回退到`0.7.2`...

**Comment by lomanyong** [comment]
@WelliJohn hello，0.8.0已经发布...这个问题已经解决啦...。可以更新试试看
