### ISSUE TITLE
重新安装freeline

### ISSUE THREAD

**Issue by junjle** [alibaba/freeline#247]
我的freeline有点问题不能正常使用，我想完全卸载掉包括文件也清掉，然后重新安装一下，请问怎样操作能完事卸载删除文件啊

**Comment by lomanyong** [comment]
@junjle 正常只需要重新运行`./gradlew initFreeline -Pmirror`即可，当然，你也可以先删除掉文件夹下所有跟freeline相关的文件再运行也可以。
