### ISSUE TITLE
手机端上，长时间的卡在 building increment app 

### ISSUE THREAD

**Issue by tanweijiu** [alibaba/freeline#248]
在小型项目里使用freeline的编译安装更改速度是非常可观的....但是当项目增大到一定程度上（安装包大概是32m了）,pc端编译完成后，手机端就会白屏，卡在 building increment app ...最后app白屏挂掉了...

**Comment by lomanyong** [comment]
@tanweijiu 这个跟安装包大小没啥关系吧...在使用freeline的工程上30M大小的app不少的...。`building increment app`的时候会有个`killProcess`的操作，应该是跟你们工程本身的一些逻辑有所冲突或者没处理好，导致crash或者ANR了...
