### ISSUE TITLE
全量编译时报styles或themes中的属性找不到，增量编译时报各种系统类找不到

### ISSUE THREAD

**Issue by vipjinxiao** [alibaba/freeline#250]
使用python freeline.py -f命令全量编译时，报出类似
/res/values/styles.xml:667: error: Error: No resource found that matches the given name: attr 'android:layout_width'.
...
这样的错误，有很多

尝试过0.7.2、0.7.3.1和0.8.0版本，其中0.7.3.1和0.8.0版本虽然报错，但是实际上编译好像是成功的，应用也能自动跑起来，0.7.2版本应用未能自动跑起来，手动点击时直接crash

在0.7.3.1和0.8.0版本时，全量编译后，修改部分代码，使用python freeline.py命令增量编译时，报
警告: [options] 未与 -source 1.7 一起设置引导类路径
...
 错误: 程序包android.view不存在
import android.view.View;
...
类似的错误

也看过其他的issues，可能有帮助的信息有：
1. jar_dependencies.json文件存在且有内容
2. debug包未开混淆
3. 使用的jdk1.8但未使用lambda等高级语法
4. build.gradle中加入了freeline { hack true}

**Comment by lomanyong** [comment]
@vipjinxiao `错误: 程序包android.view不存在`这个报错不大正常，意味着`android.jar`没有加入classpath。如果使用`python freeline.py -d`的话，会输出debug日志，可以看看javac命令参数里是否有${sdk-dir}/android.jar。

资源没找到的问题（`No resource found`），推荐使用`0.8.0`版本测试。从你的日志里可以看到报错的都是android命名空间的参数未找到，综合上面的叙述，似乎是sdk目录的位置有问题？

在这个路径`~/.freeline/cache/xxxx/project_description.json`这个文件，打开后，会有个`compile_sdk_directory`的字段。在路径`${compile_sdk_directory}/android.jar`，这个android.jar不存在的话，就会引起你上面出现的问题。

可以先排查看看

**Comment by vipjinxiao** [comment]
@lomanyong  确实是你说的这个问题，因为我们的compileSdkVersion写的'Google Inc.:Google APIs:23'，project_description.json中的compile_sdk_directory最后的路径也是/Google Inc.:Google APIs:23，而实际上在/Android/sdk/platforms/中只有android-23文件夹

那现在有什么办法可以解决吗？我将compileSdkVersion改为23的话会导致之前的一些google map的业务用不了。我可以直接修改project_description.json中的compile_sdk_directory么？还是说我只能升级google map api的版本？

**Comment by lomanyong** [comment]
@vipjinxiao 目前还没有提供专门的配置用于定制化修改compileSdkVersion的。

我查了下相关的 SDK 信息，`'Google Inc.:Google APIs:23'`应该是还在使用比较旧的 Map V1 才需要的。新的 Google Map 的 SDK 集成在 Google Play Service 的 SDK 里，应该不需要继续这样添加依赖了。你们可以看下是否可以升级 SDK。

后面的版本我会提供可以定制化地接口..让开发者可以自由地去修改本地的配置项...

**Comment by vipjinxiao** [comment]
好的  谢谢~  那我升级google map吧
