### ISSUE TITLE
一个工程中存在两个application module，切换工程编译报错

### ISSUE THREAD

**Issue by zjc** [alibaba/freeline#251]
我们之前集成了患者端app能正常使用，编译效果非常好，在此表示感谢。但是后来集成医生段app的时候，发现没办法编译了，重新初始化的时候提示： Cannot add task ':initFreeline' as a task with that name already exists.

**Comment by lomanyong** [comment]
@zjc 如果都在一个工程下的话，切换的时候不需要反复重新`initFreeline`的。你可以试试看注释掉其中一个主module的`apply plugin: "com.antfortune.freeline"`，然后添加到另外一个application module上。

照常执行`python freeline.py -f`看看
