### ISSUE TITLE
关于freeline.zip

### ISSUE THREAD

**Issue by pcyan** [alibaba/freeline#252]
可以使用7z之类格式的提高一下压缩率或者减小包的大小吗，每次下十几兆的东西，有点慢

**Comment by lomanyong** [comment]
@pcyan 可以的，这个我后面来优化。

**Comment by msdx** [comment]
+1
我看了一下，这个包会把windows及linux/unit所需要的文件都下载下来。能够把平台分成不同的包吗？比如我是用ubuntu的，但是我发现单FreelineAapt.exe就占了15M了

**Comment by lomanyong** [comment]
@msdx 可以的，后面我会写个 API 专门来做这个事情。现在也还都是访问 Github API 来获取最新的版本...

**Comment by lomanyong** [comment]
@pcyan @msdx 下个版本发布可以解决这个issue了...

为了方便使用，暂时不使用7z压缩，目前按照平台做了区分，减少下载一些不必要的文件...减小了一部分体积，因为`initFreeline`不是一个需要经常执行的任务，所以应该也还够用。
