### ISSUE TITLE
Missing the `productFlavor` configuration?   

### ISSUE THREAD

**Issue by smallobserver** [alibaba/freeline#254]
在 build.gradle 里有多渠道打包    即 productFlavors{}
编译时报错
 Missing the `productFlavor` configuration?
  You can try to add `productFlavor` to freeline DSL, for example: 
  
    freeline { 
        hack true 
        productFlavor 'your-flavor' 
    }
  
  Then re-run `python freeline.py` again.

**Comment by lomanyong** [comment]
@smallobserver  恩，按照提示加入配置即可

加入你需要的某个配置就行。

**Comment by sleepingAnt** [comment]
'your-flavor' 是指某个flavor的名称吗？具体是怎样的？

**Comment by lomanyong** [comment]
@sleepingAnt 就是指某个 flavor 的名称...

**Comment by sleepingAnt** [comment]
哦哦，只能是一个吗，能不能填多个

**Comment by lomanyong** [comment]
@sleepingAnt 日常开发测试的话一个就够了，需要切换的时候改下配置即可...

**Comment by sleepingAnt** [comment]
好的，谢谢。
