### ISSUE TITLE
什么时候支持多设备链接到电脑上？

### ISSUE THREAD

**Issue by tanweijiu** [alibaba/freeline#256]
rt

**Comment by lomanyong** [comment]
@tanweijiu 请问多设备的使用case是什么样的呢？仅仅是多设备连接的时候不报错吗？

还有，如果每次切换设备的时候需要重新全量编译能够接受吗？

**Comment by tanweijiu** [comment]
@lomanyong  case：同一电脑链接多台设备...或许可以像正常的as在编译安装那样，提示用户选择..

我觉得并没有必要全量编译（每次编译都记录，并保留最新一份全量），但需要全量安装

**Comment by lomanyong** [comment]
@tanweijiu get，多设备连接我之前做做一个初始版本，不过交互带来的用户体验不是很好，所以没有合入master。

1.0 发版前会好好考虑一下怎么处理这个问题，多谢反馈。

**Comment by Alimjan2009** [comment]
@lomanyong 要是支持多设备就好了，模拟器调界面的时候很有用，做成 这种 python freeline.py device_id_1 device_id_2 device_id_3 形式也不错觉得

**Comment by lomanyong** [comment]
@Alimjan2009 多谢建议...最近其他事情比较多...这块在之后肯定会处理的~

**Comment by charvenhe** [comment]
多设备暂无支持计划
