### ISSUE TITLE
0.8.0版本无法初始化

### ISSUE THREAD

**Issue by zhoujianhanyu** [alibaba/freeline#258]
执行./gradlew initFreeline后，一直卡在Building 0%>:initFreeline

**Comment by lomanyong** [comment]
@zhoujianhanyu 网络问题，使用`./gradlew initFreeline -Pmirror`即可。

**Comment by zhoujianhanyu** [comment]
@lomanyong 新版本经常要重新编译，从0.7.2开始就有这个问题， 但不频繁，新版本比较频繁。 偶尔执行python freeline.py 后就不动，只能重启android studio。我改成0.7.0就没问题。

**Comment by lomanyong** [comment]
@zhoujianhanyu 需要重新编译是指出现什么提示呢？

**Comment by zhoujianhanyu** [comment]
@lomanyong 同步失败

**Comment by lomanyong** [comment]
@zhoujianhanyu 同步失败是指？有log吗？

**Comment by zhoujianhanyu** [comment]
@lomanyong 这是刚刚出现的
[WARNING] NoInstallationException occurs, a clean build will be automatically executed.
同步失败的今天还没碰到。
