### ISSUE TITLE
Error:Could not get unknown property 'com' for object of type com.antfortune.freeline.FreelineExtension.

### ISSUE THREAD

**Issue by DukeLee1989** [alibaba/freeline#264]
Error:Could not get unknown property 'com' for object of type com.antfortune.freeline.FreelineExtension.
请问这个什么原因啊

**Comment by lomanyong** [comment]
@DukeLee1989 这是你的配置写乱了吧..

**Comment by DukeLee1989** [comment]
我也发现了，谢谢，第一次用。
