### ISSUE TITLE
0.8版本导致经常ANR

### ISSUE THREAD

**Issue by lovexujh** [alibaba/freeline#266]
11-04 06:11:32.096 28143-28143/ E/dalvikvm: Could not find class 'org.micro.freeline.hackload.ClassVerifier', referenced from method com.antfortune.freeline.FreelineConfig.<init>
11-04 06:11:32.096 28143-28143/ E/dalvikvm: Could not find class 'org.micro.freeline.hackload.ClassVerifier', referenced from method ....<init>
11-04 06:11:32.096 28143-28143/... E/dalvikvm: Could not find class 'org.micro.freeline.hackload.ClassVerifier', referenced from method ....<init>
11-04 06:11:32.104 28143-28143/... E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.antfortune.freeline.resources.MonkeyPatcher.monkeyPatchExistingResources
11-04 06:11:32.108 28143-28143/... E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.antfortune.freeline.resources.MonkeyPatcher.pruneResourceCache

**Comment by lomanyong** [comment]
@lovexujh 可以换台手机或者完全卸载重装测试吗？或者可以有trace看下是哪里导致的anr...

**Comment by lovexujh** [comment]
@lomanyong 卸载后使用一段时间还是会重现

**Comment by lomanyong** [comment]
@lovexujh 这里一般不会引起ANR，建议如果多次出现的话可以看下trace。issue里可以搜下，有不少提过ANR的，目前大多数是app本身的一些逻辑引起的，麻烦再排查下哈。
