### ISSUE TITLE
Public symbol string/vertical_commend_public_btn declared here is not defined

### ISSUE THREAD

**Issue by DukeLee1989** [alibaba/freeline#269]
请问这个问题，我要怎么设置extraResourceDependencyPaths，是包含vertical_commend_public_btn 的string.xml路径？

**Comment by DukeLee1989** [comment]
假设/develop/android/common/src/debug/res下有个包含vertical_commend_public_btn 的string.xml路径,是这样写嘛
extraResourceDependencyPaths =['/develop/android/common/src/debug/res]

**Comment by lomanyong** [comment]
@DukeLee1989 是的..

````gradle
freeline {
    extraResourceDependencyPaths = ['/develop/android/common/src/debug/res']
}
````
