### ISSUE TITLE
一直停在[DEBUG] collecting project info,please wait a while...

### ISSUE THREAD

**Issue by zhonghanwen** [alibaba/freeline#27]
新建的项目是可以使用你们的库，但是我实际运用到项目中就一直卡在这里。
![image](https://cloud.githubusercontent.com/assets/12220537/17992839/57a1474e-6b7d-11e6-9128-c337d00f6243.png)

**Comment by lomanyong** [comment]
@zhonghanwen 我这边检查了一下这里应该没有阻塞的操作，ctrl + c结束掉再来还一直重复这个现象吗？

**Comment by zhonghanwen** [comment]
@lomanyong 重试过几次还是这样子！

**Comment by charvenhe** [comment]
@zhonghanwen 你们有用mac，或者linux平台吗，在他们机器上也有一样的问题吗

**Comment by zhonghanwen** [comment]
没有在其他平台试过！我用windows就出现这个问题！

**Comment by lishensan** [comment]
mac 平台测试过了，也是一样，一直等在那里。

**Comment by lomanyong** [comment]
@lishensan 具体是卡在哪里呢？有日志吗？

**Comment by charvenhe** [comment]
@lishensan，可以加个-d，然后把日志贴一下

**Comment by lishensan** [comment]
就这个样子。

**Comment by lishensan** [comment]
![qq 20160830140612](https://cloud.githubusercontent.com/assets/3710982/18077958/81625c8a-6ebb-11e6-9147-2506f730a40d.jpg)

**Comment by lishensan** [comment]
![Uploading QQ图片20160830140612.jpg…]()

**Comment by lishensan** [comment]
![qq 20160830140612](https://cloud.githubusercontent.com/assets/3710982/18078113/5388a3b8-6ebc-11e6-95c8-4a4ff52b773b.jpg)

**Comment by charvenhe** [comment]
@lishensan @zhonghanwen 加我们官方群，我们跟进下

**Comment by zhonghanwen** [comment]
哪个官方群？

**Comment by lomanyong** [comment]
@lishensan @zhonghanwen 可以加一下这个微信群.

![](http://ww3.sinaimg.cn/large/006tKfTcgw1f7bt5m9yrij30ny0zkdgp.jpg)

**Comment by lomanyong** [comment]
Note:
经过交流，卡在了寻找依赖的地方。该出逻辑可能出现了正则的死循环，由于没有具体的`build.gradle`文件所以无法定位。目前通过修改modules依赖搜寻的方式，解决了这个问题。
