### ISSUE TITLE
freeline 插件运行错误

### ISSUE THREAD

**Issue by simidaxu** [alibaba/freeline#274]
studio安装freeline插件，点击运行的时候提示
 please install freeline first

**Comment by lomanyong** [comment]
@simidaxu 按照README提示，先运行一下`./gradlew initFreeline -Pmirror` 或者 `gradlew.bat initFreeline -Pmirror`即可。视你的系统环境选择...

**Comment by simidaxu** [comment]
谢谢。现在是可以编译成功了。不过我修改一行代码，run之后并没有改动？需要怎么操作吗。

**Comment by simidaxu** [comment]
运行后出现Segmentation fault这个提示

**Comment by lomanyong** [comment]
@simidaxu 麻烦贴出日志一下..

**Comment by simidaxu** [comment]
@lomanyong 
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 7.6s
[DEBUG] [sync_client] Android-Lib has no need to sync inc res pack.
[DEBUG] [sync_client] checkresource: http://127.0.0.1:41128/checkResource
[DEBUG] [sync_client] base resource exists, there is no need to sync full resource pack
[DEBUG] [sync_client] start to sync Android-Main incremental res pack...
[DEBUG] [sync_client] Android-Main pack size: 24kb
[DEBUG] [sync_client] pushres: http://127.0.0.1:41128/pushResource?mode=increment&bundleId=base-res
[DEBUG] [sync_client] sync Android-Main incremental res pack finished
[DEBUG] [sync_client] start to sync incremental dex...
[DEBUG] [sync_client] pushdex: http://127.0.0.1:41128/pushDex?dexName=merged
[DEBUG] [sync_client] dex path: F:\workspace\code\Android-Main\build\freeline\freeline-dexes\merged.dex
[DEBUG] [sync_client] start to sync native file...
[DEBUG] [sync_client] pushNative: http://127.0.0.1:41128/pushNative?restart
Segmentation fault

**Comment by simidaxu** [comment]
我的手机是坚果手机，Android版本是5.1.1 smartisan os v3.1.4

**Comment by lomanyong** [comment]
@simidaxu 可以用`python freeline.py -d`执行一下，贴出完整的日志吗？

这部分日志不够完整...

锤子机型我们有测过，也是可以使用的。

**Comment by simidaxu** [comment]
@lomanyong  我装的是python 2.7.12，运行python freeline.py -d后，前面都很正常，后面直接弹出对话框python停止运行了，log上无异常
![qq 20161110161502](https://cloud.githubusercontent.com/assets/4651410/20169166/f01b7a0c-a760-11e6-8a07-f3663a969271.png)
