### ISSUE TITLE
添加不进plugin

### ISSUE THREAD

**Issue by a124779683** [alibaba/freeline#276]
我有一个项目在app的module中添加 plugin，总是报下面的错。其他项目只添加这个都不会报错~~都能正常使用，麻烦帮我看看原因。
Error:Failed to resolve: com.antfortune.freeline:runtime-no-op:0.8.1
<a href="openFile:C:/DevelopTool/androidDev/Main/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.antfortune.freeline:runtime:0.8.1
<a href="openFile:C:/DevelopTool/androidDev/Main/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by lomanyong** [comment]
@a124779683 网络问题吧？都是已经发布到jcenter了，如果没有jcenter的话可以手动加上看看...

````gradle
allprojects {
    repositories {
        jcenter()
    }
}
````

**Comment by a124779683** [comment]
非常感谢~确实是网络问题~~昨天折腾一天都不行，今天就正常了~~！
