### ISSUE TITLE
每次编译增量更新以后停留在building increment app.....

### ISSUE THREAD

**Issue by jtsky** [alibaba/freeline#278]
每次编译增量更新以后停留在building increment app.....，然后改点代码第二次就正常了

**Comment by lomanyong** [comment]
@jtsky 可以搜下已有的issue哈，之前都有人遇见，大部分情况都是跟app自身的一些逻辑有关...

**Comment by jtsky** [comment]
@lomanyong  难道跟我再application的onCreat()方法里初始化了一些东西有关吗?

**Comment by lomanyong** [comment]
@jtsky 对于application的这个问题，你可以尝试使用#273 提到的方法来解决试试看。

**Comment by liuhaoer** [comment]
@jtsky    这个问题你解决了吗 我这边也是这个问题
