### ISSUE TITLE
配置了 productFlavors 报错

### ISSUE THREAD

**Issue by yanweimin7** [alibaba/freeline#28]
Execution failed for task ':app:mergeApk_DEBUGDebugAssets'.
> /Users/wey/work/android/stock-android/app/build/intermediates/assets/debug/apktime (No such file or directory)

取消 productFlavors 就没问题了

**Comment by lomanyong** [comment]
@yanweimin7 添加一个配置项到freeline DSL中即可，可以参考下面的例子：

````gradle
freeline {
    hack true
    productFlavor "develop"
}
````

**Comment by yanweimin7** [comment]
好，建议这个加到readme 里面。
