### ISSUE TITLE
FreelineCore.init()的作用是什么，为什么调不调都可以？

### ISSUE THREAD

**Issue by xiebudong** [alibaba/freeline#280]
如题

**Comment by lomanyong** [comment]
@xiebudong Freeline默认替换你的Application类，在FreelineApplication中已经执行了`FreelineCore.init(this);`。默认情况下不需要调用，如果你在build.gradle中配置了`applicationProxy false`关掉了默认替换，则需要手动加上`FreelineCore.init(this);`.
