### ISSUE TITLE
代码中新增了Java8的method reference时增量编译运行crash

### ISSUE THREAD

**Issue by hicomein** [alibaba/freeline#281]
新增了类似于这样子的代码：
mConsultantOpinionContainer.setOnReloadDataListener(this::loadFeedData);
貌似增量编译还不支持这个特性，全量编译是没问题的。

**Comment by lomanyong** [comment]
@hicomein 如果你使用了retrolambda的话应该是可以支持的，如果是jack的话，目前还不支持...
