### ISSUE TITLE
一直停留在 "building increment app..."，最后代码改动不生效

### ISSUE THREAD

**Issue by chenzhong13** [alibaba/freeline#283]
freeline 版本: 0.8.1
配置:
```
freeline {
    hack true
    productFlavor 'myflavor'
    applicationProxy false
}
```

使用全量编译之后，修改了 activity 里面的代码，添加了 toast，然后运行 python freeline.py。就一直停留在一个黑色的界面，中间显示 building increment app...，然后出现 ANR 提示，最近进入了应用界面，但是发现改动没有生效

**Comment by lomanyong** [comment]
@chenzhong13 你那里可以trace看下是哪里ANR了吗？已经close的issues里也有跟你类似的问题...目前大部分都是app本身的一些操作导致的...麻烦先排查看看~

**Comment by chenzhong13** [comment]
再补充一个，我发现如果一直停留在上述界面，我锁屏一下再开屏，应用界面就显示了。是不是没有自动切换界面呢？

**Comment by lomanyong** [comment]
@chenzhong13 肯定会自动切换的呀
