### ISSUE TITLE
执行python freeline.py一直卡在那边不动

### ISSUE THREAD

**Issue by r17171709** [alibaba/freeline#286]
![image](https://cloud.githubusercontent.com/assets/4522859/20168796/edd77ca2-a75e-11e6-9d65-45bfc8702326.png)

**Comment by lomanyong** [comment]
@r17171709 日志显示正在执行`read_project_info_task`，实际上是`gradlew.bat checkBeforeCleanBuild`。通常这里会卡住的很大原因跟你的网络情况相关，你可以手动执行一下`gradlew.bat checkBeforeCleanBuild`看看

**Comment by r17171709** [comment]
你好，我代理分别开、关试过都不行。。。

**Comment by r17171709** [comment]
@lomanyong 你好，我代理分别开、关试过都不行。。。
