### ISSUE TITLE
Fragment in Activity  use butterknife

### ISSUE THREAD

**Issue by tengfei86** [alibaba/freeline#287]
increment build  @Bind View Error 
throw NullPointerException

**Comment by lomanyong** [comment]
@tengfei86 Can you provide any sample codes that can cause this exception? I tested ButterKnife with new **@Bind** codes added and the result is ok.

**Comment by tengfei86** [comment]
I hava a fragment in a Activity ,the Fragment use ButterKnife @Bind a TextView ,throw a exception when use incremental build. But if use ButterKnife in activity use  incremental build is ok.

**Comment by lomanyong** [comment]
@tengfei86 I tested ButterKnife with Fragment and the result is ok, too. So, could you provide the sample codes or sample repo that can repeat the crash?

**Comment by lomanyong** [comment]
@tengfei86 I figure out this problem.. Fix later.
