### ISSUE TITLE
一直停留在Building 0%>:initFreeline 不动

### ISSUE THREAD

**Issue by RaftingJack** [alibaba/freeline#289]
使用./gradlew initFreeline  或者 ./gradlew initFreeline -Pmirror 都是停在initFreeline不动，配置是按照github上来的

**Comment by lomanyong** [comment]
@RaftingJack 基本都是网络问题...麻烦可以搜下相关的issue，有不少碰到跟你一样的问题的，通常30s内就能执行完initFreeline。如果没有`jcenter()`的话可以加上，速度会比`mavenCentral()`来的快点..
