### ISSUE TITLE
连接不上设备

### ISSUE THREAD

**Issue by yanweimin7** [alibaba/freeline#29]
ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package com.XXX is not found.
[ERROR] ---------------------------------------

**Comment by lomanyong** [comment]
@yanweimin7 你们有配置applicationIdSuffix吗？

**Comment by yanweimin7** [comment]
没有，pm list package 是能够找到com.wacai.stock的

**Comment by yanweimin7** [comment]
defaultConfig {
        applicationId "com.wacai.stock"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 11 
        versionName "1.1.3"
        multiDexEnabled true

**Comment by lomanyong** [comment]
@yanweimin7 是否在你们的Application类中调用了`FreelineCore.init(this);`了呢

**Comment by yanweimin7** [comment]
调用了的 
FreelineCore.init(this);
        Global.init(this);

**Comment by lomanyong** [comment]
@yanweimin7 你们的android gradle版本是多少的呢？

**Comment by yanweimin7** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip

**Comment by lomanyong** [comment]
@yanweimin7 app启动后可以看下logcat，过滤一下`freeline`的日志，看是否有freeline相关的日志输出

**Comment by yanweimin7** [comment]
08-26 18:34:06.074 25971-25971/? I/Freeline: freeline start initial process...
08-26 18:34:06.075 25971-25971/? I/Freeline: freeline init application
08-26 18:34:06.079 25971-25971/? I/Freeline: start to inject dex...
08-26 18:34:06.079 25971-25971/? I/Freeline: start to inject resources...
08-26 18:34:06.080 25971-25971/? I/Freeline: dynamicInfoSp: {}
08-26 18:34:06.080 25971-25971/? I/Freeline: resMap: {}
08-26 18:34:06.080 25971-25971/? I/Freeline: start to load hackload.dex...
08-26 18:34:06.081 25971-25971/? I/Freeline.hackDex: /data/data/com.xxx/cache/hack/hackload.dex dex length: 848
08-26 18:34:06.081 25971-25971/? I/Freeline.hackDex: /data/data/com.xxx/cache/hack/opt opt length: 4096
08-26 18:34:06.084 25971-25971/? I/Freeline.hackDex: after opt, dex len:848; opt len:4096
08-26 18:34:06.084 25971-25971/? I/Freeline: load hackload，dex size:848
08-26 18:34:06.084 25971-25971/? I/Freeline: freeline init server
08-26 18:34:06.126 879-1612/? I/ActivityManager: Start proc 26002:com.xxx:freeline/u0a540 for service com.xxx/com.antfortune.freeline.FreelineService
08-26 18:34:06.205 26002-26002/? I/Freeline.Service: onStartCommand Received start id 1, intent: Intent { cmp=com.xxx/com.antfortune.freeline.FreelineService }
08-26 18:34:06.221 26002-26002/? I/Freeline.Service$Inner: onStartCommand Received start id 1, intent: Intent { cmp=com.xxx/com.antfortune.freeline.FreelineService$InnerService }

**Comment by lomanyong** [comment]
@yanweimin7  有没有这句log呢？ `Freeline.increment server running on port xxxxx`

**Comment by charvenhe** [comment]
@yanweimin7，是否是没开启debug模式呢

**Comment by yanweimin7** [comment]
debug是开启了的 ， 没看到Freeline.increment server running on port xxxxx

netstat 命令结果：
tcp6       0      0 :::41128               :::*                   LISTEN
tcp6       0      0 :::48432               :::*                   LISTEN
tcp6       0      0 ::ffff:127.0.0.1:52670 :::*                   LISTEN
tcp6       0      0 ::ffff:127.0.0.1:41128 ::ffff:127.0.0.1:48590 TIME_WAIT
tcp6       0      0 ::ffff:127.0.0.1:41128 ::ffff:127.0.0.1:48600 TIME_WAIT
tcp6       0      0 ::ffff:127.0.0.1:41128 ::ffff:127.0.0.1:48610 TIME_WAIT
udp6       0      0 :::34009               :::*                   CLOSE
udp6    3008      0 :::39285               :::*                   CLOSE
udp6       0      0 :::47508               :::*                   CLOSE
udp6       0      0 :::58858               :::*                   CLOSE

**Comment by charvenhe** [comment]
@yanweimin7,可以换台机器看看吗？貌似tcp启动不了

**Comment by charvenhe** [comment]
@yanweimin7 Freeline.increment server running on port 是运行在另外一个独立进程的，你可以检查下日志filter是不是过滤了，另外看看mainifest的是不是debugable关闭了。freeline非debug模式不会开启tcp端口的

**Comment by lomanyong** [comment]
@yanweimin7 可以先检查下电脑上是否使用了任何网络代理app，有使用的话可以先关掉。然后也可以使用这个runtime版本`com.antfortune.freeline:runtime:0.6.0.1609051840`，看是否可以稳定连接上app。

**Comment by johngef** [comment]
我也有同样的问题

**Comment by johngef** [comment]
@yanweimin7 你的问题解决了吗

**Comment by lomanyong** [comment]
@johngef 你那边也是连接不上，一直在"try to connect"吗？

**Comment by johngef** [comment]
`[INFO] preparing for tasks...
[-][connect_device_task] failed. in 14.5s
[-][gradle_aapt_task] finished. in 0.0s
[-][CTBusiness] finished. in 0.0s
[-][CTTour] finished. in 4.9s
[-][CtripMain] finished. in 0.1s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package ctrip.android.view is not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 14.5s
[DEBUG] Total time: 14.9s
[DEBUG] --------------------------------------------------------`

**Comment by johngef** [comment]
[INFO] preparing for tasks...
[-][connect_device_task] failed. in 14.5s
[-][gradle_aapt_task] finished. in 0.0s
[-][CTBusiness] finished. in 0.0s
[-][CTTour] finished. in 4.9s
[-][CtripMain] finished. in 0.1s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package ctrip.android.view is not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 14.5s
[DEBUG] Total time: 14.9s
[DEBUG] --------------------------------------------------------

**Comment by johngef** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@johngef 你们的app中是否调用了`FreelineCore.init(this);`了吗？

还有，最好检查下是否有开着网络代理，导致`127.0.0.1`无法正常使用的情况。

**Comment by johngef** [comment]
调用了

**Comment by lomanyong** [comment]
````
adb forward tcp:41128 tcp:41128
curl -v 127.0.0.1:41128/checkSync?sync=1\&uuid=22
````

@johngef 执行一下以上两行命令，然后麻烦贴一下输出..

**Comment by lomanyong** [comment]
@johngef `ctrip.android.view`这个包名，执行`adb shell pm list packages ctrip.android.view`，是否存在这个包呢？

**Comment by charvenhe** [comment]
@jiaoge 更新到0.6.1上再试试看

**Comment by charvenhe** [comment]
0.7已经进行专门处理，后续有类似问题移步这里讨论 #152
