### ISSUE TITLE
freeline plugin in Android Studio 

### ISSUE THREAD

**Issue by huclengyue** [alibaba/freeline#290]
I use freeline plugin in Android Studio  
![](https://cloud.githubusercontent.com/assets/9107717/20173577/d05b7460-a774-11e6-9ae3-7dd07f7ada18.png)
What should I do?

**Comment by lomanyong** [comment]
@huclengyue Follow the README instructions, execute `gradlew.bat initFreeline -Pmirror` in the command line (cmd for Windows).
