### ISSUE TITLE
咨询：0.8.1,每次全量提示无法inflater到edittext，修改资源文件需重新全量

### ISSUE THREAD

**Issue by asdf3309** [alibaba/freeline#291]
1#修改资源文件需重新全量生成，这个是正常的吗？否则就是爆edittext无法找到，奇怪。就是一个edittext，没什么其他东西呀，，
2@全量后自动运行的第一次就是会失败，然后手动打开就行了，然后就可以增量了，这个情况正常吗。、。。也是报错无法inflater到edittext，，醉了。

**Comment by lomanyong** [comment]
@asdf3309 hi，能够提供一个可以复现这个问题的sample工程吗？我这里没办法复现这个问题...

**Comment by phoenix19900219** [comment]
修改资源文件, 重新运行, 就出现这个问题

**Comment by phoenix19900219** [comment]
下面是一个堆栈信息

**Comment by phoenix19900219** [comment]
-15 15:17:27.099 11291 11291 E AndroidRuntime: FATAL EXCEPTION: main
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: Process: a.b.c.d, PID: 11291
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{a.b.c.d/a.b.c.d.activity.LoginActivity}: android.view.InflateException: Binary XML file line #108: Binary XML file line #108: Error inflating class EditText
11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2456)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:159)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:152)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5507)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #108: Binary XML file line #108: Error inflating class EditText
11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at a.b.c.d.activity.LoginActivity.normalLoginLogic(LoginActivity.java:119)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at a.b.c.d.activity.LoginActivity.onCreate(LoginActivity.java:99)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6304)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2409)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	... 9 more
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #108: Error inflating class EditText
11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	... 18 more
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=0
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at java.lang.String.charAt(Native Method)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:107)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.content.res.TypedArray.getInt(TypedArray.java:355)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:1111)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:64)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:60)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:62)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:58)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1017)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1076)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
        11-15 15:17:27.099 11291 11291 E AndroidRuntime: 	... 28 more

**Comment by phoenix19900219** [comment]
@lomanyong , 这个问题能尽快修一下么?

**Comment by lomanyong** [comment]
@phoenix19900219 有可以复现这个问题的 sample 工程吗？单纯看这个log的话没办法定位是哪里有问题...

**Comment by phoenix19900219** [comment]
@lomanyong, https://github.com/phoenix19900219/Freeline-creash-demo运行项目, 然后把activity_main.xml中的ImageView注释放开, 再运行,

**Comment by lomanyong** [comment]
@phoenix19900219 收到，我看下...

**Comment by lomanyong** [comment]
@phoenix19900219 这个demo在我这里运行正常...增量资源编译没有crash发生。同样的demo你那里如果发生了crash的话，可以给我一下你的crash的堆栈吗？

以及，你是windows/linux/macOS？

**Comment by phoenix19900219** [comment]
@lomanyong crash堆栈:

**Comment by lomanyong** [comment]
@phoenix19900219 使用的设备和系统版本是？

**Comment by phoenix19900219** [comment]
@lomanyong 机型是: 一加3, 系统6.0.1;  Lenovo Z90-7, 系统6.0.1

**Comment by phoenix19900219** [comment]
@lomanyong 下面这个是是在 "华为 Hol-T00" (系统4.2.2)上报的crash, 增量资源编译后一启动就crash了:

**Comment by lomanyong** [comment]
@phoenix19900219 有在模拟器上测试过吗？

**Comment by phoenix19900219** [comment]
@lomanyong 都是真机

**Comment by lomanyong** [comment]
@phoenix19900219 crash之后，再点开app都可以正常使用吗？

**Comment by lomanyong** [comment]
@phoenix19900219 华为的crash看着是百度系统的问题...有个`BaiduAssets`。

**Comment by phoenix19900219** [comment]
@lomanyong 嗯, 这个是百度云OS, 这个每次启动都crash; 前面那两个启动不crash, 点击"去登录"按钮的时候crash

**Comment by phoenix19900219** [comment]
@lomanyong 前面那个应该和系统没关系, 我这边的手机都crash了

**Comment by phoenix19900219** [comment]
@lomanyong 你按我说的操作去做, 应该是可以重新的

**Comment by lomanyong** [comment]
@phoenix19900219 恩，刚刚重新了，需要进入那个 LoginActivity 才会 crash，我晚上找下原因。

**Comment by phoenix19900219** [comment]
@lomanyong 好的, 加油!

**Comment by lomanyong** [comment]
@phoenix19900219 问题找出来了，出现crash的原因应该是你们使用`imeActionId`这个属性的时候直接引用了`viewId`，但是实际上引用`viewId`的时候，在 App 中处理回调函数时，回调的 id 会不正确，正确的处理方式应该是单独在资源文件中定义一个`integer`属性，如：

````xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer name="ime_action_id">100</integer>
</resources>
```` 

然后在`EditText`中的`imeActionId`中引用这个值，如：

````xml
<EditText
    android:id="@id/password"
    android:layout_width="match_parent"
    android:layout_height="56dp"
    android:imeActionLabel="@string/action_settings"
    android:imeOptions="actionUnspecified"
    android:imeActionId="@integer/ime_action_id"
    android:hint="请输入密码"
    android:inputType="textPassword" />
````

将`imeActionId`的引用实际viewId的地方修改后即可正常增量资源编译。

可以参考如下链接：
- [Why does setting imeActionId with a predefined ID resource create an error?](http://stackoverflow.com/questions/23713604/why-does-setting-imeactionid-with-a-predefined-id-resource-create-an-error)
- [EditText设置IME动作问题](http://blog.csdn.net/mzhhzm008/article/details/51615592)
- [Android EditText使用](http://blog.csdn.net/a13069730106/article/details/52250320)

**Comment by phoenix19900219** [comment]
@lomanyong ,  的确是这个问题, 非常感谢 !!

**Comment by Tobi1025** [comment]
执行python freeline.py -h命令时，报错
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "/Users/qiaojingfei/Desktop/\u5bb6\u653fapp/jz_app_android/freeline/freeline_core/__init__.py", line 1, in <module>
    import build_commands
ModuleNotFoundError: No module named 'build_commands'
