### ISSUE TITLE
demo使用freeline编译出错，gradle普通打包OK

### ISSUE THREAD

**Issue by r17171709** [alibaba/freeline#292]
E:\workspace_demo\sample\app\src\main\java\com\antfortune\freeline\sample\App.java:6: 错误: 找不到符号
import com.antfortune.freeline.FreelineCore;
                              ^
  符号:   类 FreelineCore
  位置: 程序包 com.antfortune.freeline
警告: 以下选项未被任何处理程序识别: '[androidManifestFile, resourcePackageName]'
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevelopDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

**Comment by lomanyong** [comment]
@r17171709 这明显没有添加依赖吧...麻烦先排查一下吧..

**Comment by r17171709** [comment]
额不是的，这种简单的问题我是不会问的，主要是图上传不了，我既然说gradle可以正常打包，肯定就是依赖添加OK的，我也不是新手

**Comment by lomanyong** [comment]
@r17171709 你是直接打包sample工程的？可以看下sample工程的`settings.gradle`文件，include了两个在runtime文件夹里的module...应该是缺少了这两个module

**Comment by r17171709** [comment]
![image](https://cloud.githubusercontent.com/assets/4522859/20250844/2d0a8062-aa4e-11e6-9cb4-8520fb283f5d.png)
已经加了

**Comment by lomanyong** [comment]
@r17171709 `app`的`build.gradle`的依赖呢？ sample直接拉下来代码都是可以找到依赖的...不知道你是否有做过什么修改...

**Comment by r17171709** [comment]
我仅仅是改动了android还有support等的版本而已

**Comment by lomanyong** [comment]
@r17171709 代码上传到github上看下？

**Comment by r17171709** [comment]
不好意思，我的锅，我刚才回退的时候确实有漏加东西了，谢谢
