### ISSUE TITLE
新增静态方法无法实现增量编译

### ISSUE THREAD

**Issue by BruceHurrican** [alibaba/freeline#295]
伪代码如下:
````
public class AA{
        public static void test01(){
                  System.out.println("haha");
        }
}

public class BB{
      public static void testAA(){
           AA.test01();
      }
}
````
全量编译后,在 AA 中添加一个静态方法
````
public class AA{
        public static void test01(){
                  System.out.println("haha");
        }

        public static void test02(){
                  System.out.println("haha2");
        }
}
````
修改 BB 中的调用
````
public class BB{
      public static void testAA(){
           AA.test02();
      }
}
````
增量编译后，报 test02方法找不到，freeline 版本为0.7.3.1

**Comment by lomanyong** [comment]
@BruceHurrican 我这边测试了一下并没有复现这个问题...能够提供可以复现的sample工程吗？

**Comment by BruceHurrican** [comment]
@lomanyong demo地址，https://github.com/BruceHurrican/BruceDaily/tree/fldemo ,注意：验证时，新增的静态方法必须是 从无到有，注释反注释这种无法验证上述场景的

**Comment by lomanyong** [comment]
@BruceHurrican 用你的这个分支的代码测试了，也是新增的`public static`方法，但是也没有出现类似的crash。

你测试的设备是的系统版本+设备是什么样的？

**Comment by BruceHurrican** [comment]
@lomanyong 上述场景不一定会 crash ，我提供的 demo 是想说明，对于新增的静态方法，别处调用时，增量编译通过，但是实际结果不对，即原本打开的是百度的网址，增量更新目标是打开搜狐网址，但是编译后，打开的还是百度网址。 我使用的是 mac  freeline 版本0.7.3.1，测试机型 moto X，红米 note3 ， bug 复现率 1/5。

**Comment by lomanyong** [comment]
@BruceHurrican 我这边有测过多次新增静态方法，应该都没有问题，都能出现新的网页。你之前修改的是不是涉及到了静态常量了？

**Comment by BruceHurrican** [comment]
@lomanyong 之前的修改有涉及到静态常量，那个 url 测试时，是作为静态常量新增出来的

**Comment by lomanyong** [comment]
@BruceHurrican 那是跟以前一样，是静态常量的问题？

**Comment by BruceHurrican** [comment]
嗯，刚刚回滚了代码，确实是静态常量的问题

**Comment by lomanyong** [comment]
@BruceHurrican 恩，issue先close了。
