### ISSUE TITLE
全量编译时编译了所有的 productFlavor

### ISSUE THREAD

**Issue by chenzhong13** [alibaba/freeline#298]
freeline 版本：0.8.1

项目中有多个 productionFlavor，我使用如下方法指定了 flavor
```
freeline {
    productFlavor 'XXXX'
}
```
但是发现，该配置的作用只是指定了安装哪个 flavor 的 apk，遇到需要全量编译的情况时，freeline 要将所有的 flavor 编译一次，很耗时。期望即使全量编译也只编译上述配置指定的 flavor，请问怎么处理呢

**Comment by lomanyong** [comment]
@chenzhong13 0.8.1应该没有这个问题了才对，可以看下`~/.freeline/cache/xxxxxx/project_description.json`这个文件的`build_script`字段是什么编译命令？

快速解决方法，加入配置：
````
freeline {
    ...
    buildScript "your-build-script"
}
````

也可以快速解决你的问题。同时已经有相关的issue有提到这个问题，提问前可以先搜搜看看。

**Comment by chenzhong13** [comment]
工程 flavor 配置如下：
```
flavorDimensions "pn", "env"
productFlavors {
    pnold {
        dimension "pn"
    }
    pnnew {
        dimension "pn"
    }

    envproduction {
        dimension "env"
    }
    envtest {
        dimension "env"
    }

}
```

如果使用 freeline 的 productFlavor 来控制，配置如下：

```
android {
    ...
    freeline {
        productFlavor: 'pnoldEnvtest'
    }
}
```
那么， project_description.json 文件 build_script 字段的值是 gradlew.bat assembleDebug。



如果使用 freeline 的 buildScript 字段，配置如下：
```
android {
    ...
    freeline {
        buildScript 'gradlew.bat assemblePnoldEnvtestDebug'
    }
}
```
那么， project_description.json 文件 build_script 字段的值是 gradlew.bat assemblePnoldEnvtestDebug。

**Comment by lomanyong** [comment]
@chenzhong13 `flavorDimensions`这个属性，freeline暂时还没有很好的支持...估计是这个原因导致了你的问题...

**Comment by chenzhong13** [comment]
好，那我先指定 buildScript 嘛，thx
