### ISSUE TITLE
同一文件同一次编译修改，只有部分修改生效

### ISSUE THREAD

**Issue by chenzhong13** [alibaba/freeline#299]
freeline 版本: 0.8.1

代码如下 :
```
findViewById(R.id.test_btn).setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        // 改动 1
        Toast.makeText(LoginActivity.this, "click1234", Toast.LENGTH_SHORT).show();
    }
});
// 改动 2
Log.d("zhongchen", "LoginActivity");
```

上述代码是 activity#onCreate 中的一段代码，期望是，我进入这个 Activity 后，其在 onCreate 时，输入一段日志，当我点击某个按钮时，toast 一段信息。

我同时修改了 Toast 的内容和 Log 的内容。但是发现，使用 freeline 增量编译后，toast 的内容确实改变了，但是 Log 打印的信息却没有变（我退出过该 activity 并重新进入）。也就是说，同一个类文件中，同一次编译所做的修改，有部分没有生效，请问是什么原因呢

我拍了个视频： https://pan.baidu.com/s/1qYlgfms

**Comment by lomanyong** [comment]
@chenzhong13 原理上来说应该不会有这个现象，我本地测试了也没有相同的发生...

你那里是否可以提供必现的路径或者sample工程呢？

**Comment by chenzhong13** [comment]
sample 工程提供不了哟，因为是公司的应用

**Comment by lomanyong** [comment]
@chenzhong13 你修改的地方是否是全局静态常量或者final修饰的呢？

**Comment by chenzhong13** [comment]
完整的代码：
```
public class BaseActivity extends Activity {
	
	@Override
	public void onCreate(Bundle savedInstanceState) {

		...
		setupView();
	}

	protected void setupView() {
	}
}

public class LoginActivity extends BaseActivity() {
	
	@Override
	protected void setupView() {

		...
		findViewById(R.id.test_btn).setOnClickListener(new View.OnClickListener() {
    		@Override
    		public void onClick(View v) {
        		// 改动 1
        		Toast.makeText(LoginActivity.this, "click1234", Toast.LENGTH_SHORT).show();
    		}
		});
		// 改动 2
		Log.d("zhongchen", "LoginActivity");
	}
}
```

**Comment by lomanyong** [comment]
@chenzhong13 我根据这段代码做了个sample改动也都能生效...

**Comment by chenzhong13** [comment]
问题并没哟解决为什么就关了呢，能不能 QQ 远程帮我看看，我的 QQ: 2681636455

**Comment by lomanyong** [comment]
@chenzhong13 先给我发下邮件吧，还遇见问题可以带着日志跟sample代码一起。`lomanyong@gmail.com`

**Comment by zhangzzqq** [comment]
freline在一些地方不起作用
  比如python freline.py  baseApplication的oncreate方法中加入一个Toast--“hello world”,只有python freline.py  -f起作用
