### ISSUE TITLE
单独修改资源文件，freeline运行后闪退

### ISSUE THREAD

**Issue by yak99** [alibaba/freeline#302]
10月份在qcon大会上第一次了解到freeline，当时非常兴奋，如获至宝，秒级编译，热部署。。。这些功能对于android开发者来说能大大的提高开发效率，最近将freeline引入到我们项目里，发现了下面几个问题，希望能帮忙一起看下

1 修改资源文件闪退问题
a. 修改java文件，运行python freeline.py 正常
b. 修改java文件+资源文件（layout里的布局文件），运行python freeline.py 正常
c.  修改资源文件，不修改java文件，运行python freeline.py  **app闪退，需要手动启动app**

2 无法debug
看我们的freeline.py 里有 -d 参数，应该是debug的意思，但是执行 python freeline.py -d app起来的时候无法进入设置的断点（android studio 2.1.1），如果无法像在android studio里进行调试，那freeline的实用性将大打折扣，我希望是我环境搭建的问题，而不是不支持调试

对于上面的问题，我已经将我们的工程简化成demo，这个demo工程能重现上面问题，工程文件见附件。用的freeline版本 0.8.1，gradle jdk等版本见demo工程，我初步怀疑是和静态变量有关，重现步骤：
layout/activity_main.xml 修改textview的text属性，然后运行python freeline.py  闪退

这两个问题困扰我一个多星期，实在希望能在项目组里推广freeline，一直在摸搜不想放弃，希望能在这里得到帮助，非常感谢

PS: 工程文件压缩成.zip 还是无法上传，所以就把后缀直接改成了.pdf，下载下来的时候请把文件后缀名改回 .rar 即 MyApplication2.PDF 改为MyApplication2.rar

[MyApplication2.PDF](https://github.com/alibaba/freeline/files/591558/MyApplication2.PDF)

**Comment by lomanyong** [comment]
@yak99 抱歉哈...有点奇怪...刚看到这个issue...

先回到下debug的问题，`-d`是显示freeline的debug log的参数，windows下，默认显示debug log。

要debug app，需要在Android Studio里点击那个`attach debugger`的按钮即可，新的断点逻辑会走到了...

**Comment by lomanyong** [comment]
@yak99 这个问题不是闪退，没有闪退的堆栈，而是被`finish()`掉了。

在你的`BaseActivity`里有这个调用：
````java
        @Override
	protected void onDestroy() {
		super.onDestroy();

		// 结束Activity&从堆栈中移除
		AppManager.getAppManager().finishActivity(this);
	}
````
而在 Freeline 增量编译资源你更新的时候，会调用`Activity#recreate()`。最终导致重建的`Activity`直接被`finish`掉了，就出现了类似你提到的“闪退”的现象。

排查方法，你可以在`MainActivity`的`onDestroy()`方法里加入`log`，会看到这里被调用了两次。

把这里的`finishActivity()`处理了就能够正常使用了。

**Comment by yak99** [comment]
@lomanyong 增量编译重建activity 调用recreate() 为什么会导致两次 onDestroy方法的触发？ 第二次的触发是为什么？ 怎么解释 java文件修改+资源文件修改就只会触发一次,而单单修改资源文件就会触发两次？从这个角度讲应该和我们freeline重建activity的逻辑有关，而不是工程代码中BaseActivity的问题，并且android studo 启动都不会有问题；

另外您的回复中提到：把这里的finishActivity()处理了就能够正常使用了。
对于这个修改，我如何判断那次是需要finish ，哪一次不要finish呢？而且对于能正常运行的项目代码，为了适应freeline而进行代码逻辑的改动，应该是尽可能少甚至不应该修改（除非我的逻辑本来就存在错误，而没被发现）；希望给点修改建议，谢谢

**Comment by lomanyong** [comment]
@yak99 代码修改的时候是freeline执行了killProcess了，这时`finish()`不会生效。

我们也是在做到使用freeline的时候尽量不会涉及到你们本身代码逻辑的修改...只是你们这里的调用貌似本身就有点问题？为什么需要在`onDestroy()`的时候调用`finish()`呢？`onDestroy()`的时候不是本身就是进入`finish()`流程了吗？

**Comment by yak99** [comment]
@lomanyong  谢谢你的回复，也谢谢freeline团队为我们分享这么好用的插件！支持你们，顶！
