### ISSUE TITLE
初次使用时报错

### ISSUE THREAD

**Issue by hiperioncn** [alibaba/freeline#308]
按向导配置后，执行 ./gradlew initFreeline成功。
点击AndroidStuido工具栏的freeline按钮出现以下错误：
````
Traceback (most recent call last):
  File "freeline.py", line 49, in <module>
    main()
  File "freeline.py", line 45, in main
    freeline.call(args=args)
  File "freeline.py", line 20, in call
    self.dispatcher.call_command(args)
  File "/Users/hiperion/AndroidStudioProjects/Bloomsky/freeline/freeline_core/dispatcher.py", line 57, in call_command
    self._exec_command(self._command)
  File "/Users/hiperion/AndroidStudioProjects/Bloomsky/freeline/freeline_core/dispatcher.py", line 100, in _exec_command
    '[WARNING] some important file missed, a clean build will be automatically executed.')
  File "/Users/hiperion/AndroidStudioProjects/Bloomsky/freeline/freeline_core/dispatcher.py", line 125, in _retry_clean_build
    self._setup_clean_build_command(is_build_all_projects=False)
TypeError: _setup_clean_build_command() takes exactly 3 arguments (2 given)
````

**Comment by houpe** [comment]
换下python 版本试试 用2.7+的 你是不是3.几的··

**Comment by hiperioncn** [comment]
python -V
Python 2.7.10
后来我关闭了instantrun，又执行了一遍 python freeline.py -f全量编译之后，就可以用了，freeline插件能否增加判断初次执行全量编译？

**Comment by lomanyong** [comment]
@hiperioncn 插件在新版本里加了判断，目前还有点bug要修复，修复完会release的

**Comment by pkliang** [comment]
我也遇到这个问题了，我的python版本是2.7.11， 执行了全量编译后，还是不行

**Comment by lomanyong** [comment]
@pkliang 发现问题了...是bug，我尽快修复。你可以执行`python freeline.py -f -d`来绕过这个问题。或者暂时降级到0.8.1，执行`gradlew initFreeline -PfreelineVersion=0.8.1`

**Comment by pkliang** [comment]
@lomanyong 好的，谢谢

**Comment by 646634231** [comment]
一直让我设置JAVA_HOME,Please declares your JAVA_HOME to system env!，我是WIN10的系统

**Comment by sugarPro** [comment]
Traceback (most recent call last):
  File "freeline.py", line 6, in <module>
    from freeline_core.dispatcher import Dispatcher
ImportError: No module named freeline_core.dispatcher

**Comment by lomanyong** [comment]
@sugarPro 使用 Python 2.7

**Comment by CJC-ivotten** [comment]
0.8.7版本也遇到这个问题，情况一摸一样，我的python也是2.7.10。

**Comment by xiyouMc** [comment]
@CJC-ivotten 我试过了。删除目录下面的freeline相关文件，然后重新initFreeline，即可恢复。

**Comment by chanlk** [comment]
D:\ex>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 3.0.1
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.8
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.8
[DEBUG] [WARNING] some important file missed, a clean build will be automatically executed.
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\ex\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 651000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save ex module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.3s
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.9s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.9s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.9s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.9s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.9s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.6s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.91s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\ex\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\ex\freeline_core\gradle_tools.py", line 233, in execute
    self._fill_cache_map(all_modules)
  File "D:\ex\freeline_core\gradle_tools.py", line 247, in _fill_cache_map
    md5 = get_md5(settings_path)
  File "D:\ex\freeline_core\utils.py", line 84, in get_md5
    target_file = open(fpath, 'rb')
IOError: [Errno 2] No such file or directory: 'D:\\ex\\settings.gradle'

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.9s
[DEBUG] Total time: 1.1s
[DEBUG] --------------------------------------------------------


请问我这个是出什么问题了，我用的是windows，谢谢

**Comment by bishi2016** [comment]
@chanlk  跟你遇到同样的问题

**Comment by SuperMan-1997** [comment]
请问这个必须要加吗？plugins id 'com.antfortune.freeline'  我一直在这里报错
