### ISSUE TITLE
python freeline.py 增量编译对于多module项目，非主module改动编译失败

### ISSUE THREAD

**Issue by xuzhitao2015** [alibaba/freeline#309]
主module的packageName于子module的packageName不同，只改动子module上的代码，运行python freeline.py增量编译提示Error，全量编译没问题（python freeline.py -f)

如下：（路径和包名已替换）
警告: [options] 未与 -source 1.7 一起设置引导类路径
MyActivity.java:22: 错误: 找不到符号
import com.demo.data.R;
                              ^
  符号:   类 R
  位置: 程序包 com.demo.data
1 个错误

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 1.0s
[DEBUG] Total time: 1.1s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@xuzhitao2015 `com.demo.data`这个是哪个module的包名？子module的`xxx.xxx.xxx.R`跟manifest里定义的一样吗？

**Comment by xuzhitao2015** [comment]
com.demo.data是子module的包名和子module的manifest中定义一样，但和主module中的包名不一样

**Comment by xuzhitao2015** [comment]
@lomanyong  com.demo.data是子module的包名和子module的manifest中定义一样，但和主module中的包名不一样

**Comment by lomanyong** [comment]
@xuzhitao2015 可以提供这部分完整的日志吗？

**Comment by lomanyong** [comment]
@xuzhitao2015  参考 #284 ，应该已经解决这个问题了...
