### ISSUE TITLE
python freeline.py 后面的参数是什么意思?

### ISSUE THREAD

**Issue by swkfx** [alibaba/freeline#310]
-a 全量?
-d debug 模式?
[-h] [-v] [-f] [-w] [-a] [-c] [-d] [-i]
麻烦告知一下 或者去哪里看呢?

**Comment by swkfx** [comment]
optional arguments:
  -h, --help        show this help message and exit
  -v, --version     show version
  -f, --cleanBuild  force to execute a clean build
  -w, --wait        make application wait for debugger
  -a, --all         together with '-f', freeline will force to clean build all
                    projects.
  -c, --clean       clean cache directory and workspace
  -d, --debug       enable debug mode
  -i, --init        init freeline project

thx

**Comment by swkfx** [comment]
编译中可以取消编译吗?

**Comment by lomanyong** [comment]
@swkfx 取消编译直接`ctrl + c`或者`cmd + c`即可。
