### ISSUE TITLE
试用遇到一些问题

### ISSUE THREAD

**Issue by OccurSomething** [alibaba/freeline#311]
1、freeline基本在debug下使用，release版本（要混淆）不会开启，一些配置信息不需要加只在debug下才设置吗？不加会不会造成release版本有问题？
比如    freeline {
        hack true
        productFlavor "develop"
        autoDependency false
    }
2、还是会存在resourceNotFound的情况
3、app已经用freeline启动过，手机也和电脑连接正常，现在退出app，然后run freeline，蛮大的概率启动不了app，不管是全量还是增量

**Comment by lomanyong** [comment]
@OccurSomething 

1. 你看得应该是sample工程吧，正式版本的工程你按照README集成，只需要一行`classpath "com.antfortune.freeline:gradle:xxxx"`即可。在release包里只会加入一个空实现的库，不影响release版本。
2. resource not found的情况可以单独发下详细的日志来看下
3. 增量起不来可能可以理解，Service被系统杀掉无法连接到app，虽然freeline加入了唤醒Service的操作，但是还有一定的概率因为系统原因无法唤醒。但是全量无法自动安装启动的话，这就不正常了...
