### ISSUE TITLE
关于release版本的配置问题

### ISSUE THREAD

**Issue by OccurSomething** [alibaba/freeline#312]
Freeline的一些配置（包括classPath、apply plugin、freeline{}），打Release包时要不要去掉，不去掉有没有问题，如果必须去掉有没有一些自动的配置方式使得debug才配置release不配置？

**Comment by lomanyong** [comment]
@OccurSomething 不需要去掉，freeline本身已经做了处理了，不会对你们构建`release`版本产生影响的。
