### ISSUE TITLE
下载新版本的freeline只需要更新project的gradle文件么

### ISSUE THREAD

**Issue by Huyamin150** [alibaba/freeline#313]
下载新版本的freeline只需要更新project主项目下的gradle文件的版本么

**Comment by lomanyong** [comment]
@Huyamin150 更新完根目录的`build.gradle`的版本后，重新执行一下`gradlew initFreeline -Pmirror`，即可。可以手动执行`python freeline.py -v`确认一下版本是否跟你`build.gradle`中配置的一致。
