### ISSUE TITLE
此工具的dx是否支持java8语法的源文件编译？

### ISSUE THREAD

**Issue by wangpenghit2155** [alibaba/freeline#317]
Android N版本以后，不再推荐javac+dx方式了，而用jack来编译了。因此N版本代码里编译出来的dx好像处理java8文件时会报错。不知道这个工具能否处理java8语法格式的文件呢

**Comment by lomanyong** [comment]
@wangpenghit2155 很抱歉...目前不支持jack编译...dex增量的原理导致的...

**Comment by wangpenghit2155** [comment]
那请问如果用javac+dx编译的话，java8的语法支持么?

**Comment by lomanyong** [comment]
@wangpenghit2155 不能完全支持，使用retrolambda可以支持lambda语法，其余的语法不一定能够支持。
