### ISSUE TITLE
clean build

### ISSUE THREAD

**Issue by krmao** [alibaba/freeline#318]
对于 华为 mat8 手机，freeline 运行一次，华为手机需要点确定才能安装，假如你此时不在身边，错过了，重新润一次，就会重新clean build, 体验非常的不好

pull 一次代码后也会遭遇 clean build

**Comment by lomanyong** [comment]
@krmao 

1. 这个体验不好的原因是`adb`安装失败的时候没有按照约定俗成返回非 0 错误码，导致调用方无法判断你是否安装成功。当然，出现这种情况的时候，你可以手动执行`adb install`先安装上，就可以绕过重新`clean build`的情况了。具体的优化体验在后续的版本里会给出...
2. pull 代码的时候重新`clean build`这种情况你要看日志具体分析，比如你`pull`完代码出现了`build.gradle`或者`AndroidManifest.xml`文件有修改，又或者由超过20个文件出现修改，会自动全量是正常的情况，这是 freeline 自动全量的策略
