### ISSUE TITLE
Task '–Pmirror' not found in root project 'Android'.

### ISSUE THREAD

**Issue by OccurSomething** [alibaba/freeline#319]
我好几个同事用命令行./gradlew initFreeline –Pmirror报错：
FAILURE: Build failed with an exception.

* What went wrong:
Task '–Pmirror' not found in root project 'Android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

如果不加-Pmirror下载又非常非常慢，这个该如何处理？

**Comment by lomanyong** [comment]
@OccurSomething `Task '–Pmirror' not found in root project 'Android'.`

这句话明显表示执行错了吧...那个`-`符号是减号...你貌似用了个特殊符号...

换成减号就可以了`./gradlew -Pmirror`
