### ISSUE TITLE
assets下的文件内容修改也会导致莫名其妙的问题以至于崩溃

### ISSUE THREAD

**Issue by OccurSomething** [alibaba/freeline#321]
修改assets下的某个文件，哪怕改动很小，会导致id错乱引发 Resources$NotFoundException、空指针等异常崩溃，我看到官方文档只介绍——不支持删除带id的资源，会报错，但感觉assets下的小小改动（任何改动，不仅仅是删除）也会导致类似问题，assets下的文件不算带id的资源吧？

**Comment by lomanyong** [comment]
@OccurSomething 我一会测试看看...

**Comment by OccurSomething** [comment]
这个问题有点怪异，我的工程（较复杂）就有问题，我做的简单的demo却没有这个问题。
我在主工程的assets文件夹下增加一个无用的txt文件，内容是一个字符串，修改字符串内容，增量编译成功之后运行每次都报错

**Comment by lomanyong** [comment]
@OccurSomething 方便把运行的python日志，跟crash的错误栈发出来看看嘛？

**Comment by OccurSomething** [comment]
不方便上传日志，这个问题也可能是累积造成的，但我把手机上的app删除之后再编译目前没再出现
