### ISSUE TITLE
查找project_description.json路径错误

### ISSUE THREAD

**Issue by ljk01200120** [alibaba/freeline#322]
我调用 gradlew checkBeforeCleanBuild 命令生成project_description.json文件在Save to C:\Users\58\.freeline\cache\a8775fbf2270880e63bcc33cd3ecd8c7\project_description.json 这个路径下，但是运行的时候说找不到这个文件，我看到程序是在另一个路径下找这个文件：freeline_core.exceptions.NoConfigFoundException: C:\Windows\system32\config\systemprofile\.freeline\cache\a8775fbf2270880e63bcc33cd3ecd8c7\project_description.json not found，为什么会去这个路径下找？

**Comment by lomanyong** [comment]
@ljk01200120  以下来自 Python 的文档：
>**os.path.expanduser(path)**

>On Unix and Windows, return the argument with an initial component of ~ or ~user replaced by that user‘s home directory.

>On Unix, an initial ~ is replaced by the environment variable HOME if it is set; otherwise the current user’s home directory is looked up in the password directory through the built-in module pwd. An initial ~user is looked up directly in the password directory.

>On Windows, HOME and USERPROFILE will be used if set, otherwise a combination of HOMEPATH and HOMEDRIVE will be used. An initial ~user is handled by stripping the last directory component from the created user path derived above.

>If the expansion fails or if the path does not begin with a tilde, the path is returned unchanged.

`os.path.expanduser('~')`这段代码原本应该返回的路径：`C:\Users\58\`，但是返回了`C:\Windows\system32\config\systemprofile`。

是否是你系统中这里的环境变量设置有问题？

- %HOME%
- %USERPROFILE%
- %HOMEDRIVE%%HOMEPATH%

**Comment by ljk01200120** [comment]
我的环境变量里设置了%HOME%，它的值是%USERPROFILE%，USERPROFILE这个的值是系统默认的吧，其它的没有设置，还会有其它对这个有影响吗？

**Comment by lomanyong** [comment]
@ljk01200120 你本地可以echo一下环境变量看看值吗？或者一个简单的python命令输出`os.path.expanduser('~')`的值看看？

**Comment by young316** [comment]
我这里也设置了本地的HOME路径，python的os.path.expanduser('~')指向了我的Home，但Gradle Plugin里，用的

**Comment by young316** [comment]
我的Windows 7 配了环境变量HOME，可以看到Python的os.path.expanduser('~')指向的是我自定义的HOME路径，但Groovy代码中使用的cachedir是System.properties['user.home']，指向的是C:/Users/xxx/

把dispatcher.py中cache_dir的路径使用os.getenv('USERPROFILE')后，可以正常使用，

===
@ljk01200120 的情况像是执行python脚本用了用户‘SYSTEM’的路径，而不是用户58的

**Comment by lomanyong** [comment]
@ljk01200120 @young316 hi，这样修改一下你的项目配置，修改版本号为：0.8.2.1611302135

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        ......
        classpath 'com.antfortune.freeline:gradle:0.8.2.1611302135'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
然后执行一下这个命令：

win: `gradlew initFreeline -PfreelineVersion=0.8.2.1611302135`
linux/mac: `./gradlew initFreeline -PfreelineVersion=0.8.2.1611302135`
执行 `python freeline.py -v` 确认一下 freeline 的版本为：0.8.2.1611302135

最后，重新使用freeline编译看下是否解决了你的问题。

**Comment by young316** [comment]
@lomanyong 谢谢回复，前几天看到了更新，自己本地打包验证过了，这个路径不会有平台、环境变量问题了

**Comment by lomanyong** [comment]
@young316 好的，0.8.3 发版后会正式 fix 这个问题..
