### ISSUE TITLE
extend other class not Loader class

### ISSUE THREAD

**Issue by abcdef434** [alibaba/freeline#328]
引入一個module使用當中的application class
````
public class App extends OtherApp {
}
````
原本為
````
public class App extends OtherApp
{
}
````
發現otherapp當中的oncreate沒被執行，後來改為第一個形式run freeline 即正常

不知道怎麼形容這狀況

**Comment by lomanyong** [comment]
@abcdef434 没看明白......你如果想要使用自己的application的话，参考一下issue #273 应该可以解决你的问题了...

**Comment by abcdef434** [comment]
嗯，我也不知道怎麼解釋這狀況
目前已在三個project導入使用，唯獨這個project有此問題
差異點在於"{"的位置
如果使用studio的run/debug無此問題，跑freeline compile沒問題但是在otherapp當中應該要初始化的東西卻回報null

調整"{"位置之後正常....

**Comment by abcdef434** [comment]
看過 #273 照做無用

**Comment by lomanyong** [comment]
@abcdef434 。。。跟"{"符号的位置有关系？

**Comment by abcdef434** [comment]
是的，所以我才非常疑惑

**Comment by abcdef434** [comment]
至少目前三個project的狀況是
public class App extends OtherApp {}
正常運作

**Comment by lomanyong** [comment]
@abcdef434 额...抱歉...这种问题就没打算fix了...所以issue我先关闭了...
