### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by zeng1990java** [alibaba/freeline#33]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeFirDebugAssets'.
> ../Gank/app/build/intermediates/assets/debug/apktime (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by lomanyong** [comment]
@zeng1990java 项目中是否有指定的flavor呢？有的话需要配置一下..例如：

````gradle
freeline {}

**Comment by zeng1990java** [comment]
有，
productFlavors {
            fir {
            }
        }
没看懂你说要配置什么

**Comment by lomanyong** [comment]
@zeng1990java 你们平时的打包命令是什么呢？比如如果是`gradlew.bat assembleFirDebug`的话，则flavor为Fir，则需要配置为：

````gradle
freeline {
    hack true
    productFlavor "fir"
}
````

**Comment by zeng1990java** [comment]
多谢，成功了，但是耗时还是一样的，看输出主要是install apk和clean build task和耗时很多，你看正常吗
[-][read_project_info_task] finished. in 4.9s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] finished. in 17.5s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 15.5s
[-][build_base_resource_task] finished. in 0.5s
[-][generate_project_info_task] finished. in 0.0s

**Comment by lomanyong** [comment]
@zeng1990java 你可以修改一下代码再执行一下`python freeline.py`看下。

freeline并不加速全量编译，主要是加速增量编译。在增量编译前，需要有一个全量编译的底包作为基线包。经过一次全量编译后，再执行`python freeline.py`就会进行增量编译了。如果遇见`build.gradle`以及`AndroidManifest.xml`之类的修改，freeline会自动执行全量编译重新打基线包。

**Comment by zeng1990java** [comment]
zxbdeMBP:FreelineDemo zxb$ python freeline.py 
[WARNING] check sync status failed, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 4.6s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] finished. in 9.6s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 13.9s
[-][build_base_resource_task] finished. in 0.4s
[-][generate_project_info_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 28.1s
[DEBUG] Total time: 28.4s
[DEBUG] --------------------------------------------------------
新建了一个只有一个MainActiivty和一个Application的工程，不管有没有改代码，每次的执行结果基本都要28秒多，不用freeline的时候也是这么久，不知道是不是使用的姿势不对

**Comment by lomanyong** [comment]
@zeng1990java 看日志提示猜测你的目标设备上装了多个依赖freeline的app，这个会导致基线对齐失败重新打全量包。估计目标设备上还安装了freeline sample这个app，可以卸载掉后重新试试看。

**Comment by zeng1990java** [comment]
对，我把其他使用了freeline的Demo项目删除后就是可以了，非常感谢你的解答 @lomanyong

**Comment by charvenhe** [comment]
@zeng1990java 方便的话在你们的项目试试，看看增量模式下，资源或代码修改耗时多少，跟你们原来相比如何

**Comment by zeng1990java** [comment]
@charvenhe 集成了，小改动的话2秒以内。但是好像不支持打包的时候改包文件名称，需要注释掉如下代码
`applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def outputFile = output.outputFile
            def outputDirPath = project.hasProperty('outputPath') ? outputPath : outputFile.parent
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def fileName
                if(project.hasProperty('outputPath')){
                    // 输出apk名称为Merchant_v1.0_SoftwareUpdate_release.apk
                    fileName = "Merchant_v${defaultConfig.versionName}_${variant.productFlavors[0].name}_${variant.buildType.name}.apk"
                }else{
                    // 输出apk名称为Merchant_v1.0_2015-01-15_SoftwareUpdate_release.apk
                    fileName = "Merchant_v${defaultConfig.versionName}_${releaseTime()}_${variant.productFlavors[0].name}_${variant.buildType.name}.apk"
                }

                output.outputFile = new File(outputDirPath, fileName)
            }
        }
    }`

**Comment by charvenhe** [comment]
@zeng1990java ,apk path 你可以通过DSL指定

freeline {
    hack true
    productFlavor "dev"
    apkPath "your apk path"
}

**Comment by zeng1990java** [comment]
可以了，多谢 @charvenhe

**Comment by charvenhe** [comment]
@zeng1990java 不客气，可以在你们项目多试试，资源增量也试试看看有没问题

**Comment by zeng1990java** [comment]
@charvenhe 恩
