### ISSUE TITLE
Didn't find class "com.antfortune.freeline.FreelineApplication"

### ISSUE THREAD

**Issue by le4** [alibaba/freeline#330]
按照官网的步骤继承的，一运行项目就报这个错误！
java.lang.ClassNotFoundException: Didn't find class "com.antfortune.freeline.FreelineApplication"

**Comment by lomanyong** [comment]
@le4 你是用的 Android Studio 的 run 来执行的吧...应该使用`python freeline.py -f`来编译，或者用插件的编译按钮来...否则会出现你的这些问题...

**Comment by le4** [comment]
好的，现在解决了 谢谢
