### ISSUE TITLE
全量编译的时候找不到apk安装包

### ISSUE THREAD

**Issue by OccurSomething** [alibaba/freeline#332]
增量编译好像是找不到apk的，全量编译也找不到吗？或者缓存在哪个文件夹下？
不能像as的编译能在build/output/apk下能看到apk文件吗？

**Comment by lomanyong** [comment]
@OccurSomething 什么意思呢？增量编译是不会编译出新的apk的，freeline本质上就是在一个apk上不断地做热更新...只会有增量产物（res.pack或者dex），不会有新的apk。

如果想要更清楚地了解的话，建议可以去看下一下的文章：
- [Freeline - Android平台上的秒级编译方案](https://yq.aliyun.com/articles/59122)
- [Android秒级编译工具Freeline新特性支持！](https://yq.aliyun.com/articles/62334)

**Comment by OccurSomething** [comment]
我主要问的是全量编译也没有apk？

**Comment by lomanyong** [comment]
@OccurSomething 全量编译跟普通编译一样，出来的apk都在`build/outputs/apk`这个路径这里...
