### ISSUE TITLE
initFreeline的时候报错

### ISSUE THREAD

**Issue by sameland** [alibaba/freeline#334]
initFreeline的时候报错了，错误信息如下，是gradle的版本问题吗？我现在的gradle版本是2.2.1的

* What went wrong:
A problem occurred evaluating project ':packages:jupiter'.
> Failed to apply plugin [id 'com.antfortune.freeline']
   > Could not find method testCompile() for arguments [com.antfortune.freeline:runtime-no-op:0.8.2] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@1ac9a702.

**Comment by lomanyong** [comment]
@sameland 麻烦google一下`Could not find method testCompile() for arguments`，然后找下错误的原因吧...

**Comment by sameland** [comment]
testCompile()貌似是Gradle Java plugin内的方法，看这个错误提示是freeline plugin中用了testCompile去依赖了com.antfortune.freeline:runtime-no-op:0.8.2这个包导致的，我试了一下直接通过androidTestCompile去依赖com.antfortune.freeline:runtime-no-op:0.8.2这个包就不会出现这个问题，通过testCompile去依赖就报错了同样的问题。

**Comment by sameland** [comment]
找到问题了，低版本的Android gradle plugin不支持testCompile方法

**Comment by lomanyong** [comment]
@sameland 大概是到多少版本可以说明一下吗？

**Comment by sameland** [comment]
@lomanyong 应该是1.1以上的版本才支持，具体可以参考一下这个http://stackoverflow.com/questions/32893008/gradle-dsl-method-not-found-testcompile

**Comment by lomanyong** [comment]
@sameland 那版本也确实是太低了....我自测过的大概支持android gradle plugin 1.3-~1.5+吧

**Comment by sameland** [comment]
嗯嗯  我这边已经升级了  现在又遇到了一个问题找不到这个Task啊   Task 'initFreeline' not found   ＝ ＝

**Comment by lomanyong** [comment]
@sameland  `apply plugin: "com.antfortune.freeline"`这个加上后自然能找到...

**Comment by sameland** [comment]
加了的。。。

**Comment by lomanyong** [comment]
@sameland #47 #86 应该是你本地的问题...

**Comment by sameland** [comment]
好的 我看看哈 谢啦

**Comment by sameland** [comment]
还有是有问题，我这边的主module工程是在root目录下的子目录下的，就相当于是三级目录了，但我看python脚本去拿主module的时候，只把我这个主module工程的名称拿出来跑，少了二级目录，所有就会报找不到该project的问题

**Comment by lomanyong** [comment]
@sameland 我自己记个issue吧，尽快给你修复这个问题。麻烦你把错误栈给我发下，或者给我提供一个sample工程，我好尽快解决这个问题。

**Comment by sameland** [comment]
其实就是这一块脚本去拿module name的时候有些局限

**Comment by sameland** [comment]
def get_all_modules(dir_path):
    settings_path = os.path.join(dir_path, 'settings.gradle')
    if os.path.isfile(settings_path):
        data = get_file_content(settings_path)
        modules = []
        for item in re.findall(r'''['"]:(.*?)['"]''', data):
            index = item.rfind(':')
            if index == -1:
                modules.append({'name': item, 'path': item})
            else:
                modules.append({'name': item[index + 1:], 'path': item.replace(":", os.sep)})
        # modules = [item.replace(":", os.sep) for item in re.findall(r'''['"]:(.*?)['"]''', data)]
        return filter(lambda module: os.path.isdir(os.path.join(dir_path, module['path'])), modules)
    return []


比如我是:A:B,这里只能拿到B，但真正的路径是:A:B

**Comment by lomanyong** [comment]
@sameland 正常情况下不会走这段逻辑的，这段是0.5.x的时候的早期逻辑了，新的模块获取都是从gradle插件来的...

**Comment by sameland** [comment]
加了这个貌似就ok了
freeline {
    buildScript ""
}


但又遇到了另外一个问题：
 File "/Users/Ethan/Android/wandoujia/tinker/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/Ethan/Android/wandoujia/tinker/freeline/freeline_core/gradle_clean_build.py", line 116, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "/Users/Ethan/Android/wandoujia/tinker/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by lomanyong** [comment]
@sameland 额..加那个不对...你可以先看下wiki的 DSL-References...`buildScript`是全量编译命令...直接放空的跟没放其实差不多...

你遇见的那个问题有完整的日志吗？建议调试freeline的时候使用`python freeline.py -d`命令，会输出比较完成的日志...

**Comment by sameland** [comment]
嗯嗯  因为我的工程在三层目录里，所以需要加上buildScript才能正常编译，buildScript的gradle路径不对才报错了 ＝ ＝，现在已经OK了。现在又遇到了一个新问题：
* What went wrong:
Execution failed for task ':packages:jupiter:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 14 declared in library [com.antfortune.freeline:runtime:0.8.2] /Users/Ethan/Android/wandoujia/tinker/packages/jupiter/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.antfortune.freeline" to force usage

freeline只支持14以上吗？

**Comment by lomanyong** [comment]
@sameland 是的...默认最低sdk 14，你可以直接按照推荐的做法` use tools:overrideLibrary="com.antfortune.freeline" to force usage`，覆盖掉...反正你们测试的时候不会使用低版本的设备，打包的话不会有影响..

**Comment by sameland** [comment]
嗯嗯  问题都解决了  增量编译很强！ 谢哈
