### ISSUE TITLE
Whether trigger the full compilation is determined by files which md5 value has been modified

### ISSUE THREAD

**Issue by aa5279aa** [alibaba/freeline#338]
Now，if we modify some files like manifest.xml,build.gradle, and execute python freeline.py ,that will trigger a full compilation.

Generally, we decide whether or not to modify the file based on the last modification time.
In the case, it will cause a problem. 

It will still lead to a full compilation even if we stash the file with no change like manifest.xml. 
I hope to solve this problem as soon as possible.

Therefore,I suggest that we should judge this core file by it's MD5 value. 

At least we should have a while list,whether the file in the white list has changed, it should be defined by its MD5 value rather than the last modification time.

**Comment by lomanyong** [comment]
@aa5279aa Nice suggestion, the white list can be configured in build.gradle with freeline DSL that will be embed in `project_description.json`.

And do you intend to ignore all the files that will cause full build?

**Comment by Soul-HQian** [comment]
@aa5279aa good idea！

**Comment by aa5279aa** [comment]
Nice!
Other use modify time.
