### ISSUE TITLE
freeline_id_keeper_public error，能运行，但是有error

### ISSUE THREAD

**Issue by lzhAndroid** [alibaba/freeline#339]
build/freeline/dating/backup/res/values/freeline_id_keeper_public.xml:16887: error: Public symbol color/svip_border_color declared here is not defined.

猜测是因为library的colors.xml文件有svip_border_color的资源，application中定义了相同的资源导致的。

[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 278.2s
[DEBUG] Total time: 278.4s
[DEBUG] --------------------------------------------------------

**Comment by lzhAndroid** [comment]
已经升级到最新的0.8.2版本了，还是有这个问题。缓存什么的都清过了

**Comment by lomanyong** [comment]
@lzhAndroid 参考wiki - 常见问题#资源编译出错，你应该可以知道那些not found的资源在哪个文件夹，添加进入配置文件即可（只需要res一级，不需要区分到drawable）

具体配置参考wiki或者issue #337 #238 #269

**Comment by lzhAndroid** [comment]
我在DSL里加入了，extraResourceDependencyPaths = ['../dating/src/main/res/'] ，这个路径是以写freeline DSL的build文件为相对路径的对么？加了以后，还是有问题。同一目录下，我的colors.xml文件有两个，分别是colors.xml和colors_bbb.xml。这个会有影响么？

**Comment by lzhAndroid** [comment]
@lomanyong

**Comment by lzhAndroid** [comment]
我在DSL里加入了，extraResourceDependencyPaths = ['../dating/src/main/res/'] ，这个路径是以写freeline DSL的build文件为相对路径的对么？加了以后，还是有问题。同一目录下，我的colors.xml文件有两个，分别是colors.xml和colors_bbb.xml。这个会有影响么？ @lomanyong

**Comment by lomanyong** [comment]
@lzhAndroid 没有影响的，你参考一下别人是如何进行配置的...尽量写全路径，或者用groovy语法来拼接..

**Comment by lzhAndroid** [comment]
@lomanyong 写了绝对路径后，databinding的layout出问题了。里面的@{}语法会出现找不到资源的报错。如果我路径写到values一级，又变回原来的color资源找不到了😂

**Comment by lomanyong** [comment]
@lzhAndroid 路径只要写到res就可以了..后面再细节的路径不需要写...
