### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by yangwuan55** [alibaba/freeline#34]
![image](https://cloud.githubusercontent.com/assets/5218120/18043042/c329bed4-6df7-11e6-954d-bfc67402fb7a.png)
initFreeline的时候不断出现上面的情况，求解。

**Comment by lomanyong** [comment]
@yangwuan55 去掉`--debug`之类的参数看下呢？上面的干扰信息比价多看不出来内容

如果是因为国内网络环境问题导致的话，可以使用`./gradlew initFreeline -Pmirror`，来使用镜像下载

**Comment by gaoxuxu** [comment]
./gradlew initFreeline -Pmirror 我使用的时候下载失败了，挂个代理就行

**Comment by lomanyong** [comment]
@gaoxuxu 如果连`./gradlew initFreeline -Pmirror`都需要使用代理的话...那么你那里的网络访问github api应该也存在问题...
