### ISSUE TITLE
文档中说是支持2.x～6.x,我的build.gradle中设置minsdk为11时编译会报错如下

### ISSUE THREAD

**Issue by ChaserSheng** [alibaba/freeline#340]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 11 cannot be smaller than version 14 declared in library [com.antfortune.freeline:runtime:0.8.2] /Users/wangsheng/AndroidStudioProjects/GoldMobileBank-Android/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.antfortune.freeline" to force usage

**Comment by lomanyong** [comment]
@ChaserSheng 之前的一篇技术文章看到的吧，当时测试过支持2.x-6.x，不过当时还没开源...。开源后的sdk版本是从sdk 14开始的...不建议使用以下的..
