### ISSUE TITLE
一直卡在read_project_info_task...

### ISSUE THREAD

**Issue by MeiXXD** [alibaba/freeline#343]
mac os，as版本2.2.2，gradle 2.14.1，build gradle 2.2.2。
安装插件后，发现在application gradle文件中添加了github中介绍的依赖代码，然后同步了一下。之后点击插件安装后出来的Freeline图标，一直卡着不动。卡着不向下走，只能手动关掉。

请问这是什么原因？谢谢啦。我没有配置正确吗？

**Comment by MeiXXD** [comment]
通过执行 ./gradlew checkBeforeCleanBuild 已解决，谢谢啦！好用，好快！！！

**Comment by yang1006** [comment]
./gradlew checkBeforeCleanBuild有用，同样问题已解决。
