### ISSUE TITLE
想问一下是不是不支持dagger?

### ISSUE THREAD

**Issue by vbnn20** [alibaba/freeline#344]
第一次python freeline.py之后,
我在fragment中inject就不能成功编译。

**Comment by lomanyong** [comment]
@vbnn20 不要光描述现象。。不能成功编译的话有日志就贴一下日志...还有是在什么情况下出现的...

**Comment by vbnn20** [comment]
Detele

**Comment by lomanyong** [comment]
@vbnn20 hi，这样修改一下你的项目配置，修改版本号为：0.8.2.1611262211
````gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        ......
        classpath 'com.antfortune.freeline:gradle:0.8.2.1611262211'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
````

然后执行一下这个命令：

- win: `gradlew initFreeline -PfreelineVersion=0.8.2.1611262211`
- linux/mac: `./gradlew initFreeline -PfreelineVersion=0.8.2.1611262211`

然后重新使用freeline编译看下是否解决了你的问题。

**Comment by vbnn20** [comment]
Detele

**Comment by lomanyong** [comment]
@vbnn20 你们可以先用着这个版本，后续有问题再给我提issue吧，这个bug的修复在下个版本进入...后面升级了就能正常使用了...
