### ISSUE TITLE
感觉每次都是全量编译

### ISSUE THREAD

**Issue by pphdsny** [alibaba/freeline#35]
# python freeline.py
**[WARNING] NoInstallationException occurs, a clean build will be automatically executed.**
[-][read_project_info_task] finished. in 22.1s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] finished. in 164.6s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 27.5s
[-][build_base_resource_task] finished. in 10.2s
[-][generate_project_info_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 15.1s
[DEBUG] Task engine running time: 214.3s
[DEBUG] Total time: 229.4s
[DEBUG] --------------------------------------------------------

是不是上面的Warning造成的？

**Comment by lomanyong** [comment]
@pphdsny 是的，可以先确认一下手机上是否安装了多个依赖了freeline的app吗？比如说freeline的sample工程，如果有的话，可以卸载掉，再重新用freeline打包试试看

**Comment by pphdsny** [comment]
freeline的sample工程没有安装，至于其他的App是否有用过freeline,这边就不太清楚了。有木有办法能看其他App有木有用freeline

**Comment by lomanyong** [comment]
@pphdsny 通常报这个exception是因为你的手机上执行`adb shell pm list package {your package}`，没有存在你的工程app导致的..

**Comment by pphdsny** [comment]
@lomanyong 是不是adb命令要配全局环境啊，我这边木有配置！

**Comment by lomanyong** [comment]
@pphdsny freeline会自动去获取你的adb所在的位置的，这点不会影响。你本地要自己使用`adb`命令的话，可以自己配置下环境变量

**Comment by pphdsny** [comment]
@lomanyong 
adb shell pm list package com.yourdream.app.android
package:com.yourdream.app.android
执行了，你上面的那条命令，是有这个包存在的！

**Comment by lomanyong** [comment]
@pphdsny 可以看一下`~/.freeline/cache/xxxxxxx/project_description.json`这个文件，看下里面的`pakage`字段是否正确

**Comment by charvenhe** [comment]
@pphdsny Freeline的运行期依赖加了么

**Comment by pphdsny** [comment]
@charvenhe 加了依赖
@lomanyong 看了该文件，里面找到package为null

**Comment by lomanyong** [comment]
@pphdsny 额...`python freeline.py -f`之后，查看那个文件，这个字段还是null？

package这个字段是根据applicationId来获取的，通常都配置在defaultConfig DSL里，你们这里有特殊配置吗？

**Comment by pphdsny** [comment]
@lomanyong 好了，我们applicationId没有配置，用的是AndroidManifest里面默认的，加上去就好了，谢谢了！真的编译很快~

**Comment by lomanyong** [comment]
@pphdsny 欢迎多体验哈~增量java跟增量资源都可以试试看

**Comment by pphdsny** [comment]
@lomanyong 再问个问题，新增的freeline.py和freeline，你们会加到git版本控制里面去么？

**Comment by lomanyong** [comment]
@pphdsny 你们可以自己添加到`.gitignore`里面的
