### ISSUE TITLE
警告: [options] 未与 -source 1.7 一起设置引导类路径

### ISSUE THREAD

**Issue by fuzhengchao** [alibaba/freeline#350]
错误: 程序包android.support.v7.widget不存在

警告下面就是一连串的类找不到。

**Comment by lomanyong** [comment]
@fuzhengchao 这个问题好久没遇见了...你用的是哪个版本的freeline？

然后，可以检查下${main_module}/build/freeline/jar_dependencies.json这个文件是否存在，以及里面是否有内容...

**Comment by fuzhengchao** [comment]
我把jdk改为1.7了，没有报这个警告了。${main_module}/build/freeline/jar_dependencies.json这个文件存在的，里面有内容。第一次能够成功运行，修改一个module种的代码过后，运行时会出现该module下一连串类找不到。

**Comment by lomanyong** [comment]
@fuzhengchao 确认下，找不到的是否都是系统类？

如果是linux/mac下的话，运行`python freeline.py -d`，如果是windows的话直接运行后，freeline的日志里会有一个javac命令，可以看下相应的classpath是否添加进入命令行中了...

**Comment by fuzhengchao** [comment]
不是系统类，我修改了一个类。出现找不到的类都是我修改这个类import的类。javac在执行我修改的类时就失败了，error是  incremental  javac compile failed.

**Comment by lomanyong** [comment]
@fuzhengchao 麻烦贴个完整的日志吧...

**Comment by fuzhengchao** [comment]
@lomanyong 日志见附件，非常感谢。

[freeline.txt](https://github.com/alibaba/freeline/files/614727/freeline.txt)

**Comment by fuzhengchao** [comment]
@lomanyong 恩，使用的0.8.2版本。

**Comment by lomanyong** [comment]
@fuzhengchao 从日志来看应该缺失了几个关键的依赖字段...缺失的原因还需要你本地的几份日志文件来分析看看，麻烦将文件发邮件给我一下吧... lomanyong#gmail.com

几个文件：
- `${main_module}/build/freeline/jar_dependencies.json`
- `${main_module}/build/freeline/project_info_cache.json`
- `~/.freeline/cache/xxxxx/project_description.json`

**Comment by fuzhengchao** [comment]
@lomanyong 好的。

**Comment by lomanyong** [comment]
经确认是第三方 gradle 分包插件导致的..
