### ISSUE TITLE
运行完了但是apk并没有装到手机上

### ISSUE THREAD

**Issue by kingofglory** [alibaba/freeline#351]
[DEBUG] [tracing] build_base_resource_aapt_task: 4161.00001335ms
[DEBUG] [build_base_resource_task] build_base_resource_task finish in 4.2s
[DEBUG] [task_engine] it takes task engine 32.09s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 32.1s
[DEBUG] Total time: 32.3s
[DEBUG] --------------------------------------------------------
如上，显示任务执行完了，但是apk并没有安装到手机上。三星galaxy s4 ，4.2.2安卓版本

**Comment by lomanyong** [comment]
@kingofglory 上面的日志里应该有个`adb install`的命令，可以看下命令是否正确，包括 apk path之类的信息。也需要检查一下你的设备是否是online的，可以通过`adb devices`查看。

如果apk path出错的话，可以添加配置修改一下：
````gradle
freeline {
    ....
    apkPath "your-apk-path"
}
````
