### ISSUE TITLE
安装依赖报错java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by OccurSomething** [alibaba/freeline#353]
命令行./gradlew.initFreeline -Pmirror 安装依赖时报错
java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0
提示我的某个子工程第一行报上面这个错，我的子工程本来用的是apply plugin: 'android-library'，但改成apply plugin: 'com.android.library'之后还是一样报错

**Comment by lomanyong** [comment]
@OccurSomething 看下`java -version`的版本，你现在需要升级到 java8才能编译...

这个是你本地的问题..不是freeline导致的...

可以参考：
- [Getting error when trying to run new project in Android Studio 2.2.1](http://stackoverflow.com/questions/37312404/getting-error-when-trying-to-run-new-project-in-android-studio-2-2-1)
- [How to fix java.lang.UnsupportedClassVersionError: Unsupported major.minor version](http://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi)
