### ISSUE TITLE
国内 cdn 源支持

### ISSUE THREAD

**Issue by zhenian** [alibaba/freeline#354]
./gradlew initFreeline   时， 发现，下载 

https://github.com/alibaba/freeline/releases/download/0.8.2/freeline-v0.8.2.zip  

时会跳到 github-cloud.s3.amazonaws.com 去。

众所周知的原因，导致卡死。是否可以添加国内 cdn 源支持？？

**Comment by lomanyong** [comment]
@zhenian 额，没仔细看 README 吧...已有国内镜像支持。执行`./gradlew initFreeline -Pmirror`即可
