### ISSUE TITLE
ubuntu 16.04 failed

### ISSUE THREAD

**Issue by taoisym** [alibaba/freeline#355]
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/home/taoisym/src/in/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/home/taoisym/src/in/freeline/freeline_core/gradle_clean_build.py", line 116, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "/home/taoisym/src/in/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------

**Comment by lomanyong** [comment]
@taoisym 目录下没有`gradlew`文件？

**Comment by taoisym** [comment]
有，运行了./gradlew initFreeline
Python 2.7.12

**Comment by taoisym** [comment]
+ default shell is zsh

**Comment by lomanyong** [comment]
@taoisym `python freeline.py -d`会输出运行的编译命令...看下那个编译命令是否有问题...

**Comment by taoisym** [comment]
试过了，错误差不多

**Comment by lomanyong** [comment]
@taoisym 不是啊……执行那个命令会输出调试日志…里面有gradle的编译命令…看那个命令是否有问题…

或者你直接把日志都贴出来…

**Comment by taoisym** [comment]
[DEBUG] [task_engine] it takes task engine 17.38s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/home/taoisym/src/in/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/home/taoisym/src/in/freeline/freeline_core/gradle_clean_build.py", line 116, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "/home/taoisym/src/in/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 17.4s
[DEBUG] Total time: 17.6s
[DEBUG] --------------------------------------------------------

**Comment by taoisym** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] find root build.gradle changed, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /home/taoisym/src/in/app.in/app.main/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 772542
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app.main module file stat
[DEBUG] [generate_file_stat_task] save app.custompaster module file stat
[DEBUG] [generate_file_stat_task] save app.usercenter module file stat
[DEBUG] [generate_file_stat_task] save app.publish2 module file stat
[DEBUG] [generate_file_stat_task] save app.friend module file stat
[DEBUG] [generate_file_stat_task] save app.login module file stat
[DEBUG] [generate_file_stat_task] save app.tag module file stat
[DEBUG] [generate_file_stat_task] save app.square module file stat
[DEBUG] [generate_file_stat_task] save app.diary module file stat
[DEBUG] [generate_file_stat_task] save app.pastermall module file stat
[DEBUG] [generate_file_stat_task] save app.livecam module file stat
[DEBUG] [generate_file_stat_task] save app.camera module file stat
[DEBUG] [generate_file_stat_task] save app.photo module file stat
[DEBUG] [generate_file_stat_task] save app.testhelper module file stat
[DEBUG] [generate_file_stat_task] save lib.in.delegate module file stat
[DEBUG] [generate_file_stat_task] save lib.in.resources module file stat
[DEBUG] [generate_file_stat_task] save lib.in.font module file stat
[DEBUG] [generate_file_stat_task] save lib.comm.util module file stat
[DEBUG] [generate_file_stat_task] save lib.in.chat module file stat
[DEBUG] [generate_file_stat_task] save lib.in.push module file stat
[DEBUG] [generate_file_stat_task] save lib.in.pay module file stat
[DEBUG] [generate_file_stat_task] save lib.in.qrcode module file stat
[DEBUG] [generate_file_stat_task] save lib.in.storage module file stat
[DEBUG] [generate_file_stat_task] save lib.in.http module file stat
[DEBUG] [generate_file_stat_task] save lib.in.upload module file stat
[DEBUG] [generate_file_stat_task] save lib.in.statistics module file stat
[DEBUG] [generate_file_stat_task] save lib.in.location module file stat
[DEBUG] [generate_file_stat_task] save lib.core.encrypt module file stat
[DEBUG] [generate_file_stat_task] save lib.in.ar module file stat
[DEBUG] [generate_file_stat_task] save lib.in.tagimagelayout module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.3s
[DEBUG] [read_project_info_task] read_project_info_task finish in 17.4s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 17.4s
[DEBUG] [gradle_clean_build_task] gradlew.bat :app.in:app.main:assembleDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 17.4s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 17.4s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 17.4s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 17.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 17.38s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/home/taoisym/src/in/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/home/taoisym/src/in/freeline/freeline_core/gradle_clean_build.py", line 116, in execute
    output, err, code = cexec(command.split(' '), callback=None, cwd=cwd)
  File "/home/taoisym/src/in/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 17.4s
[DEBUG] Total time: 17.6s
[DEBUG] --------------------------------------------------------

**Comment by taoisym** [comment]
估计什么问题？

**Comment by lncosie** [comment]
这个是mac下的,也出错了

[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
python freeline.py  
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.0s
[-][generate_file_stat_task] finished. in 0.4s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guaziorg/src/in/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/guaziorg/src/in/freeline/freeline_core/gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/guaziorg/src/in/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 0.4s
[DEBUG] Total time: 0.7s
[DEBUG] --------------------------------------------------------
➜  in #
➜  in python freeline.py -d  
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False, wait=False)
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /Users/guaziorg/src/in/app.in/app.main/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 194711
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app.main module file stat
[DEBUG] [generate_file_stat_task] save app.custompaster module file stat
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app.usercenter module file stat
[DEBUG] [generate_file_stat_task] save app.publish2 module file stat
[DEBUG] [generate_file_stat_task] save app.friend module file stat
[DEBUG] [generate_file_stat_task] save app.login module file stat
[DEBUG] [generate_file_stat_task] save app.tag module file stat
[DEBUG] [generate_file_stat_task] save app.square module file stat
[DEBUG] [generate_file_stat_task] save app.diary module file stat
[DEBUG] [generate_file_stat_task] save app.pastermall module file stat
[DEBUG] [generate_file_stat_task] save app.livecam module file stat
[DEBUG] [generate_file_stat_task] save app.camera module file stat
[DEBUG] [generate_file_stat_task] save app.photo module file stat
[DEBUG] [generate_file_stat_task] save app.testhelper module file stat
[DEBUG] [generate_file_stat_task] save lib.in.delegate module file stat
[DEBUG] [generate_file_stat_task] save lib.in.resources module file stat
[DEBUG] [generate_file_stat_task] save lib.in.font module file stat
[DEBUG] [generate_file_stat_task] save lib.comm.util module file stat
[DEBUG] [generate_file_stat_task] save lib.in.chat module file stat
[DEBUG] [generate_file_stat_task] save lib.in.push module file stat
[DEBUG] [generate_file_stat_task] save lib.in.pay module file stat
[DEBUG] [generate_file_stat_task] save lib.in.qrcode module file stat
[DEBUG] [generate_file_stat_task] save lib.in.storage module file stat
[DEBUG] [generate_file_stat_task] save lib.in.http module file stat
[DEBUG] [generate_file_stat_task] save lib.in.upload module file stat
[DEBUG] [generate_file_stat_task] save lib.in.statistics module file stat
[DEBUG] [generate_file_stat_task] save lib.in.location module file stat
[DEBUG] [generate_file_stat_task] save lib.core.encrypt module file stat
[DEBUG] [generate_file_stat_task] save lib.in.ar module file stat
[DEBUG] [generate_file_stat_task] save lib.in.tagimagelayout module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.3s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.35s to execute tasks.
python freeline.py -d  
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False, wait=False)
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /Users/guaziorg/src/in/app.in/app.main/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 291553
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app.main module file stat
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app.custompaster module file stat
[DEBUG] [generate_file_stat_task] save app.usercenter module file stat
[DEBUG] [generate_file_stat_task] save app.publish2 module file stat
[DEBUG] [generate_file_stat_task] save app.friend module file stat
[DEBUG] [generate_file_stat_task] save app.login module file stat
[DEBUG] [generate_file_stat_task] save app.tag module file stat
[DEBUG] [generate_file_stat_task] save app.square module file stat
[DEBUG] [generate_file_stat_task] save app.diary module file stat
[DEBUG] [generate_file_stat_task] save app.pastermall module file stat
[DEBUG] [generate_file_stat_task] save app.livecam module file stat
[DEBUG] [generate_file_stat_task] save app.camera module file stat
[DEBUG] [generate_file_stat_task] save app.photo module file stat
[DEBUG] [generate_file_stat_task] save app.testhelper module file stat
[DEBUG] [generate_file_stat_task] save lib.in.delegate module file stat
[DEBUG] [generate_file_stat_task] save lib.in.resources module file stat
[DEBUG] [generate_file_stat_task] save lib.in.font module file stat
[DEBUG] [generate_file_stat_task] save lib.comm.util module file stat
[DEBUG] [generate_file_stat_task] save lib.in.chat module file stat
[DEBUG] [generate_file_stat_task] save lib.in.push module file stat
[DEBUG] [generate_file_stat_task] save lib.in.pay module file stat
[DEBUG] [generate_file_stat_task] save lib.in.qrcode module file stat
[DEBUG] [generate_file_stat_task] save lib.in.storage module file stat
[DEBUG] [generate_file_stat_task] save lib.in.http module file stat
[DEBUG] [generate_file_stat_task] save lib.in.upload module file stat
[DEBUG] [generate_file_stat_task] save lib.in.statistics module file stat
[DEBUG] [generate_file_stat_task] save lib.in.location module file stat
[DEBUG] [generate_file_stat_task] save lib.core.encrypt module file stat
[DEBUG] [generate_file_stat_task] save lib.in.ar module file stat
[DEBUG] [generate_file_stat_task] save lib.in.tagimagelayout module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.4s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guaziorg/src/in/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/guaziorg/src/in/freeline/freeline_core/gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/guaziorg/src/in/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 0.4s
[DEBUG] Total time: 0.7s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@taoisym 你是虚拟机？还是真的在ubuntu下的？被识别成windows了...

解决方案就是配置一下buildScript：
````gradle
freeline {
    ...
    buildScript: "./gradlew :app.in:app.main:assembleDebug"
}
````

**Comment by lomanyong** [comment]
@lncosie `chmod +x gradlew`

**Comment by taoisym** [comment]
不是虚拟机，我先试试这个2个方法

**Comment by lomanyong** [comment]
@taoisym 有挺多 Linux 环境下的都使用过...第一次遇见会在 Linux 下会被识别成 Windows 的...感觉有点奇怪...

**Comment by taoisym** [comment]
是的哦，我们自己的一个gradle 脚本，也出现了这个问题，后来加了个platform='unix'才好

**Comment by lomanyong** [comment]
@taoisym 现在可以正常使用了吗？

**Comment by taoisym** [comment]
估计是我们自己的脚本问题    
你给的这个
buildScript: "./gradlew :app.in:app.main:assembleDebug"
被我们改过了，我看看

**Comment by taoisym** [comment]
我用uname输出的是
Linux

**Comment by lomanyong** [comment]
@taoisym freeline 在 gradle 插件中判断系统是调用了：`Os.isFamily(Os.FAMILY_WINDOWS)`，你可以直接在你的`build.gradle`文件里调用输出看看...

**Comment by yanglele** [comment]
@lomanyong windows10 下也报
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
File "/Users/guaziorg/src/in/freeline/freeline_core/task.py", line 123, in execute
self.task.execute()
File "/Users/guaziorg/src/in/freeline/freeline_core/gradle_clean_build.py", line 75, in execute
output, err, code = cexec(command.split(' '), callback=None)
File "/Users/guaziorg/src/in/freeline/freeline_core/utils.py", line 28, in cexec
p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
这个错误，windows下没有chmod命令啊，求解
