### ISSUE TITLE
全量编译能通过，增量编译就报错

### ISSUE THREAD

**Issue by niugehaoshuai** [alibaba/freeline#359]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Freeline trace:: makeFileResources all resource. Time Elapsed: 51.740000 ms 
Freeline trace:: compile values. Time Elapsed: 700.360000 ms 
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.237000 ms 

gChangeList = res/activitys/layout/activity_email_login.xml:res/values/freeline_id_keeper_public.xml:res/values/freeline_id_keeper_ids.xml
-resoucres-md5-cache-path = /Users/nieshun/Documents/space/Github1/oeasy_android/opmeetingsystem/build/freeline/arsc_cache.dat
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
warning: overwriting '/Users/nieshun/Documents/space/Github1/oeasy_android/opmeetingsystem/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/assets/apktime' with '/Users/nieshun/Documents/space/Github1/oeasy_android/opmeetingsystem/build/freeline/freeline-assets/apktime'
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
/Users/nieshun/Documents/space/Github1/oeasy_android/opmeetingsystem/build/freeline/opmeetingsystem/backup/res/values/freeline_id_keeper_public.xml:9014: error: Public symbol string/area declared here is not defined.
/Users/nieshun/Documents/space/Github1/oeasy_android/opmeetingsystem/build/freeline/opmeetingsystem/backup/res/values/freeline_id_keeper_public.xml:10652: error: Public symbol string/type declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 1.6s
[DEBUG] Total time: 1.9s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@niugehaoshuai 关键的日志：
````
/Users/nieshun/Documents/space/Github1/oeasy_android/opmeetingsystem/build/freeline/opmeetingsystem/backup/res/values/freeline_id_keeper_public.xml:9014: error: Public symbol string/area declared here is not defined.
/Users/nieshun/Documents/space/Github1/oeasy_android/opmeetingsystem/build/freeline/opmeetingsystem/backup/res/values/freeline_id_keeper_public.xml:10652: error: Public symbol string/type declared here is not defined.
````

是否执行了删除 string 资源的操作？

如果不是的话，可以看看这两个没有找到的资源是定义在哪个路径的，是否是第三方库引入的？

**Comment by niugehaoshuai** [comment]
@lomanyong 没有删除 string 类型的数据，也没有引入第三方库，我的增量编译没有成功过，特意只改了一个跳转和一个 padding 属性。弱弱的问下，怎么知到这两个资源的定义路径

**Comment by lomanyong** [comment]
@niugehaoshuai 不是很清楚你是怎么操作的...你可以先尝试 clean 一下，然后再编译。

string 资源定义的路径就是指`string/area`和`string/type`这两个 string 资源定义在哪个 strings.xml 里，路径在哪里。可以通过全局搜搜找一下...

`python freeline.py -d`会输出 freeline 的调试日志...在编译出错的地方有一个 aapt 命令。aapt 命令通过`-s`参数把各个资源路径添加进去打包。

通常，freeline 应该会自动找全所有的资源路径，并添加到 aapt 命令的参数里。出现这个错误的原因主要就两个：
1. 删除了资源了（freeline 目前不支持删除带 id 的资源）
2. 缺失了资源路径导致没有找到

**Comment by niugehaoshuai** [comment]
clean 了一下可以了，非常感谢你回复这么及时
