### ISSUE TITLE
gradle sync失败

### ISSUE THREAD

**Issue by philos3** [alibaba/freeline#360]
Failed to resolve: com.antfortune.freeline:runtime:0.8.2

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.1'
        classpath 'com.antfortune.freeline:gradle:0.8.2'
    }
}

compileSdkVersion 23
    buildToolsVersion '23.0.3'

**Comment by lomanyong** [comment]
@philos3 网络问题...

文件是存在的：http://jcenter.bintray.com/com/antfortune/freeline/runtime/0.8.2/

**Comment by philos3** [comment]
不大可能啊，这两天一直都是这个错误

**Comment by lomanyong** [comment]
@philos3 不然别人是怎么可以下载的呢....文件有没有那个链接访问一下就知道了...

**Comment by philos3** [comment]
原因找到了http://jcenter.bintray.com/ 我的项目是mavenCentral() （有些包在maven私服上），怎么同时支持jcenter()和mavenCentral()

**Comment by lomanyong** [comment]
@philos3 在 build.gradle 中配置一下就行了...

````gradle
allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}

````

**Comment by philos3** [comment]
这样配置是优先走jcenter?找不到再去mavencenter？？

**Comment by lomanyong** [comment]
@philos3 right，你也可以自己调换顺序...

**Comment by philos3** [comment]
THX~~~
