### ISSUE TITLE
Execution failed for task initFreeline

### ISSUE THREAD

**Issue by DovSnier** [alibaba/freeline#361]
Error:Execution failed for task ':initFreeline'.
> Can't get http://obr0ndq7a.bkt.clouddn.com/freeline/freeline-v0.8.2.zip to F:\WorkSpace\freeline.zip.tmp

**Comment by lomanyong** [comment]
@DovSnier 网络问题...已经是国内镜像了。麻烦提issue前先搜索一下已有的issue。

可以参考 issue #345

**Comment by DovSnier** [comment]
你好,这个之前我看了下的,大致步骤(**window 环境**)如下:
1.安装配置Python 2.7.12环境变量;
2.clean 项目;
3.执行gradlew checkBeforeCleanBuild;
4.执行gradlew initFreeline -Pmirror ,这个和#345情况一样(这个还是不行,但是mac 上直接就过去了,不知道window 本地环境有啥我没有配置好的呢);
5.最终自己拿着报错的url链接下载下来,解压到指定项目目录下参考#348,跑了下还是一样的结果;

![001](https://cloud.githubusercontent.com/assets/4525446/20706080/8735fdbe-b660-11e6-84f0-928b93f67bcf.png)

就是想小白式的用下提升编译速度的,有没有简单配置window 下的freeline 环境教程啊,实在是在这个上面花了好多时间;

**Comment by lomanyong** [comment]
@DovSnier 如果自己下载解压了就不需要再执行`initFreeline -Pmirror`了。

简单运行一下`python freeline.py -v`，如果能够看到输出了版本号的话，基本就是下载下来了。

REAMDE 上的就是配置教程了，非常简单....你连国内镜像都访问不了的话已经是特殊现象了....
