### ISSUE TITLE
[WARNING] check sync status failed, a clean build will be automatically executed.

### ISSUE THREAD

**Issue by hiperioncn** [alibaba/freeline#362]
增量编译时出现这个提示，无法进行增量编译。
[WARNING] check sync status failed, a clean build will be automatically executed.

**Comment by lomanyong** [comment]
@hiperioncn 尝试卸载手机上的apk，再重新用freeline打包编译安装..

**Comment by hiperioncn** [comment]
多谢

**Comment by lomanyong** [comment]
@hiperioncn 可以参考#366 了解一下原因...
