### ISSUE TITLE
merge_dex_task finish in 0.0s然后就停着不动了

### ISSUE THREAD

**Issue by xummerj** [alibaba/freeline#363]
经常有这种情况，然后只好强制结束python进程，进行全量编译才可以，是什么原因？

````
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.8s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 16.5s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy E:\AS\test-job\app\build\freeline\job\dex\classes.dex to E:\AS\test-job\app\build\freeline\freeline-dexes\merged.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
````

**Comment by lomanyong** [comment]
@xummerj 这一部分有完整一点的日志吗？

**Comment by xummerj** [comment]
E:\AS\test-job>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False, wait=False)
[DEBUG] [scan_changed_files_command] find E:\AS\zz-job\job\src\main\res\layout\job_base_list_item.xml has modification.
[DEBUG] [scan_changed_files_command] find E:\AS\zz-job\job\src\main\java\nd\sdp\zongzhi\job\widget\BaseListItemView.java has modification.
[DEBUG] find app has 0 java files modified.
[DEBUG] find job has 1 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1480471505.7739837,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "job": {
            "src": [
                "E:\\AS\\zz-job\\job\\src\\main\\java\\nd\\sdp\\zongzhi\\job\\widget\\BaseListItemView.java"
            ],
            "so": [],
            "assets": [],
            "libs": [],
\1.1.8.2.smartcan.release\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.github.chrisbanes.photoview\library\1.2.4\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\cssdkextend\1.1.4.csextend\res -S E:\AS\test-j
ob\app\build\intermediates\exploded-aar\com.nd.sdp.android\webviewwrapper\2.0.0-versionrelease\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\ucmaincomponentlan\1.0.5.9.ucmaincomlan\res -S E:\AS\test-job\app\build\intermediates\e
xploded-aar\com.nd.android.smartcan\smartcan-appfactory\1.5.5.7.smartcan.release\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\mock-test\1.0.5\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.csext\c
ontentServiceSdk\1.9.5.8\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.social\module_commonResource\7.8.0.4558\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\smartcan-accountclient-aar\1.2.1.5
.ucsdk\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.social\module_setting\7.9.1.87de4fe5\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.common\photopicker-js\0.3.2\res -S E:\AS\test-job\app\build\
intermediates\exploded-aar\com.nd.android.sdp.common\downloadmanager\1.1.6\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\downloader-jswrapper\0.1.5\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.co
mmon.draggablewidget\draggable-tip\1.0.3.ec1d90\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.tencent.bugly\crashreport\2.2.2\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\crashreport\0.1.8\res -S E:\AS\test-job
\app\build\intermediates\exploded-aar\com.nd.sdp\webviewcomponent\1.9.0.webview.end\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\incrementalupdate\1.1.4-incrementalupdate\res -S E:\AS\test-job\app\build\intermediates\exploded-a
ar\com.nd.component.android\maincomponent\1.7.2.6.maincom.release\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\maincomprivateui\1.1.2.maincomPrivateUi.dev\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp\co
mmonfeatures\1.2.0.commonfeatures\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\virtualorgsdk\0.0.3.9.vorgsdk\res -S E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\ox\0.0.1.1.oxsdk\res -S E:\AS\
test-job\app\build\intermediates\exploded-aar\com.nd.sdp\uc_component\0.7.2.3.uccom\res -S E:\AS\test-job\app\build\freeline\app\backup\res -A E:\AS\test-job\app\build\freeline\freeline-assets -A E:\AS\test-job\app\assets -A E:\AS\test-job\app\build\generated\
assets\shaders\debug -A E:\AS\zz-job\job\src\main\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.8.2\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.android.support\cardview-v7\23.1.1\assets -A
 E:\AS\test-job\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.1.1\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.1\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.a
ndroid.support\recyclerview-v7\23.1.1\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.android.support\design\23.1.1\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\assets -A E:\AS\test-job\app\
build\intermediates\exploded-aar\com.nd.sdp.android\skin-loader\1.2.2\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\in.srain.cube\ultra-ptr\1.0.11\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.tumblr\remember\1.0.0\assets -A
 E:\AS\test-job\app\build\intermediates\exploded-aar\me.zhanghai.android.materialprogressbar\library\1.1.4\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.afollestad\material-dialogs\0.8.4.2\assets -A E:\AS\test-job\app\build\intermediates\ex
ploded-aar\com.nd.sdp.android.common\res\0.1.75.6\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.social\module_audiorecorder\8.0.0.1684\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\io.reactivex\rxandroid\1.1.0
\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.common\audioplayer\0.1.63\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nostra13.universalimageloader\universal-image-loader\2.0.8.0\assets -A E:\AS\test-job\
app\build\intermediates\exploded-aar\com.android.support\palette-v7\23.1.1\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\pl.droidsonroids.gif\android-gif-drawable\1.2.2\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.github.ra
hatarmanahmed\circularprogressview\2.3.2\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.common\photoview\2.1.218\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.common\photoview-iml\1.0.140\ass
ets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.social\module_recorder\5.6.0.4341\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.tbruyelle.rxpermissions\rxpermissions\0.7.0\assets -A E:\AS\test-job\app\build\int
ermediates\exploded-aar\com.nd.hy.component\CropImage\1.9.3\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.sdp.common\photopicker\2.3.1\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\jp.wasabeef\glide-transformation
s\2.0.0\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.makeramen\roundedimageview\2.2.1\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.handmark.pulltorefresh\library\1.3\assets -A E:\AS\test-job\app\build\intermediates\exp
loded-aar\com.squareup.sqlbrite\sqlbrite\0.6.0\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.jakewharton.rxbinding\rxbinding\0.4.0\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.trello\rxlifecycle\0.5.0\assets -A E:\AS\te
st-job\app\build\intermediates\exploded-aar\nd.sdp.common\leaf-android\1.0.8\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\commons-util-aar\1.1.8.2.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\explod
ed-aar\com.nd.sdp.android\processcheck\1.1.1.dev\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\network-aar\1.1.8.2.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\sm
artcan-core-aar\1.1.8.2.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\datalayer-aar\1.1.8.2.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\smartcan
-datacollection-aar\1.1.8.2.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\datatransfer-aar\1.1.8.2.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\f
ramework-aar\1.1.8.2.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.github.chrisbanes.photoview\library\1.2.4\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.android.smartcan\cssdkextend\1.1.4.csextend\a
ssets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\webviewwrapper\2.0.0-versionrelease\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\ucmaincomponentlan\1.0.5.9.ucmaincomlan\assets -A E:\AS\test-jo
b\app\build\intermediates\exploded-aar\com.nd.android.smartcan\smartcan-appfactory\1.5.5.7.smartcan.release\assets -A E:\AS\test-job\app\build\intermediates\exploded-aar\com.nd.sdp.android\mock-test\1.0.5\assets -A E:\AS\test-job\app\build\intermediates\explod
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'E:\\AS\\test-job\\app\\build\\freeline\\app\\backup\\com\\nd\\smartcan\\appfactory\\demo\\R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 3.6s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy E:\AS\test-job\app\build\freeline\job\dex\classes.dex to E:\AS\test-job\app\build\freeline\freeline-dexes\merged.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s

**Comment by gunC** [comment]
我也出现这个情况了

**Comment by gunC** [comment]
try to connect device 1 times..
wake up Service:...
....
try to connect device 10 times..
wake up Service:..

**Comment by lomanyong** [comment]
@gunC 你的这个应该是不同的情况，查看 issue #152
