### ISSUE TITLE
org.greenrobot.eventbus.EventBusException: Default instance already exists

### ISSUE THREAD

**Issue by mmchong3173** [alibaba/freeline#364]
进行增量编译时出现应用停止运行：
````
Unable to start receiver com.antfortune.freeline.FreelineReceiver: java.lang.RuntimeException: 
Unable to create application com.antfortune.freeline.FreelineApplication: 
org.greenrobot.eventbus.EventBusException: 
Default instance already exists. It may be only set once before it's used the first time to ensure consistent behavior.
````

**Comment by lomanyong** [comment]
@mmchong3173 这些日志是连贯在一起的？

参考一下 #273 做下修改，看是否可以被解决...

**Comment by mmchong3173** [comment]
@lomanyong 日志是连贯的，顺便说下我是在android4.3的系统下遇到的，freeline插件是0.8.2版本的；添加你说的修改后，错误变成java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation，定位在我项目application里面的EventBus.builder().addIndex(new XNEventBusIndex()).installDefaultEventBus();这一句。

**Comment by lomanyong** [comment]
@mmchong3173 能够提供一个简单的能够复现这个问题的sample代码给我吗...我试试看...

**Comment by lomanyong** [comment]
@mmchong3173 先在 5.0+ 的机型上测试一下？你们的项目应该是multiDex的吧？

**Comment by mmchong3173** [comment]
@lomanyong 5.0+上没有这个问题，确实用了multiDex，是因为这个的原因吗？

**Comment by lomanyong** [comment]
@mmchong3173 问题原因是 EventBus 的类被分到了非第一个 dex 中，而且 freeline 没有对第三方库进行 class 注入，所以在 dalvik 的 Android 设备上会出现这个问题，在 ART 的不会出现。

第三方库的 class 注入我在后面的版本里加入一下，之前是因为担心污染了你本地的缓存库所以没有加入..

**Comment by yinshudi** [comment]
请问一下第三方库的 class 注入的进度怎么样了?遇到了相同的问题.

**Comment by lomanyong** [comment]
@yinshudi 可以在 5.0+ 的设备上先使用吗？

**Comment by yinshudi** [comment]
好的,没有临时解决方案那只能换机器了.谢谢回复
