### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by huangying812** [alibaba/freeline#365]
老版本是0.7.2，然后通过插件自动升级，项目级build.gradle设置了新的版本0.8.2，执行更新的时候却还是找的0.7.2的版本路径，手动去项目文件下清理掉freeline.py、freeline_core、freeline等，再执行gradlew initFreeline 或者gradlew initFreeline -Pmirror都还是去get 0.7.2的。。。

**Comment by lomanyong** [comment]
@huangying812 确认吗...你如果是已经修改过`classpath "com.antfortune.freeline:gradle:0.8.2"`，就算插件可能识别错了，手工执行命令不可能会出问题的...

插件问题 @pengwei1024 可以看下..

**Comment by pengwei1024** [comment]
好，我分析下

**Comment by huangying812** [comment]
确认修改了，截了图的
![1](https://cloud.githubusercontent.com/assets/14348643/20738631/8cb73656-b6ef-11e6-9506-e3ddd4c86bec.png)
![2](https://cloud.githubusercontent.com/assets/14348643/20738642/9b47baba-b6ef-11e6-999d-34388607a170.png)

**Comment by huangying812** [comment]
应该跟插件无关，我自己使用cmd命令也是一样的

**Comment by pengwei1024** [comment]
@lomanyong runtime都正确了应该不是插件问题

**Comment by lomanyong** [comment]
@huangying812 你使用的 cmd 命令是什么...那句`for specific version`只有在加入参数`-PfreelineVersion=0.7.2`才会出现...这个参数是用来下载指定的 freeline 依赖版本的。

**Comment by huangying812** [comment]
@lomanyong 哦，不是那种复杂的命令，我指的的自己手动修改build.gradle 里面的 classpath 到0.8.2，然后用cmd执行init命令而已

**Comment by lomanyong** [comment]
@huangying812 你试下执行`./gradlew initFreeline -PfreelineVersion=0.8.2`

**Comment by huangying812** [comment]
可以，升级成功

**Comment by lomanyong** [comment]
@huangying812 你是不是在 gradle 的文件里哪里定义了一个变量`freelineVersion`了...
