### ISSUE TITLE
Python 3 支持

### ISSUE THREAD

**Issue by zhenian** [alibaba/freeline#367]
开发过程中使用了一些工具只支持  Python 3的。
但是 freeline 只支持 2.7+

希望尽快添加 Python 3支持。

## 临时解决方案

目前的临时解决方案，面临不同 Python 版本需求时，
使用 shell 脚本封装多一层，
在执行前，使用 `pyenv local` 变更版本 Python 版本再执行。

**Comment by lomanyong** [comment]
@zhenian 我最近找时间做下支持...

**Comment by imknown** [comment]
感觉 `Python 2` 各种秘制错误
https://github.com/alibaba/freeline/issues/588

**Comment by yufan2014** [comment]
怎么切换android studio使用的Python版本？

**Comment by PhantomQi** [comment]
作为Python菜鸟想问下，freeline使用2.7是出于什么考虑呢

**Comment by lomanyong** [comment]
@PhantomQi 大多数 Mac 或者 Linux 用户，系统自带的 Python 版本为 2.7。

**Comment by charvenhe** [comment]
Python暂无支持计划

**Comment by charvenhe** [comment]
纠正，是python3

**Comment by yufan2014** [comment]
现在还不支持python3吗？

**Comment by javalue** [comment]
现在还不支持python3吗~
