### ISSUE TITLE
what version of python is the best for the freeline script?

### ISSUE THREAD

**Issue by haogg** [alibaba/freeline#37]
what version of python is the best for the freeline script?

**Comment by lomanyong** [comment]
@haogg We only tested freeline with 2.7+ in both win/linux/mac. There may be some errors occur with Python 3+.

**Comment by haogg** [comment]
that's it. I have 3.5.1 installed,thus some errors happen

**Comment by lomanyong** [comment]
@haogg you can change your python version to 2.7+， and try agin. Python 3.+ support is in freeline's roadmap.
