### ISSUE TITLE
Mac电脑第一次initFreeline出错

### ISSUE THREAD

**Issue by shizhangbiao** [alibaba/freeline#370]
* Where:
Build file '/项目地址/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by lomanyong** [comment]
@shizhangbiao 。。。这个不是freeline的问题...你把你的环境变量里的 java 升级为 java8 即可...
