### ISSUE TITLE
使用增量更新时，不会自动打开App？

### ISSUE THREAD

**Issue by panacena** [alibaba/freeline#371]
使用增量更新时，不会自动打开App？必须手动点击app打开嘛？

**Comment by lomanyong** [comment]
@panacena 通常情况会自动打开 app，不会自动打开的有两种情况：
1. `adb devices`显示设备 offline
2. 从`python freeline.py -d`的日志看出，packageName和launcherActivity错了..

如果是 1 情况，执行`adb kill-server`和`adb start-server`可以解决
如果是 2 情况，可以手动在 freeline DSL 中添加配置来解决
