### ISSUE TITLE
修改的文件没有被监测到

### ISSUE THREAD

**Issue by OccurSomething** [alibaba/freeline#372]
以下是部分log，看到[DEBUG] [sync_client] app has no need to sync inc res pack.[DEBUG] [sync_client] no incremental dexes in .  而且Activity是没有重启的，界面也看不到我新增的这个button

[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [sync_client] apktime path: /Users/weixiangzhong/data/android_studio_workspace/Test/app/build/freeline/freeline-assets/apktime
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [app_inc_invoker] app old R.java path: /Users/weixiangzhong/data/android_studio_workspace/Test/app/build/generated/source/r/debug/test/example/com/test/R.java
[DEBUG] [sync_client] your local sync value is: 195511
[DEBUG] [sync_client] your local uuid value is: 195509
[DEBUG] [app_inc_invoker] app new R.java path: /Users/weixiangzhong/data/android_studio_workspace/Test/app/build/freeline/app/backup/test/example/com/test/R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'/Users/weixiangzhong/data/android_studio_workspace/Test/app/build/freeline/app/backup/test/example/com/test/R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.2s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.2s
[DEBUG] [sync_client] app has no need to sync inc res pack.
[DEBUG] [sync_client] no incremental dexes in .
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.0s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.2s
[DEBUG] [clean_cache_task] remove cache: /Users/weixiangzhong/data/android_studio_workspace/Test/app/build/freeline/app/respack/app.rflag
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.2s
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 0.19s to execute tasks.

**Comment by OccurSomething** [comment]
其中java代码没有修改

**Comment by lomanyong** [comment]
@OccurSomething 应该是没有扫描到这个文件存在改动，所以就没有增量更新了。完整的日志会看到前面有个文件改动的列表，应该基本是空的。

给下文件路径？以及路径是否是根据 flavor 进行配置的？

**Comment by OccurSomething** [comment]
是的，没变化，productflavor是必须的吗？我这边测试项目没配置
{
    "build_info": {
        "last_clean_build_time": 1480505075.0,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}

**Comment by OccurSomething** [comment]
另外，我先xml里新增一个Button，增量编译能显示，然后又把这个Button删去，全量编译重启app之后发现被删除的Button还在，其中java代码都是没有修改。
简单说只修改xml，在增量和全量间切换，可能就遇到新增的Button没显示，或者删除的Button还显示。

**Comment by lomanyong** [comment]
@OccurSomething 要从日志来确认是否传输过去并且生效了，推荐配置上 flavor，否则会出现你使用的 flavor 指定的目录查找不到的问题..

**Comment by OccurSomething** [comment]
我配置了flavor但还是会有上面的问题，还是没扫描出我已经修改了xml布局文件

**Comment by lomanyong** [comment]
@OccurSomething 麻烦贴个你们工程 product flavor 的配置？

具体的目录，在`${main_module}/build/freeline/${your-module}/resource_dependencies.json`这个文件里有记录具体的路径，可以看下路径是否包含在其中..

**Comment by tenggangren** [comment]
Androidstudio2.2.2还好，刚升级的2.2.3 ，freeline就抽风了，修改的文件检测不到更新！！ 每次全量真是愁人

**Comment by lomanyong** [comment]
@tenggangren 出问题除了描述情况也要贴日志阿同学。。。

**Comment by tenggangren** [comment]
我的是Androidstudio2.2.3 +　freeline 0.8.2 ， 现在换成0.8.3版本是ok的了！  日志就是跟这位同学类似，修改的文件没有检测到！
