### ISSUE TITLE
执行到一半的时候出现这个错误.如何解决.?

### ISSUE THREAD

**Issue by vicwing** [alibaba/freeline#373]
Microsoft Windows [版版本本 10.0.14393]
(c) 2016 Microsoft Corporation。。保保留留所所有有权权利利。。

D:\Qfang.com\app\QfangWang490>#
'#' 不不是是内内部部或或外外部部命命令令，，也也不不是是可可运运行行的的程程序序
或或批批处处理理文文件件。。

D:\Qfang.com\app\QfangWang490>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False)
[DEBUG] collecting project info, please wait a while...
[DEBUG] [scan_changed_files_command] find D:\Qfang.com\app\QfangWang490\QfangPalm\build.gradle has modification.
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\Qfang.com\app\QfangWang490\QfangPalm\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 642000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save QfangPalm module file stat
[DEBUG] [generate_file_stat_task] save ptr-lib module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.3s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.3s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.3s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.3s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.3s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.1s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.31s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.Install.listDirs(Install.java:95)
        at org.gradle.wrapper.Install.access$200(Install.java:29)
        at org.gradle.wrapper.Install$1.call(Install.java:64)
        at org.gradle.wrapper.Install$1.call(Install.java:47)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:47)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 0.3s
[DEBUG] Total time: 0.7s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@vicwing 明显本地的环境有问题...可以手动执行一下`gradlew.bat -q checkBeforeCleanBuild`...

参考链接：[Gradle wrapper fails with NullPointer Exception](https://discuss.gradle.org/t/gradle-wrapper-fails-with-nullpointer-exception/1254)
