### ISSUE TITLE
提示java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by ChaosWu** [alibaba/freeline#375]
* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by lomanyong** [comment]
@ChaosWu 问题原因：从 Android Studio 2.2 开始，默认使用内置的 Java8 版本，如果你的系统环境变量中使用的还是 Java7 的话，就会出现这个问题，解决方案就是升级系统的 Java 版本，配置到 Java8

已有相关的 issue，麻烦提问前可以先搜索一下...
