### ISSUE TITLE
DSL文档能给个例子么，excludeHackClasses怎么使用？

### ISSUE THREAD

**Issue by chen28683** [alibaba/freeline#376]

**Comment by lomanyong** [comment]
@chen28683 Freeline 更为详细的中文文档在这周会上线...

可以参考下面的使用方式：

**excludeHackClasses**
- 引入版本：0.5.0
- 参数类型：List[String]
- 默认值：[]
- 参数说明：打包过程中，freeline 会对 class 进行插桩，默认会跳过父类为`android/app/Application`的类。如果你有特殊需求需要绕过插桩，可以通过这个配置项进行配置
- 使用方法：["Your-class-name.class", "your-second-class-name.class"]
