### ISSUE TITLE
freeline/release-tools/FreeLineAapt 打包资源出错

### ISSUE THREAD

**Issue by zhangxiaang** [alibaba/freeline#378]
`build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/username/Library/Android/sdk/platforms/android-23/android.jar -M /Users/username/AndroidStudioProjects/project_name/build/intermediates/manifests/full/debug/AndroidManifest.xml -S`

后面都是项目内的资源打包出错的资源，奇怪的是 apk安装了 但是就是运行不起来...

**Comment by lomanyong** [comment]
@zhangxiaang 资源打包出错的日志里会有详细的出错日志，可以把出错日志贴出来看下...如果是丢失资源依赖路径的话，可以看下相关的 wiki 以及 issue： #339 or [wiki - 资源编译出错：Public symbol xxxx declared here is not defined](https://github.com/alibaba/freeline/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%B5%84%E6%BA%90%E7%BC%96%E8%AF%91%E5%87%BA%E9%94%99public-symbol-xxxx-declared-here-is-not-defined)

**Comment by zhangxiaang** [comment]
嗯 通过添加res路径解决啦～

**Comment by lomanyong** [comment]
@zhangxiaang 好的。不过能说下那个没找到的资源路径有什么特殊的地方吗？需要了解一下为什么 freeline 不能自动监测到...

**Comment by Febare** [comment]
[ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline\release-tools\FreelineAapt.exe package -f -I E:\android-sdk-windows\platforms\android-25\android.jar -M E:\wmqAndroid\app\build\intermediates\manifests\full\debug\An
droidManifest.xml -S E:\wmqAndroid\app\src\main\res -S E:\wmqAndroid\app\build\generated\res\rs\debug -S E:\wmqAndroid\app\build\generated\res\resValues\debug -S C:\Users\Febare\.android\build-cache\65e9b0b299114cba4
2828752e4b22dc4144fc996\output\res -S C:\Users\Febare\.android\build-cache\efc3cc85dd48c0764e654f1ab160dc0254313a51\output\res -S C:\Users\Febare\.android\build-cache\97ae699b00d1f3fdc8cd59816348ab6856c1ebce\output\r
es -S C:\Users\Febare\.android\build-cache\ec272cb8212e8e4751cdd81eca666b31c5529179\output\res -S C:\Users\Febare\.android\build-cache\b9eff7a57c60639ad43201fb3aa576675903dfd8\output\res -S C:\Users\Febare\.android\b
uild-cache\d44fbe79edfe2d1fb936d988bc5890e8684154f8\output\res -S C:\Users\Febare\.android\build-cache\b3d82967a971d4159e8ee2be184e089e31695c6b\output\res -S C:\Users\Febare\.android\build-cache\3b4a8820db3d71ed7d415
4d22a7aa7245e98b081\output\res -S C:\Users\Febare\.android\build-cache\a1de8d274225a1c4dc4e1c7804904dc2063f2a24\output\res -S C:\Users\Febare\.android\build-cache\be09dbf75f24e9a1dd16bc41586b7b4f15cf578c\output\res -
S C:\Users\Febare\.android\build-cache\80ea12e519a86ac26175f7e24785d36ff128cf20\output\res -S C:\Users\Febare\.android\build-cache\3dd7b2ffc5defa633dcfe6e1ad4625403c8ed75a\output\res -S C:\Users\Febare\.android\build
-cache\a8f29da56d3e1f60e3ef73cb6e2384fa87bb2315\output\res -S C:\Users\Febare\.android\build-cache\0b2ef916cf4894a11c02d9ac72bb50e56ecd1026\output\res -S C:\Users\Febare\.android\build-cache\36a3ad03cd5f66f749b27e60e
1cf7a03d4393598\output\res -S C:\Users\Febare\.android\build-cache\179634d5fbb4e3fed4427bc1f621b6577475e34c\output\res -S C:\Users\Febare\.android\build-cache\791dc2bd65f3245e8d868d1b446c40bf80582862\output\res -S C:
\Users\Febare\.android\build-cache\d1b2a31526d9800a6347126e3e20699f92660269\output\res -S C:\Users\Febare\.android\build-cache\de04572179d13f1d4943f941edd1f38a518cdafe\output\res -S C:\Users\Febare\.android\build-cac
he\c9649f82cb2ba6bf512907b91e2e04f4506f4acc\output\res -S C:\Users\Febare\.android\build-cache\7432486749322fc27c5157758b09f0a76a77fb4d\output\res -S C:\Users\Febare\.android\build-cache\4d5ddd07a54188f5c34a3191529c3
7cd2b33b8d9\output\res -S C:\Users\Febare\.android\build-cache\9e74a6c0b4ef9bb25300904243a6e46dbdb0c99b\output\res -S C:\Users\Febare\.android\build-cache\6bb9eea2ef4c418ef5c3cbb866c932bddd5519a7\output\res -S C:\Use
rs\Febare\.android\build-cache\b5665cb18c79fa9cff56a3dfeccc51cefd55af6a\output\res -S C:\Users\Febare\.android\build-cache\1dcb1dfec63625a3a29aedf2a01b1904ef529ca3\output\res -S C:\Users\Febare\.android\build-cache\8
d62542c4e2fd00fdd99a463ac2cef533f860f35\output\res -S C:\Users\Febare\.android\build-cache\639f1256214720e343621f5a3057050c0d001641\output\res -S C:\Users\Febare\.android\build-cache\d9fc5bf0cd8a930cab8d5b3fd0d2d47e8
29e1b63\output\res -S C:\Users\Febare\.android\build-cache\76d55fb2fad6b793580c736988184defcf1321ba\output\res -S C:\Users\Febare\.android\build-cache\d1a41189597a7ed3e4abc7ff0ae336f986322347\output\res -S C:\Users\F
ebare\.android\build-cache\9d289cd62fc6701c9aaea008902fff1f48687c41\output\res -S C:\Users\Febare\.android\build-cache\b23b9a816604e8d6b4b011fbf4d0b359bcddc978\output\res -S C:\Users\Febare\.android\build-cache\e1534
2bd046f56faf5d730fbf680860751cc95f4\output\res -S C:\Users\Febare\.android\build-cache\96e973431349c6d7d276f6b6b1ae49eb73e32b8e\output\res -S C:\Users\Febare\.android\build-cache\a3c11296c76985117827ef032020ebf505e10
788\output\res -S C:\Users\Febare\.android\build-cache\e637c4b6c79c672750f87b8c04c4bf9376d270b6\output\res -S C:\Users\Febare\.android\build-cache\97ffa7d0ef860c94e2789dcf205de2f7bc8b569d\output\res -S C:\Users\Febar
e\.android\build-cache\f2cd8566eeb4b250f1831413326dba7af63dd2fa\output\res -S C:\Users\Febare\.android\build-cache\cd8fedd72a4f12014ccd6411494880730b0cafd6\output\res -S C:\Users\Febare\.android\build-cache\91a7e3a0a
f823eabf306922b60b0369464433e09\output\res -S C:\Users\Febare\.android\build-cache\96a1c292ec41993f9365bd96c7830920c11f2d7f\output\res -S C:\Users\Febare\.android\build-cache\23f6aa8db0744a7191db512dd2c5e812204a03cb\
output\res -S C:\Users\Febare\.android\build-cache\a4f1417eb233829e179b6b22dab8be8c6269da67\output\res -S C:\Users\Febare\.android\build-cache\08ebdd6d914575e249ebfb42942176ddb8b460b4\output\res -S C:\Users\Febare\.a
ndroid\build-cache\4f4f7c55c44af591bf837fd1120e31ec860001df\output\res -S E:\wmqAndroid\app\build\freeline\app\backup\res -A E:\wmqAndroid\app\build\freeline\freeline-assets -A E:\wmqAndroid\app\src\main\assets -A E:
\wmqAndroid\app\build\generated\assets\shaders\debug -A C:\Users\Febare\.android\build-cache\65e9b0b299114cba42828752e4b22dc4144fc996\output\assets -A C:\Users\Febare\.android\build-cache\efc3cc85dd48c0764e654f1ab160
dc0254313a51\output\assets -A C:\Users\Febare\.android\build-cache\97ae699b00d1f3fdc8cd59816348ab6856c1ebce\output\assets -A C:\Users\Febare\.android\build-cache\ec272cb8212e8e4751cdd81eca666b31c5529179\output\assets
 -A C:\Users\Febare\.android\build-cache\b9eff7a57c60639ad43201fb3aa576675903dfd8\output\assets -A C:\Users\Febare\.android\build-cache\d44fbe79edfe2d1fb936d988bc5890e8684154f8\output\assets -A C:\Users\Febare\.andro
id\build-cache\b3d82967a971d4159e8ee2be184e089e31695c6b\output\assets -A C:\Users\Febare\.android\build-cache\3b4a8820db3d71ed7d4154d22a7aa7245e98b081\output\assets -A C:\Users\Febare\.android\build-cache\a1de8d27422
5a1c4dc4e1c7804904dc2063f2a24\output\assets -A C:\Users\Febare\.android\build-cache\be09dbf75f24e9a1dd16bc41586b7b4f15cf578c\output\assets -A C:\Users\Febare\.android\build-cache\80ea12e519a86ac26175f7e24785d36ff128c
f20\output\assets -A C:\Users\Febare\.android\build-cache\3dd7b2ffc5defa633dcfe6e1ad4625403c8ed75a\output\assets -A C:\Users\Febare\.android\build-cache\a8f29da56d3e1f60e3ef73cb6e2384fa87bb2315\output\assets -A C:\Us
ers\Febare\.android\build-cache\0b2ef916cf4894a11c02d9ac72bb50e56ecd1026\output\assets -A C:\Users\Febare\.android\build-cache\36a3ad03cd5f66f749b27e60e1cf7a03d4393598\output\assets -A C:\Users\Febare\.android\build-
cache\179634d5fbb4e3fed4427bc1f621b6577475e34c\output\assets -A C:\Users\Febare\.android\build-cache\791dc2bd65f3245e8d868d1b446c40bf80582862\output\assets -A C:\Users\Febare\.android\build-cache\d1b2a31526d9800a6347
126e3e20699f92660269\output\assets -A C:\Users\Febare\.android\build-cache\de04572179d13f1d4943f941edd1f38a518cdafe\output\assets -A C:\Users\Febare\.android\build-cache\c9649f82cb2ba6bf512907b91e2e04f4506f4acc\outpu
t\assets -A C:\Users\Febare\.android\build-cache\7432486749322fc27c5157758b09f0a76a77fb4d\output\assets -A C:\Users\Febare\.android\build-cache\4d5ddd07a54188f5c34a3191529c37cd2b33b8d9\output\assets -A C:\Users\Febar
e\.android\build-cache\9e74a6c0b4ef9bb25300904243a6e46dbdb0c99b\output\assets -A C:\Users\Febare\.android\build-cache\6bb9eea2ef4c418ef5c3cbb866c932bddd5519a7\output\assets -A C:\Users\Febare\.android\build-cache\b56
65cb18c79fa9cff56a3dfeccc51cefd55af6a\output\assets -A C:\Users\Febare\.android\build-cache\1dcb1dfec63625a3a29aedf2a01b1904ef529ca3\output\assets -A C:\Users\Febare\.android\build-cache\8d62542c4e2fd00fdd99a463ac2ce
f533f860f35\output\assets -A C:\Users\Febare\.android\build-cache\639f1256214720e343621f5a3057050c0d001641\output\assets -A C:\Users\Febare\.android\build-cache\d9fc5bf0cd8a930cab8d5b3fd0d2d47e829e1b63\output\assets
-A C:\Users\Febare\.android\build-cache\76d55fb2fad6b793580c736988184defcf1321ba\output\assets -A C:\Users\Febare\.android\build-cache\d1a41189597a7ed3e4abc7ff0ae336f986322347\output\assets -A C:\Users\Febare\.androi
d\build-cache\9d289cd62fc6701c9aaea008902fff1f48687c41\output\assets -A C:\Users\Febare\.android\build-cache\b23b9a816604e8d6b4b011fbf4d0b359bcddc978\output\assets -A C:\Users\Febare\.android\build-cache\e15342bd046f
56faf5d730fbf680860751cc95f4\output\assets -A C:\Users\Febare\.android\build-cache\96e973431349c6d7d276f6b6b1ae49eb73e32b8e\output\assets -A C:\Users\Febare\.android\build-cache\a3c11296c76985117827ef032020ebf505e107
88\output\assets -A C:\Users\Febare\.android\build-cache\e637c4b6c79c672750f87b8c04c4bf9376d270b6\output\assets -A C:\Users\Febare\.android\build-cache\97ffa7d0ef860c94e2789dcf205de2f7bc8b569d\output\assets -A C:\Use
rs\Febare\.android\build-cache\f2cd8566eeb4b250f1831413326dba7af63dd2fa\output\assets -A C:\Users\Febare\.android\build-cache\cd8fedd72a4f12014ccd6411494880730b0cafd6\output\assets -A C:\Users\Febare\.android\build-c
ache\91a7e3a0af823eabf306922b60b0369464433e09\output\assets -A C:\Users\Febare\.android\build-cache\96a1c292ec41993f9365bd96c7830920c11f2d7f\output\assets -A C:\Users\Febare\.android\build-cache\23f6aa8db0744a7191db5
12dd2c5e812204a03cb\output\assets -A C:\Users\Febare\.android\build-cache\08ebdd6d914575e249ebfb42942176ddb8b460b4\output\assets -A C:\Users\Febare\.android\build-cache\4f4f7c55c44af591bf837fd1120e31ec860001df\output
\assets -m -J E:\wmqAndroid\app\build\freeline\app\backup --auto-add-overlay -F E:\wmqAndroid\app\build\freeline\base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path E:\wmqAndroid\app\build\freeli
ne\arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[ERROR] --------------------------------------------------------
我这里也有个问题已经没想明白，折腾了好久，哪位大神指点一下
