### ISSUE TITLE
after freeline build cannot start main activity.

### ISSUE THREAD

**Issue by kiwionly** [alibaba/freeline#379]
hi, 

I had an issue when after freeline build, the main activity unable to start.

freeline version 0.8.2
android 7.0

**Comment by lomanyong** [comment]
@kiwionly Any crash log output??

**Comment by kiwionly** [comment]
hm.. this happen start after second time running freeline, I don't see any exception in log, I see the activity showing "build increment app" with white background before the activity get destroy.

here the log

com.catalog:freeline I/Freeline.CheckSync: devUuid: 134000
com.catalog:freeline I/Freeline.CheckSync: dev apkflag:134000, last sync is:134001, current sync is:134001
                                           
                                           --------- beginning of system
com.catalog:freeline I/Freeline.CheckSync: devUuid: 134000
com.catalog:freeline I/Freeline.CheckSync: dev apkflag:134000, last sync is:134001, current sync is:134001
com.catalog:freeline D/Freeline.PushDex: dex file received (132416 bytes), rename result :true, save to /data/user/0/com.catalog/cache/temp/dex/merged.apk
com.catalog:freeline I/Freeline.CloseLongLink: save last sync value: 2
com.catalog:freeline I/Freeline.CloseLongLink: with dex changes, need to restart the process (activity stack will be reserved)
com.catalog I/Freeline: ext:134000
com.catalog I/Freeline.Receiver: receive action type: 2
com.catalog I/Freeline: apply dynamicDex /data/user/0/com.catalog/cache/temp/dex
com.catalog I/Freeline: update dynamic time: 1480572807304
com.catalog D/Freeline.MiddlewareAct: kill process: 29230

**Comment by lomanyong** [comment]
@kiwionly Usually, freeline will automatically restart the current activity of your app when there is no crash happened. But if you called `activity.finish()` manually in your `onDestroy()` callback, the activity won't start.

Can you show me some sample codes that can cause the issue?

**Comment by mmchong3173** [comment]
I've had the same problem，If the current activity is at the bottom of the stack, like MainActivity, the incremental compile time will not re open the application

**Comment by lomanyong** [comment]
@mmchong3173 Could you show me some sample code that can replay this case? Or tell me some details about how to replay it?

Freeline will restart the current activity, not the activity on the bottom of the stack.

**Comment by kiwionly** [comment]
I try on some application, it working as expected.

current on is not working, still try to figure out where is the root cause.

**Comment by lomanyong** [comment]
@kiwionly You can provide the logcat output when the application finished so that we can help you figure out the root cause..

**Comment by kiwionly** [comment]
hi, 

my steps to run freeline like this:
.
build -> deploy app (activity started) -> run freeline (activity started) -> run freeline (second time onward, run freeline, activity will force close, but the code changed is apply to the app, just it need to manually restart from background task)

log below:
...
com.catalog:freeline D/Freeline.PushDex: dex file received (130128 bytes), rename result :true, save to /data/user/0/com.catalog/cache/temp/dex/merged.apk
com.catalog:freeline I/Freeline.CloseLongLink: save last sync value: 1
com.catalog:freeline I/Freeline.CloseLongLink: with dex changes, need to restart the process (activity stack will be reserved)
com.catalog I/Freeline: ext:59000
com.catalog I/Freeline.Receiver: receive action type: 2
com.catalog I/Freeline: apply dynamicDex /data/user/0/com.catalog/cache/temp/dex
com.catalog I/Freeline: update dynamic time: 1480665162765
? I/ActivityManager: START u0 {flg=0x10000000 cmp=com.catalog/com.antfortune.freeline.MiddlewareActivity (has extras)} from uid 10176 on display 0
com.catalog V/FA: Activity paused, time: 1319290206
com.catalog V/FA: onActivityCreated
com.catalog V/FA: Activity resumed, time: 1319290252
? I/ActivityManager: Displayed com.catalog/com.antfortune.freeline.MiddlewareActivity: +108ms
? I/ActivityManager: Process com.google.android.apps.translate (pid 16013) has died
? D/ActivityManager: cleanUpApplicationRecord -- 16013
com.catalog D/Freeline.MiddlewareAct: kill process: 14832
com.catalog I/Process: Sending signal. PID: 14832 SIG: 9
? I/WindowManager: WIN DEATH: Window{257ab92 u0 com.catalog/com.antfortune.freeline.MiddlewareActivity}
? D/GraphicsStats: Buffer count: 6
? I/ActivityManager: Process com.catalog (pid 14832) has died
? D/ActivityManager: cleanUpApplicationRecord -- 14832
? I/WindowManager: Destroying surface Surface(name=com.catalog/com.antfortune.freeline.MiddlewareActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
? W/ActivityManager: Force removing ActivityRecord{6cc4506 u0 com.catalog/com.antfortune.freeline.MiddlewareActivity t5749}: app died, no saved state
? I/WindowManager: WIN DEATH: Window{30d748a u0 com.catalog/com.catalog.activity.MainActivity}
? I/WindowManager: Destroying surface Surface(name=com.catalog/com.catalog.activity.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
? W/ActivityManager: Force removing ActivityRecord{1fdba85 u0 com.catalog/.activity.MainActivity t5749}: app died, no saved state
...

**Comment by lomanyong** [comment]
@kiminotes Sorry for missing your reply. These logs can't provide enough message that can help me solve this problem. The best way is that you can provide me some samples codes could replay this issue.
