### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by magical-xu** [alibaba/freeline#381]
when i run freeline , it report this Exception
: java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

I use the Android Studio 's jre . The jdk version is 1.8 .

Main module 's build.gradle :  compileSdkVersion 23  buildToolsVersion "23.0.2"
gradle version 2.14.1 

how to fixed it ?

**Comment by lomanyong** [comment]
@magical-xu #375
