### ISSUE TITLE
不支持.9图的更新

### ISSUE THREAD

**Issue by luckyandyzhang** [alibaba/freeline#383]
修改了.9图后，运行freeline看不到变化
freeline 0.8.2

**Comment by lomanyong** [comment]
@luckyandyzhang 请贴出修改了.9.png之后的运行日志...`python freeline.py -d`

**Comment by luckyandyzhang** [comment]
@lomanyong 

python freeline.py -d   
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False, wait=False)
[DEBUG] [scan_changed_files_command] find /Users/Andy/Dev/project/cover/Hidden/app/src/main/res/drawable-xhdpi/game_dragon_buy_dialog_bg.9.png has modification.
[DEBUG] find app has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1480583729.0,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [
                "/Users/Andy/Dev/project/cover/Hidden/app/src/main/res/drawable-xhdpi/game_dragon_buy_dialog_bg.9.png"
            ],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [gradle_inc_builder] find app modules have res changed
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [sync_client] apktime path: /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/freeline-assets/apktime
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [app_inc_invoker] find app has resource files modification.
[DEBUG] [sync_client] your local sync value is: 776257
[DEBUG] [gradle_aapt_task] start to execute aapt command...
[DEBUG] [sync_client] your local uuid value is: 776256
[DEBUG] [tracing] generate_id_keeper_files: 0.43797492981ms
[DEBUG] [tracing] incremental_databinding_process: 0.219821929932ms
[DEBUG] [app_inc_invoker] find relative path: res/drawable-xhdpi/game_dragon_buy_dialog_bg.9.png
[DEBUG] [app_inc_invoker] find relative path: res/values/freeline_id_keeper_public.xml
[DEBUG] [app_inc_invoker] find relative path: res/values/freeline_id_keeper_ids.xml
[DEBUG] [app_inc_invoker] aapt exec: freeline/release-tools/FreelineAapt package -f -I /Users/Andy/Dev/android-sdk/platforms/android-24/android.jar -M /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/manifests/full/_0/debug/AndroidManifest.xml -S /Users/Andy/Dev/project/cover/Hidden/app/src/main/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/generated/res/resValues/_0/debug -S /Users/Andy/Dev/project/cover/Hidden/app/build/generated/res/rs/_0/debug -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.jakewharton/butterknife/8.4.0/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.github.ctiao/DanmakuFlameMaster/0.4.9/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-compat/24.2.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-core-utils/24.2.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-core-ui/24.2.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-media-compat/24.2.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-fragment/24.2.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.2.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/24.2.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/securityguardaar3-5.1.81/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/alisdk-feedback-2.2.0/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/backup/res -A /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/freeline-assets -A /Users/Andy/Dev/project/cover/Hidden/app/src/main/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/generated/assets/shaders/_0/debug -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.jakewharton/butterknife/8.4.0/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.github.ctiao/DanmakuFlameMaster/0.4.9/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-compat/24.2.1/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-core-utils/24.2.1/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-core-ui/24.2.1/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-media-compat/24.2.1/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-fragment/24.2.1/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.2.1/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/24.2.1/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/securityguardaar3-5.1.81/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/alisdk-feedback-2.2.0/assets -A /Users/Andy/Dev/project/cover/Hidden/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/assets --custom-package com.cover.hidden -m -J /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/backup --auto-add-overlay -P /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml -F /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/respack/app.pack --debug-mode --auto-add-overlay --no-version-vectors --buildIncrement res/drawable-xhdpi/game_dragon_buy_dialog_bg.9.png:res/values/freeline_id_keeper_public.xml:res/values/freeline_id_keeper_ids.xml --resoucres-md5-cache-path /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.3s
[DEBUG] [app_inc_invoker] aapt use time: 787.25194931ms
[DEBUG] [app_inc_invoker] merged_changed_list:
[DEBUG] [app_inc_invoker] [u'res/drawable-xhdpi/game_dragon_buy_dialog_bg.9.png', u'res/values/freeline_id_keeper_public.xml', u'res/values/freeline_id_keeper_ids.xml']
[DEBUG] [tracing] run_incremental_aapt_task: 791.23711586ms
[DEBUG] [app_inc_invoker] modify /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/backup/com/cover/hidden/R.java
[DEBUG] [app_inc_invoker] copy /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/backup/com/cover/hidden/R.java to /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/freeline-backup-r/com/cover/hidden/R.java
[DEBUG] [app_inc_invoker] modify /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/freeline-backup-r/com/cover/hidden/R.java
[DEBUG] [tracing] check_other_modules_resources: 9.64617729187ms
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.8s
[DEBUG] [app] app start to run after waiting 0.8s
[DEBUG] [app_inc_invoker] app old R.java path: /Users/Andy/Dev/project/cover/Hidden/app/build/generated/source/r/_0/debug/com/cover/hidden/R.java
[DEBUG] [app_inc_invoker] app new R.java path: /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/backup/com/cover/hidden/R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'/Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/backup/com/cover/hidden/R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.8s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.8s
[DEBUG] [sync_client] checkresource: http://127.0.0.1:41128/checkResource
[DEBUG] [sync_client] base resource exists, there is no need to sync full resource pack
[DEBUG] [sync_client] start to sync app incremental res pack...
[DEBUG] [sync_client] app pack size: 10kb
[DEBUG] [sync_client] pushres: http://127.0.0.1:41128/pushResource?mode=increment&bundleId=base-res
[DEBUG] [sync_client] sync app incremental res pack finished
[DEBUG] [sync_client] no incremental dexes in .
[DEBUG] [sync_client] start to sync close longlink...
[DEBUG] [sync_client] closeLongLink: http://127.0.0.1:41128/closeLongLink?no&lastSync=2
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.2s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 1.0s
[DEBUG] [clean_cache_task] remove cache: /Users/Andy/Dev/project/cover/Hidden/app/build/freeline/app/respack/app.rflag
[DEBUG] [clean_cache_task] refresh app ids.xml
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.7s
[DEBUG] [update_stat_task] refresh /Users/Andy/Dev/project/cover/Hidden/app/src/main/res/drawable-xhdpi/game_dragon_buy_dialog_bg.9.png stat
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 1.06s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 1.1s
[DEBUG] Total time: 1.3s
[DEBUG] --------------------------------------------------------

**Comment by luckyandyzhang** [comment]
@lomanyong 修改之后，运行freeline，显示出来的效果变成了普通的png

**Comment by lomanyong** [comment]
@luckyandyzhang 能否提供给我有问题的`.9.png`图片让我测试看看呢？

**Comment by luckyandyzhang** [comment]
[test9png.zip](https://github.com/alibaba/freeline/files/624226/test9png.zip)

@lomanyong

**Comment by lomanyong** [comment]
@luckyandyzhang 确实 .9.png 的图的修改应该是 bug，应该还得修改 aapt，我们之后看下解决方案。

**Comment by luckyandyzhang** [comment]
@lomanyong 猴🐵

**Comment by lomanyong** [comment]
@luckyandyzhang Hi，你可以用下这个附件里的 FreelineAapt，替换你项目目录下的`freeline/release-tools`下的同名文件，看下是否解决了你的`.9.png`图片的问题。

[FreelineAapt.zip](https://github.com/alibaba/freeline/files/654813/FreelineAapt.zip)

**Comment by luckyandyzhang** [comment]
@lomanyong 可以了~

**Comment by lomanyong** [comment]
@luckyandyzhang 好的，下个版本更新会带上这个修改。
