### ISSUE TITLE
Execution failed for task ':app:MdmApp:processStuDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by YaFengYi** [alibaba/freeline#384]
````
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:MdmApp:processStuDebugResources'.
Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:185)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:82)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
Caused by: com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:873)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:178)
Caused by: com.android.ide.common.process.ProcessException: Error while executing 'D:\Android\Android-SDK\sdk\build-tools\24.0.2\aapt.exe' with arguments {package -f --no-crunch -I D:\Andro
id\Android-SDK\sdk\platforms\android-23\android.jar -M E:\MyTestProjects\TestMdmStu\app\MdmApp\build\intermediates\manifests\full\stu\debug\AndroidManifest.xml -S E:\MyTestProjects\TestMdmS
tu\app\MdmApp\build\intermediates\res\merged\stu\debug -m -J E:\MyTestProjects\TestMdmStu\app\MdmApp\build\generated\source\r\stu\debug -F E:\MyTestProjects\TestMdmStu\app\MdmApp\build\inte
rmediates\res\resources-stu-debug.ap_ --debug-mode --custom-package app --ignore-assets !.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~ -0 apk -P E:\MyTestProjects\
TestMdmStu\app\MdmApp\build\freeline\public_keeper.xml --output-text-symbols E:\MyTestProjects\TestMdmStu\app\MdmApp\build\intermediates\symbols\stu\debug --no-version-vectors}
````
混淆关闭了也是上述错误
  freeline {
        hack true
        buildScript 'gradlew.bat clean assembleDebug -Pf=dev'
    }

**Comment by lomanyong** [comment]
@YaFengYi 你可以直接执行一下这个命令：`D:\Android\Android-SDK\sdk\build-tools\24.0.2\aapt.exe package -f --no-crunch -I D:\Andro
id\Android-SDK\sdk\platforms\android-23\android.jar -M E:\MyTestProjects\TestMdmStu\app\MdmApp\build\intermediates\manifests\full\stu\debug\AndroidManifest.xml -S E:\MyTestProjects\TestMdmS
tu\app\MdmApp\build\intermediates\res\merged\stu\debug -m -J E:\MyTestProjects\TestMdmStu\app\MdmApp\build\generated\source\r\stu\debug -F E:\MyTestProjects\TestMdmStu\app\MdmApp\build\inte
rmediates\res\resources-stu-debug.ap_ --debug-mode --custom-package app --ignore-assets !.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~ -0 apk -P E:\MyTestProjects\
TestMdmStu\app\MdmApp\build\freeline\public_keeper.xml --output-text-symbols E:\MyTestProjects\TestMdmStu\app\MdmApp\build\intermediates\symbols\stu\debug --no-version-vectors`

看下输出的报错信息，具体定位在哪个资源文件，直接修改即可。

**Comment by YaFengYi** [comment]
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.
        3.
        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app app not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
第一次python freeline.py可以成功，第二次Pyhon freeline.py的时候失败！

**Comment by lomanyong** [comment]
@YaFengYi 日志不是有提示吗...可以先检查一下，对照一下#152
