### ISSUE TITLE
增量更新安装的时候失败

### ISSUE THREAD

**Issue by YaFengYi** [alibaba/freeline#385]
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Please make sure your application is properly running in your device.
Check follow steps:
1. Make sure the versions python freeline.py -v, freeline-gradle and freeline-runtime are the same;
2. Make sure there is no network proxy.
3.
More about this can see: #152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app app not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
第一次python freeline.py可以成功，第二次Pyhon freeline.py的时候失败！

**Comment by lomanyong** [comment]
@YaFengYi 日志有提示呀...你可以参考一下issue #152

**Comment by YaFengYi** [comment]
好的 谢谢
