### ISSUE TITLE
旧项目导入运行失败,提示No such file or directory

### ISSUE THREAD

**Issue by ppg408331701** [alibaba/freeline#386]
完全新建项目是可以的,但是旧项目就会出现这个问题

yanxiaobodeMacBook-Pro:UT-Android ppg777$ python freeline.py  

[INFO] preparing for tasks...

[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 0.0s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

env: bash\r: No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 3.4s
[DEBUG] Task engine running time: 0.1s
[DEBUG] Total time: 3.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@ppg408331701 旧项目目录下没有`gradlew `这个文件？没有的话可以从别的项目拷贝一下过来，然后添加一下可执行权限：`chmod +x gradlew`，重新运行即可。
