### ISSUE TITLE
Win10系统，一直提示Please declares your JAVA_HOME to system env!

### ISSUE THREAD

**Issue by 646634231** [alibaba/freeline#389]

**Comment by lomanyong** [comment]
@646634231 你使用的是哪个版本的...如果是旧版，你可以更新到0.8.2再看看..

**Comment by 646634231** [comment]
@lomanyong 用的是最新的，一次四十多秒的全量编译可以，普通freeline-dbug就报这个

**Comment by lomanyong** [comment]
@646634231 一个地方：检查一下`~/.freeline/cache/xxxxx/project_description.json`这个文件里的`java_home`字段是否存在，且值是否正确...

**Comment by 646634231** [comment]
@lomanyong 没有这个文件呢
