### ISSUE TITLE
  File "freeline.py", line 2 SyntaxError: encoding problem: utf8

### ISSUE THREAD

**Issue by zeshaoaaa** [alibaba/freeline#39]
请问怎么解决这个问题？

**Comment by lomanyong** [comment]
@zeshaoaaa 请问是否修改过这个文件呢？默认是utf-8编码的...现在看报错好像是因为带了BOM所以报错了。可以通过工具将其转为utf-8编码的。

**Comment by demoface** [comment]
把前两行删除了就好了，我的也遇到了

**Comment by lomanyong** [comment]
@demoface 我又google了一下，应该是因为这个原因：`# -*- coding:utf8 -*-`要替换为`# -*- coding:utf-8 -*-`

我之后修改提交一下。

**Comment by zeshaoaaa** [comment]
@lomanyong 我已经改了，文件上也是加了这个“-”，但是在as里面运行freeline还是报同一个错误

**Comment by lomanyong** [comment]
@zeshaoaaa 删掉头两行呢？
