### ISSUE TITLE
全量编译正常，增量编译异常

### ISSUE THREAD

**Issue by 464559332** [alibaba/freeline#390]
全量编译正常部署，后续修改再次编译提示Freeline Error
python的异常 WindowsError：[Error 87]必现，87 参数错误.不知道具体原因。
请参考下面的图片
![image](https://cloud.githubusercontent.com/assets/22049111/20823212/2e74352c-b88d-11e6-87c9-3fa159317128.png)

**Comment by lomanyong** [comment]
@464559332  如果 Java Home 路径包含空格，请先转移到一个不含空格的路径中。

如果还无法解决，可能是存在 javac 参数过长的问题，参考#382

把`classpath: "com.antfortune.freeline:gradle:0.8.2"`升级一下版本`com.antfortune.freeline:gradle:0.8.2.1611302135`，然后手动执行`gradlew initFreeline -PfreelineVersion=0.8.2.1612011823`，看下能够解决这个问题。

**Comment by 464559332** [comment]
您好：

已经按照您说的完善如下修改，依然还存在新问题：
1）修改 Java Home
2）完善classpath: "com.antfortune.freeline:gradle:0.8.2"升级一下版本com.antfortune.freeline:gradle:0.8.2.1611302135，然后手动执行gradlew initFreeline -PfreelineVersion=0.8.2.1612011823
希望您能再给一些帮助我们共同完善freeline，异常见下图
![qq 20161202142009](https://cloud.githubusercontent.com/assets/22049111/20824802/746eaff0-b89a-11e6-95f1-e9118a312c3a.png)

**Comment by lomanyong** [comment]
@464559332 麻烦确认一下`python freeline.py -v`，确认一下版本是否是`0.8.2.1612011823`。如果是的话，可以把你的日志，发一份完整的，上传附件上来看下...
