### ISSUE TITLE
使用flavorDimensions，编译不成功

### ISSUE THREAD

**Issue by captain-miao** [alibaba/freeline#391]
我们使用了flavorDimensions
```
flavorDimensions "product", "channel"
```

配置了productFlavor，然后会提示freeline找不到
```
    freeline {
        hack true
        productFlavor 'wbtest'
    }
```

> What went wrong:
A problem occurred evaluating project ':app'.
Could not find method freeline() for arguments [build_44rr3hodamqskavy3ku001krk$_run_closure3$_closure14@6e289355] on project ':app' of type org.gradle.api.Project.

ps: 我使用只定义了productFlavor的工程，测试没问题。

**Comment by lomanyong** [comment]
@captain-miao `A problem occurred evaluating project ':app'. Could not find method freeline() for arguments `这个不像是 flavorDimensions的问题？看着像是没有`apply plugin: "com.antfortune.freeline"`

关于 flavorDimensions 的问题，已知 #176 ，之前一直没有好好解决，最近来搞定一下..

**Comment by captain-miao** [comment]
通过 freeline自动配置的，看了下apply plugin: "com.antfortune.freeline"配置对的。

不知道错误为什么提示是这样的哈，问题重复，先关闭了。
