### ISSUE TITLE
增量编译不支持 ButterKnife 8.4.0 ?

### ISSUE THREAD

**Issue by jp1017** [alibaba/freeline#392]
freeline 对黄油刀支持的不怎么好？

1 我的操作很简单，布局添加一个TextView,

然后Activity绑定该TextView

>@BindView(R.id.bt_main) TextView mTvMain;

后面initData里设置TextView值，

>mTvMain.setText("hello java");

就报空指针了

然而，clean 后，用AS编译，运行，正常显示。

2 类似，一个Button, 

绑定点击事件

```
    @OnClick(R.id.bt_user_info_update)
    public void onClick() {
        showToast("正在提交");
    }
```

freeline　运行后点击 无效，但是As编译运行可正常点击.

所以，freeline对黄油刀支持不好吗？

测试版本:

freeline 0.8.2 + ButterKnife 8.4.0

**Comment by lomanyong** [comment]
@jp1017 Nope，测过是支持的。如果你那边测试会出问题的话，最好是能够提供一个可以复现的 git 代码地址...我这边来测试看下具体的原因在哪里...

还有，如果使用 freeline 的时候出现了 crash 之类的问题的话，不需要 clean，用 as 编译，直接使用`python freeline.py -f`或者 freeline IDE 插件提供的全量编译的按钮即可。

ButterKnife 目前已知没有支持好的是继承 Activity 的注解注入会出现 null，这个也会在近期解决...

**Comment by jp1017** [comment]
哈哈，加 -f  参数可以的，另外，IDE插件都是不带-f的吧，能设置？

**Comment by lomanyong** [comment]
@jp1017 

![]()

红圈处，可以自行`-f`。

ButterKnife 出问题的代码给我提供一份 sample 吧..

**Comment by jp1017** [comment]
看到了，好用

ButterKnife  没出问题，是我没有加 -f 参数，

>python freeline.py -f  

是可以的 😄 👍

**Comment by lomanyong** [comment]
@jp1017 额，不是的...`-f`是执行全量编译...按理说你普通使用增量编译，butterknife 应该是可以支持的...使用`-f`的话，跟你平时打包没啥区别...

**Comment by jp1017** [comment]
我这里随便添加点布局，用 ButterKnife 绑定，增量编译都不行，，

**Comment by lomanyong** [comment]
@jp1017 所以麻烦提供一个可以复现这个问题的 sample 代码吧，我看下是否是之前测出来的已知问题，以便尽快修复...

**Comment by jp1017** [comment]
这样啊，我一会写个小demo吧

**Comment by jp1017** [comment]
@lomanyong Demo here: https://github.com/jp1017/FreelineButterKnife

**Comment by lomanyong** [comment]
@jp1017 问题的原因是之前在一篇文章里有提到的 freeline 现在支持的是第三方（也是目前使用最广泛）的 apt 插件，而还没有支持 android-gradle 标准的 annotationProcessor。这个问题预计在后面的迭代版本里会解决，你目前可以这样简单修改来绕过问题：

添加第三方 apt 插件：
````gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.antfortune.freeline:gradle:0.8.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
````

模块配置：
````gradle
apply plugin: 'com.android.application'
apply plugin: 'android-apt'
apply plugin: 'com.antfortune.freeline'

...

dependencies {
    ......

    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
}
````

**Comment by jp1017** [comment]
知道了，非常感谢！ :+1:

**Comment by tanweijiu** [comment]
annotationProcessor 现在都开始转用这个了吧.. @lomanyong

**Comment by lomanyong** [comment]
@tanweijiu 恩，官方支持的...下个版本会把这个的解析加上。

**Comment by ding33211** [comment]
请问下个版本何时可以出
