### ISSUE TITLE
修改 layout 后出现：full resource pack not found: /Users/xx/Android/workspace/xxx-android/project/app/build/freeline/base-res.so

### ISSUE THREAD

**Issue by VankaIn** [alibaba/freeline#393]
增加了：
`android:maxLines="1"
android:ellipsize="end"`

没有删除资源 id。

**Comment by lomanyong** [comment]
@VankaIn 重新全量编译`python freeline.py -f`，然后看下是否有报错。出错的原因应该是你第一次编译的时候有出错没有生成`base-res.so`文件，或者误删了这个文件导致的。
