### ISSUE TITLE
Freeline Plugin command 'python' not found. if first installation python or Set Environment variable, Please restart your computer

### ISSUE THREAD

**Issue by AndroidCrazyBoy** [alibaba/freeline#395]
Freeline Plugin
command 'python' not found. if first installation python or Set Environment variable, Please restart your computer
重启之后 依然 无效，

**Comment by mmchong3173** [comment]
安装2.7+版本的python，配好path路径基本没问题了，如果python配置好了，在增量或全量编译的时候不加上python也是没问题的

**Comment by lomanyong** [comment]
@AndroidCrazyBoy python 没有安装....安装完需要重启 Android Studio..

**Comment by lijiankun24** [comment]
我也遇到同样的问题了，freeline安装完成以后，重启AS之后，还是会有同样的问题，请问楼主解决这个问题了吗

**Comment by lomanyong** [comment]
@lijiankun24 那就重启一下电脑确认 python 能被 AS 识别...

**Comment by lijiankun24** [comment]
怎么确认Python可以被AS识别呢

**Comment by lijiankun24** [comment]
@lomanyong 怎么确认Python可以被AS识别呢？

**Comment by lomanyong** [comment]
@lijiankun24 AS 不再提示这个问题...

**Comment by lijiankun24** [comment]
@lomanyong 试着重启了一下，还是会有这个提示，我的AS版本是2.2.3，会不会和这有关系呢？

**Comment by lomanyong** [comment]
@lijiankun24 没关系...你安装 Python 了吗？这里的问题是安装了 Python 但是没有被识别，从你的回复来看我感觉你没有安装 Python...

**Comment by lijiankun24** [comment]
@lomanyong 我在AS的terminal中执行了gradlew initFreeline -Pmirror命令，也显示的是Successful的，但是也还是会有这样的问题

**Comment by lomanyong** [comment]
@lijiankun24 没有安装 Python...上面不是也说了吗..

**Comment by lijiankun24** [comment]
@lomanyong sorry…

**Comment by JiWenBo** [comment]
如何配置Python路径啊

**Comment by lomanyong** [comment]
@JiWenBo 安装 Python...

**Comment by Demarcia-cn** [comment]
确定已装Pyhton，但还是有上面的提示，特索中。。。
