### ISSUE TITLE
env: bash\r: No such file or directory

### ISSUE THREAD

**Issue by MeiXXD** [alibaba/freeline#396]
env: bash\r: No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild

windows可以正常使用，将windows下开发的项目copy到mac上后执行freeline会报这个错误。

应该是windows下\r\n和mac下\r的问题。

但是想明确的是，checkBeforeCleanBuild是freeline的吧，这个是不是你们git提交的时候造成的？

有没有简单的办法去修改格式错误的文件？
并不知道修改哪个文件，每次都全工程跑  find . -type f -exec dos2unix {} \;  导致自己所有的文件都变成修改状态了。

谢谢了！

**Comment by lomanyong** [comment]
@MeiXXD 这个明显是不是 freeline 的问题吧。。。Linux/Mac和Windows同步文件的时候，git 有选项可以自己搞定换行符的问题...如果是直接拷贝自然会出问题。

出问题的文件`gradlew`出现换行符的问题是拷贝导致的...

推荐使用 git 来同步...配置好跨平台换行符的选项...不要直接手动 copy...

**Comment by MeiXXD** [comment]
已经使用dos2unix解决，是gradlew文件格式的问题，谢谢了！

On Sat, Dec 3, 2016 at 7:43 PM, Yong <notifications@github.com> wrote:
@MeiXXD [https://github.com/MeiXXD] 这个明显是不是 freeline 的问题吧。。。Linux/Mac和Windows同步文件的时候，git 有选项可以自己搞定换行符的问题...如果是直接拷贝自然会出问题。

出问题的文件 gradlew 出现换行符的问题是拷贝导致的...

推荐使用 git 来同步...配置好跨平台换行符的选项...不要直接手动 copy...
