### ISSUE TITLE
增量编译识别不了copy过来的java文件

### ISSUE THREAD

**Issue by wowow1989** [alibaba/freeline#398]
增量编译识别不了copy过来的java文件，只能全局编译
版本：0.8.2
操作系统：mac
android studio版本：2.2.1

**Comment by lomanyong** [comment]
@wowow1989 copy过来的文件是指？需要描述一下..如果 copy 覆盖的文件时间戳没有变化，freeline 是无法识别的，这个跟 git 切换分支差不多...

**Comment by wowow1989** [comment]
试了下，时间戳没有变化，不过这样的话体验不是很好！

**Comment by lomanyong** [comment]
@wowow1989 这个不属于很常见的 case，版本管理还是使用 git 或者 svn 比较好...用 copy 的方式之前一直没有特别处理的...

或者你还有什么特殊的用途吗？

**Comment by wowow1989** [comment]
这个和版本管理没有关系，只是添加功能时候，会移过来一些其它工程的代码，或者从一个包移到另一个包。
