### ISSUE TITLE
增量编译不会重新打包APK

### ISSUE THREAD

**Issue by BestDI** [alibaba/freeline#402]
修改代码之后,执行python freeline.py命令后,在build/outputs/apk名录下生成的apk还是上次全量编译时生成的APK.
版本：0.8.2
操作系统：Linux

[-][merge_dex_task] failed. in 0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s

**Comment by lomanyong** [comment]
@BestDI 增量编译不重新打包 apk 是正常现象。。这个你可以去了解一下 freeline 的原理...本质上是在 app 上不停地做热修复....
