### ISSUE TITLE
apk path not exist

### ISSUE THREAD

**Issue by zxsr20** [alibaba/freeline#404]
这个freeline_project_description.json文件中的"apk_path": "MasterSuiteCN-cn-debug.apk",是正确的，
build.gradle中我也是freeline {
        hack true
        productFlavor 'cn'
        apkPath "MasterSuiteCN-cn-debug.apk"
    }
然后在项目的build／outputs／apk目录下也是有这个MasterSuiteCN-cn-debug.apk的，但是插件为什么会去找MasterSuiteCN-debug.apk，表示很困惑

python freeline.py -d
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False, wait=False)
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 427180
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save MasterSuiteCN module file stat
[DEBUG] [generate_file_stat_task] save ForexMaster module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.1s
[DEBUG] [read_project_info_task] read_project_info_task finish in 2.2s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 2.2s
[DEBUG] [gradle_clean_build_task] ./gradlew :MasterSuiteCN:assembleDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 109.8s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 112.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 112.0s
[DEBUG] [install_apk_task] check device' connection...
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline_annotation_info.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/jar_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/public_keeper.xml
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/stat_cache.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/ForexMaster/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/ForexMaster/resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline-assets/apktime
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/resources_dependencies.json
[DEBUG] [clean_all_cache_task] clean_all_cache_task finish in 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 111.8s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 109.8s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 112.0s
[DEBUG] [append_file_stat_task] generate_file_stat_task in append mode
[DEBUG] collecting project info, please wait a while...
[DEBUG] [generate_apt_files_task] generate_apt_files_task finish in 0.0s
[DEBUG] collecting project info, please wait a while...
[DEBUG] [append_file_stat_task] no new modules found.
[DEBUG] [append_file_stat_task] append_file_stat_task finish in 0.0s
[DEBUG] [install_apk_task] install_apk_task finish in 0.0s
[DEBUG] [build_base_resource_task] /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/public_keeper.xml exists, move to dst: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/backup/res/values/freeline_id_keeper_public.xml
[DEBUG] [generate_project_info_task] generate_project_info_task finish in 0.0s
[DEBUG] [build_base_resource_task] generating ids.xml from public.xml...
[DEBUG] find manifest: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/manifests/full/cn/debug/AndroidManifest.xml
[DEBUG] [build_base_resource_task] aapt exec: freeline/release-tools/FreelineAapt package -f -I /Users/hzfdt/Library/Android/sdk/platforms/android-21/android.jar -M /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/manifests/full/cn/debug/AndroidManifest.xml -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/generated/res/rs/cn/debug -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/build/generated/res/rs/release -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android/1.4-beta2/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/support-v4/23.4.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.2.1/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fbcore/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline-base/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/drawee/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fresco/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/org.jdeferred/jdeferred-android-aar/1.2.4/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/8.3.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.google.android.gms/play-services-analytics/8.3.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/backup/res -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline-assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/school-db -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/generated/assets/shaders/cn/debug -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/build/generated/assets/shaders/release -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android/1.4-beta2/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/support-v4/23.4.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.2.1/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fbcore/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline-base/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/drawee/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fresco/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/assets -m -J /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/backup --auto-add-overlay -F /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[DEBUG] [build_base_resource_task] generate base resource success: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/base-res.so
[DEBUG] [tracing] build_base_resource_aapt_task: 5287.40787506ms
[DEBUG] [build_base_resource_task] build_base_resource_task finish in 5.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 117.37s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
apk path: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/outputs/apk/MasterSuiteCN-debug.apk, not exists.
[ERROR] --------------------------------------------------------
[ERROR] apk not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 117.4s
[DEBUG] Total time: 117.6s

**Comment by lomanyong** [comment]
@zxsr20 apk path 是需要完整的路径的，

````gradle
freeline {
    ......
    apkPath "/Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/outputs/apk/MasterSuiteCN-cn-debug.apk"
}
````

为了方便适配不同的平台，推荐使用`apkPath project.rootProject.file("MasterSuiteCN/build/outputs/apk/MasterSuiteCN-cn-debug.apk").getAbsolutePath()`

**Comment by zxsr20** [comment]
大牛，你好，这样也是没有解决，还是提示，是否是那里写死了，之前的版本好像我都没有配过这个apkpath
 python freeline.py -d
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False, wait=False)
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 427180
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save MasterSuiteCN module file stat
[DEBUG] [generate_file_stat_task] save ForexMaster module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.1s
[DEBUG] [read_project_info_task] read_project_info_task finish in 2.2s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 2.2s
[DEBUG] [gradle_clean_build_task] ./gradlew :MasterSuiteCN:assembleDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 109.8s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 112.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 112.0s
[DEBUG] [install_apk_task] check device' connection...
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline_annotation_info.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/jar_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/public_keeper.xml
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/stat_cache.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/ForexMaster/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/ForexMaster/resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline-assets/apktime
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/resources_dependencies.json
[DEBUG] [clean_all_cache_task] clean_all_cache_task finish in 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 111.8s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 109.8s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 112.0s
[DEBUG] [append_file_stat_task] generate_file_stat_task in append mode
[DEBUG] collecting project info, please wait a while...
[DEBUG] [generate_apt_files_task] generate_apt_files_task finish in 0.0s
[DEBUG] collecting project info, please wait a while...
[DEBUG] [append_file_stat_task] no new modules found.
[DEBUG] [append_file_stat_task] append_file_stat_task finish in 0.0s
[DEBUG] [install_apk_task] install_apk_task finish in 0.0s
[DEBUG] [build_base_resource_task] /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/public_keeper.xml exists, move to dst: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/backup/res/values/freeline_id_keeper_public.xml
[DEBUG] [generate_project_info_task] generate_project_info_task finish in 0.0s
[DEBUG] [build_base_resource_task] generating ids.xml from public.xml...
[DEBUG] find manifest: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/manifests/full/cn/debug/AndroidManifest.xml
[DEBUG] [build_base_resource_task] aapt exec: freeline/release-tools/FreelineAapt package -f -I /Users/hzfdt/Library/Android/sdk/platforms/android-21/android.jar -M /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/manifests/full/cn/debug/AndroidManifest.xml -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/generated/res/rs/cn/debug -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/build/generated/res/rs/release -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android/1.4-beta2/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/support-v4/23.4.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.2.1/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fbcore/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline-base/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/drawee/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fresco/0.9.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/org.jdeferred/jdeferred-android-aar/1.2.4/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/8.3.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.google.android.gms/play-services-analytics/8.3.0/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/res -S /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/backup/res -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/freeline-assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/school-db -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/generated/assets/shaders/cn/debug -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/ForexMaster/build/generated/assets/shaders/release -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.squareup.leakcanary/leakcanary-android/1.4-beta2/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/support-v4/23.4.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.2.1/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fbcore/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline-base/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/drawee/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.facebook.fresco/fresco/0.9.0/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/assets -A /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.2/assets -m -J /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/MasterSuiteCN/backup --auto-add-overlay -F /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[DEBUG] [build_base_resource_task] generate base resource success: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/freeline/base-res.so
[DEBUG] [tracing] build_base_resource_aapt_task: 5287.40787506ms
[DEBUG] [build_base_resource_task] build_base_resource_task finish in 5.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 117.37s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
apk path: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/outputs/apk/MasterSuiteCN-debug.apk, not exists.
[ERROR] --------------------------------------------------------
[ERROR] apk not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 117.4s
[DEBUG] Total time: 117.6s
[DEBUG] --------------------------------------------------------
ct-MacBook-Pro:FDTMaster-Android hzfdt$ python freeline.py
[WARNING] some important file missed, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 5.4s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] finished. in 172.5s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] failed. in 0.0s
[-][build_base_resource_task] finished. in 6.9s
[-][generate_project_info_task] finished. in 0.0s
[-][generate_apt_files_task] finished. in 0.0s
[-][append_file_stat_task] finished. in 0.0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
apk path: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/outputs/apk/MasterSuiteCN-debug.apk, not exists.
[ERROR] --------------------------------------------------------
[ERROR] apk not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 184.8s
[DEBUG] Total time: 184.9s
[DEBUG] --------------------------------------------------------
ct-MacBook-Pro:FDTMaster-Android hzfdt$ python freeline.py
[INFO] preparing for tasks...
[-][read_project_info_task] finished. in 3.5s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] finished. in 90.9s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] failed. in 0.0s
[-][build_base_resource_task] finished. in 5.5s
[-][generate_project_info_task] finished. in 0.0s
[-][generate_apt_files_task] finished. in 0.0s
[-][append_file_stat_task] finished. in 0.0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
apk path: /Users/hzfdt/AndroidStudioProjects/FDTMaster-Android/MasterSuiteCN/build/outputs/apk/MasterSuiteCN-debug.apk, not exists.
[ERROR] --------------------------------------------------------
[ERROR] apk not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 99.9s
[DEBUG] Total time: 100.1s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zxsr20 你用的是哪个版本的。。gradle插件，跟`python freeline.py -v`版本一致吗？

**Comment by lomanyong** [comment]
@zxsr20 不需要一直重复开同样的 case...
