### ISSUE TITLE
可以用freeline运行debug，也可以直接运行AS的debug，但是当我Generate singed apk时报错

### ISSUE THREAD

**Issue by wangzhengchao** [alibaba/freeline#406]
Error:Execution failed for task ':project-appmodule:transformClassesAndResourcesWithProguardForWandoujiaRelease'.
> java.io.IOException: Can't write [D:\minsu_workspace\project\appmodule\build\intermediates\transforms\proguard\wandoujia\release\jars\3\1f\main.jar] (Can't read [D:\minsu_workspace\project\appmodule\build\intermediates\exploded-aar\com.antfortune.freeline\runtime-no-op\0.8.2\jars\classes.jar(;;;;;;**.class)] (Duplicate zip entry [com/antfortune/freeline/a.class == classes.jar:com/antfortune/freeline/FreelineCore.class]))

**Comment by wangzhengchao** [comment]
Android Studio 2.2.2
Build #AI-145.3360264, built on October 18, 2016
JRE: 1.8.0_76-release-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by lomanyong** [comment]
@wangzhengchao 检查一下你的 build.gradle 的配置，不需要手动`compile "com.antfortune.freeline:xxxxxx"`，如果有的话，把这些配置去掉。保留`classpath "com.antfortune.freeline:gradle:x.x.x"`即可。

**Comment by wangzhengchao** [comment]
我的build.gradle里面没有 compile "com.antfortune.freeline:xxxxxx"， @lomanyong ，麻烦大神在帮我看看

**Comment by lomanyong** [comment]
@wangzhengchao 你可以先 clean 一下。出现这种情况的原因很明显，可能是同时添加了`runtime`跟`runtime-no-op`导致的。如果你只是添加了 freeline 的 gradle 插件的话是不会出现这个问题的...问题还是在于你本地自己的配置...你最好还是能够再排查一下...

**Comment by wangzhengchao** [comment]
@lomanyong ，按您提供的方案，已解决，多谢！！！

**Comment by SuperMan-1997** [comment]
我按照文档中在build.gradle下添加apply plugin 'com.antfortune.freeline' 一直报错，请问改怎么解决
A problem occurred evaluating project ':app'.
> Could not get unknown property 'plugin' for project ':app' of type org.gradle.api.Project.
