### ISSUE TITLE
修改了xml资源文件后再执行freeline会提示full resource pack not found

### ISSUE THREAD

**Issue by zhujun2730** [alibaba/freeline#407]
full resource pack not found:    MyProject/app/build/freeline/base-res.so

**Comment by lomanyong** [comment]
@zhujun2730 重新全量编译python freeline.py -f，然后看下是否有报错。

出错的原因应该是你第一次编译的时候有出错没有生成base-res.so文件，或者误删了这个文件导致的。

至于编译资源出错的具体解决方案，可以参考：[wiki - 常见问题#资源编译出错](https://github.com/alibaba/freeline/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E7%BC%96%E8%AF%91%E8%B5%84%E6%BA%90%E6%8A%A5%E9%94%99)，你应该可以知道那些`not found`的资源在哪个文件夹，添加进入配置文件即可（只需要res一级，不需要区分到drawable），具体配置参考wiki或者issue #238 #269

**Comment by zhujun2730** [comment]
非常感谢！请问下，还需要在application里执行   FreelineCore.init(this); 吗？

**Comment by lomanyong** [comment]
@zhujun2730 如果没有在 freeline DSL 里配置 `applicationProxy false` 的话，默认是不需要执行的。

**Comment by zhujun2730** [comment]
谢谢，那 这个DSL 是否必须加？  
freeline {
        hack true
        autoDependency false
    }

**Comment by lomanyong** [comment]
@zhujun2730 视工程情况添加，freeline DSL 主要用来配置复杂工程使用的，具体可以看文档：[Freeline DSL References](https://github.com/alibaba/freeline/wiki/Freeline-DSL-References)

**Comment by zhujun2730** [comment]
重新编译了还是没有生成 base-res.so ==

**Comment by lomanyong** [comment]
@zhujun2730 编译没成功，`python freeline.py -f -d`会有报错日志的...

**Comment by zhujun2730** [comment]
编译通过了，但是就是不生成这个文件

**Comment by lomanyong** [comment]
@zhujun2730 。。。。。只是 apk 编译通过了而已。日志里有 ERROR 的。

前面说的都是有理由的，麻烦把日志贴出来吧...不然没办法分析...：`python freeline.py -f -d`

**Comment by zhujun2730** [comment]
/Users/XXXX/freeline/app/backup/res/values/freeline_id_keeper_public.xml:2359: error: Public symbol drawable/white_round_rect declared here is not defined.

应该是部分资源id没有被找到，我这里添加了  
freeline {
        extraResourceDependencyPaths = ['/src/main/res']
}

**Comment by lomanyong** [comment]
@zhujun2730 这个路径是需要绝对路径的，直接这样的相对路径无法被识别。

对了，也麻烦你使用这个命令：`./gradlew :{your-main-module}:assembleDebug -PfreelineBuild=true > freeline_build.log`，然后将`freeline_build.log`这个文件通过邮件发我一下...

**Comment by zhujun2730** [comment]
我已经写绝对路径了。。extraResourceDependencyPaths =  ['Users/anany/project/AndroidStudioProjects/XXX/app/src/main/res']    还是报id未定义，是路径写错了吗

**Comment by lomanyong** [comment]
@zhujun2730 `/Users/anany/project/AndroidStudioProjects/XXX/app/src/main/res`
