### ISSUE TITLE
已经加上了extraResourceDependencyPaths，但报错 not defined

### ISSUE THREAD

**Issue by VankaIn** [alibaba/freeline#408]
......./backup/res/values/freeline_id_keeper_public.xml:1852: error: Public symbol drawable/rc_btn_public_service_unfollow_selector declared here is not defined.

报这个错，改 java 代码可以增量，但是改 xml 不能运行

**Comment by lomanyong** [comment]
@VankaIn 确认配置正确吗...

**Comment by zhujun2730** [comment]
@lomanyong 和他一样的问题，extraResourceDependencyPaths 配好了路径，还是报资源 not defined

**Comment by VankaIn** [comment]
@lomanyong 确认了。
![image](https://cloud.githubusercontent.com/assets/7741489/20910362/f6aa27d4-bb9b-11e6-9bbe-006de33c570b.png)
2个路径均能到达 res 目录

**Comment by lomanyong** [comment]
@VankaIn @zhujun2730 麻烦将以下两个日志文件邮件发我一下...以便定位一下具体问题在哪里：

`gradlew` 在 win 下为 `gradlew`，Linux/Mac 下为`./gradlew`
````
gradlew :{main-module}:assemble{your-flavor}Debug -PfreelineBuild=true > gradle_bulid.log
python freeline.py -f -d > freeline_build.log
````
会生成`gradle_build.log`和`freeline_build.log`两个文件，把这两个文件邮件发我一下把。

最好能够升级到`0.8.3`.

**Comment by VankaIn** [comment]
@lomanyong 已发，谢谢

**Comment by lomanyong** [comment]
@VankaIn @zhujun2730 

基本定位出错的问题在 PNG 图片错误上，好早以前也有人遇见类似的问题，给处理忘了...

这里记录一下，资源编译出错的日志中有类似的日志：
````
ERROR: Failure processing PNG image /Users/anany/project/AndroidStudioProjects/FptAndroid/app/src/main/res/drawable-xhdpi/icon_rule.png
ERROR: Failure processing PNG image /Users/anany/project/AndroidStudioProjects/FptAndroid/app/src/main/res/drawable-xhdpi/titlemore.png
````

出错后，导致大量的资源无法被找到...

**Comment by lomanyong** [comment]
伪造成 PNG 的 JPG 导致的错误...
