### ISSUE TITLE
如何设置编译的时候用gradle assembleDebug, 而不是 gradle build？

### ISSUE THREAD

**Issue by zewenwang** [alibaba/freeline#409]
RT 

如何设置编译的时候用gradle assembleDebug, 而不是 gradle build？
毕竟在debug阶段用到release包的几率比较小，而release包Proguard过程又耗时严重，所以希望只打debug包就好了，有没有相应的命令呢

**Comment by lomanyong** [comment]
@zewenwang 使用 freeline 的时候默认的全量编译指令就是`gradlew assembleDebug`了，除非你自己设置修改过....

**Comment by zewenwang** [comment]
got it
