### ISSUE TITLE
NoConfigFoundException: /Users/huangyaoshi/.freeline/cache/a889ab4ce8044dee8e88136f8bb56b20/project_description.json not found, please execute gradlew checkBeforeCleanBuild first.

### ISSUE THREAD

**Issue by huangbom** [alibaba/freeline#412]
我查看了相关的两个问题，还是没有解决

我使用的是
`classpath 'com.antfortune.freeline:gradle:0.8.3' `

在mac环境下出现了问题：
`  File "/Users/huangyaoshi/Desktop/gold-android/freeline/freeline_core/gradle_clean_build.py", line 44, in generate_sorted_build_tasks
    build_base_resource_task = BuildBaseResourceTask(self._config, self._project_info)
  File "/Users/huangyaoshi/Desktop/gold-android/freeline/freeline_core/gradle_tools.py", line 618, in __init__
    self.__init_attributes()
  File "/Users/huangyaoshi/Desktop/gold-android/freeline/freeline_core/gradle_tools.py", line 623, in __init_attributes
    self._config = read_freeline_config()
  File "/Users/huangyaoshi/Desktop/gold-android/freeline/freeline_core/dispatcher.py", line 161, in read_freeline_config
    raise NoConfigFoundException(config_path)
NoConfigFoundException: /Users/huangyaoshi/.freeline/cache/a889ab4ce8044dee8e88136f8bb56b20/project_description.json not found, please execute gradlew checkBeforeCleanBuild first.

`

./huangdeMBP:gold-android huangyaoshi$ ./gradlew checkBeforeCleanBuild
Old file /Users/huangyaoshi/Desktop/gold-android/freeline_project_description.json removed.
Save to /Users/huangyaoshi/Desktop/gold-android/freeline_project_description.json

**Comment by lomanyong** [comment]
@huangbom 重新执行一下`./gradlew initFreeline -Pmirror`，确认一下`python freeline.py -v`显示版本为0.8.3。

中间有一阵缓存没有及时更新导致的...

**Comment by huangbom** [comment]
🙏
