### ISSUE TITLE
initfreeline 一直是0%

### ISSUE THREAD

**Issue by space0o0** [alibaba/freeline#413]
<img width="232" alt="qq20161205-0 2x" src="https://cloud.githubusercontent.com/assets/8923417/20889383/c7b3cdd0-bb3d-11e6-94f9-fd1354d58da9.png">

**Comment by lomanyong** [comment]
@space0o0 请仔细阅读 README，可以加上参数`-Pmirror`走国内镜像...

**Comment by space0o0** [comment]
@lomanyong 我一直加-Pmirror的，试了好多次了，总是卡在0%

**Comment by lomanyong** [comment]
@space0o0 日志完整地截个图？
