### ISSUE TITLE
 No module named 'build_commands'

### ISSUE THREAD

**Issue by Icyoung** [alibaba/freeline#414]
第一次用，请指教
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File 项目地址\freeline_core\__init__.py", line 1, in <module>
    import build_commands
ImportError: No module named 'build_commands'

**Comment by lomanyong** [comment]
@lcyoung 使用的是 python3 吗？目前还不支持这个...

**Comment by Icyoung** [comment]
嗯 python 3.5.2 好的 谢谢~
