### ISSUE TITLE
初始编译就出现问题

### ISSUE THREAD

**Issue by ManbasJi** [alibaba/freeline#416]
Freeline server in app com.qunyu.taoduoduo not found. Please make sure your application is properly running in your device.
有时候还会出现这个问题

 build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

**Comment by lomanyong** [comment]
@ManbasJi 日志应该有提示你去查看 #152 ，大部分问题都可以解决...
