### ISSUE TITLE
配置出错后，即使修改仍然会一直报错，除非重新打开as

### ISSUE THREAD

**Issue by ml0728119** [alibaba/freeline#419]
在build.gradle 中配置   
 freeline {
        hack true
        productFlavor "pgyer"
    }

  productFlavor "pgyer"  一开始由于引号写错，就报出找找不到productFlavor 。之后修改正确后，一直报该错误。关掉as后，重新run就正确了。

还有一个在刚刚开始配置的时候，要下载freeline.zip时候，下载出错，就一直下载不成功，反复出错。重启as后就下载成功。

**Comment by lomanyong** [comment]
@ml0728119 这个问题跟 freeline 没有关系...跟 AS 或者你本地的环境设置关系比较大一些..
