### ISSUE TITLE
默认的buildtype是release吗，还是说不支持manifest的sourceSets

### ISSUE THREAD

**Issue by Panjianan** [alibaba/freeline#421]
![image](https://cloud.githubusercontent.com/assets/11548553/20911465/164312ac-bba3-11e6-9b11-751a0943e475.png)
freeline跑出来的是main里的那个

**Comment by lomanyong** [comment]
@Panjianan 全量编译的话，使用的是 debug，你从哪段日志来判断使用了 main 的？

**Comment by Panjianan** [comment]
我两个manifest用的不同的application，log出来是是main的那个

**Comment by Panjianan** [comment]
![image](https://cloud.githubusercontent.com/assets/11548553/20911761/5761189a-bba5-11e6-99ed-09233888eabc.png)
我刚才重新试了，不用freeline就是debug的

**Comment by lomanyong** [comment]
@Panjianan 参考一下 #273 做下修改，自己手动在 debug application 加入 `FreelineCore.init(this);`，clean 后重新编译。

出现问题的原因：Freeline 自动去获取 application 的时候确实是去找到 main manifest 的...
