### ISSUE TITLE
有gradle 2.14.1  为啥 还要去下载呢?

### ISSUE THREAD

**Issue by hongyang51** [alibaba/freeline#423]
as 2.2.2  gradle 2.14.1

 ./gradlew checkBeforeCleanBuild
输入之后  就开始 漫长的downloading

**Comment by lomanyong** [comment]
@hongyang51 terminal 执行跟 as 环境不一样... gradle 自己判断要去下载的...不是 freeline 指定的... 我们也希望不需要重复去下载= =...

**Comment by hongyang51** [comment]
@lomanyong  我已经配置了 环境变量 不会替换吗? 没有更好的办法解决 吗?  只有等待吗? 谢谢

**Comment by lomanyong** [comment]
@hongyang51 推荐使用非环境变量的，可以减少一些不必要的未知 bug...。

可以网上搜索一下相关的 gradle 离线下载配置的方法，还是挺快的，不会等待太久。

**Comment by eren000** [comment]
我觉得这个问题需要解决一下，目前只有用gradle-wrapper能够正常运行，如果本地配置gradle的话，不能够正常运行。

**Comment by lomanyong** [comment]
@eren000 "如果本地配置gradle的话，不能够正常运行。"，这个指的是？

**Comment by eren000** [comment]
@lomanyong  我的gradle是用的3.2.1，本地配置的。在setting→gradle里，只有选择 Use default gradle-Wrapper,才能正常运行（当然在这一步，gradle会自动下载gradle-wrapper.properties里distributionUrl的gradle版本）。但是如果gradlesetting设置成use local gradle distribution，不能正常运行。不知道这是不是一个bug。

**Comment by lomanyong** [comment]
@eren000 这个明显不是bug把...
