### ISSUE TITLE
添加 Change log 

### ISSUE THREAD

**Issue by zhenian** [alibaba/freeline#425]
现在不清楚每个版本的变更了什么功能点。
建议维护一份 Change log ，记录每个版本发布，做了什么功能变更。
以便用户确认要不要升级。

原因：团队人多的话，需要判断是否统一升级工具。

**Comment by lomanyong** [comment]
@zhenian 主要在 github 的 releases 里有 changelog：

链接：https://github.com/alibaba/freeline/releases

我在 README 里也更新一下 changelog 的链接。

之后的 changelog 都会越来越详细，尽可能地涉及到每个修改的点。

多谢提议~
