### ISSUE TITLE
data binding occurs error in v0.8.3

### ISSUE THREAD

**Issue by yinchuandong** [alibaba/freeline#426]
When I use data binding, it gives me some errors, 

```
/Users/yinchuandong/androidapp/androidstudio/itime_android/app/src/main/res/layout/activity_main
.xml:30: error: Error: No resource type specified (at 'onClick' with value 
'@{tabBarVM.onTabBarClick(0)}')
```

This is the full log:
[freeline.log.txt](https://github.com/alibaba/freeline/files/633026/freeline.log.txt)

**Comment by lomanyong** [comment]
@yinchuandong Could you provide these files located in `/Users/yinchuandong/androidapp/androidstudio/itime_android/app/build/freeline/app/resource_dependencies.json` and `/Users/yinchuandong/androidapp/androidstudio/itime_android/app/build/freeline/databinding_path_cache.json`

**Comment by yinchuandong** [comment]
Hi, @lomanyong 

These are the two files as you required. Wish you can address the problem asap. Thanks.

[resources_dependencies.json.txt](https://github.com/alibaba/freeline/files/633300/resources_dependencies.json.txt)

[databinding_path_cache.json.txt](https://github.com/alibaba/freeline/files/633297/databinding_path_cache.json.txt)

**Comment by lomanyong** [comment]
@yinchuandong Do you have any configuration in freeline DSL like `extraResourceDependencyPaths `?

**Comment by yinchuandong** [comment]
@lomanyong Yes, I did,
This is my extraResourceDependencyPaths
```
freeline {
        extraResourceDependencyPaths = ['/Users/yinchuandong/androidapp/androidstudio/itime_android/app/src/main/res']
}
```

If I didn't configure it, there would be an error - "Public resource xxx not defined". Can you also come up with a solution to improve this as well?

**Comment by lomanyong** [comment]
@yinchuandong Just remove this `extraResourceDependencyPaths` config. Then execute command `python freeline.py -f -d > freeline_build.log` and email this log file to me.

I think you have the similar problem with issue #408 .

There are logs like "ERROR: Failure processing PNG image xxx" in the error output.

**Comment by yinchuandong** [comment]
@lomanyong Hi, this is the build log without extraResourceDependencyPaths.

[freeline_build.log.txt](https://github.com/alibaba/freeline/files/633440/freeline_build.log.txt)

**Comment by lomanyong** [comment]
@yinchuandong Check the resource files located in this directory: `/Users/yinchuandong/androidapp/androidstudio/itime_android/app/build/freeline/freeline-databinding/app/5f3f6f4791eab42475a18c9e2bce69e8/res`. These files were processed by databinding tool.

I guess there may be something wrong while processing.

**Comment by yinchuandong** [comment]
@lomanyong Sorry for my late reply. I checked the directory. In freeline/xxx/5f3f6f4791eab42475a18c9e2bce69e8/res directory, there just are some **xml** drawable and animation resources, while all image resources are missing.

**Comment by lomanyong** [comment]
@yinchuandong Execute this command: `java -jar freeline/release-tools/databinding-cli8.jar -p org.unimelb.itime -i /Users/yinchuandong/androidapp/androidstudio/itime_android/app/src/debug/res -o /Users/yinchuandong/androidapp/androidstudio/itime_android/app/build/freeline/freeline-databinding/app/3db7110e6c278caf8baa573b0a64a56e/res -d /Users/yinchuandong/androidapp/androidstudio/itime_android/app/build/freeline/freeline-databinding/merged_layoutinfo -c /Users/yinchuandong/androidapp/androidstudio/itime_android/app/build/freeline/freeline-databinding/app/3db7110e6c278caf8baa573b0a64a56e/java -l false -v 22 -s /Users/yinchuandong/android-sdks`

Is there any error outputs?

**Comment by lomanyong** [comment]
@yinchuandong databinding processor will be stopped when the exception throws in freeline 0.8.4.

**Comment by yinchuandong** [comment]
Sorry, I was too busy in last two weeks. My problem still exists. I assume that it is caused by the data binding processor, probably custom binding adapter, like Picasso library or some android selector drawable file. Unfortunately, I can not accurately address this issues because my project is really large.  So I didn't use freeline. If I have sufficient spare time, I will deeply research it.

**Comment by lomanyong** [comment]
@yinchuandong Could you provide any sample codes that can replay your problem? 

Freeline with the version 0.8.4 will be aborted while the databinding process occurs any exceptions. You can also provide the error output as well.

**Comment by yinchuandong** [comment]
@lomanyong 
This is the binding adapter:
![image](https://cloud.githubusercontent.com/assets/3993196/21480664/5e32022e-cbb3-11e6-90bb-794ce3715ac9.png)

This is the layout image view:
![image](https://cloud.githubusercontent.com/assets/3993196/21480703/a392b476-cbb3-11e6-8609-75d3d117e630.png)

there is an error: 
`process databinding error: Source '/Users/yinchuandong/androidapp/androidstudio/itime_android/app/src/main/res/drawable/drawable-xxhdpi' exists but is a directory
`

I am not sure the binding adapter is the cause of freeline building error. It is just my assumption. 

These are the logs with and without extraResourceDependencyPaths configured respectively.
[freeline_with_resource_path.log.txt](https://github.com/alibaba/freeline/files/672863/freeline_with_resource_path.log.txt)
[freeline_without_resource_path.log.txt](https://github.com/alibaba/freeline/files/672864/freeline_without_resource_path.log.txt)
