### ISSUE TITLE
求全量编译的时候提速的建议

### ISSUE THREAD

**Issue by tanweijiu** [alibaba/freeline#429]
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 4.4s
[DEBUG] Task engine running time: 424.0s
[DEBUG] Total time: 428.4s
[DEBUG] --------------------------------------------------------
八分钟啊.......

**Comment by lomanyong** [comment]
@tanweijiu 全量编译提速网上有蛮多介绍的吧...最方便快捷的就是加内存换 SSD，或者修改 gradle 构建任务等等...

freeline 提供的主要是尽量绕过全量编译，使用增量编译的方式来提高调试效率，但是至少要一次全量编译这个是少不了的...
