### ISSUE TITLE
python freeline.py 增量编译的时候 IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by 29995270** [alibaba/freeline#43]
init 和 python freeline.py -f 都是 ok 的
但是修改代码后 python freeline.py 就会报错

Traceback (most recent call last):
  File "D:\as\new\im_android\freeline_core\android_tools.py", line 304, in execute
    self._command.execute()
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 159, in execute
    map(lambda command: command.execute(), self.command_list)
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 159, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 193, in execute
    self._invoker.append_r_file()
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 378, in append_r_file
    write_file_content(main_r_path, content)
  File "D:\as\new\im_android\freeline_core\utils.py", line 118, in write_file_content
    with open(target_path, 'w') as fp:
IOError: [Errno 2] No such file or directory: u'D:\\as\\new\\im_android\\app\\build\\freeline\\app\\backup\\com\\kanjian\\radio\\R.java'

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@29995270 可以贴出更完整的日志吗？这里缺少一些上下文，不是很好判断哪里出问题.

**Comment by 29995270** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False)
[DEBUG] [scan_changed_files_command] find D:\as\new\im_android\app\src\com\kanjian\radio\ui\fragment\radio\MineMenuFragment.java has modification.
[DEBUG] find KanjianTV has 0 java files modified.
[DEBUG] find pay has 0 java files modified.
[DEBUG] find app has 1 java files modified.
[DEBUG] find SwipeMenuListView has 0 java files modified.
[DEBUG] find ImageBlurring has 0 java files modified.
[DEBUG] find handmark_pulltorefresh has 0 java files modified.
[DEBUG] find model has 0 java files modified.
[DEBUG] find umeng_libs has 0 java files modified.
[DEBUG] find baichuan_feedback has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1472538968.1583998,
        "is_root_config_changed": false
    },
    "projects": {
        "KanjianTV": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "pay": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "app": {
            "src": [
                "D:\\as\\new\\im_android\\app\\src\\com\\kanjian\\radio\\ui\\fragment\\radio\\MineMenuFragment.java"
            ],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "SwipeMenuListView": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "ImageBlurring": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "handmark_pulltorefresh": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "model": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "umeng_libs": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "baichuan_feedback": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [ImageBlurring]
[DEBUG] [task_engine] depth: 2, task: [pay]
[DEBUG] [task_engine] depth: 2, task: [baichuan_feedback]
[DEBUG] [task_engine] depth: 2, task: [handmark_pulltorefresh]
[DEBUG] [task_engine] depth: 2, task: [model]
[DEBUG] [task_engine] depth: 2, task: [SwipeMenuListView]
[DEBUG] [task_engine] depth: 4, task: [KanjianTV]
[DEBUG] [task_engine] depth: 4, task: [umeng_libs]
[DEBUG] [task_engine] depth: 6, task: [app]
[DEBUG] [task_engine] depth: 11, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 13, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 14, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 15, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: D:\as\new\im_android\app\build\freeline\freeline-assets\apktime
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [pay] pay start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 272000
[DEBUG] [ImageBlurring] ImageBlurring start to run after waiting 0.0s
[DEBUG] [handmark_pulltorefresh] handmark_pulltorefresh start to run after waiting 0.0s
[DEBUG] [baichuan_feedback] baichuan_feedback start to run after waiting 0.0s
[DEBUG] [model] model start to run after waiting 0.0s
[DEBUG] [ImageBlurring_inc_invoker] ImageBlurring old R.java path: None
[DEBUG] [ImageBlurring_inc_invoker] ImageBlurring new R.java path: None
[DEBUG] [ImageBlurring_inc_invoker] src changed files:
[DEBUG] [model_inc_invoker] model old R.java path: D:\as\new\im_android\model\build\generated\source\r\androidTest\debug\com\kanjian\radio\model\R.java
[DEBUG] [ImageBlurring_inc_invoker] []
[DEBUG] [ImageBlurring_inc_invoker] ImageBlurring project has no change, need not go ahead
[DEBUG] [ImageBlurring_inc_invoker] ImageBlurring code only change R.java, need not go ahead
[DEBUG] [model_inc_invoker] model new R.java path: None
[DEBUG] [ImageBlurring_inc_javac_compile] no need to execute
[DEBUG] [pay_inc_invoker] pay old R.java path: D:\as\new\im_android\pay\build\generated\source\r\androidTest\debug\com\kanjian\radio\pay\R.java
[DEBUG] [handmark_pulltorefresh_inc_invoker] handmark_pulltorefresh old R.java path: D:\as\new\im_android\3rdparty\handmark_pulltorefresh\build\generated\source\r\androidTest\debug\com\handmark\pulltorefresh\library\R.java
[DEBUG] [model_inc_invoker] src changed files:
[DEBUG] [ImageBlurring_inc_dex_compile] no need to execute
[DEBUG] [model_inc_invoker] []
[DEBUG] [pay_inc_invoker] pay new R.java path: None
[DEBUG] [handmark_pulltorefresh_inc_invoker] handmark_pulltorefresh new R.java path: None
[DEBUG] [ImageBlurring] ImageBlurring finish in 0.0s
[DEBUG] [model_inc_invoker] model project has no change, need not go ahead
[DEBUG] [baichuan_feedback_inc_invoker] baichuan_feedback old R.java path: D:\as\new\im_android\baichuan_feedback\build\generated\source\r\androidTest\debug\com\kanjian\radio\feedback\R.java
[DEBUG] [pay_inc_invoker] src changed files:
[DEBUG] [handmark_pulltorefresh_inc_invoker] src changed files:
[DEBUG] [model_inc_invoker] model code only change R.java, need not go ahead
[DEBUG] [SwipeMenuListView] SwipeMenuListView start to run after waiting 0.0s
[DEBUG] [pay_inc_invoker] []
[DEBUG] [handmark_pulltorefresh_inc_invoker] []
[DEBUG] [model_inc_javac_compile] no need to execute
[DEBUG] [pay_inc_invoker] pay project has no change, need not go ahead
[DEBUG] [baichuan_feedback_inc_invoker] baichuan_feedback new R.java path: None
[DEBUG] [handmark_pulltorefresh_inc_invoker] handmark_pulltorefresh project has no change, need not go ahead
[DEBUG] [pay_inc_invoker] pay code only change R.java, need not go ahead
[DEBUG] [handmark_pulltorefresh_inc_invoker] handmark_pulltorefresh code only change R.java, need not go ahead
[DEBUG] [model_inc_dex_compile] no need to execute
[DEBUG] [pay_inc_javac_compile] no need to execute
[DEBUG] [handmark_pulltorefresh_inc_javac_compile] no need to execute
[DEBUG] [baichuan_feedback_inc_invoker] src changed files:
[DEBUG] [model] model finish in 0.0s
[DEBUG] [baichuan_feedback_inc_invoker] []
[DEBUG] [pay_inc_dex_compile] no need to execute
[DEBUG] [handmark_pulltorefresh_inc_dex_compile] no need to execute
[DEBUG] [baichuan_feedback_inc_invoker] baichuan_feedback project has no change, need not go ahead
[DEBUG] [pay] pay finish in 0.0s
[DEBUG] [KanjianTV] KanjianTV start to run after waiting 0.0s
[DEBUG] [baichuan_feedback_inc_invoker] baichuan_feedback code only change R.java, need not go ahead
[DEBUG] [handmark_pulltorefresh] handmark_pulltorefresh finish in 0.0s
[DEBUG] [baichuan_feedback_inc_javac_compile] no need to execute
[DEBUG] [baichuan_feedback_inc_dex_compile] no need to execute
[DEBUG] [baichuan_feedback] baichuan_feedback finish in 0.0s
[DEBUG] [umeng_libs] umeng_libs start to run after waiting 0.0s
[DEBUG] [SwipeMenuListView_inc_invoker] SwipeMenuListView old R.java path: D:\as\new\im_android\3rdparty\SwipeMenuListView\build\generated\source\r\androidTest\debug\com\baoyz\swipemenulistview\R.java
[DEBUG] [SwipeMenuListView_inc_invoker] SwipeMenuListView new R.java path: None
[DEBUG] [SwipeMenuListView_inc_invoker] src changed files:
[DEBUG] [SwipeMenuListView_inc_invoker] []
[DEBUG] [SwipeMenuListView_inc_invoker] SwipeMenuListView project has no change, need not go ahead
[DEBUG] [SwipeMenuListView_inc_invoker] SwipeMenuListView code only change R.java, need not go ahead
[DEBUG] [SwipeMenuListView_inc_javac_compile] no need to execute
[DEBUG] [SwipeMenuListView_inc_dex_compile] no need to execute
[DEBUG] [SwipeMenuListView] SwipeMenuListView finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [KanjianTV_inc_invoker] KanjianTV old R.java path: D:\as\new\im_android\KanjianTV\build\generated\source\r\kanjiantv\debug\com\kanjian\radio\tv\R.java
[DEBUG] [app_inc_invoker] app old R.java path: D:\as\new\im_android\app\build\generated\source\r\develop\debug\com\kanjian\radio\R.java
[DEBUG] [KanjianTV_inc_invoker] KanjianTV new R.java path: None
[DEBUG] [KanjianTV_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] app new R.java path: None
[DEBUG] [umeng_libs_inc_invoker] umeng_libs old R.java path: D:\as\new\im_android\umeng_libs\build\generated\source\r\develop\debug\com\kanjian\radio\umengstatistics\R.java
[DEBUG] [KanjianTV_inc_invoker] []
[DEBUG] [KanjianTV_inc_invoker] KanjianTV project has no change, need not go ahead
[DEBUG] [KanjianTV_inc_invoker] KanjianTV code only change R.java, need not go ahead
[DEBUG] [umeng_libs_inc_invoker] umeng_libs new R.java path: None
[DEBUG] [KanjianTV_inc_javac_compile] no need to execute
[DEBUG] [KanjianTV_inc_dex_compile] no need to execute
[DEBUG] [KanjianTV] KanjianTV finish in 0.0s
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [umeng_libs_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'D:\\as\\new\\im_android\\app\\src\\com\\kanjian\\radio\\ui\\fragment\\radio\\MineMenuFragment.java']
[DEBUG] [umeng_libs_inc_invoker] []
[DEBUG] [app_inc_javac_compile] start to execute javac command...
[DEBUG] [umeng_libs_inc_invoker] umeng_libs project has no change, need not go ahead
[DEBUG] [umeng_libs_inc_invoker] umeng_libs code only change R.java, need not go ahead
[DEBUG] [app_inc_invoker] avoid windows unicode error for D:\as\new\im_android\app\build\freeline\app\backup\com\kanjian\radio\R.java
[DEBUG] [umeng_libs_inc_javac_compile] no need to execute
[DEBUG] [umeng_libs_inc_dex_compile] no need to execute
[DEBUG] [umeng_libs] umeng_libs finish in 0.0s
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.2s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.2s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.1s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.1s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.2s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\as\new\im_android\freeline_core\android_tools.py", line 304, in execute
    self._command.execute()
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 159, in execute
    map(lambda command: command.execute(), self.command_list)
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 159, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 193, in execute
    self._invoker.append_r_file()
  File "D:\as\new\im_android\freeline_core\gradle_inc_build.py", line 378, in append_r_file
    write_file_content(main_r_path, content)
  File "D:\as\new\im_android\freeline_core\utils.py", line 118, in write_file_content
    with open(target_path, 'w') as fp:
IOError: [Errno 2] No such file or directory: u'D:\\as\\new\\im_android\\app\\build\\freeline\\app\\backup\\com\\kanjian\\radio\\R.java'

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------


这些就是 执行 python freeline.py 后的日志

**Comment by lomanyong** [comment]
`D:\as\new\im_android\app\build\generated\source\r\develop\debug\com\kanjian\radio\R.java`这个路径的R.java好像不存在？

可以重新`python freeline.py -f`重新全量打包一次，然后再来增量试试看嘛？

**Comment by charvenhe** [comment]
@29995270 加入我们官方群，我们来跟进


https://camo.githubusercontent.com/479dab1e7188653c6351a9e15f37b3a1e42929da/687474703a2f2f7777332e73696e61696d672e636e2f6c617267652f303036744b66546367773166376274356d397972696a33306e79307a6b6467702e6a7067

**Comment by 29995270** [comment]
这个路径自始至终都是没有的
重新 全量编译 再增量编译 也会报同样的错误
