### ISSUE TITLE
第二次编译没有反应

### ISSUE THREAD

**Issue by Hawken94** [alibaba/freeline#430]
首次编译因为代码有问题软件退出，修改代码之后，再编译的话没有反应，要clean project才会有反应

**Comment by lomanyong** [comment]
@Hawken94 没有任何日志怎么知道是什么问题。。。

**Comment by Hawken94** [comment]
@lomanyong 好吧，现在可以了，之前显示的是find 0 files changed。但是现在发现第二次编译还是全量的
