### ISSUE TITLE
报错：Project 'XXX' not found in root project 'XXX'

### ISSUE THREAD

**Issue by iNotExist** [alibaba/freeline#431]
终端输入python freeline.py后就报Project 'XXX' not found in root project 'XXX'
我们有两个application module,都不在根目录下面，结构类似如下：根目录/具体APP目录/多个module包括application module。

**Comment by lomanyong** [comment]
@iNotExi #251 ，Freeline 目前对多 application module 的支持可能还存在问题...

有时间的话你也可以为我们提供一个类似工程结构的 sample，方便我们后期进行支持...
