### ISSUE TITLE
MiddlewareActivity 这个类是做什么的

### ISSUE THREAD

**Issue by shingohu** [alibaba/freeline#432]
集成成功,增量编译成功时,启动界面 跳转到了 MiddlewareActivity这个界面
然后就ANR了,ARN确定后,手动启动App,增量是成功的。每次都是这种情况,是否与我的项目集成微信Tinker有关.
在多台设备上测试都是这样
部分log信息
![image](https://cloud.githubusercontent.com/assets/4944887/20917331/e3acc1b6-bbcb-11e6-8c79-45b775e6a2a8.png)

**Comment by lomanyong** [comment]
@shingohu 中转 Activity，在这里会 kill process，重启刚才的当前 Activity。

关于 ANR 的情况，跟 tinker 无关，不少 freeline 的用户同时使用了 tinker 也没有问题。大部分跟你本地的某些环境相关，搜下已有的 ANR 的 issue 的话，基本都是自己解决了...

**Comment by shingohu** [comment]
不清楚你说的本地环境指的什么 代码 还是配置还是？ 关于ANR的issue都看过了,实在找不到才来这里问的

**Comment by lomanyong** [comment]
@shingohu 这几天比较忙回复都漏掉了...

很多人可以通过重启手机的方式解决这个 ANR 的问题..大概是这样...

后面的版本也会集中把所有的 issue 都归类出出来..方便大家解决问题，并在 freeline 中给出比较友好的提示...
