### ISSUE TITLE
Complier set the api branch failure

### ISSUE THREAD

**Issue by windherd** [alibaba/freeline#435]
* I use complier manage my branches.like this:

![image](https://cloud.githubusercontent.com/assets/15173137/20919562/6ed87324-bbd7-11e6-8bab-f5af627d93d6.png)

* this is  application module's build.gradle
  `  buildConfigField "String", "API_BRANCH", "\"" + System.getProperty("hostName", "master.stage")`
  but i can't get the hostName(master.test) ,this can only be obtained the defaultValue(master.stage).

**I will be very grateful for what you can help me.**

**Comment by lomanyong** [comment]
@windherd You can easily solve this problem.

Add your own configuration in build.gradle:

````gradle
freeline {
    buildScript "./gradlew :{your-main-module}:assemble{your-flavor}Debug -DhostName=master.test"
}
````

**Comment by windherd** [comment]
**very thankful!**
