### ISSUE TITLE
主module的R文件找不到

### ISSUE THREAD

**Issue by naiyizhang** [alibaba/freeline#438]
我遇到一个问题，按照说明配置完工程运行使用正常，但是过一段时间主module的R文件找不到，import com.xx.xx.R 这个类找不到，但是运行工程还是可以安装到手机里正常运行，重新clean一下R文件正常，clean后第一次运行到手机时间又很长了，很困惑，为啥隔一段时间R文件就找不到了？工程开启了multidex，引用了超多的子module

**Comment by lomanyong** [comment]
@naiyizhang 使用的是 0.8.3 版本吗？看一下是否是跟 #284 类似的问题
