### ISSUE TITLE
incremental build task failed

### ISSUE THREAD

**Issue by lzh131606** [alibaba/freeline#439]
按照github上的教程安装之后，第一次可以编译，但是如果更新的话，就会出现incremental build task failed

**Comment by lomanyong** [comment]
@lzh131606 。。。。一点日志都没有怎么知道问题在哪里

**Comment by lzh131606** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.1.0
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.3
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.3
[DEBUG] [scan_changed_files_command] find E:\android\JavaHomework_lizehao\app\src\main\java\com\lizehao\javahomework_lizehao\ui\MainActivity.java has modification.
[DEBUG] find app has 1 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1481040405.2991319,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [
                "E:\\android\\JavaHomework_lizehao\\app\\src\\main\\java\\com\\lizehao\\javahomework_lizehao\\ui\\MainActivity.java"
            ],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [sync_client] apktime path: E:\android\JavaHomework_lizehao\app\build\freeline\freeline-assets\apktime
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 510000
[DEBUG] [sync_client] your local uuid value is: 510000
[DEBUG] [app_inc_invoker] app old R.java path: E:\android\JavaHomework_lizehao\app\build\generated\source\r\debug\com\lizehao\javahomework_lizehao\R.java
[DEBUG] [app_inc_invoker] app new R.java path: E:\android\JavaHomework_lizehao\app\build\freeline\app\backup\com\lizehao\javahomework_lizehao\R.java
[DEBUG] avoid windows unicode error for E:\android\JavaHomework_lizehao\app\build\freeline\app\backup\com\lizehao\javahomework_lizehao\R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'E:\\android\\JavaHomework_lizehao\\app\\src\\main\\java\\com\\lizehao\\javahomework_lizehao\\ui\\MainActivity.java', u'E:\\android\\JavaHomework_lizehao
\\app\\build\\freeline\\app\\backup\\com\\lizehao\\javahomework_lizehao\\R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_javac_compile] start to execute javac command...
[DEBUG] avoid windows unicode error for E:\android\JavaHomework_lizehao\app\build\freeline\app\backup\com\lizehao\javahomework_lizehao\R.java
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] add apt related file: E:\android\JavaHomework_lizehao\app\src\main\java\com\lizehao\javahomework_lizehao\ui\ShowCityFragment.java
[DEBUG] [app_inc_invoker] add apt related file: E:\android\JavaHomework_lizehao\app\src\main\java\com\lizehao\javahomework_lizehao\ui\ShowProvinceFragment.java
[DEBUG] [app_inc_invoker] add apt related file: E:\android\JavaHomework_lizehao\app\src\main\java\com\lizehao\javahomework_lizehao\ui\WeatherFutureFragment.java
[DEBUG] [app_inc_invoker] add apt related file: E:\android\JavaHomework_lizehao\app\src\main\java\com\lizehao\javahomework_lizehao\ui\WeatherMainFragment.java
[DEBUG] [app_inc_invoker] add apt related file: E:\android\JavaHomework_lizehao\app\src\main\java\com\lizehao\javahomework_lizehao\ui\WeatherMainFragment.java
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.3s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.3s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.3s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.3s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.3s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "E:\android\JavaHomework_lizehao\freeline_core\android_tools.py", line 334, in execute
    self._command.execute()
  File "E:\android\JavaHomework_lizehao\freeline_core\gradle_inc_build.py", line 186, in execute
    map(lambda command: command.execute(), self.command_list)
  File "E:\android\JavaHomework_lizehao\freeline_core\gradle_inc_build.py", line 186, in <lambda>
    map(lambda command: command.execute(), self.command_list)
  File "E:\android\JavaHomework_lizehao\freeline_core\gradle_inc_build.py", line 225, in execute
    self._invoker.run_javac_task()
  File "E:\android\JavaHomework_lizehao\freeline_core\gradle_inc_build.py", line 617, in run_javac_task
    self.debug('javac exec: ' + ' '.join(javacargs))
  File "E:\android\JavaHomework_lizehao\freeline_core\android_tools.py", line 374, in debug
    Logger.debug('[{}_inc_invoker] {}'.format(self._name, message))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u674e' in position 376: ordinal not in range(128)

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.3s
[DEBUG] Total time: 0.5s
[DEBUG] --------------------------------------------------------
 不好意思，忘记贴了

**Comment by lomanyong** [comment]
@lzh131606 重复了.. #437 ，我最近排查下这个问题...
