### ISSUE TITLE
Freeline ERROR  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Huawei-yuan** [alibaba/freeline#442]
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.8s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.4s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.83s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.PathAssembler.getDistName(PathAssembler.java:77)
        at org.gradle.wrapper.PathAssembler.getDistribution(PathAssembler.java:43)
        at org.gradle.wrapper.Install.createDist(Install.java:43)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 4.7s
[DEBUG] Task engine running time: 0.8s
[DEBUG] Total time: 5.5s

**Comment by lomanyong** [comment]
@Huawei-yuan 本地 gradle 环境的问题...可以直接把这个错误日志去搜下...

**Comment by mysangithub** [comment]
Hi Team,
I'm also facing the same issue and been looking for the resolution.
I'm a beginner and tried all the resolutions as per github and stackoverflow comments, but still no luck.
Please assist on this.
Thanks in Advance

Regards,
Santhoshkumar S
