### ISSUE TITLE
有没有什么办法可以重新部署应用

### ISSUE THREAD

**Issue by answer1989** [alibaba/freeline#444]
在实际的项目中遇到一些问题，直接显示到当前界面的话，界面布局错乱了，但是重新启动的话又正常了，具体什么原因还没查到，不知是否和Activity的启动方式有关，我想问下有没有什么配置是可以从应用的第一个Activity开始启动，而不是启动到我当前正在显示的界面，或者需要改动的话，从哪部分代码改动。

**Comment by lomanyong** [comment]
@answer1989 资源错乱的问题可以看 #260 ，暂时还未解决，偶现。

额，freeline 之所以快是因为默认就是进入到你当前的 activity，默认就是这样处理的...你有什么特殊需求是要到第一个 activity 吗？
