### ISSUE TITLE
build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

### ISSUE THREAD

**Issue by heiandroid** [alibaba/freeline#446]

**Comment by lomanyong** [comment]
@heiandroid 没日志没描述怎么知道是什么问题。。。

**Comment by heiandroid** [comment]
加了一个配置就好了.
freeline {
      hack true
      productFlavor 'your-flavor'
  }

**Comment by AstroGypsophila** [comment]
加完后可以，如何指定build release版本。
gradlew.bat :app:assembleDebug

**Comment by lomanyong** [comment]
@AstroGypsophila 按照你们平时 release 版本的方式 release 即可...freeline 不是用来打 release 版本的...

**Comment by AstroGypsophila** [comment]
@lomanyong 是由于项目运行只能release版本打开App与查看更改效果，我并非是想要打包。

**Comment by lomanyong** [comment]
@AstroGypsophila 目前还没有支持任意指定 buildType 的计划...
