### ISSUE TITLE
在Gradle下的分包方案，在Freeline编译不通过

### ISSUE THREAD

**Issue by firsthubgit** [alibaba/freeline#447]
com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:546)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
        at com.android.dx.command.dexer.Main.run(Main.java:275)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

这个问题在Gradle下编译不会出现

**Comment by lomanyong** [comment]
@firsthubgit 参考 #273 ，然后 clean 一下，重新编译，应该可以解决你的问题

**Comment by firsthubgit** [comment]
@lomanyong 按照#273的试了一下，还是出这个错。

**Comment by lomanyong** [comment]
@firsthubgit 额...跟项目大不大没什么关系..不少知名的大 app 都可以正常使用 freeline 的...

还出现这个问题肯定是你没 clean，或者你们本来分在第一个 dex 的类就非常多，导致只引入了 freeline 的几个类就出了问题...

**Comment by firsthubgit** [comment]
@lomanyong 感谢感谢，真的是第一个dex的类太多了，引入freeline出了问题。已解决

**Comment by ysq1051838264** [comment]
为什么第二次编译的时候，不会安装包
ysqMac-mini:KingNew ysq$ python freeline.py  
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.3s
[-][gradle_aapt_task] finished. in 0.0s
[-][domain] finished. in 0.2s
[-][BleLib] finished. in 0.2s
[-][app] finished. in 0.0s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] finished. in 0.0s
[-][clean_cache_task] finished. in 0.0s
[-][update_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.5s
[DEBUG] Task engine running time: 0.4s
[DEBUG] Total time: 0.9s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@ysq1051838264 建议简单了解一下 freeline 的原理，freeline 只在一次全量安装 apk 的基础上不停地做增量热修复...所以后面的编译都是不需要安装的...

**Comment by ysq1051838264** [comment]
@lomanyong 那第二次编译了之后，就是看到自己写的界面没有改变，是不是不支持Kotlin语言哦

**Comment by firsthubgit** [comment]
@ysq1051838264 介绍里说了，不支持Kotlin

**Comment by ysq1051838264** [comment]
@firsthubgit 恩恩。。谢谢，但还是有点不明白，如果不支持Kotlin语言的话,首次编译是可以的，是第二次编译，没有更新

**Comment by lomanyong** [comment]
@ysq1051838264 首次编译实际上是调用 gradle 的编译命令...

Kotlin 如果真的需求特别大的话...后面可以考虑看下提供支持...

**Comment by ysq1051838264** [comment]
@lomanyong 哦哦哦。。好的，谢谢

**Comment by free01230** [comment]
Too many classes in --main-dex-list, main dex capacity exceeded，我这也出现了这个问题，之前是用下面的方式解决的
def patchKeepSpecs() {
   def taskClass = "com.android.build.gradle.internal.tasks.multidex.CreateManifestKeepList";
    def clazz = this.class.classLoader.loadClass(taskClass)
    def keepSpecsField = clazz.getDeclaredField("KEEP_SPECS")
  keepSpecsField.setAccessible(true)
   def keepSpecsMap = (Map) keepSpecsField.get(null)
    if (keepSpecsMap.remove("activity") != null) {
     println "KEEP_SPECS patched: removed 'activity' root"
   } else {
    println "Failed to patch KEEP_SPECS: no 'activity' root found"
    }
}

但是引入了freeline这个方法在gradle中配置报错，注掉了按照上面说的方式#273配置，clean还是不行

**Comment by firsthubgit** [comment]
@free01230  好像跟gradle插件版本有关

//以下这些都会分在主dex下，自己修改
def mainDexListActivity = ['HomeActivity', 'MainSplashActivity', "BaseActivity"]
afterEvaluate {
    project.tasks.each { task ->
        if (task.name.startsWith('collect') && task.name.endsWith('MultiDexComponents')) {
            println "main-dex-filter: found task $task.name"
            task.filter { name, attrs ->
                String componentName = attrs.get('android:name')
                if ('activity'.equals(name)) {
                    def result = mainDexListActivity.find {
                        componentName.endsWith("${it}")
                    }
                    return result != null
                } else {
                    return true
                }
            }
        }
    }
}


参考文章：http://p.codekk.com/detail/Android/TangXiaoLv/Android-Easy-MultiDex

**Comment by free01230** [comment]
@firsthubgit 多谢！按照你给的参考内容解决了。
