### ISSUE TITLE
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s  一直停在这里就不动了

### ISSUE THREAD

**Issue by liu-this** [alibaba/freeline#449]
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\WorkSpace\PYYX\pyyxandroid\pyyx\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 17000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save module module file stat
[DEBUG] [generate_file_stat_task] save common module file stat
[DEBUG] [generate_file_stat_task] save data module file stat
[DEBUG] [generate_file_stat_task] save sdk module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s

**Comment by MeiXXD** [comment]
之前使用没有出现问题。
今天更新android studio版本（2.2.3）和gradle版本造成了同样的问题。

应该是freeline_project_description.json文件没有根据项目变更而更新造成的。

删除项目工程下的freeline文件，重新gradlew initFreeline或者gradlew initFreeline -Pmirror就行了（windows系统）。
或者手动更新freeline_project_description.json文件也行（有待验证）？

**Comment by lomanyong** [comment]
@MeiXXD  @liu-this 应该是卡在 gradle 下载上了，手动执行`gradlew checkBeforeCleanBuild`，就可以看到具体停在哪个地方了...
