### ISSUE TITLE
建议FreelineExtension中增加一项abi

### ISSUE THREAD

**Issue by gaoxuxu** [alibaba/freeline#45]
我不知道是不是个强需求，我们项目中打包时会输出`armeabi`和`x86`、`universal`三个包，最终的`.apk`文件名是`$projectName-$productFlavor-$abi-debug.apk`的形式，现在是通过配置`apkPath`来解决的

**Comment by lomanyong** [comment]
@gaoxuxu 恩，在下一步迭代中会增强这方面的支持。其实也算是强需求了，需要c++/so方面的app蛮多的

**Comment by lomanyong** [comment]
晚上查阅了相关的文档，这个应该是需要增加对`apk splits`的支持。

大概有几个解决方案：

1. 插件实现一套类似apk splits的逻辑
2. 调用android gradle plugin相关的splits逻辑
3. 提供extension参数支持
4. hook apk产物，从产物中选取一个作为默认的apk

对于以上解决方案来说，方案4可能更为通用一些，可以覆盖一些app在gradle生成产物时自定义产物命名的逻辑。接下来的feature开发将会着手从这个角度来入手解决。

参考资料：
- [Android Gradle DSL#Splits](http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.Splits.html)
- [Apk Splits](http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits)

**Comment by lomanyong** [comment]
@gaoxuxu  1a85b6d 以支持自动获取apk名，不过默认如果是多abi的话，默认获取含有armbi的apk，如果对于这里还有特殊需求，可以配置`apkPath`。

下个release版本支持。
