### ISSUE TITLE
gradle initFreeline初始化的时候，出现这个问题，请问怎么解决？

### ISSUE THREAD

**Issue by behindeye** [alibaba/freeline#450]
![image](https://cloud.githubusercontent.com/assets/13843519/20995035/35de6b56-bd2f-11e6-9410-7141ca532581.png)

**Comment by lomanyong** [comment]
@behindeye 本地环境的 java 版本改为 JDK 8 即可解决这个问题了...有相关的issue，可以自己搜索一下

**Comment by behindeye** [comment]
好的我试试，谢谢博主的无私奉献 @lomanyong
