### ISSUE TITLE
proto相关问题

### ISSUE THREAD

**Issue by wutongke** [alibaba/freeline#451]
工程中使用了proto，自动生成java文件，使用freeline全量编译时，第一次全量编译时proto还没有生成proto文件，因此没有放置在缓存中，当第二次编译时，会检测到新增了很多的java文件，再次进行全量编译，其实proto文件在第一次全量编译时就已经存在了，感觉freeline的文件检查是否可以编译完成后再次检查？

**Comment by lomanyong** [comment]
@wutongke 你们编译过程中生成的文件直接放在 src 目录里面？

**Comment by wutongke** [comment]
放置在build目录，然后在gradle中设置了sourceSets。
用的库是这个   https://github.com/square/wire

**Comment by lomanyong** [comment]
@wutongke 其实这种编译期生成代码的 case，最好不要配置到 sourceSets 中，而是通过 gradle plugin，将输出的 task 注册到当前 variant 里，类似`variant.registerJavaGeneratingTask(generateTask, freelineGenerateOutputDir)`的做法。这样的话，就不会干扰到 freeline 对编译期生成文件的监测了。

**Comment by wutongke** [comment]
谢谢，我试试
