### ISSUE TITLE
library module 使用 data binding在断开链接后再次build会报错

### ISSUE THREAD

**Issue by syy555** [alibaba/freeline#452]
注: ************* Generating BR file com.fangdd.mobile.preownedhouse. use final: true
注: writing file com.fangdd.mobile.preownedhouse.BR
注: writing file com.fdd.mobile.customer.BR
注: writing file com.android.databinding.library.baseAdapters.BR
注: writing file android.databinding.DataBinderMapper
/Users/lee/Android/CustomerAndroid/preownedhouse/build/generated/source/apt/release/android/databinding/DataBinderMapper.java:10: 错误: 需要常量表达式
                case com.fdd.mobile.customer.R.layout.xf_view_loadfail_1:
                                                     ^
/Users/lee/Android/CustomerAndroid/preownedhouse/build/generated/source/apt/release/android/databinding/DataBinderMapper.java:12: 错误: 需要常量表达式
                case com.fdd.mobile.customer.R.layout.xf_recycler_brand_hall_item:
                                                     ^
/Users/lee/Android/CustomerAndroid/preownedhouse/build/generated/source/apt/release/android/databinding/DataBinderMapper.java:14: 错误: 需要常量表达式
                case com.fdd.mobile.customer.R.layout.activity_topbar_layout:
                                                     ^
/Users/lee/Android/CustomerAndroid/preownedhouse/build/generated/source/apt/release/android/databinding/DataBinderMapper.java:20: 错误: 需要常量表达式
                case com.fdd.mobile.customer.R.layout.nh_list_item:
                                                     ^
/Users/lee/Android/CustomerAndroid/preownedhouse/build/generated/source/apt/release/android/databinding/DataBinderMapper.java:24: 错误: 需要常量表达式
                case com.fdd.mobile.customer.R.layout.xf_brand_hall_item:
                                                     ^
/Users/lee/Android/CustomerAndroid/preownedhouse/build/generated/source/apt/release/android/databinding/DataBinderMapper.java:26: 错误: 需要常量表达式
                case com.fdd.mobile.customer.R.layout.xf_item_search_result_list:
                                                     ^

**Comment by lomanyong** [comment]
@syy555 能提供可以复现错误的 sample 吗？freeline 在dataBinding方面的测试还不够充分，主要靠使用的团队反馈来解决问题...
