### ISSUE TITLE
linux下编不过，一直卡着

### ISSUE THREAD

**Issue by geek000** [alibaba/freeline#456]
![20161208_171115](https://cloud.githubusercontent.com/assets/10459206/21004771/025ccf46-bd6d-11e6-80f3-3ca8c3834fac.png)
到了最后一行就不动了，同样的工程 在windows上就过去了，但是windows也有个小问题 就是在下载的时候 电脑上的idm自动弹出接管下载了，我是自己下好，自己复制到主项目下，然后再编一次成功的，但是linux不行

**Comment by geek000** [comment]
吃了个饭回来有下文了
Please wait a minute...
      [get] Getting: http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
      [get] To: /home/lynn/WorkSpace/ProjectAndroid/Kedacom/zhcx_master/freeline.zip.tmp
      [get] Error getting http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip to /home/lynn/WorkSpace/ProjectAndroid/Kedacom/zhcx_master/freeline.zip.tmp
:initFreeline FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initFreeline'.
> java.net.SocketException: Unexpected end of file from server

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20 mins 2.234 secs
这是啥原因啊 网络是通的啊

**Comment by geek000** [comment]
@ #345 根据这个 手动搞定了 - - 太蛋疼了 不知道那个初始化方法是不是还要优化 不知道卡哪一步

**Comment by lomanyong** [comment]
@geek000 你应该很少使用命令行操作 gradle 命令才有这个问题吧...

后面考虑加个时间检查。。然后给个提示。。。

**Comment by geek000** [comment]
@lomanyong 请问下你说的 才有这个问题 是哪个问题呢  
我到现在也没整明白问题在哪里，即使真的网络不通，我也已经收到下载zip包到项目根目录了 也没起作用 也没任何提示 还是自己手动解压操作的

**Comment by lomanyong** [comment]
@geek000 前面说的“才有这个问题”指的是在命令行操作 gradle，自动下载 gradle.zip 的问题。

如果你是正常通过命令来执行下载的话，不会没有任何作用也没任何提示的...

**Comment by geek000** [comment]
@lomanyong 下载gradle.zip? 这个我是知道的，你们那用的gradlew命令 执行时候本地没有gradle会去下载？ 但是我已经能用gradlew命令正常打包了 ，其他的问题你们再看着优化吧，反正这个项目弄好了 我现在也不折腾了，有其他问题我会再提的

**Comment by lomanyong** [comment]
@geek000 能够用 AS 直接执行 gradlew 命令来编译跟切换到命令行执行确实不一样。至于为什么同样的 versionCode 还会去重复下载 gradle.zip 还没具体去深究。

初次初始化的版本检查已经从 Github API 迁回国内的服务了，通常这里也不会太卡。
