### ISSUE TITLE
command 'python' not found

### ISSUE THREAD

**Issue by allenli0413** [alibaba/freeline#457]
command 'python' not found. if first installation python or Set Environment variable, Please restart your computer   这是什么原因呢，用命令行就可以编译？

**Comment by pengwei1024** [comment]
你是第一次安装python吗？或者没有设置环境变量？重启电脑就可以解决了。

**Comment by pengwei1024** [comment]
@allenli0413

**Comment by allenli0413** [comment]
不是第一次安装了，重启了不管用，环境变量不知道要配置哪个？ @pengwei1024

**Comment by pengwei1024** [comment]
@allenli0413 配置python到环境变量。不配置环境变量找不到python的安装路径。。。

**Comment by allenli0413** [comment]
@pengwei1024 python 路径一般是在哪啊

**Comment by pengwei1024** [comment]
@allenli0413 你执行命令是怎么执行的？ 直接执行python freeline.py 吗？window上就是安装python的目录， linux及mac上可以用whereis python找
