### ISSUE TITLE
0.8.2开启了多个aapt进程是什么鬼

### ISSUE THREAD

**Issue by tenggangren** [alibaba/freeline#458]
![baiduhi_2016-12-9_11-42-26](https://cloud.githubusercontent.com/assets/4515352/21036955/c74e6cbe-be04-11e6-900a-d806b7b498e0.png)

卡的不行了

**Comment by lomanyong** [comment]
@tenggangren 。。。freeline 应该不会导致这个问题...更多可能是你本地自己结束进程之类的，没有结束完全...
