### ISSUE TITLE
0.83 添加插件。运行报错

### ISSUE THREAD

**Issue by yatou252303** [alibaba/freeline#459]
Information:Gradle tasks [initFreeline]
Information:BUILD FAILED
Information:Total time: 0.492 secs
Error:FAILURE: Build failed with an exception.

* What went wrong:
Task 'initFreeline' not found in project ':app'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by act262** [comment]
你这个估计是apply plugin后没有同步导致的,先试下sync gradle后再跑一下.

**Comment by yatou252303** [comment]
同步了，依然报找不到initFreeline，但是 initFreeline 明明在gradle task 列表中可以看到，好纠结

**Comment by lomanyong** [comment]
@yatou252303 执行 initFreeline 的时候只需要`gradlew initFreeline`即可，不需要加具体的 module

**Comment by dfm899** [comment]
我也遇到同样的问题
