### ISSUE TITLE
增量失败，子module更新检测到了

### ISSUE THREAD

**Issue by tenggangren** [alibaba/freeline#465]
D:\androidstudioproject\yuedu_master\***-yuedu-android\columnistlibrary\src\main\java\com\****\columnist\ui\ColumnDetailActivity.java:250: 错误:  
找不到符号                                                                                                                                           
        H5Tools.getInstance().destroyWebView(mWebView, mWebViewLayout);
        ^
  符号:   变量 H5Tools                                                                                                                               
  位置: 类 ColumnDetailActivity                                                                                                                      
注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出                                                                                
79 个错误                                                                                                                                            
1 个警告                                                                                                                                             

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.

**Comment by lomanyong** [comment]
@tenggangren 详细一点的日志？
