### ISSUE TITLE
日志输出

### ISSUE THREAD

**Issue by MeiXXD** [alibaba/freeline#466]
windows下使用freeline，执行python freeline.py，其实是在执行python freeline.py  -d，会产生大量日志信息。

请问如何设置，把默认debug关掉，变成想要debug的时候，手动添加-d来实现debug模式？

日志变成mac那样精简。

$ python freeline.py  
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.2s
[-][gradle_aapt_task] finished. in 0.0s
[-][asynctaskdialog] finished. in 0.0s
[-][projectFoundation] finished. in 0.0s
[-][activityManager] finished. in 0.0s
[-][cmbShellProject] finished. in 1.9s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] finished. in 0.1s
[-][clean_cache_task] finished. in 0.0s
[-][update_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 2.1s
[DEBUG] Total time: 2.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@MeiXXD windows 的问题主要是没有比较好的控制台 API 来实现绘制...之后如果有比较好的解决方案的话会来搞定这个问题。不过目前还没有，所以默认状态下 windows 直接输出 debug 日志了...
