### ISSUE TITLE
AndroidStudio的Terminal错误日志输出只显示80个字节

### ISSUE THREAD

**Issue by junjle** [alibaba/freeline#468]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':njs:pro
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
这是我的freeline编译错误之后的terminal错误日志输出，每行只显示80个字节，而且后面的没有显示，我用的0.8.2

**Comment by jp1017** [comment]
@junjle 打开右下角 Gradle Console， 可查看全部

**Comment by jp1017** [comment]
这个问题，可删掉build文件夹解决

**Comment by junjle** [comment]
好的我试试
