### ISSUE TITLE
编译出来后的清掉文件乱码问题

### ISSUE THREAD

**Issue by huangwenqiang** [alibaba/freeline#469]
![image](https://cloud.githubusercontent.com/assets/11918130/21092417/3e32d732-c087-11e6-8ca6-96bcdaefb812.png)

这是freeline编译后生成的清单文件，注册的一个activity。label这个属性采用了硬编码

**Comment by huangwenqiang** [comment]
下面是我的清单文件注册的一个。
  <activity
            android:name="com.xiaoka.ddyc.rescue.activity.RescueEmerItemActivity"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:label="紧急电话"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateHidden|adjustResize"/>

**Comment by lomanyong** [comment]
@huangwenqiang 这个字段尽量不要硬编码吧，不是 best practice...暂时没有修复这个编码问题的打算...
