### ISSUE TITLE
执行gradlew initFreeline -Pmirror  出现错误

### ISSUE THREAD

**Issue by lovezt** [alibaba/freeline#47]
我自己创建了一个AS的项目，进行相关配置以后，运行gradlew initFreeline -Pmirror  出现错误， 错误如下：
E:\mywork\MyApplication>gradlew initFreeline -Pmirror
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'initFreeline' not found in root project 'MyApplication'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option
 to get the stack trace. Run with                                              -
-info
or                                                                             -
-debug
option to get more log output.

BUILD FAILED

**Comment by lomanyong** [comment]
没有在主module`apply plugin: "com.antfortune.freeline"`？

**Comment by lovezt** [comment]
@lomanyong    apply plugin: "com.antfortune.freeline"    我加了

**Comment by lovezt** [comment]
@lomanyong 下面是我的主mode的build.gradle文件内容：
apply plugin: 'com.android.application'
apply plugin: 'com.antfortune.freeline'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    signingConfigs {
        relase {
            keyAlias 'qihoo'
            keyPassword '360jia'
            storeFile file('360jia.keystore')
            storePassword '360jia'
        }
    }

    defaultConfig {
        applicationId "com.example.zhangtao_iri.myapplication"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.relase
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    freeline {
        hack true
        productFlavor "develop"
    }

    productFlavors {
        normal {
        }

        develop {
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.+'
    compile 'com.antfortune.freeline:runtime:0.5.4'
}

**Comment by lovezt** [comment]
@lomanyong  问题我找到了  是我自己的问题  谢谢

**Comment by Huyamin150** [comment]
@lovezt 请问你是怎么解决的，

**Comment by lijun952048910** [comment]
一样也是这个错误，Task 'initFreeline' not found in root project 'xxxx'.
