### ISSUE TITLE
使用./gradlew initFreeline -Pmirror，发生java.net.UnknownHostException: static.freelinebuild.com

### ISSUE THREAD

**Issue by ysemylord** [alibaba/freeline#470]
执行
./gradlew initFreeline -Pmirror

过程
freeline auto add runtime dependencies: 0.8.3
Incremental java compilation is an incubating feature.
find variant debug start hack process...
variant release is not debug, skip hack process.
:initFreeline
Freeline initial process start...
[NOTE] Download freeline dependency from mirror...
Downloading release pack from http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
Please wait a minute...
      [get] Getting: http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
      [get] To: /Users/xuyabo/Documents/kuaijiankang/android_kjk/freeline.zip.tmp
> Building 0% > :initFreeline

结果
* What went wrong:
Execution failed for task ':initFreeline'.
> java.net.UnknownHostException: static.freelinebuild.com

**Comment by lomanyong** [comment]
@ysemylord 网络问题。。你可以手动访问： http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip 看看
