### ISSUE TITLE
Android studio插件0.8.3出错！！！！

### ISSUE THREAD

**Issue by huangsanm** [alibaba/freeline#471]
版本：
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0-alpha1'
        classpath 'com.antfortune.freeline:gradle:0.8.3'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.antfortune.freeline'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
    defaultConfig {
        applicationId "com.huashengmi.si"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
工程的freeline模块是通过插件自动添加后面运行报错：
[INFO] preparing for tasks...
[-][read_project_info_task] failed. in 10.5s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] failed. in 0s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
freeline auto add runtime dependencies: 0.8.3

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 10.5s
[DEBUG] Total time: 10.6s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@huangsanm 执行一下`./gradlew -q checkBeforeCleanBuild --stacktrace`看下错误栈是什么样的...

**Comment by wenwenwen888** [comment]
@lomanyong 我的也是报这个错
执行`./gradlew -q checkBeforeCleanBuild --stacktrace`之后
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':nice-spinner'.
      > Could not resolve all dependencies for configuration ':nice-spinner:classpath'.
         > Could not find com.android.tools.build:gradle:2.2.3.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
           Required by:
               ListDemo:nice-spinner:unspecified
         > Could not find com.android.tools.build:gradle:2.2.3.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
           Required by:
               ListDemo:nice-spinner:unspecified

**Comment by lomanyong** [comment]
@wenwenwen888 你这个错不一样。。从网络直接访问来看`mavenCentral()`确实没有这个文件了。。你可以多配一个`jcenter()`看看。

````gradle
repositories {
    mavenCentral()
    jcenter()
}
````

**Comment by jp1017** [comment]
> A problem occurred configuring project ':app'.

app下gradle配置有问题吗，仔细检查下 @huangsanm

**Comment by wenwenwen888** [comment]
@huangsanm 
`    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
    }`
加上了,还是不行,错误信息没变

**Comment by jp1017** [comment]
@wenwenwen888 你这个不是网络问题就是配置问题，贴一下根gradle文件看看？

**Comment by wenwenwen888** [comment]
@jp1017 
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath "io.realm:realm-gradle-plugin:2.0.2"
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
        classpath 'com.antfortune.freeline:gradle:0.8.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by jp1017** [comment]
@wenwenwen888 需要翻墙，配置没问题的

**Comment by wenwenwen888** [comment]
@jp1017 感谢帮忙解答. 解决了,是因为我项目里引用的一个module也用到了gradle , 然后我加上了这句
```
buildscript {
    repositories {
        jcenter()        -----原本是没有这句的,加上就行了
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
    }
}
```
