### ISSUE TITLE
不支持对Lambda表达式的修改

### ISSUE THREAD

**Issue by shanhujiao** [alibaba/freeline#472]
Caused by: java.lang.NoSuchMethodError:HomeFragment$$Lambda$9.lambdaFactory$
v -> {
                ...
        }
修改为下面的形式
new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                   ...
            }
        });

**Comment by lomanyong** [comment]
@shanhujiao 是使用了 retrolambda 吗？
