### ISSUE TITLE
Can't get http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip

### ISSUE THREAD

**Issue by ftc300** [alibaba/freeline#475]
Error:Execution failed for task ':initFreeline'.
> Can't get http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip to ***************\freeline.zip.tmp

**Comment by lomanyong** [comment]
@ftc300 这是网络问题阿。。你手动访问以下就知道的...你可以多试一下...
