### ISSUE TITLE
wifi adb 连接设备 运行报错连接不到设备

### ISSUE THREAD

**Issue by zxp0505** [alibaba/freeline#476]
当执行 python freeline.py  出现以下错误的信息

[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Use `adb devices` to check your device connection
[ERROR] --------------------------------------------------------
[ERROR] No device's connection found
[ERROR] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zxp0505 目前不支持 wifi adb 连接...

**Comment by zxp0505** [comment]
OK
