### ISSUE TITLE
init失败

### ISSUE THREAD

**Issue by ml0728119** [alibaba/freeline#477]
:initFreeline (Thread[Daemon worker,5,main]) started.
:initFreeline
Executing task ':initFreeline' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Freeline initial process start...
[NOTE] Download freeline dependency from mirror...
Downloading release pack from http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
Please wait a minute...
      [get] Getting: http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
      [get] To: D:\StudioWorks\MallGit\Mall\freeline.zip.tmp
      [get] http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip permanently moved to null
      [get] Error getting http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip to D:\StudioWorks\MallGit\Mall\freeline.zip.tmp
:initFreeline FAILED
:initFreeline (Thread[Daemon worker,5,main]) completed. Took 1.285 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initFreeline'.
> java.net.MalformedURLException

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 13.664 secs
Stopped 0 compiler daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':initFreeline'.] f
rom daemon DaemonInfo{pid=14508, address=[c0287e9c-9d14-4da2-bbef-15206d8ce03d port:63313, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], idle=false, lastBusy=1481600916960, conte
xt=DefaultDaemonContext[uid=20eb1aac-fe7d-4de8-9187-00d3eddfdc7b,javaHome=C:\Program Files\Java\jdk1.8.0_20,daemonRegistryDir=C:\Users\cpr011\.gradle\daemon,pid=14508,idleTime
out=10800000,daemonOpts=-XX:MaxPermSize=1024m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx4096m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} (build shou
ld be done).

但是在sample中可以成功。在sample中即使删除freeline、freeline_core和freeline..py，再执行greadlew initFeeline -Pmirror 就可以执行成功，但是集成到自己项目中就会报错

**Comment by ml0728119** [comment]
http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
这个地址用浏览器访问可以直接下载。

**Comment by ml0728119** [comment]
解压zip放到项目根目录，执行 >python freeline.py -f

D:\StudioWorks\MallGit\Mall>python freeline.py -f
Traceback (most recent call last):
  File "freeline.py", line 49, in <module>
    main()
  File "freeline.py", line 45, in main
    freeline.call(args=args)
  File "freeline.py", line 20, in call
    self.dispatcher.call_command(args)
  File "D:\StudioWorks\MallGit\Mall\freeline_core\dispatcher.py", line 31, in call_command
    self._config = read_freeline_config()
  File "D:\StudioWorks\MallGit\Mall\freeline_core\dispatcher.py", line 161, in read_freeline_config
    raise NoConfigFoundException(config_path)
freeline_core.exceptions.NoConfigFoundException: C:\Users\cpr011\.freeline\cache\8cc6451ffacbc15cdf3f17e7cd81eb71\project_description.json not found, please execute gradlew ch
eckBeforeCleanBuild first.

**Comment by lomanyong** [comment]
@ml0728119 你开代理了吗...这基本是你本地网络环境的问题...

你也可以下载后，把文件放在你的项目根目录里执行`./gradlew initFreeline -PfreelineLocal=freeline.zip`

**Comment by lomanyong** [comment]
@ml0728119 不推荐自己解压= =。freeline 除了自动下载解压之外，还做了不少其他的操作。。

**Comment by ml0728119** [comment]
@lomanyong 另外拿了两个项目测试，均可init成功

**Comment by jp1017** [comment]
@ml0728119 @lomanyong 我也遇到此情况，测试了多个项目，有一个init失败 :cry:

**Comment by ml0728119** [comment]
@lomanyong 问题解决了。
@jp1017 你看看项目下gradle.properties文件中有没有配置代理  systemProp.http.proxyHost

**Comment by lomanyong** [comment]
@jp1017 应该是代理有问题。。但是我用代理的时候是可以访问的，国外的朋友应该访问也没问题...

**Comment by jp1017** [comment]
@ml0728119 gradle.properties我都是用全局的，没有更改，然而刚 ./gradlew ./gradlew initFreeline 成功了。。。 :+1: 无心插柳 :smile:
