### ISSUE TITLE
执行gradlew initFreeline -Pmirror时，报错java.util.zip.ZipException: archive is not a ZIP archive

### ISSUE THREAD

**Issue by ysemylord** [alibaba/freeline#478]
* What went wrong:
Execution failed for task ':initFreeline'.
> Error while expanding E:\kujiankang\android_healthexpress\freeline.zip
java.util.zip.ZipException: archive is not a ZIP archive

**Comment by lomanyong** [comment]
@ysemylord 下载的时候没下载成功...你可以手动解压看看。
