### ISSUE TITLE
修改一次代码后，利用python freeline进行增量编译，出现10多处变化，并且报错，无法启动

### ISSUE THREAD

**Issue by renxiaoys1** [alibaba/freeline#482]
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出
100 个错误
1 个警告

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.5s
[DEBUG] Task engine running time: 3.7s
[DEBUG] Total time: 4.1s
[DEBUG] -------------------------------------------

**Comment by lomanyong** [comment]
@renxiaoys1 请执行`python freeline.py -d`贴出详细的日志。。这样子的日志没办法排查问题的...
