### ISSUE TITLE
执行python freeline.py报错

### ISSUE THREAD

**Issue by ysemylord** [alibaba/freeline#484]
\build\intermediates\manifests\full\debug\AndroidManifest.xml:38: AAPT: Error parsing XML: not well-formed (invalid token)
这是我的AndroidManifest有错吗?

**Comment by jp1017** [comment]
不用freeline，as编译运行也报错吧,,检查下清单文件第38行是不是有问题呢？ @ysemylord

**Comment by ysemylord** [comment]
找到问题了，是因为AndroidManifes中直接用了汉字，解决了
