### ISSUE TITLE
./gradlew initFreeline -Pmirror  成功,   python freeline.py 执行出错

### ISSUE THREAD

**Issue by samwwwc** [alibaba/freeline#485]
执行./gradlew initFreeline -Pmirror 没问题
Old file /Applications/enzo/workspace/dev_code/TestFL/freeline_project_description.json removed.
Save to /Applications/enzo/workspace/dev_code/TestFL/freeline_project_description.json

BUILD SUCCESSFUL

Total time: 37.376 secs

执行完 ./gradlew initFreeline -Pmirror 后
执行 python freeline.py 报错.

/Applications/enzo/workspace/dev_code/TestFL/app/src/main/java/okwl/enzo/com/testfl/MyApp.java:5: 错误: 找不到符号
import com.antfortune.freeline.FreelineCore;
^
[ERROR] --------------------------------------------------------
[ERROR] build failed with script: ./gradlew :app:assembleDevelopDebug -P freelineBuild=true -PdisableAutoDependency=true
[ERROR] --------------------------------------------------------

自己写的一个helloWord demo没有其他东西.

配置是从官方demo扒的.

配置如下.

**Comment by samwwwc** [comment]
(app gradle)

apply plugin: 'com.android.application'
apply plugin: 'com.antfortune.freeline'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
    defaultConfig {
        applicationId "okwl.enzo.com.testfl"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    freeline {
        hack true
        productFlavor "develop"
        autoDependency false
    }
    productFlavors {
        normal {

        }

        develop {
        }
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    testCompile 'junit:junit:4.12'
}

**Comment by samwwwc** [comment]
(project gradle)

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
            classpath 'com.android.tools.build:gradle:2.2.3'
            classpath 'com.antfortune.freeline:gradle:0.8.3'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by samwwwc** [comment]
两次执行log如下:

freeline auto add runtime dependencies: 0.8.3
Incremental java compilation is an incubating feature.
variant normalDebug is not develop, skip hack process.
variant normalRelease is not debug, skip hack process.
find variant developDebug start hack process...
variant developRelease is not debug, skip hack process.
:initFreeline
Freeline initial process start...
[NOTE] Download freeline dependency from mirror...
Downloading release pack from http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
Please wait a minute...
      [get] Getting: http://static.freelinebuild.com/freeline/0.8.3/all/freeline.zip
      [get] To: /Applications/enzo/workspace/dev_code/TestFL/freeline.zip.tmp
download success.
removing existing freeline directory
    [unzip] Expanding: /Applications/enzo/workspace/dev_code/TestFL/freeline.zip into /Applications/enzo/workspace/dev_code/TestFL
unziped freeline.zip.
{
    "project_type": "gradle",
    "android_gradle_plugin_version": "2.2.3",
    "freeline_gradle_plugin_version": "0.8.3",
    "java_home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home",
    "freeline_cache_dir": "/Applications/enzo/workspace/dev_code/TestFL",
    "auto_dependency": false,
    "product_flavor": "develop",
    "build_script": "./gradlew :app:assembleDevelopDebug",
    "build_script_work_directory": "",
    "root_dir": "/Applications/enzo/workspace/dev_code/TestFL",
    "main_project_name": "app",
    "main_project_dir": "app",
    "build_directory": "/Applications/enzo/workspace/dev_code/TestFL/app/build",
    "build_cache_dir": "/Applications/enzo/workspace/dev_code/TestFL/app/build/freeline",
    "build_tools_version": "24.0.2",
    "sdk_directory": "/Users/enzo/Library/Android/sdk",
    "build_tools_directory": "/Users/enzo/Library/Android/sdk/build-tools/24.0.2",
    "compile_sdk_version": "android-24",
    "compile_sdk_directory": "/Users/enzo/Library/Android/sdk/platforms/android-24",
    "package": "okwl.enzo.com.testfl",
    "debug_package": "okwl.enzo.com.testfl",
    "main_manifest_path": "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/AndroidManifest.xml",
    "launcher": "okwl.enzo.com.testfl.MainActivity",
    "apk_path": "/Applications/enzo/workspace/dev_code/TestFL/app/build/outputs/apk/app-develop-debug.apk",
    "extra_dep_res_paths": [
        
    ],
    "exclude_dep_res_paths": [
        
    ],
    "main_r_path": "/Applications/enzo/workspace/dev_code/TestFL/app/build/generated/source/r/develop/debug/R.java",
    "use_jdk8": true,
    "main_src_directory": [
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/java",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/java",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/java",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/java"
    ],
    "main_res_directory": [
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/res",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/res",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/res",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/res"
    ],
    "main_assets_directory": [
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/assets",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/assets",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/assets",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/assets"
    ],
    "main_jni_directory": [
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/jni",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/jni",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/jni",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/jni"
    ],
    "main_jniLibs_directory": [
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/jniLibs",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/jniLibs",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/jniLibs",
        "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/jniLibs"
    ],
    "project_source_sets": {
        "app": {
            "main_src_directory": [
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/java",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/java",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/java",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/java"
            ],
            "main_res_directory": [
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/res",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/res",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/res",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/res"
            ],
            "main_assets_directory": [
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/assets",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/assets",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/assets",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/assets"
            ],
            "main_jni_directory": [
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/jni",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/jni",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/jni",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/jni"
            ],
            "main_jniLibs_directory": [
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/developDebug/jniLibs",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/debug/jniLibs",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/develop/jniLibs",
                "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/jniLibs"
            ],
            "main_manifest_path": "/Applications/enzo/workspace/dev_code/TestFL/app/src/main/AndroidManifest.xml"
        }
    },
    "modules": [
        {
            "name": "app",
            "path": "/Applications/enzo/workspace/dev_code/TestFL/app"
        }
    ],
    "module_dependencies": {
        "app": [
            
        ]
    },
    "databinding": [
        
    ],
    "databinding_modules": [
        
    ]
}
Old file /Applications/enzo/workspace/dev_code/TestFL/freeline_project_description.json removed.
Save to /Applications/enzo/workspace/dev_code/TestFL/freeline_project_description.json

BUILD SUCCESSFUL

Total time: 37.376 secs
RonniedeiMac-2:TestFL enzo$ python freeline.py
[INFO] preparing for tasks...
[-][read_project_info_task] finished. in 8.3s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] failed. in 9.9s
[-][clean_all_cache_task] failed. in 0s
[-][install_apk_task] failed. in 0s
[-][build_base_resource_task] failed. in 0s
[-][generate_project_info_task] failed. in 0s
[-][generate_apt_files_task] failed. in 0s
[-][append_file_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.
freeline auto-dependency disabled
Incremental java compilation is an incubating feature.
variant normalDebug is not develop, skip hack process.
variant normalRelease is not debug, skip hack process.
find variant developDebug start hack process...
find default apk path: /Applications/enzo/workspace/dev_code/TestFL/app/build/outputs/apk/app-develop-debug.apk
Old file /Applications/enzo/workspace/dev_code/TestFL/freeline_project_description.json removed.
Save to /Applications/enzo/workspace/dev_code/TestFL/freeline_project_description.json
Freeline add additionalParameters `-P /Applications/enzo/workspace/dev_code/TestFL/app/build/freeline/public_keeper.xml` to aaptOptions
TestFL merge resources task not found.
TestFL merge assets task not found.
runtime merge resources task not found.
runtime merge assets task not found.
runtime merge resources task not found.
runtime merge assets task not found.
runtime-no-op merge resources task not found.
runtime-no-op merge assets task not found.
Freeline not found apt plugin for app[aptEnabled: true, isAptEnabled: false, javaCompile: false]
variant developRelease is not debug, skip hack process.
:app:preBuild UP-TO-DATE
:app:preDevelopDebugBuild UP-TO-DATE
:app:checkDevelopDebugManifest
:app:preDevelopReleaseBuild UP-TO-DATE
:app:preNormalDebugBuild UP-TO-DATE
:app:preNormalReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2421Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCompat2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUi2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUtils2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportFragment2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportMediaCompat2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2421Library UP-TO-DATE
:app:prepareDevelopDebugDependencies
:app:compileDevelopDebugAidl UP-TO-DATE
:app:compileDevelopDebugRenderscript UP-TO-DATE
:app:generateDevelopDebugBuildConfig UP-TO-DATE
:app:generateDevelopDebugFreelineConfig
:app:generateDevelopDebugResValues UP-TO-DATE
:app:generateDevelopDebugResources UP-TO-DATE
:app:resourcesInterceptorBeforeMergeDevelopDebugResources
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-compat/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-compat/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-core-utils/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-core-utils/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-core-ui/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-core-ui/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-media-compat/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-media-compat/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-fragment/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-fragment/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.2.1/res
add library resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.2.1/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/src/main/res
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/generated/res/rs/develop/debug
add local resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/generated/res/rs/develop/debug
find resource path: /Applications/enzo/workspace/dev_code/TestFL/app/build/generated/res/resValues/develop/debug
add local resource: /Applications/enzo/workspace/dev_code/TestFL/app/build/generated/res/resValues/develop/debug
Old file /Applications/enzo/workspace/dev_code/TestFL/app/build/freeline/app/resources_dependencies.json removed.
Save to /Applications/enzo/workspace/dev_code/TestFL/app/build/freeline/app/resources_dependencies.json
:app:mergeDevelopDebugResources UP-TO-DATE
:app:processDevelopDebugManifest
find manifest file path: /Applications/enzo/workspace/dev_code/TestFL/app/build/intermediates/manifests/full/develop/debug/AndroidManifest.xml
:app:processDevelopDebugResources
:app:generateDevelopDebugSources
:app:incrementalDevelopDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDevelopDebugJavaWithJavac
:app:compileDevelopDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDevelopDebugJavaWithJavac FAILED

BUILD FAILED

Total time: 8.76 secs

/Applications/enzo/workspace/dev_code/TestFL/app/src/main/java/okwl/enzo/com/testfl/MyApp.java:5: 错误: 找不到符号
import com.antfortune.freeline.FreelineCore;
                              ^
  符号:   类 FreelineCore
  位置: 程序包 com.antfortune.freeline
/Applications/enzo/workspace/dev_code/TestFL/app/src/main/java/okwl/enzo/com/testfl/MyApp.java:15: 错误: 找不到符号
        FreelineCore.init(this);
        ^
  符号:   变量 FreelineCore
  位置: 类 MyApp
2 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevelopDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: ./gradlew :app:assembleDevelopDebug -P freelineBuild=true -PdisableAutoDependency=true
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 18.1s
[DEBUG] Total time: 18.5s
[DEBUG] --------------------------------------------------------

**Comment by jp1017** [comment]
> variant normalDebug is not develop, skip hack process.

根据上面这个提示, 更改如下：

```
freeline {
hack true
productFlavor "normal"
autoDependency false
}
```

试试吧，不会怀孕 :smile:

**Comment by samwwwc** [comment]
果然没怀孕. 果然好了. 看到了没有怀孕的 helloWord

**Comment by jp1017** [comment]
厉害了啊 欢迎入坑 :smiling_imp:

**Comment by MartinDong** [comment]
为什么我的改了也不行，不开心

**Comment by MartinDong** [comment]
![image](https://cloud.githubusercontent.com/assets/7735699/21711244/b99c2ea0-d428-11e6-9047-ecb8442c800e.png)

**Comment by lomanyong** [comment]
@MartinDong 明显依赖没加进来...最好再检查一下...

**Comment by MartinDong** [comment]
@lomanyong 恩恩，经过检查确实是少配置了一些东西，但是最好再完善一下使用说明，因为按照使用说明配置就会出现类似的情况，我是看着你们提供的demo对照着看了一下，找到了原因。
