### ISSUE TITLE
子module修改，增量编译几乎每次都爆出   错误：找不到符号 ****** ，错误无法访问XXXX ，  必须要全量编译才行的

### ISSUE THREAD

**Issue by tenggangren** [alibaba/freeline#486]
![Uploading image.png…]()

**Comment by lomanyong** [comment]
@tenggangren 图片没有上传成功，这个错误需要详细的日志。`python freeline.py -d > freeline_log.txt`可以输出到文件中..

**Comment by kyangc** [comment]
一样的问题。

**Comment by lomanyong** [comment]
@kyangc hi，从你的日志来看，这个问题是个 bug，下个版本修复一下。

**Comment by kyangc** [comment]
@lomanyong 谢谢，辛苦。
