### ISSUE TITLE
NoClassDefFoundError: com/android/tools/idea/gradle/dsl/model/GradleBuildModel (moments ago)

### ISSUE THREAD

**Issue by 921712319** [alibaba/freeline#487]
这是怎么回事。点击android studio的freeline插件图标不能运行，报这个错。

**Comment by lomanyong** [comment]
@921712319 你用的是什么版本的 Android Studio？

看着是版本的问题..

**Comment by 921712319** [comment]
Android Studio1.4.1，如果我用命令行是可以的。但是用插件运行就不行了。

**Comment by lomanyong** [comment]
@pengwei1024 插件应该没有兼容到 1.4.1 吧？

@921712319 你可以暂时先使用命令行的方式运行一下...

**Comment by pengwei1024** [comment]
看报错是不支持1.4，没有GradleBuildModel 类， 建议还是升级到2.0以上吧

**Comment by jp1017** [comment]
@921712319 升级下as吧，最新稳定2.2.3， 2.3也快要出来了，新版本功能更强大哦 :smile:
