### ISSUE TITLE
E/Freeline: java.lang.ClassNotFoundException: com.antfortune.freeline.FreelineConfig

### ISSUE THREAD

**Issue by guangit** [alibaba/freeline#488]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.antfortune.freeline.FreelineConfig" on path: DexPathList[[zip file

**Comment by lomanyong** [comment]
@guangit 是否使用android studio而不是 freeline 打包导致的这个问题？

**Comment by guangit** [comment]
点击的插件图标

**Comment by lomanyong** [comment]
@guangit 参考 #273 应该可以解决你的问题，确保使用 freeline 打包。如果要切换到 AS 打包的话，记得先 clean 一下。

**Comment by RWebRTC** [comment]
Yes, this help me
