### ISSUE TITLE
Freeline DSL 配置，相对路径支持

### ISSUE THREAD

**Issue by zhenian** [alibaba/freeline#492]
extraResourceDependencyPaths 的配置要绝对路径。
但是在团队中，项目在不同的成员的机器上，位置是不用的。这个配置不能能用。使用起来很麻烦。

**Comment by lomanyong** [comment]
@zhenian 可以通过：`project.rootProject.file("your-relative-path").getAbsolutePath()`

这样的方式，达到团队所有成员统一使用一份 build.gradle 文件~

这些我们都考虑过的不用担心~近期会有一份比较完整的中文使用文档出来，会给出一些注意事项，应该可以帮助你们解决这些问题了。

**Comment by DukeLee1989** [comment]
请问这个中文文档什么时候给出来啊？

**Comment by lomanyong** [comment]
@DukeLee1989 [Freeline 中文文档](https://www.freelinebuild.com/docs/zh_cn/)，可以先在这里看，还在完善中，有什么意见可以提供给我们。
