### ISSUE TITLE
是我哪个文件出错了吗?

### ISSUE THREAD

**Issue by pdog18** [alibaba/freeline#493]
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
![default](https://cloud.githubusercontent.com/assets/17060376/21247632/f97348e2-c36b-11e6-91cb-b873dd4a9df6.png)

**Comment by lomanyong** [comment]
@pdog18 Google it. 跟 Freeline 没有关系...应该是执行 gradlew 命令的时候出问题了... gradlew 初始化的问题...
