### ISSUE TITLE
module在非根目录下build failed，找不到module路径

### ISSUE THREAD

**Issue by xjh1994** [alibaba/freeline#494]
手动改freeline_project_description.json也没有，会被重新修改掉，不知道是在哪边生成的

**Comment by xjh1994** [comment]
比如我的module在项目根目录/platform/app(app是module名)，settings.gradle里是include ":platform:app"

**Comment by lomanyong** [comment]
@xjh1994 `build failed`的日志贴出来看下吧..

**Comment by xjh1994** [comment]
* What went wrong:
Project 'platform' not found in root project 'Test'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] --------------------------------------------------------
[ERROR] build failed with script: ./gradlew :platform:assembleDebug -P freelineBuild=true
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 19.4s
[DEBUG] Total time: 19.6s
[DEBUG] --------------------------------------------------------

@lomanyong

**Comment by xjh1994** [comment]
@lomanyong  platform是在settings.gradle里面的，只不过不在根目录，好像freeline不能识别

**Comment by lomanyong** [comment]
@xjh1994 这样配置一下试试看：
````gradle
freeline {
    buildScript "./gradlew :platform:app:assembleDebug"
}
````

**Comment by xjh1994** [comment]
@lomanyong 
按照你说的，init是成功了，但点击AndroidStudio的插件又报错了：

Traceback (most recent call last):
  File "/Users/xjh1994/txby/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/xjh1994/txby/freeline/freeline_core/gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "/Users/xjh1994/txby/freeline/freeline_core/utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.1s
[DEBUG] Total time: 0.3s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@xjh1994 `gradlew`这个文件在目录下不存在，可以从其他工程拷贝一个过来。

**Comment by xjh1994** [comment]
@lomanyong 
```
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "/Users/xjh1994/xxx/freeline/freeline_core/task.py", line 123, in execute
    self.task.execute()
  File "/Users/xjh1994/xxx/freeline/freeline_core/gradle_tools.py", line 642, in execute
    self.run_aapt()
  File "/Users/xjh1994/xxx/freeline/freeline_core/gradle_tools.py", line 727, in run_aapt
    self.debug('aapt exec: ' + ' '.join(aapt_args))
TypeError: sequence item 0: expected string, NoneType found

```

**Comment by lomanyong** [comment]
@xjh1994 目录下没有`freeline_core/release-tools`文件夹？这个报错是`FreelineAapt`不存在导致的...
