### ISSUE TITLE
如果project下面是多个module，应该如何配置？

### ISSUE THREAD

**Issue by stay4cold** [alibaba/freeline#495]

**Comment by lomanyong** [comment]
@stay4cold 不需要配置...只需要在主工程（application module）添加配置就可以了...

**Comment by stay4cold** [comment]
@lomanyong 我的工程下面有两个application module，在两个中都配置就提示重复

**Comment by lomanyong** [comment]
@stay4cold 参考#251 ，目前还没有彻底支持好多 application module，你要切换 module 的话，目前只能注释掉另外一个 module 的 freeline 配置

**Comment by stay4cold** [comment]
@lomanyong 了解了  谢谢
