### ISSUE TITLE
incremental javac compile failed

### ISSUE THREAD

**Issue by mmchong3173** [alibaba/freeline#496]
我在代码里加上这句：
    private LinkedHashMap<String, Boolean> mUserNameMap = new LinkedHashMap<String, Boolean>() {
        @Override
        protected boolean removeEldestEntry(Entry<String, Boolean> eldest) {
            return size() == 10;
        }
    };

警告: [options] 未与 -source 1.7 一起设置引导类路径                                                                            
D:\Develop\Projects\FreelineBugDemo\app\src\main\java\demo\freeline\com\activity\MainActivity.java:22: 错误:                   
 Entry在LinkedHashMap中不是公共的; 无法从外部程序包中对其进行访问                                                              
        protected boolean removeEldestEntry(Entry<String, Boolean> eldest) {
}

就报了上面这个错，在增量的时候。

**Comment by lomanyong** [comment]
@mmchong3173 这个是 JDK 8 的 API 吧...本来也只有开启了 Jack 后可以用...如果项目没有开启 Jack 的话，不推荐使用高版本的 API ，运行期会报错...

同时，freeline 现在不支持和 Jack 一起使用...

**Comment by mmchong3173** [comment]
@lomanyong  可是我项目没有开启jack，这段代码是生效的

**Comment by lomanyong** [comment]
@mmchong3173 测了一下确实有这个问题，我找下原因。

**Comment by lomanyong** [comment]
@mmchong3173 将代码改为：

````java
LinkedHashMap<String, Boolean> mUserNameMap = new LinkedHashMap<String, Boolean>() {
            @Override
            protected boolean removeEldestEntry(Map.Entry<String, Boolean> eldest) {
                return super.removeEldestEntry(eldest);
            }
};
````

即可解决你的问题，默认的`LinkedHashMap.Entry`确实是私有的。`Map.Entry`才是可以被外部访问的。
