### ISSUE TITLE
 build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

### ISSUE THREAD

**Issue by yihoudejintian** [alibaba/freeline#498]
应用通过run能运行成功，但是通过freeline就是不能成功，出现
 build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace这样的错误？？？如何解决

**Comment by lomanyong** [comment]
@yihoudejintian 日志阿 = =。没日志看不了问题...

**Comment by yihoudejintian** [comment]
已经解决了，谢谢[愉悦]

**Comment by buketanwan** [comment]
@yihoudejintian 楼主怎么解决的,分享下

**Comment by yihoudejintian** [comment]
@buketanwan 
因为配置信息错误，需要添加这一行
freeline {
      hack true
      productFlavor 'yourflavor'
  }

如果build.gradle中配置了productFlavors 就需要这样配置
