### ISSUE TITLE
执行python freeline.py 报错【build base resources failed with: freeline/release-tools/FreelineAapt 】

### ISSUE THREAD

**Issue by littletanker** [alibaba/freeline#50]
执行python freeline.py 报错了

````
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:11612: error: Public symbol string/yotest_free_info declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:11614: error: Public symbol string/yotest_free_time declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:11616: error: Public symbol string/yotest_name declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:11618: error: Public symbol string/yotest_rate declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:11620: error: Public symbol string/yx_alter declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:11622: error: Public symbol string/yx_friend_apply_hint_message declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:11624: error: Public symbol string/zhifubao_start_failed declared here is not defined.
ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/test/Library/Android/sdk/platforms/android-21/android.jar -M /Users/test/AndroidGit//test//app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/test/AndroidGit//test//app/src/main/res -S /Users/test/AndroidGit//test//libYxKnife/src/main/res -S /Users/test/AndroidGit//test//libwatchdog/src/main/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/support-v4/23.1.1/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.bugtags.library/bugtags-lib/1.3.3/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.5.4/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar//test//fanxingsdk/unspecified/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/gridlayout-v7/21.0.3/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.1.1/res -S /Users/test/AndroidGit//test//app/build/generated/res/rs/debug -S /Users/test/AndroidGit//test//app/build/freeline/app/backup/res -A /Users/test/AndroidGit//test//app/build/freeline/freeline-assets -A /Users/test/AndroidGit//test//app/src/main/assets -m -J /Users/test/AndroidGit//test//app/build/freeline/app/backup --auto-add-overlay -F /Users/test/AndroidGit//test//app/build/freeline/base-res.so --debug-mode --resoucres-md5-cache-path /Users/test/AndroidGit//test//app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 159.4s
[DEBUG] Total time: 159.7s
[DEBUG] --------------------------------------------------------
````

**Comment by lomanyong** [comment]
@littletanker 有更完整的日志吗？这一部分有点少..

**Comment by charvenhe** [comment]
@littletanker 可以看看string/zhifubao_start_failed 这些找不到的资源所在的路径是不是没在
下面的-S 里面，如果没在，可以手工通过DSL添加一下 

[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/test/Library/Android/sdk/platforms/android-21/android.jar -M /Users/test/AndroidGit//test//app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/test/AndroidGit//test//app/src/main/res -S /Users/test/AndroidGit//test//libYxKnife/src/main/res -S /Users/test/AndroidGit//test//libwatchdog/src/main/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/support-v4/23.1.1/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.bugtags.library/bugtags-lib/1.3.3/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.5.4/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar//test//fanxingsdk/unspecified/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/gridlayout-v7/21.0.3/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/test/AndroidGit//test//app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.1.1/res -S /Users/test/AndroidGit//test//app/build/generated/res/rs/debug -S /Users/test/AndroidGit//test//app/build/freeline/app/backup/res -A /Users/test/AndroidGit//test//app/build/freeline/freeline-assets -A /Users/test/AndroidGit//test//app/src/main/assets -m -J /Users/test/AndroidGit//test//app/build/freeline/app/backup --auto-add-overlay -F /Users/test/AndroidGit//test//app/build/freeline/base-res.so --debug-mode --resoucres-md5-cache-path /Users/test/AndroidGit//test//app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*

**Comment by littletanker** [comment]
@lomanyong  @charvenhe 最低版本支持是9还是14？
Manifest merger failed : uses-sdk:minSdkVersion 11 cannot be smaller than version 14 declared in library [com.antfortune.freeline:runtime:0.5.4]

**Comment by lomanyong** [comment]
@littletanker freeline-runtime定义的是14，如果一定需要使用9的话，可以使用下面这个，加上`tools:overrideLibrary="com.antfortune.freeline"`：

````xml
<uses-sdk
        android:minSdkVersion="9"
        android:targetSdkVersion="21"
        tools:overrideLibrary="com.antfortune.freeline"/>
````

**Comment by littletanker** [comment]
@charvenhe string/zhifubao_start_failed 这些找不到的资源都是定义在app的res的strings.xml里面的，

- 
![image](https://cloud.githubusercontent.com/assets/10558177/18114643/51c6bd6c-6f6b-11e6-9024-5293effb81e2.png)
上面是执行./gradlew initFreeline的结果

**Comment by lomanyong** [comment]
@littletanker 上面那个你可以发一下更为完整aapt日志，应该不止那几行日志吧..问题应该出在那部分没贴出来的日志里

**Comment by littletanker** [comment]
@lomanyong  这是没切出来的那部分日志
python freeline.py 
[INFO] preparing for tasks...
[-][read_project_info_task] finished. in 10.7s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] finished. in 111.3s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] failed. in 0.0s
[-][build_base_resource_task] failed. in 5.4s
[-][generate_project_info_task] finished. in 0.0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Freeline trace:: makeFileResources all resource. Time Elapsed: 13689.537000 ms 
Freeline trace:: compile values. Time Elapsed: 938.976000 ms 
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.458000 ms 

-resoucres-md5-cache-path = /Users/test/AndroidGit/testGitProject/app/build/freeline/arsc_cache.dat
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
/Users/test/AndroidGit/testGitProject/app/src/main/res/drawable-xhdpi/pic_videocall_mask_bottom.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/test/AndroidGit/testGitProject/app/src/main/res/drawable-xhdpi/pic_videocall_mask_top.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/test/AndroidGit/testGitProject/app/src/main/res/values/strings.xml:17: error: Found text "uap
" where item tag is expected

/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:6735: error: Public symbol array/profile_of_zodiac declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:6906: error: Public symbol string/China declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:6908: error: Public symbol string/a_key_fa declared here is not defined.
/Users/test/AndroidGit/testGitProject/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml:6910: error: Public symbol string/about_me_music_title declared here is not defined.

**Comment by lomanyong** [comment]
`/Users/test/AndroidGit/testGitProject/app/src/main/res/values/strings.xml:17: error: Found text "uap
" where item tag is expected`

@littletanker  可以看一下这个文件的这一行，应该有一些不必要的字符，删掉就行了

**Comment by littletanker** [comment]
@lomanyong 确实strings有些不必要的字符，去掉没报上面的错了，但出现下面的问题了

 python freeline.py 
[INFO] preparing for tasks...
[-][read_project_info_task] finished. in 9.6s
[-][generate_file_stat_task] finished. in 0.2s
[-][gradle_clean_build_task] finished. in 128.0s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] failed. in 0.0s
[-][build_base_resource_task] finished. in 7.4s
[-][generate_project_info_task] finished. in 0.0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
apk path: /Users/test/AndroidGit/testGitProject/app/build/outputs/apk/app-debug.apk, not exists.
[ERROR] --------------------------------------------------------
[ERROR] apk not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 145.1s
[DEBUG] Total time: 145.4s
[DEBUG] --------------------------------------------------------
`

**Comment by lomanyong** [comment]
@littletanker 你们可以加个配置：

freeline {
    apkPath "your-apk-path"
}

出现问题的原因应该是你们的apk最后输出有改过名字的

**Comment by lomanyong** [comment]
@littletanker 也可以使用这个：`apkPath project.rootProject.file("your-relative-path").getAbsolutePath()`，这样的方式可以方便团队的人一起使用。

**Comment by littletanker** [comment]
ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Please make sure your application is properly running in your device.
Check follow steps:
1. If freeline is not added to your app's denpendencies, modifiy your dependency and run python freeline.py -f.
[ERROR] --------------------------------------------------------
[ERROR] Package com.XXX is not found.
[ERROR] ---------------------------------------

@lomanyong 第二次运行报了这个~

**Comment by lomanyong** [comment]
@littletanker 额，你们在应用的application类有使用`FreelineCore.init(this);`吗？

**Comment by littletanker** [comment]
@lomanyong 有的，在onCreate里面加入了FreelineCore.init(this);

**Comment by lomanyong** [comment]
@littletanker 可以过滤一下logcat中的freeline相关的日志，看下freeline的socket是否启动起来了。或者换台设备试试看

**Comment by littletanker** [comment]
@lomanyong  使用AS运行了一次，后面再使用python freeline.py就正常了，难道我打开的姿势不对？？

**Comment by lomanyong** [comment]
@littletanker 也没发现哪个姿势不对...可以先日常使用看看

**Comment by littletanker** [comment]
@lomanyong  我是配置完build.gradle之后，使用命令./gradlew initFreeline 和python freeline.py。这个时候日志打印没有freeline相关的日志，但使用AS手动运行过一次就出来freeline的日志了，然后运行使用python freeline.py貌似就ok了。

很棒的产品，先蹂躏一下了！

**Comment by lomanyong** [comment]
@littletanker 哈哈欢迎多体验哈~

对了，能告知下你们是哪个app嘛？以及增量的数据跟原本打包的数据对比如何？我们希望可以了解一下这个数据

**Comment by littletanker** [comment]
@lomanyong  有机会再私聊哈，我已经进了微信群

**Comment by lomanyong** [comment]
@littletanker 好的~有问题可以加我微信私聊
