### ISSUE TITLE
在layout中改了一个颜色值得时候报apt错误

### ISSUE THREAD

**Issue by Rethen** [alibaba/freeline#504]
apt exec: I:\Program Files\Java\jdk1.8.0_74\bin\javac.exe @I:\AndroidProject\Ehome\app\build\freeline\app\javac_args_file

[ERROR] --------------------------------------------------------
[ERROR] apt compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.5s
[DEBUG] Task engine running time: 31.7s
[DEBUG] Total time: 32.2s
[DEBUG] ---------

**Comment by lomanyong** [comment]
@Rethen 没有更详细的日志？
