### ISSUE TITLE
build failed with script: gradlew.bat :iHealth:assembleDebug -P freelineBuild=true --stacktrace

### ISSUE THREAD

**Issue by duyulx** [alibaba/freeline#509]
C:\App\ihealth-android>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.0.0
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] [WARNING] some important file missed, a clean build will be automatically executed.
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: C:\App\ihealth-android\iHealth\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 932000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save iHealth module file stat
[DEBUG] [generate_file_stat_task] save rubber-loader module file stat
[DEBUG] [generate_file_stat_task] save zBarScannerLibrary module file stat
[DEBUG] [generate_file_stat_task] save library module file stat
[DEBUG] [generate_file_stat_task] save iOS_Dialog_Library module file stat
[DEBUG] [generate_file_stat_task] save OneSDK module file stat
[DEBUG] [generate_file_stat_task] save svprogresshud module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 1.5s
[DEBUG] [read_project_info_task] read_project_info_task finish in 10.2s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 10.2s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 10.2s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 10.2s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 10.2s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 8.7s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 10.2s to execute tasks.
[DEBUG] [task_engine] it takes task engine 10.2s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
freeline auto add runtime dependencies: 0.8.4
variant defaultChannelDebug is not baidu, skip hack process.
variant defaultChannelRelease is not debug, skip hack process.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkBeforeCleanBuild'.
>  invalid productFlavor : baidu

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 10.2s
[DEBUG] Total time: 10.4s
[DEBUG] --------------------------------------------------------

C:\App\ihealth-android>

DSL配置
   freeline {
        hack true
    }

**Comment by lomanyong** [comment]
@duyulx 日志里有提示的：`invalid productFlavor : baidu`，配置的 productFlavor 不正确...
