### ISSUE TITLE
增量编译 APP 中的高德地图只显示LOGO ，而正常编译的时候地图是可以正常显示的

### ISSUE THREAD

**Issue by Gyueqi** [alibaba/freeline#511]
[WARNING] some important file missed, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 13.8s
[-][generate_file_stat_task] finished. in 0.0s
[-][gradle_clean_build_task] finished. in 34.7s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 8.4s
[-][build_base_resource_task] finished. in 0.7s
[-][generate_project_info_task] finished. in 0.0s
[-][generate_apt_files_task] finished. in 0.0s
[-][append_file_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 56.8s
[DEBUG] Total time: 57.0s
[DEBUG] --------------------------------------------------------

编译中是没有报错的    所有程序为一个包下运行 并没有分包的情况 
<img width="403" alt="qq20161219-154545 2x" src="https://cloud.githubusercontent.com/assets/17306784/21304816/ab489b24-c602-11e6-9f2b-4a06aa114b32.png">

**Comment by lomanyong** [comment]
@Gyueqi 这个应该是高德的问题吧...之前有类似的高德的问题...

**Comment by Gyueqi** [comment]
不是高德的问题吧 我正常编译是地图是可以出来的啊   增量就不可以了  这个增量可以改变地图的东西？ 不可能吧

**Comment by Gyueqi** [comment]
@lomanyong    这个不是高德的问题吧  正常编译是可以使用的啊   就只有增量编译不可以  难道是增量编译改变了什么？

**Comment by lomanyong** [comment]
@Gyueqi 全量编译跟你平时普通打包差不多，增量编译没有改变什么，但是 killProcess 并重启了。这个时候，为什么高德没有正常工作了呢？你应该去看下你的 logcat 有没有相关的日志，然后分析看看...

**Comment by Gyueqi** [comment]
@lomanyong   LOGCAT 日志 我贴出来了 就这么多 没有任何的相关的说明。。。。

**Comment by lomanyong** [comment]
@Gyueqi 那个不是logcat的日志，那个是terminal命令行的日志。logcat 就是正常你 app 里输出的日志。

**Comment by Gyueqi** [comment]
@lomanyong  
02:17.926 9259-9259/? D/dalvikvm: Late-enabling CheckJNI
12-19 18:02:17.946 9259-9259/? D/ActivityThread: handleBindApplication:com.ydgy.lm:freeline
12-19 18:02:17.946 9259-9259/? D/ActivityThread: setTargetHeapUtilization:0.25
12-19 18:02:17.946 9259-9259/? D/ActivityThread: setTargetHeapMinFree:2097152
12-19 18:02:17.956 9259-9259/? D/FreelineApplication: FreelineApplication#onCreate()
12-19 18:02:17.956 9259-9259/? E/dalvikvm: Could not find class 'org.micro.freeline.hackload.ClassVerifier', referenced from method com.antfortune.freeline.FreelineConfig.<init>
12-19 18:02:17.956 9259-9259/? W/dalvikvm: VFY: unable to resolve const-class 4902 (Lorg/micro/freeline/hackload/ClassVerifier;) in Lcom/antfortune/freeline/FreelineConfig;
12-19 18:02:17.956 9259-9259/? D/dalvikvm: VFY: replacing opcode 0x1c at 0x000d
12-19 18:02:17.966 9259-9259/? D/FreelineApplication: create application: com.ydgy.lm.App
12-19 18:02:17.966 9259-9259/? I/Freeline: freeline start initial process...
12-19 18:02:17.966 9259-9259/? I/Freeline: freeline init application
12-19 18:02:17.966 9259-9259/? I/Freeline: start to inject dex...
12-19 18:02:17.966 9259-9259/? I/Freeline: start to inject resources...
12-19 18:02:17.966 9259-9259/? I/Freeline: dynamicInfoSp: {}
12-19 18:02:17.966 9259-9259/? I/Freeline: resMap: {}
12-19 18:02:17.966 9259-9259/? I/Freeline: start to load hackload.dex...
12-19 18:02:17.966 9259-9259/? I/Freeline.hackDex: /data/data/com.ydgy.lm/cache/hack/hackload.dex dex length: 848
12-19 18:02:17.966 9259-9259/? I/Freeline.hackDex: /data/data/com.ydgy.lm/cache/hack/opt opt length: 4096
12-19 18:02:17.966 9259-9259/? I/Freeline.hackDex: after opt, dex len:848; opt len:4096
12-19 18:02:17.966 9259-9259/? I/Freeline: load hackload，dex size:848
12-19 18:02:17.966 9259-9259/? I/Freeline: start to inject native lib...
12-19 18:02:17.966 9259-9259/? I/Freeline.hackNative: native lib inject process start...
12-19 18:02:17.966 9259-9259/? I/Freeline.hackNative: inject native lib success [Ljava.io.File;@41c57c58
12-19 18:02:17.966 9259-9259/? D/FreelineApplication: realApplication#attach(Context)
12-19 18:02:17.966 9259-9259/? I/Freeline: freeline start initial process...
12-19 18:02:17.966 9259-9259/? I/Freeline: freeline init application
12-19 18:02:17.976 9259-9259/? I/Freeline: start to inject dex...
12-19 18:02:17.976 9259-9259/? I/Freeline: start to inject resources...
12-19 18:02:17.976 9259-9259/? I/Freeline: dynamicInfoSp: {}
12-19 18:02:17.976 9259-9259/? I/Freeline: resMap: {}
12-19 18:02:17.976 9259-9259/? I/Freeline: start to load hackload.dex...
12-19 18:02:17.976 9259-9259/? I/Freeline.hackDex: /data/data/com.ydgy.lm/cache/hack/hackload.dex dex length: 848
12-19 18:02:17.976 9259-9259/? I/Freeline.hackDex: /data/data/com.ydgy.lm/cache/hack/opt opt length: 4096
12-19 18:02:17.976 9259-9259/? I/Freeline.hackDex: after opt, dex len:848; opt len:4096
12-19 18:02:17.976 9259-9259/? I/Freeline: load hackload，dex size:848
12-19 18:02:17.976 9259-9259/? I/Freeline: start to inject native lib...
12-19 18:02:17.976 9259-9259/? I/Freeline.hackNative: native lib inject process start...
12-19 18:02:17.976 9259-9259/? I/Freeline.hackNative: inject native lib success [Ljava.io.File;@41c5c090
12-19 18:02:18.006 9259-9259/? I/dalvikvm: Could not find method android.widget.ImageView.<init>, referenced from method com.facebook.drawee.view.DraweeView.<init>
12-19 18:02:18.006 9259-9259/? W/dalvikvm: VFY: unable to resolve direct method 19924: Landroid/widget/ImageView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
12-19 18:02:18.006 9259-9259/? D/dalvikvm: VFY: replacing opcode 0x70 at 0x0000
12-19 18:02:18.006 9259-9259/? I/dalvikvm: Could not find method com.facebook.drawee.view.DraweeView.getImageTintList, referenced from method com.facebook.drawee.view.DraweeView.init
12-19 18:02:18.006 9259-9259/? W/dalvikvm: VFY: unable to resolve virtual method 28361: Lcom/facebook/drawee/view/DraweeView;.getImageTintList ()Landroid/content/res/ColorStateList;
12-19 18:02:18.006 9259-9259/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0015
12-19 18:02:18.006 9259-9259/? D/FreelineApplication: realApplication#onCreate()
12-19 18:02:18.006 9259-9259/? I/Freeline.Service: onStartCommand Received start id 1, intent: Intent { cmp=com.ydgy.lm/com.antfortune.freeline.FreelineService }
12-19 18:02:18.006 9259-9259/? D/Freeline.LongLinkServer: Freeline.increment server running on port 41128
12-19 18:02:18.006 9259-9259/? I/Freeline.Service: onStartCommand Received start id 2, intent: Intent { cmp=com.ydgy.lm/com.antfortune.freeline.FreelineService }
12-19 18:02:18.006 9259-9259/? D/Freeline.LongLinkServer: Freeline.increment server is already running
12-19 18:02:18.026 9259-9259/? I/Freeline.Service$Inner: onStartCommand Received start id 1, intent: Intent { cmp=com.ydgy.lm/com.antfortune.freeline.FreelineService$InnerService }
12-19 18:02:18.026 9259-9259/? I/Freeline.Service$Inner: onStartCommand Received start id 2, intent: Intent { cmp=com.ydgy.lm/com.antfortune.freeline.FreelineService$InnerService }
没有报错啊  这边都是运行提示

**Comment by lomanyong** [comment]
@Gyueqi 额...不是随便截一部分日志就能帮你分析整个 app 的运行情况的。

这里的关注点应该是高德为什么不能正常工作，你应该去分析高德 sdk 带的日志，而不是来看 freeline 的日志。
