### ISSUE TITLE
build_base_resource_task failed

### ISSUE THREAD

**Issue by neuyu** [alibaba/freeline#513]
freeline 0.8.4
process databinding error: Source '/Users/neu/*/app/src/main/res/.svn/prop-base' exists but is a directory

java -jar freeline/release-tools/databinding-cli8.jar -p com.*.* -i /Users/neu/*/app/src/main/res -o /Users/neu/*/app/build/freeline/freeline-databinding/app/618fb6d15e15699e1f4366d3ad79fc82/res -d /Users/neu/*/app/build/freeline/freeline-databinding/merged_layoutinfo -c /Users/neu/*/app/build/freeline/freeline-databinding/app/618fb6d15e15699e1f4366d3ad79fc82/java -l false -v 15 -s /Users/neu/Library/Android/sdk

同样失败，配置了DSL:

freeline {
    extraResourceDependencyPaths = ['/Users/neu/*/app/src/main/res']
}

**Comment by neuyu** [comment]
可以正常使用，正常修改Java代码，但是如果修改res内文件，提示：
process databinding error: Source '/Users/neu/*/app/src/main/res/values/strings.xml' and destination '/Users/neu/*/app/src/main/res/values/strings.xml' are the same

**Comment by lomanyong** [comment]
@neuyu 抱歉没注意到 issue，麻烦可以贴出详细一点的日志吗..
