### ISSUE TITLE
编译时间长

### ISSUE THREAD

**Issue by Zihuatanejo50** [alibaba/freeline#518]
运行项目，总是在31s左右，看了下freeline日志，是这个时间占用了98%（connect_device_task]），这是什么问题？thx！

[INFO] preparing for tasks...
[-][connect_device_task] finished. in 31.3s
[-][gradle_aapt_task] finished. in 0.0s
[-][internetenvsetting] finished. in 0.0s
[-][UI] finished. in 0.0s
[-][GuaZi_Sales_Android] finished. in 2.1s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] finished. in 0.1s
[-][clean_cache_task] finished. in 0.0s
[-][update_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 31.5s
[DEBUG] Total time: 31.7s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@Zihuatanejo50 执行一下`python freeline.py -d`输出一下具体的 debug 日志看下...

**Comment by Zihuatanejo50** [comment]
这是全部日志，

[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.1.2
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] [scan_changed_files_command] find /Users/Zihuatanejo/coding/b_sales_android/GuaZi_Sales_Android/src/main/java/com/guazi/android/sales/seller/vl/activity/CustomerFragment.java has modification.
[DEBUG] find GuaZi_Sales_Android has 1 java files modified.
[DEBUG] find internetenvsetting has 0 java files modified.
[DEBUG] find UI has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1482221291.0,
        "is_root_config_changed": false
    },
    "projects": {
        "GuaZi_Sales_Android": {
            "src": [
                "/Users/Zihuatanejo/coding/b_sales_android/GuaZi_Sales_Android/src/main/java/com/guazi/android/sales/seller/vl/activity/CustomerFragment.java"
            ],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "internetenvsetting": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "UI": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [internetenvsetting]
[DEBUG] [task_engine] depth: 2, task: [UI]
[DEBUG] [task_engine] depth: 4, task: [GuaZi_Sales_Android]
[DEBUG] [task_engine] depth: 5, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 7, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 8, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 9, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: /Users/Zihuatanejo/coding/b_sales_android/GuaZi_Sales_Android/build/freeline/freeline-assets/apktime
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [internetenvsetting] internetenvsetting start to run after waiting 0.0s
[DEBUG] [UI] UI start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 602567
[DEBUG] [sync_client] your local uuid value is: 602566
[DEBUG] [internetenvsetting_inc_invoker] internetenvsetting old R.java path: /Users/Zihuatanejo/coding/b_sales_android/internetenvsetting/build/generated/source/r/release/com/example/zhangcaoyang/internetenvsetting/R.java
[DEBUG] [internetenvsetting_inc_invoker] internetenvsetting new R.java path: None
[DEBUG] [UI_inc_invoker] UI old R.java path: /Users/Zihuatanejo/coding/b_sales_android/UI/build/generated/source/r/release/com/guazi/crm/ui/R.java
[DEBUG] [UI_inc_invoker] UI new R.java path: None
[DEBUG] [internetenvsetting_inc_invoker] src changed files:
[DEBUG] [internetenvsetting_inc_invoker] []
[DEBUG] [internetenvsetting_inc_invoker] internetenvsetting project has no change, need not go ahead
[DEBUG] [internetenvsetting_inc_invoker] internetenvsetting code only change R.java, need not go ahead
[DEBUG] [internetenvsetting_inc_javac_compile] no need to execute
[DEBUG] [UI_inc_invoker] src changed files:
[DEBUG] [UI_inc_invoker] []
[DEBUG] [UI_inc_invoker] UI project has no change, need not go ahead
[DEBUG] [UI_inc_invoker] UI code only change R.java, need not go ahead
[DEBUG] [UI_inc_javac_compile] no need to execute
[DEBUG] [internetenvsetting_inc_dex_compile] no need to execute
[DEBUG] [internetenvsetting] internetenvsetting finish in 0.0s
[DEBUG] [UI_inc_dex_compile] no need to execute
[DEBUG] [UI] UI finish in 0.0s
[DEBUG] [GuaZi_Sales_Android] GuaZi_Sales_Android start to run after waiting 0.0s
[DEBUG] [GuaZi_Sales_Android_inc_invoker] GuaZi_Sales_Android old R.java path: /Users/Zihuatanejo/coding/AndroidStudioProjects/GuaZi_Sales_Android/build/generated/source/r/debug/com/ganji/android/haoche/R.java
[DEBUG] [GuaZi_Sales_Android_inc_invoker] GuaZi_Sales_Android new R.java path: /Users/Zihuatanejo/coding/AndroidStudioProjects/GuaZi_Sales_Android/build/freeline/GuaZi_Sales_Android/backup/com/ganji/android/haoche/R.java
[DEBUG] [GuaZi_Sales_Android_inc_invoker] src changed files:
[DEBUG] [GuaZi_Sales_Android_inc_invoker] [u'/Users/Zihuatanejo/coding/AndroidStudioProjects/GuaZi_Sales_Android/src/main/java/com/guazi/android/sales/seller/vl/activity/CustomerFragment.java']
[DEBUG] [GuaZi_Sales_Android_inc_javac_compile] start to execute javac command...


[DEBUG] [GuaZi_Sales_Android_inc_dex_compile] start to execute dex command...
[DEBUG] [GuaZi_Sales_Android_inc_invoker] dex exec: freeline/release-tools/dx --dex --no-optimize --force-jumbo --multi-dex --output=/Users/Zihuatanejo/coding/AndroidStudioProjects/GuaZi_Sales_Android/build/freeline/GuaZi_Sales_Android/dex /Users/Zihuatanejo/coding/AndroidStudioProjects/GuaZi_Sales_Android/build/freeline/GuaZi_Sales_Android/classes
[DEBUG] [GuaZi_Sales_Android] GuaZi_Sales_Android finish in 1.5s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 1.5s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy /Users/Zihuatanejo/coding/AndroidStudioProjects/GuaZi_Sales_Android/build/freeline/GuaZi_Sales_Android/dex/classes.dex to /Users/Zihuatanejo/coding/AndroidStudioProjects/GuaZi_Sales_Android/build/freeline/freeline-dexes/merged.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41129
[DEBUG] [connect_device_task] connect_device_task finish in 31.3s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 31.3s
[DEBUG] [sync_client] GuaZi_Sales_Android has no need to sync inc res pack.
[DEBUG] [sync_client] internetenvsetting has no need to sync inc res pack.
[DEBUG] [sync_client] UI has no need to sync inc res pack.
[DEBUG] [sync_client] start to sync incremental dex...
[DEBUG] [sync_client] pushdex: http://127.0.0.1:41129/pushDex?dexName=merged
[DEBUG] [sync_client] dex path: /Users/Zihuatanejo/coding/b_sales_android/GuaZi_Sales_Android/build/freeline/freeline-dexes/merged.dex
[DEBUG] [sync_client] start to sync close longlink...
[DEBUG] [sync_client] closeLongLink: http://127.0.0.1:41129/closeLongLink?no&lastSync=2
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.1s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 31.4s
[DEBUG] [clean_cache_task] remove cache: /Users/Zihuatanejo/coding/b_sales_android/GuaZi_Sales_Android/build/freeline/increment.restart
[DEBUG] [clean_cache_task] remove cache: /Users/Zihuatanejo/coding/b_sales_android/GuaZi_Sales_Android/build/freeline/freeline-dexes/merged.dex
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 31.4s
[DEBUG] [update_stat_task] refresh /Users/Zihuatanejo/coding/b_sales_android/GuaZi_Sales_Android/src/main/java/com/guazi/android/sales/seller/vl/activity/CustomerFragment.java stat
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 31.43s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 31.4s
[DEBUG] Total time: 31.6s
[DEBUG] --------------------------------------------------------

**Comment by Zihuatanejo50** [comment]
@lomanyong 后来把USB的用途选成传输文件(MTP)，就成了2-3s了，在改回仅限充电也是2s之间，不知道为啥？

**Comment by lomanyong** [comment]
@Zihuatanejo50 原本就是正常的开发者模式？

**Comment by Zihuatanejo50** [comment]
对，就是正常的开发者模式，好奇改了下USB的用途，connect_device_task时间就零点几秒了，很棒的开源库，赞！
