### ISSUE TITLE
配置环境出错

### ISSUE THREAD

**Issue by WJRye** [alibaba/freeline#519]
Error:Could not find method debugCompile() for arguments [com.antfortune.freeline:runtime:0.8.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by lomanyong** [comment]
@WJRye 确认你修改了正确的 build.gradle 文件，这个问题可以 Google 一下，比如：http://stackoverflow.com/questions/23796404/could-not-find-method-compile-for-arguments-gradle
