### ISSUE TITLE
建议自动生成freeline_project_description.json

### ISSUE THREAD

**Issue by zmingchun** [alibaba/freeline#522]
hi，
如题，由于freeline_project_description.json的内容大部分是跟开发机相关的（自动生成），因此不希望将它纳入git跟踪，但初始化时，没有这个文件则会阻断freeline继续执行。
PS:
不知你们是否建议将freeline相关文件纳入git跟踪，我们这边为了省得每个同事都同步下载freeline的依赖（主要是下载依赖太慢了），就将它们加入git跟踪了，因此存在以上需求。

**Comment by lomanyong** [comment]
@zmingchun Nice suggestion.

不过`initFreeline`这个步骤如果加入`-Pmirror`参数的话，在国内应该不会太慢，而且通常只需要执行一次，除了升级之外不需要多次执行。

`freeline_project_description.json`这个文件不建议同步哈。

单独要生成这个文件的话，可以直接执行`gradlew checkBeforeCleanBuild`这个 task，即可生成相应的文件了，也不会很慢。

Thanks for your feedback.

**Comment by zmingchun** [comment]
@lomanyong 好的，谢谢回复。不过建议动态文件（类似IDE的运行文件）能自动生成的，最好还是自动生成，尽量减少依赖项。

**Comment by lomanyong** [comment]
@zmingchun 具体指的是哪些文件呢？

我们也一直希望能够尽可能地减少对大家代码的侵入性以及对你们工程空间的污染，是否还有更好的建议？可以具体说说看~

**Comment by zmingchun** [comment]
@lomanyong 嗯，除了```freeline_project_description.json```外，目前没有侵入代码已经很棒了，如果```Python```文件能够项目不可见就更棒了。

**Comment by lomanyong** [comment]
@zmingchun 原本有考虑过做成一个可以通过环境变量设置为全局的工具，不过这样的话可能接入成本会相对较高，尤其是对 Windows 而言，需要手动改系统配置什么的，所以还是暂时选择通过 gradle task 来下载依赖文件，开发者只需要配置 .gitignore 来忽略无用文件的方式来集成 freeline。
