### ISSUE TITLE
python freeline.py增量编译和-f效果一样

### ISSUE THREAD

**Issue by junjle** [alibaba/freeline#523]
之前使用python freeline.py基本上几秒钟就会执行完毕，-f会出现please wait a minute,
但是现在是我用 python freeline.py命令
check sync status failed, a clean build will be automatically
UG] [gradle_clean_build_task] Gradle build task is running, please wait a miute
效果和-f一样，代码没有任何修改执行 python freeline.py这个命令也是这样，不知道什么原因导致的

**Comment by lomanyong** [comment]
@junjle 每次都反复出现`check sync status failed, a clean build will be automatically`的时候，可以选择卸载重装一下...可以查看已有的issue..
