### ISSUE TITLE
首次点击插件运行错误

### ISSUE THREAD

**Issue by zhoulujue** [alibaba/freeline#525]
Your local freeline version 0.0.0 is lower than the lastest release version 0.8.4. 
        Please update the freeline version in build.gradle. If you still want the specific version of freeline, you can execute the initial command with the extra parameter `-PfreelineVersion={your-wanted-version}`. eg: `gradlew initFreeline -PfreelineVersion=0.0.0`

**Comment by lomanyong** [comment]
@zhoulujue 你怎么添加`classpath "com.antfortune.freeline:gradle:0.8.4"`的呢？

**Comment by zhoulujue** [comment]
![2016-12-22_15-51-31](https://cloud.githubusercontent.com/assets/2437375/21418785/9a134490-c85e-11e6-8859-66b4fa938b6a.png)

**Comment by zhoulujue** [comment]
![2016-12-22_15-53-24](https://cloud.githubusercontent.com/assets/2437375/21418815/ca5f0ac6-c85e-11e6-9359-916b60b0439e.png)

**Comment by lomanyong** [comment]
@zhoulujue 看着不对呀...根工程不应该还有 android-gradle 的 classpath 吗？

**Comment by zhoulujue** [comment]
@lomanyong 是有的。我为了表示清楚，将其他 classpath 删除了以后截的图。

**Comment by zhoulujue** [comment]
@lomanyong 大概是长这样吧：
![2016-12-22_16-01-38](https://cloud.githubusercontent.com/assets/2437375/21419002/044a54ba-c860-11e6-865e-fdc2af1f39f3.png)

**Comment by zhoulujue** [comment]
@lomanyong 
![2016-12-22_16-03-50](https://cloud.githubusercontent.com/assets/2437375/21419039/3f58c870-c860-11e6-9599-51029cb5b0f8.png)

**Comment by lomanyong** [comment]
@zhoulujue 执行一下这个命令`./gradlew initFreeline -PfreelineVersion=0.8.4`，绕过这个校验。

这个错误还是第一次出现，属于说 task 执行过程中没有找到相应的插件才会报错。

**Comment by zhoulujue** [comment]
@lomanyong 
好的，我试试，多谢了！

**Comment by zhoulujue** [comment]
@lomanyong
Done! Thanks!
