### ISSUE TITLE
首次编译报错

### ISSUE THREAD

**Issue by Silence0215** [alibaba/freeline#526]
![image](https://cloud.githubusercontent.com/assets/4235185/21418907/7d54e90c-c85f-11e6-9901-d464f37f78bd.png)
![image](https://cloud.githubusercontent.com/assets/4235185/21418920/91216eba-c85f-11e6-8243-b23b5845d67d.png)

您好, 初次编译报错
classpath 'com.antfortune.freeline:gradle:0.8.4'

**Comment by lomanyong** [comment]
@Silence0215 

![](http://ww1.sinaimg.cn/large/006y8lVagw1fazms765rbj31kw05w40q.jpg)

这个错误的原因，这几个 menuitem menugroup 的是怎么定义的？这几个 id 没有被识别出来导致的出错...

**Comment by Silence0215** [comment]
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
	<group android:id="@+menugroup/new_activity_menugroup">
		<item android:id="@+menuitem/about" android:title="关于"
			android:icon="@android:drawable/ic_menu_info_details" />
		<item android:id="@+menuitem/checkupdate" android:title="检查更新"
			android:icon="@android:drawable/ic_menu_view" />
		<item android:id="@+menuitem/cancel" android:title="退出"
			android:icon="@android:drawable/ic_menu_close_clear_cancel" />
	</group>
</menu>

**Comment by Silence0215** [comment]
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
	<group android:id="@+menugroup/new_activity_menugroup">
		<item android:id="@+menuitem/about" android:title="关于"
			android:icon="@android:drawable/ic_menu_info_details" />
		<item android:id="@+menuitem/checkupdate" android:title="检查更新"
			android:icon="@android:drawable/ic_menu_view" />
		<item android:id="@+menuitem/cancel" android:title="退出"
			android:icon="@android:drawable/ic_menu_close_clear_cancel" />
	</group>
</menu> 

这个文件不能解析是么

**Comment by Silence0215** [comment]
<menu xmlns:android="http://schemas.android.com/apk/res/android">
	<group android:id="@+menugroup/new_activity_menugroup">
		<item android:id="@+menuitem/about" android:title="关于"
			android:icon="@android:drawable/ic_menu_info_details" />
		<item android:id="@+menuitem/checkupdate" android:title="检查更新"
			android:icon="@android:drawable/ic_menu_view" />
		<item android:id="@+menuitem/cancel" android:title="退出"
			android:icon="@android:drawable/ic_menu_close_clear_cancel" />
	</group>
</menu>

**Comment by Silence0215** [comment]
![image](https://cloud.githubusercontent.com/assets/4235185/21419491/e3f81b54-c862-11e6-8c5c-97e9eeee8349.png)

**Comment by lomanyong** [comment]
@Silence0215 图片没有显示出来...看不到你提供的内容...

**Comment by Silence0215** [comment]
@lomanyong 上面截图这个位置解析不了 是么 应该怎么解决

**Comment by lomanyong** [comment]
@Silence0215 这一小段代码你可以提供可以复现的sample代码给我吗？我自己测试看看，之前没遇见过这种情况...

**Comment by Silence0215** [comment]
@lomanyong 这个先不管他吧 可能这种定义menu id的方式 你那边不支持 我先改成正常的 试一下 能用了之后 我再想办法给你提供个demo
