### ISSUE TITLE
connect_device_task 执行特别长时间

### ISSUE THREAD

**Issue by deshuaizhu** [alibaba/freeline#528]
之前用的还是好好的，今天不知道怎么回事，运行的时候，一直在connect_device_task，还没有第一次全量编译快，不知道怎么回事

**Comment by lomanyong** [comment]
@deshuaizhu 参考一下 #518 看下是否可以解决你的问题

**Comment by deshuaizhu** [comment]
不好意思，我的好像是数据线连接有问题，换了一个数据线，就好了，谢谢！

**Comment by deshuaizhu** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False, wait=False)
[DEBUG] find app has 0 java files modified.
[DEBUG] find AHkit has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1482401758.0,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "AHkit": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [AHkit]
[DEBUG] [task_engine] depth: 3, task: [app]
[DEBUG] [task_engine] depth: 4, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 6, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 7, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 8, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [sync_client] apktime path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/app/build/freeline/freeline-assets/apktime
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [sync_client] your local sync value is: 236613
[DEBUG] [AHkit] AHkit start to run after waiting 0.0s
[DEBUG] [sync_client] your local uuid value is: 236608
[DEBUG] [AHkit_inc_invoker] AHkit old R.java path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/AHkit/build/generated/source/r/release/com/autohome/ahkit/R.java
[DEBUG] [AHkit_inc_invoker] AHkit new R.java path: None
[DEBUG] [AHkit_inc_invoker] src changed files:
[DEBUG] [AHkit_inc_invoker] []
[DEBUG] [AHkit_inc_invoker] AHkit project has no change, need not go ahead
[DEBUG] [AHkit_inc_invoker] AHkit code only change R.java, need not go ahead
[DEBUG] [AHkit_inc_javac_compile] no need to execute
[DEBUG] [AHkit_inc_dex_compile] no need to execute
[DEBUG] [AHkit] AHkit finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [app_inc_invoker] app old R.java path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/app/build/generated/source/r/DEV_TEST/debug/com/che168/CarMaid/R.java
[DEBUG] [app_inc_invoker] app new R.java path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/app/build/freeline/app/backup/com/che168/CarMaid/R.java
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] []
[DEBUG] [app_inc_invoker] app project has no change, need not go ahead
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] server result is -1
[DEBUG] [sync_client] server result is -1
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41132
[DEBUG] [connect_device_task] connect_device_task finish in 126.5s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 126.5s
[DEBUG] [sync_client] app has no need to sync inc res pack.
[DEBUG] [sync_client] AHkit has no need to sync inc res pack.
[DEBUG] [sync_client] no incremental dexes in .
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.0s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 126.5s
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 126.5s
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 126.55s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 126.6s
[DEBUG] Total time: 126.7s
[DEBUG] --------------------------------------------------------

**Comment by deshuaizhu** [comment]
#518 的方法我试了，还是老样子。。。

**Comment by lomanyong** [comment]
@deshuaizhu 换一根 usb 线看看...

**Comment by Zihuatanejo50** [comment]
@deshuaizhu 可以试试adb kill-server，adb start-server试一下，有时候感觉是adb冲突
