### ISSUE TITLE
通过Android Studio 插件接入不成功

### ISSUE THREAD

**Issue by shiyuexun** [alibaba/freeline#529]
第一次一个项目成功了，然后新打开一个项目，点击freeline：

Freeline Plugin: Execute task initFreeline and download freeline dependencies...

**Comment by lomanyong** [comment]
@shiyuexun task不还在执行吗。。。没有错误日志。。。

**Comment by shiyuexun** [comment]
中午到现在了。。。这个要翻墙吗？

**Comment by lomanyong** [comment]
@shiyuexun 你可以自己手动执行一下`gradlew initFreeline -Pmirror`，估计是卡在下载 gradle.zip 文件了。这个你可以自己手动处理的...你以前应该是很少手动执行过 gradle 命令...

**Comment by shiyuexun** [comment]
我好像第一次提issues...    我手动执行了，已经没问题了，然后我又打开个项目，又试了试，还是需要手动执行，所以我来提个issues。gradlew initFreeline -Pmirror这个命令我不知道是下载gradle的，以为是bug，乌龙。。。gradle我还没学多少，没手动敲过打包以外的命令。。。第一次和大神对话，很激动的

**Comment by shiyuexun** [comment]
@lomanyong  我也在杭州，交个朋友？或者收个弟子？

**Comment by lomanyong** [comment]
@shiyuexun `gradlew initFreeline -Pmirror`这个命令是用来下载 freeline 依赖的，但是在执行的过程中可能还会下载 gradle.zip，视你本地的环境而定。具体的信息可以看 freeline 的使用说明文档：https://www.freelinebuild.com/docs/zh_cn/
