### ISSUE TITLE
执行 Python freeline.py报错

### ISSUE THREAD

**Issue by AndrWang** [alibaba/freeline#53]
Traceback (most recent call last):
  File "freeline.py", line 5, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "xxx/freeline/freeline_core/__init__.py", line 1, in <module>
    import build_commands
ImportError: No module named 'build_commands'

**Comment by lomanyong** [comment]
@AndrWang python版本是？

**Comment by AndrWang** [comment]
3.5.1

**Comment by AndrWang** [comment]
我一个个的试了试,2.7是可以的 @lomanyong

**Comment by lomanyong** [comment]
@AndrWang 好的，freelien暂时还不支持Python 3+，后面会支持起来
