### ISSUE TITLE
增量编译不自动安装，报错

### ISSUE THREAD

**Issue by jingzhishang** [alibaba/freeline#533]

**Comment by lomanyong** [comment]
@jingzhishang 请给出相关的日志以及操作步骤

**Comment by jingzhishang** [comment]
javac: 无效的标记:  C:\android\android  workspace\xxx\app\build\freeline\app\classes;                                                        
用法: javac <options> <source files>                                                                                                          
-help 用于列出可能的选项

**Comment by lomanyong** [comment]
@jingzhishang 这不是关键日志...没办法分析问题...如果给不了请贴全日志...

**Comment by jingzhishang** [comment]
我增量编译的时候build下面的class文件夹是空的， 是否和我没设置classpath环境变量有关啊，以前一直没设置，

**Comment by lomanyong** [comment]
@jingzhishang `android workspace`这个目录名是包含空格吗？如果是的话，麻烦将路径改为非包含空格的路径...

**Comment by jingzhishang** [comment]
@lomanyong 好的，我试下
