### ISSUE TITLE
read_project_info任务执行非常慢

### ISSUE THREAD

**Issue by YouZiQian** [alibaba/freeline#535]
read_project_info通常需要执行20秒以上是为啥 并不是第一次运行freeline
![image](https://cloud.githubusercontent.com/assets/8923844/21476894/db208030-cb77-11e6-99d5-3e385b69b111.png)

**Comment by lomanyong** [comment]
@YouZiQian 貌似你贴出来的日志里没有那么久？通常这个 task 只在全量编译的时候执行，单纯的增量编译的话是不会执行的，应该没有特别大的影响。

**Comment by YouZiQian** [comment]
但是在我这里每次都会有这个task

**Comment by lomanyong** [comment]
@YouZiQian 意思是你每次都执行了全量编译？你可以手动执行一下`python freeline.py -d`然后贴出一下执行日志看下吗？

**Comment by YouZiQian** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] collecting project info, please wait a while...
[DEBUG] find app has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1482735330.0,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-assets/apktime
[DEBUG] [sync_client] your local sync value is: 872655
[DEBUG] [sync_client] your local uuid value is: 872655
[DEBUG] [app_inc_invoker] app old R.java path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/generated/source/r/debug/com/chonghot/tocar/R.java
[DEBUG] [app_inc_invoker] app new R.java path: None
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] []
[DEBUG] [app_inc_invoker] app project has no change, need not go ahead
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s

**Comment by YouZiQian** [comment]
`[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] collecting project info, please wait a while...
[DEBUG] find app has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1482735330.0,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-assets/apktime
[DEBUG] [sync_client] your local sync value is: 872655
[DEBUG] [sync_client] your local uuid value is: 872655
[DEBUG] [app_inc_invoker] app old R.java path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/generated/source/r/debug/com/chonghot/tocar/R.java
[DEBUG] [app_inc_invoker] app new R.java path: None
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] []
[DEBUG] [app_inc_invoker] app project has no change, need not go ahead
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
`

**Comment by YouZiQian** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] collecting project info, please wait a while...
[DEBUG] find app has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1482735330.0,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-assets/apktime
[DEBUG] [sync_client] your local sync value is: 872655
[DEBUG] [sync_client] your local uuid value is: 872655
[DEBUG] [app_inc_invoker] app old R.java path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/generated/source/r/debug/com/chonghot/tocar/R.java
[DEBUG] [app_inc_invoker] app new R.java path: None
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] []
[DEBUG] [app_inc_invoker] app project has no change, need not go ahead
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s

**Comment by lomanyong** [comment]
@YouZiQian 你贴出的日志里没有执行那个任务呀....

**Comment by YouZiQian** [comment]
但是每次我增量编译都会提示 some important file missing,a clean build ......

**Comment by lomanyong** [comment]
@YouZiQian 你贴出的两份日志看着都没有这个提示额...

提示你说的这句通常是第一次安装的时候会出现，你的工程的`${main_module}/build/freeline/stat_cache.json`这个文件丢失了...

你可以在一次编译结束后查看一下这个文件是否存在

**Comment by YouZiQian** [comment]
![image](https://cloud.githubusercontent.com/assets/8923844/21477489/5a63da9a-cb7d-11e6-86d8-2e47aa656255.png)

**Comment by YouZiQian** [comment]
这个文件是存在的
![image](https://cloud.githubusercontent.com/assets/8923844/21477504/7a2a24c4-cb7d-11e6-9135-757d217a97e8.png)

**Comment by lomanyong** [comment]
@YouZiQian 执行`python freeline.py -d`看下每次执行的结果都是什么，看下是否会走增量编译流程，还是每次都是全量编译的流程...文件存在的话不会有这样的报错的...
