### ISSUE TITLE
在layout中新增 一个TextView 并加了一个id，在java中调用时，增编编译时报错

### ISSUE THREAD

**Issue by cokui** [alibaba/freeline#537]
![image](https://cloud.githubusercontent.com/assets/10404085/21481027/1a08798a-cb9e-11e6-9f88-dcd4af32626d.png)

**Comment by cokui** [comment]
![image](https://cloud.githubusercontent.com/assets/10404085/21481093/a9e94426-cb9e-11e6-838a-c7d8a77f87a9.png)

**Comment by cokui** [comment]
![image](https://cloud.githubusercontent.com/assets/10404085/21481115/ec8bf166-cb9e-11e6-82b5-834d563109f1.png)

**Comment by cokui** [comment]
我已经试了几次了，每次都会报这个错

**Comment by lomanyong** [comment]
@cokui 问题出在下图红圈处的 error 需要处理一下：

![](http://ww4.sinaimg.cn/large/006y8lVagw1fb4g6txm0oj311g0o8jxz.jpg)

**Comment by amyliu1062** [comment]
![image](https://cloud.githubusercontent.com/assets/6679526/21495550/2c41d2bc-cc53-11e6-8323-dc25e0400f4b.png)
![image](https://cloud.githubusercontent.com/assets/6679526/21495544/2343a19a-cc53-11e6-98da-32eea23f1e0f.png)

我也是加了一个id, 编译报错

**Comment by lomanyong** [comment]
@amyliu1062 你需要贴出这部分更详细的日志...

**Comment by amyliu1062** [comment]
![image](https://cloud.githubusercontent.com/assets/6679526/21495601/8bfa5620-cc53-11e6-84e4-f56a493f17c3.png)

@lomanyong

**Comment by lomanyong** [comment]
@cokui @amyliu1062 

用下面提供的 FreelineAapt 文件替换你`freeline/release-tools`下的同名文件，并执行`chmod +x FreelineAapt`赋予可执行权限，然后重新编译看看是否有解决你的问题。

[FreelineAapt.zip](https://github.com/alibaba/freeline/files/673794/FreelineAapt.zip)

**Comment by amyliu1062** [comment]
![image](https://cloud.githubusercontent.com/assets/6679526/21495735/58469446-cc54-11e6-8e09-436392305a46.png)

@lomanyong

**Comment by lomanyong** [comment]
@amyliu1062 clean 一下再重新编译呢？每次新增 id 还都是出现同样的错误？

**Comment by cokui** [comment]
把上面出现错误的资源文件删除了，就没这个错误了。我也很奇怪，之前工程跑起来都是好好的。

**Comment by cokui** [comment]
@lomanyong

**Comment by amyliu1062** [comment]
![image](https://cloud.githubusercontent.com/assets/6679526/21561477/f1984ed2-cea7-11e6-9771-0d590c9b7aad.png)
经常出现上面的错误。重命名或者新加一个ID都有可能报这样的错误。@lomanyong

**Comment by amyliu1062** [comment]
再具体一点的图：
![image](https://cloud.githubusercontent.com/assets/6679526/21561601/82cd442e-cea9-11e6-8eed-1cfa30a8c98d.png)

**Comment by lomanyong** [comment]
@amyliu1062 替换了我给的那个 aapt 文件了吗？我上面的回复里有说到的

**Comment by AllenCoder** [comment]
同样的错误，新增资源id ,增量编译失败，然后只能再次重新全编译，非常耗时

**Comment by lomanyong** [comment]
@AllenCoder 出现失败的时候，请给出具体的操作与日志，不然无法解决任何问题，谢谢。

**Comment by lomanyong** [comment]
0.8.5 将会 fix
