### ISSUE TITLE
[+][connect_device_task] running... in 135.1s

### ISSUE THREAD

**Issue by deshuaizhu** [alibaba/freeline#538]
这个任务执行的时间特别久。。。始终没有解决。。。太闹心了，还不是必现的，但是我经常遇到
![image](https://cloud.githubusercontent.com/assets/7960936/21488816/c50c4386-cc1e-11e6-8aa9-f8d44b492f24.png)

**Comment by lomanyong** [comment]
@deshuaizhu 手动执行一下`adb`命令，看下 adb 是否冲突了。

**Comment by deshuaizhu** [comment]
![image](https://cloud.githubusercontent.com/assets/7960936/21489010/2ffc080a-cc21-11e6-9552-946448ef0a58.png)

**Comment by lomanyong** [comment]
@deshuaizhu 在 AS 的 terminal 里执行`python freeline.py -d`输出一下调试信息看看..

**Comment by deshuaizhu** [comment]
zhudeshuaideMacBook-Pro:CarMaid zhudeshuai$ python freeline.py  
[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.3s
[-][gradle_aapt_task] finished. in 0.0s
[-][AHkit] finished. in 0.0s
[-][app] finished. in 1.1s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] finished. in 0.1s
[-][clean_cache_task] finished. in 0.0s
zhudeshuaideMacBook-Pro:CarMaid zhudeshuai$ python freeline.py  -d
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] find app has 0 java files modified.
[DEBUG] find AHkit has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1482804789.0,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "AHkit": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [AHkit]
[DEBUG] [task_engine] depth: 3, task: [app]
[DEBUG] [task_engine] depth: 4, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 6, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 7, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 8, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [sync_client] apktime path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/app/build/freeline/freeline-assets/apktime
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [AHkit] AHkit start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 729432
[DEBUG] [sync_client] your local uuid value is: 729428
[DEBUG] [AHkit_inc_invoker] AHkit old R.java path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/AHkit/build/generated/source/r/androidTest/debug/com/autohome/ahkit/R.java
[DEBUG] [AHkit_inc_invoker] AHkit new R.java path: None
[DEBUG] [AHkit_inc_invoker] src changed files:
[DEBUG] [AHkit_inc_invoker] []
[DEBUG] [AHkit_inc_invoker] AHkit project has no change, need not go ahead
[DEBUG] [AHkit_inc_invoker] AHkit code only change R.java, need not go ahead
[DEBUG] [AHkit_inc_javac_compile] no need to execute
[DEBUG] [AHkit_inc_dex_compile] no need to execute
[DEBUG] [AHkit] AHkit finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [app_inc_invoker] app old R.java path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/app/build/generated/source/r/DEV_TEST/debug/com/che168/CarMaid/R.java
[DEBUG] [app_inc_invoker] app new R.java path: /Users/zhudeshuai/Desktop/WorkSpaceForGit/CarMaid/app/build/freeline/app/backup/com/che168/CarMaid/R.java
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] []
[DEBUG] [app_inc_invoker] app project has no change, need not go ahead
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s

**Comment by deshuaizhu** [comment]
这是全部的

**Comment by lomanyong** [comment]
@deshuaizhu 这个应该是数据线或者目标设备的问题吧，可以换一下看看吗？

**Comment by deshuaizhu** [comment]
数据线换了，还是会有这种问题，主要这个问题不是必现的。还有就是默认的运行方式是正常能跑起来的

**Comment by lomanyong** [comment]
@deshuaizhu 换个设备呢？

这个情况主要跟你本地的情况关联比较大...
