### ISSUE TITLE
采用dataBinding，编译报错 

### ISSUE THREAD

**Issue by lovezt** [alibaba/freeline#54]
我在项目中采用了dataBinding ,
builg.gradle中配置了
dataBinding{
        enabled true
    }
布局文件如下:
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <data>
        <import type="android.view.View"/>
        <import type="android.graphics.Color"/>
        <import type="com.qihoo.jia.presenter.MyItemClickPresenter"/>
        <variable
            name="title"
            type="String"/>
        <variable
            name="titleColor"
            type="String"/>
        <variable
            name="presenter"
            type="MyItemClickPresenter"/>
        <variable
            name="action"
            type="Integer"/>
        <variable
            name="visibility"
            type="Boolean"/>
    </data>

    <com.jia.ui.widget.MaterialRippleLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:mrl_rippleAlpha="0.2"
        app:mrl_rippleColor="#585858"
        app:mrl_rippleDelayClick="false"
        app:mrl_rippleHover="true"
        app:mrl_rippleOverlay="true">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="@dimen/common_item_height"
            android:background="@drawable/clickable_item_bg_selector"
            android:onClick="@{ () -> presenter.onItemClick(action) }"
            android:visibility='@{ visibility != null ? (visibility ? View.VISIBLE : View.GONE) : View.VISIBLE }'>

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="14.66dp"
                android:layout_marginRight="14.66dp"
                android:layout_gravity="center_vertical"
                android:textColor='@{ Color.parseColor(titleColor ?? "#0d0015") }'
                android:textSize="14dp"
                android:text="@{title, default=title}"/>

            <include layout="@layout/halving_line2"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom"/>

        </FrameLayout>

    </com.jia.ui.widget.MaterialRippleLayout>

</layout>

采用freeline编译，报错，说是支援找不到，我想问下，目前是不是不支持dataBinding

**Comment by lomanyong** [comment]
@lovezt 是的，暂时还不支持databinding，后面的版本应该会支持上。

**Comment by yangwuan55** [comment]
@lomanyong 大概什么时候支持databinding？这个需求量应该很大啊。
