### ISSUE TITLE
使用DesignSupport25.1.0增量更新java文件OK,增量编译资源文件(string跟color)失败，已经在freeline中添加DSL( extraResourceDependencyPaths = ['/src/main/res'])

### ISSUE THREAD

**Issue by wuster2015** [alibaba/freeline#542]
-resoucres-md5-cache-path = F:\TaJia\app\build\freeline\arsc_cache.dat
warning: overwriting 'F:\TaJia\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.8.4\assets\apktime' with 'F:\TaJia\app\build\freeline\freeline-assets\apktime'
F:\TaJia\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1517: error: Public symbol drawable/avd_hide_password_1 declared here is not defined.
F:\TaJia\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1519: error: Public symbol drawable/avd_hide_password_2 declared here is not defined.
F:\TaJia\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1521: error: Public symbol drawable/avd_hide_password_3 declared here is not defined.
F:\TaJia\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1523: error: Public symbol drawable/avd_show_password_1 declared here is not defined.
F:\TaJia\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1525: error: Public symbol drawable/avd_show_password_2 declared here is not defined.
F:\TaJia\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1527: error: Public symbol drawable/avd_show_password_3 declared here is not defined.

**Comment by lomanyong** [comment]
@wuster2015 已知的兼容性问题，请查看 issue #539 。将会在近期修复这个问题。
