### ISSUE TITLE
安装成功了，但是无法打开应用

### ISSUE THREAD

**Issue by chenyuantao** [alibaba/freeline#551]
应用是成功安装上了的，但是无法自动启动，手动启动也不行。

[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService
[DEBUG] [sync_client] try to connect device 1 times...
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 2 times...
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 3 times...
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 4 times...
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 5 times...
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 6 times...
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 7 times...
[DEBUG] [sync_client] wake up Service: /Users/Tao/Library/Android/sdk/platform-tools/adb shell am startservice -n 包名/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 8.4s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 8.4s

**Comment by chenyuantao** [comment]
@lomanyong

**Comment by chenyuantao** [comment]
试过换设备，试过删除重装，每次都执行的全量编译，都不行。

**Comment by lomanyong** [comment]
@chenyuantao 是因为包名不对导致的吗？

**Comment by chenyuantao** [comment]
@lomanyong 日志里的包名是正确的

**Comment by lomanyong** [comment]
@chenyuantao 我看你截取的部分日志，最后应该是连接成功了呀。你可以看下更完整的日志，后面有 adb 命令，如果包名正确的话，可以看下 launcher activity 是否也正确。

**Comment by chenyuantao** [comment]
@lomanyong 
后续的日志没有执行adb命令

[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 2.0s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 2.0s
[DEBUG] [sync_client] vshow has no need to sync inc res pack.
[DEBUG] [sync_client] PullToRefresh has no need to sync inc res pack.
[DEBUG] [sync_client] no incremental dexes in /Users/Tao/Git/MyApp/build/freeline/freeline-dexes
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.0s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 2.0s
[DEBUG] [clean_cache_task] remove cache: /Users/Tao/Git/MyApp/build/freeline/vshow/respack/vshow.rflag
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 2.1s
[DEBUG] [update_stat_task] update_stat_task finish in 0.1s

**Comment by lomanyong** [comment]
@chenyuantao 执行`python freeline.py -f -d`，你截得这段日志基本是空跑....

**Comment by chenyuantao** [comment]
@lomanyong 这是执行`python freeline.py -f -d`后的完整日志：
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=True, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /Users/Tao/Git/demo/hello/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 525283
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save hello module file stat
[DEBUG] [generate_file_stat_task] save network module file stat
[DEBUG] [generate_file_stat_task] save database module file stat
[DEBUG] [generate_file_stat_task] save PullToRefresh module file stat
[DEBUG] [generate_file_stat_task] save imageloader module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.1s
[DEBUG] [read_project_info_task] read_project_info_task finish in 2.8s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 2.8s
[DEBUG] [gradle_clean_build_task] ./gradlew :hello:assembleMookTestDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 37.6s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 40.4s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 40.4s
[DEBUG] [install_apk_task] check device' connection...
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/freeline_annotation_info.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/jar_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/public_keeper.xml
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/stat_cache.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/imageloader/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/imageloader/resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/freeline-assets/apktime
[DEBUG] [install_apk_task] start to install apk to device: /Users/Tao/Library/Android/sdk/platform-tools/adb install -r /Users/Tao/Git/demo/hello/build/outputs/apk/hello-MookTest-debug.apk
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/network/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/network/resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/database/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/database/resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/PullToRefresh/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/PullToRefresh/resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/hello/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/Tao/Git/demo/hello/build/freeline/hello/resources_dependencies.json
[DEBUG] [clean_all_cache_task] clean_all_cache_task finish in 0.3s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 40.5s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 40.6s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.3s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 37.9s
[DEBUG] [append_file_stat_task] generate_file_stat_task in append mode
[DEBUG] [generate_apt_files_task] start generate apt files stat...
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] [append_file_stat_task] no new modules found.
[DEBUG] [append_file_stat_task] append_file_stat_task finish in 0.0s
[DEBUG] [build_base_resource_task] /Users/Tao/Git/demo/hello/build/freeline/public_keeper.xml exists, move to dst: /Users/Tao/Git/demo/hello/build/freeline/hello/backup/res/values/freeline_id_keeper_public.xml
[DEBUG] [generate_project_info_task] generate_project_info_task finish in 0.0s
[DEBUG] [generate_apt_files_task] save apt files cache to path: /Users/Tao/Git/demo/hello/build/freeline/apt_files_stat_cache.json
[DEBUG] [generate_apt_files_task] generate_apt_files_task finish in 0.0s
[DEBUG] [build_base_resource_task] generating ids.xml from public.xml...
[DEBUG] [databinding_processor] java -jar freeline/release-tools/databinding-cli8.jar -p com.mook.hello.android -i /Users/Tao/Git/demo/hello/res -o /Users/Tao/Git/demo/hello/build/freeline/freeline-databinding/hello/b2cce51e9fe87b4c6b33029c6aa143b9/res -d /Users/Tao/Git/demo/hello/build/freeline/freeline-databinding/merged_layoutinfo -c /Users/Tao/Git/demo/hello/build/freeline/freeline-databinding/hello/b2cce51e9fe87b4c6b33029c6aa143b9/java -l false -v 9 -s /Users/Tao/Library/Android/sdk
[DEBUG] [databinding_processor] process databinding resources success: /Users/Tao/Git/demo/hello/res
[DEBUG] [tracing] process_databinding_resources: 3262.09878922ms
[DEBUG] replace /Users/Tao/Git/demo/hello/res with target resource dir: /Users/Tao/Git/demo/hello/build/freeline/freeline-databinding/hello/b2cce51e9fe87b4c6b33029c6aa143b9/res
[DEBUG] [build_base_resource_task] aapt exec: freeline/release-tools/FreelineAapt package -f -I /Users/Tao/Library/Android/sdk/platforms/android-23/android.jar -M /Users/Tao/Git/demo/hello/build/intermediates/manifests/full/MookTest/debug/AndroidManifest.xml -S /Users/Tao/Git/demo/hello/build/freeline/freeline-databinding/hello/b2cce51e9fe87b4c6b33029c6aa143b9/res -S /Users/Tao/Git/demo/PullToRefresh/res -S /Users/Tao/Git/demo/database/res -S /Users/Tao/Git/demo/PullToRefresh/build/generated/res/resValues/release -S /Users/Tao/Git/demo/network/build/generated/res/rs/release -S /Users/Tao/Git/demo/hello/build/generated/res/rs/MookTest/debug -S /Users/Tao/Git/demo/PullToRefresh/build/generated/res/rs/release -S /Users/Tao/Git/demo/imageloader/build/generated/res/rs/release -S /Users/Tao/Git/demo/database/build/generated/res/rs/release -S /Users/Tao/Git/demo/database/build/generated/res/resValues/release -S /Users/Tao/Git/demo/imageloader/build/generated/res/resValues/release -S /Users/Tao/Git/demo/network/build/generated/res/resValues/release -S /Users/Tao/Git/demo/hello/build/generated/res/resValues/MookTest/debug -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.4/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.databinding/library/1.2.1/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.databinding/adapters/1.2.1/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.bugtags.library/bugtags-lib/2.1.3/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.mook.mobsecurity/mobsecLib/3.0.4/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/epaySdk_v3.1.2_20160729/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.github.chrisbanes/PhotoView/1.3.0/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.shizhefei/ViewPagerIndicator/1.1.3/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/24.0.0/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.0.0/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.0.0/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/24.0.0/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/design/24.0.0/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/pl.droidsonroids.gif/android-gif-drawable/1.1.17/res -S /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/Tao/Git/demo/hello/build/freeline/hello/backup/res -A /Users/Tao/Git/demo/hello/build/freeline/freeline-assets -A /Users/Tao/Git/demo/hello/assets -A /Users/Tao/Git/demo/imageloader/build/generated/assets/shaders/release -A /Users/Tao/Git/demo/PullToRefresh/build/generated/assets/shaders/release -A /Users/Tao/Git/demo/network/build/generated/assets/shaders/release -A /Users/Tao/Git/demo/hello/build/generated/assets/shaders/MookTest/debug -A /Users/Tao/Git/demo/database/build/generated/assets/shaders/release -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.4/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.databinding/library/1.2.1/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.databinding/adapters/1.2.1/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.bugtags.library/bugtags-lib/2.1.3/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.mook.mobsecurity/mobsecLib/3.0.4/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/epaySdk_v3.1.2_20160729/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.github.chrisbanes/PhotoView/1.3.0/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.shizhefei/ViewPagerIndicator/1.1.3/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/24.0.0/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.0.0/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.0.0/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/24.0.0/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/design/24.0.0/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/pl.droidsonroids.gif/android-gif-drawable/1.1.17/assets -A /Users/Tao/Git/demo/hello/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/assets -m -J /Users/Tao/Git/demo/hello/build/freeline/hello/backup --auto-add-overlay -F /Users/Tao/Git/demo/hello/build/freeline/base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path /Users/Tao/Git/demo/hello/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[DEBUG] [build_base_resource_task] generate base resource success: /Users/Tao/Git/demo/hello/build/freeline/base-res.so
[DEBUG] [tracing] build_base_resource_aapt_task: 7040.16590118ms
[DEBUG] [build_base_resource_task] build_base_resource_task finish in 10.4s
[DEBUG] [install_apk_task] start to launch application com.mook.hello.android/com.mook.hello.android.ui.activity.SplashActivity
[DEBUG] [install_apk_task] /Users/Tao/Library/Android/sdk/platform-tools/adb shell am start -n com.mook.hello.android/com.mook.hello.android.ui.activity.SplashActivity
[DEBUG] [install_apk_task] install_apk_task finish in 15.0s
[DEBUG] [task_engine] it takes task engine 55.33s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 55.3s
[DEBUG] Total time: 55.5s
[DEBUG] --------------------------------------------------------

安装成功了，启动的Activity也对的上，就是无法启动。

**Comment by lomanyong** [comment]
@chenyuantao 手动执行` /Users/Tao/Library/Android/sdk/platform-tools/adb shell am start -n com.mook.hello.android/com.mook.hello.android.ui.activity.SplashActivity`也无法启动？

**Comment by chenyuantao** [comment]
@lomanyong 手动执行start，打印了这一行日志，但是手机上没反应
Starting: Intent { cmp=com.mook.hello.android/com.mook.hello.android.ui.activity.SplashActivity }

**Comment by chenyuantao** [comment]
@lomanyong 我们的项目是从eclipse转过来的，目录结构不是Android Studio新建项目时的那种，所以在gradle中设置了sourceSets，将目录结果按照gradle的标准配置一下。
```
android {
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
}
```
不知道这个目录结构是否会有影响？

**Comment by lomanyong** [comment]
@chenyuantao eclipse 转换过来的工程可能会有潜在的目录结构问题。不过目前的问题是你的 app 如果 package 跟 launcher activity 都没问题的话...执行 adb 命令应该没理由启动不了才对...
