### ISSUE TITLE
安装第一次能编  第二次就报错误

### ISSUE THREAD

**Issue by ccwls3290** [alibaba/freeline#552]
[dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[dispatcher] *** Android Gradle Plugin Version: 2.2.2
[dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[dispatcher] *** Freeline Python Version: v0.8.4

[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\20161225\freeline_core\dispatcher.py", line 96, in _exec_command
    command.execute()
  File "D:\20161225\freeline_core\freeline_build.py", line 21, in execute
    file_changed_dict = self._scan_command.execute()
  File "D:\20161225\freeline_core\gradle_tools.py", line 45, in execute
    build_info = self._get_build_info()
  File "D:\20161225\freeline_core\gradle_tools.py", line 71, in _get_build_info
    is_root_config_changed = os.path.getmtime(os.path.join('settings.gradle')) > last_clean_build_time
  File "C:\Python27\lib\genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 2] : 'settings.gradle'

[ERROR] --------------------------------------------------------
[ERROR] 
[ERROR] --------------------------------------------------------

**Comment by lomanyong** [comment]
@ccwls3290 目录下没有`settings.gradle`这个文件？

**Comment by ccwls3290** [comment]
没有 这个工程是eclipse转过来的

**Comment by ccwls3290** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@ccwls3290 新建一个空的settings.gradle文件，应该就可以了...
