### ISSUE TITLE
有两个主Module的项目，只能在一个Module中使用

### ISSUE THREAD

**Issue by huclengyue** [alibaba/freeline#554]
项目中有两个主Module，在其中一个Module中使用了freeline后另一个Module无法使用。
报错：
```
Error:(4, 0) Cannot add task ':initFreeline' as a task with that name already exists.
```

**Comment by lomanyong** [comment]
@huclengyue 必然...要在另一个module使用的话，需要将其中一个module的`apply plugin: "com.antfortune.freeline"`先注释掉...
