### ISSUE TITLE
全量编译可以进行，增量编译报错

### ISSUE THREAD

**Issue by sunshinehu** [alibaba/freeline#561]
[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.7s
[DEBUG] Task engine running time: 0.4s
[DEBUG] Total time: 1.1s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@sunshinehu 前面应该还有具体的报错日志。。

**Comment by sunshinehu** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] [scan_changed_files_command] find C:\Projects\Branches\v3.5.2\ProjectName\src\com\ProjectName\message\MessageImageActivity.java has modificati
on.
[DEBUG] find ProjectName has 1 java files modified.
[DEBUG] find ProjectNameSDK has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1483424053.4994328,
        "is_root_config_changed": false
    },
    "projects": {
        "ProjectName": {
            "src": [
                "C:\\Projects\\Branches\\v3.5.2\\ProjectName\\src\\com\\ProjectName\\message\\MessageImageActivity.java"
            ],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "ProjectNameSDK": {
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [ProjectNameSDK]
[DEBUG] [task_engine] depth: 3, task: [ProjectName]
[DEBUG] [task_engine] depth: 4, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 6, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 7, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 8, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
用法: javac <options> <source files>                                                                                                         
-help 用于列出可能的选项                                                                                                                     

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.8s
[DEBUG] Task engine running time: 0.4s
[DEBUG] Total time: 1.2s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@sunshinehu 请将`java_home`配置在一个不含有空格的路径上...

**Comment by sunshinehu** [comment]
并没有空格啊

**Comment by sunshinehu** [comment]
我的环境变量中JAVA_HOME是C:\Development\jdk

**Comment by lomanyong** [comment]
@sunshinehu 工程路径有含有空格的地方吗？日志里应该会有一个完整的javac命令...你可以看下...

**Comment by sunshinehu** [comment]
的确可以用了，谢谢啦
