### ISSUE TITLE
我发现了中文文档中一个错别字

### ISSUE THREAD

**Issue by a354425558** [alibaba/freeline#562]
Gradle Task: initFreeline

主要用于下载 freeline 的二进制依赖（包括 python 文件等）和生成工程描述文件。

在 build.gradle 中应用了 freeline gradle 插件之后，initFreeline这个任务会被添加到 Gradle 工程的根工程上，可以执行gradlew initFreelien来执行这个任务。

  以上中gradlew initFreelien这个是否是写错？

**Comment by lomanyong** [comment]
@a354425558 没有写错的，Mac/Linux 跟 Windows 下可能会有所不同，已在其他章节有区分，故这里不再特别分开说明

**Comment by a354425558** [comment]
https://www.freelinebuild.com/docs/zh_cn/#%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8
这是你们的链接， 你搜索initFreelien关键字

**Comment by lomanyong** [comment]
@a354425558 soga，刚才理解错了...马上改正。多谢指正。
