### ISSUE TITLE
执行freeline.py 时间跟全量一样，并且第二次执行就报错

### ISSUE THREAD

**Issue by hluguoj** [alibaba/freeline#563]
提示如下：
[INFO] preparing for tasks...
[-][connect_device_task] failed. in 17.8s
[-][gradle_aapt_task] finished. in 19.7s
[-][lzma] failed. in 0s
[-][mem_analyzer] failed. in 0s
[-][base_hook_java_proxy] failed. in 0s
[-][util] failed. in 0s
[-][mem_analyzer_interface] failed. in 0s
[-][base_hook_native_elf] failed. in 0s
[-][base] failed. in 0s
[-][protocol] failed. in 0s
[-][service] failed. in 0s
[-][app] failed. in 0s
[-][android] failed. in 0s
[-][merge_dex_task] failed. in 0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
	Please make sure your application is properly running in your device.
	Check follow steps:
	1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
	2. Make sure there is no network proxy.
	
	More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app com.xx not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.5s
[DEBUG] Task engine running time: 19.7s
[DEBUG] Total time: 20.2s
[DEBUG] --------------------------------------------------------

使用的freeline版本0.8.4，gradle版本2.14.1，gradle tool版本2.1.3，python版本2.7
根据https://github.com/alibaba/freeline/issues/152 验证，版本一致，没有用代理，使用-f全量编译后，随便修改一行代码，第一次执行python freeline.py 时间跟全量编译一样，再修改一行代码，执行 python freeline.py 就报上面的错误

**Comment by lomanyong** [comment]
@hluguoj 会出现这个情况大部分给 issue 152 提到的情况有关，代理也包括 Android Studio 本身开的代理...你也可以重启一下手机试试看，或者换一下手机，多测试看看

**Comment by hluguoj** [comment]
@lomanyong 这个问题已经解决了，应该是我这边的productFlavor填写的问题，我用了已有的productFlavor，但是我们对打包流程进行了改造，插入了很多自定义的task。我新创建了一个productFlavor，使用新创建的productFlavor就没有问题了。谢谢你
