### ISSUE TITLE
freeline编译后无反应

### ISSUE THREAD

**Issue by a354425558** [alibaba/freeline#564]
AndroidStudio run是正常的。然后执行clean后， 开始用python插件按钮run，就出现以下信息：
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 154.9s
[DEBUG] Total time: 155.3s
然后就没屁眼了， 在点python插件的run， 也是一样无任何反应。究竟是为何， 求大神帮忙

**Comment by lomanyong** [comment]
@a354425558 没明白你的描述。。

**Comment by a354425558** [comment]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.

        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app com.cn.android.meixi not found. Please make sure your application is properly running in your device.
拜托了大神

**Comment by lomanyong** [comment]
@a354425558 大部分参考过 #152 后都可以解决了...
