### ISSUE TITLE
请问freeline运行后如何debug？

### ISSUE THREAD

**Issue by strongmanb** [alibaba/freeline#566]

**Comment by lomanyong** [comment]
@strongmanb 参考一下文档：[Freeline文档：如何进行断点调试？](https://www.freelinebuild.com/docs/zh_cn/#%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E6%96%AD%E7%82%B9%E8%B0%83%E8%AF%95%EF%BC%9F)
