### ISSUE TITLE
每次打包只能执行-f模式，非-f模式会报一堆找不到符号的错误

### ISSUE THREAD

**Issue by johnx4** [alibaba/freeline#57]
任意修改一段代码都会出现

**Comment by lomanyong** [comment]
@johnx4 希望能够贴一下日志，以便分析问题

**Comment by johnx4** [comment]
@lomanyong 去掉混淆后发现OK了，请问什么时候能支持混淆

**Comment by lomanyong** [comment]
@johnx4 目前暂时没有在debug包中支持混淆的计划，如果有什么特殊的需求的话，可以考虑在后续版本迭代中加入支持的。
