### ISSUE TITLE
0.8.4版本增量更新错误 incremental res build failed

### ISSUE THREAD

**Issue by scdqs** [alibaba/freeline#570]
![image](https://cloud.githubusercontent.com/assets/5986625/21668661/ed8c0022-d33e-11e6-8fa3-ee671b91f72a.png)

第一次全量编译没有问题，然后修改了一下布局（就改了一下高度）然后增量更新就报错了。
查了一下我的工程资源中不存在这个资源。这个id不知道怎么生成的，clean和rebuild后依然有这个问题。

**Comment by lomanyong** [comment]
@scdqs 已知问题，参考 #539 。我一会会先放出一个 Mac 可用的版本...可以先用上...
