### ISSUE TITLE
打包资源出错 

### ISSUE THREAD

**Issue by d342784178** [alibaba/freeline#578]
/Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/freeline-databinding/app/301c86d2a16087c1ee2d5316e3f9c209/res/values/styles.xml:24: error: Error: No resource found that matches the given name: attr 'android:textColor'.

/Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/freeline-databinding/app/301c86d2a16087c1ee2d5316e3f9c209/res/values/styles.xml:25: error: Error: No resource found that matches the given name: attr 'android:textSize'.

build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/mic/android-sdk-macosx/platforms/android-23/android.jar -M /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/freeline-databinding/app/301c86d2a16087c1ee2d5316e3f9c209/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/generated/res/resValues/debug -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/generated/res/rs/debug -S /Users/mic/AndroidStudioProjects/MyApplication/PinterestLikeAdapterView/src/main/res -S /Users/mic/AndroidStudioProjects/MyApplication/pulltorefresh/res -S /Users/mic/AndroidStudioProjects/MyApplication/imageselector/src/main/res -S /Users/mic/AndroidStudioProjects/MyApplication/PinterestLikeAdapterView/build/generated/res/resValues/release -S /Users/mic/AndroidStudioProjects/MyApplication/pulltorefresh/build/generated/res/resValues/release -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/freeline-databinding/DljLibrary/0ff9aee5d88801e997df3339930d55ec/res -S /Users/mic/AndroidStudioProjects/MyApplication/PagerIndicator/res -S /Users/mic/AndroidStudioProjects/MyApplication/pulltorefresh/build/generated/res/rs/release -S /Users/mic/AndroidStudioProjects/MyApplication/PinterestLikeAdapterView/build/generated/res/rs/release -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.4/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/support-v4/23.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.databinding/library/1.2.1/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.databinding/adapters/1.2.1/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.baoyz.swipemenulistview/library/1.3.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.alipay.euler/andfix/0.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/23.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/23.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/cardview-v7/23.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/io.reactivex/rxandroid/1.2.1/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.hwangjr.rxbus/rxbus/1.0.5/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/design/22.2.1/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.jakewharton.rxbinding/rxbinding/0.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.trello/rxlifecycle/0.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.trello/rxlifecycle-components/0.4.0/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res -S /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/app/backup/res -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/freeline-assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/src/main/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/generated/assets/shaders/debug -A /Users/mic/AndroidStudioProjects/MyApplication/pulltorefresh/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.antfortune.freeline/runtime/0.8.4/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/support-v4/23.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.databinding/library/1.2.1/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.databinding/adapters/1.2.1/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.baoyz.swipemenulistview/library/1.3.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.alipay.euler/andfix/0.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/23.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/23.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/cardview-v7/23.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/23.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/io.reactivex/rxandroid/1.2.1/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.hwangjr.rxbus/rxbus/1.0.5/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/design/22.2.1/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.jakewharton.rxbinding/rxbinding/0.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.trello/rxlifecycle/0.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.trello/rxlifecycle-components/0.4.0/assets -A /Users/mic/AndroidStudioProjects/MyApplication/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/assets -m -J /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/app/backup --auto-add-overlay -F /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*

**Comment by lomanyong** [comment]
@d342784178 需要更详细的错误日志.
