### ISSUE TITLE
使用freeline编译的包，会导致socket的信道，读取返回-1

### ISSUE THREAD

**Issue by wswenyue** [alibaba/freeline#579]
服务器端socket表示没有断开信道。
但是客户端socket读取却返回了-1.
如果去掉freeline则是正常的。

**Comment by lomanyong** [comment]
@wswenyue 先参考 #273 改造一下试试看？

**Comment by wswenyue** [comment]
freeline {
    applicationProxy false
}

加了这个貌似解决了

**Comment by wswenyue** [comment]
@lomanyong 能解释一下原因吗？

**Comment by lomanyong** [comment]
@wswenyue 还得加上`FreelineCore.init(this);`在Application里。应该是Freeline自动给你替换Application造成了你应用初始化异常了...

**Comment by wswenyue** [comment]
好的谢谢你.
