### ISSUE TITLE
修改代码后构建报错

### ISSUE THREAD

**Issue by demoface** [alibaba/freeline#58]
[DEBUG] [app_inc_invoker] app old R.java path: D:\studiospace\HiveBox\app\build\
generated\source\r\official\debug\com\fcbox\hivebox\R.java
[DEBUG] [sync_client] your local sync value is: 145000
[DEBUG] [app_inc_invoker] app new R.java path: None
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'D:\\studiospace\\HiveBox\\app\\src\\main\\java\\com
\\fcbox\\hivebox\\HBApplication.java']
[DEBUG] [app_inc_javac_compile] start to execute javac command...
[DEBUG] [app_inc_invoker] avoid windows unicode error for D:\studiospace\HiveBox
\app\build\freeline\app\backup\com\fcbox\hivebox\R.java
[DEBUG] [app] app finish in 0.1s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.1s
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 1.2s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 1.2s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 1.2s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 1.2s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 1.25s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\studiospace\HiveBox\freeline_core\android_tools.py", line 304, in exe
cute
    self._command.execute()
  File "D:\studiospace\HiveBox\freeline_core\gradle_inc_build.py", line 159, in
execute
    map(lambda command: command.execute(), self.command_list)
  File "D:\studiospace\HiveBox\freeline_core\gradle_inc_build.py", line 159, in
<lambda>
    map(lambda command: command.execute(), self.command_list)
  File "D:\studiospace\HiveBox\freeline_core\gradle_inc_build.py", line 193, in
execute
    self._invoker.append_r_file()
  File "D:\studiospace\HiveBox\freeline_core\gradle_inc_build.py", line 378, in
append_r_file
    write_file_content(main_r_path, content)
  File "D:\studiospace\
\HiveBox\freeline_core\utils.py", line 118, in write_file_
content
    with open(target_path, 'w') as fp:
IOError: [Errno 2] No such file or directory: u'D:\\studiospace\\HiveBox\\app\\b
uild\\freeline\\app\\backup\\comfcbox**hivebox**\\R.java'

[ERROR] --------------------------------------------------------
[ERROR] incremental build task failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.4s
[DEBUG] Task engine running time: 1.2s
[DEBUG] Total time: 1.7s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@demoface 这个问题我已经在其他issue中解决了，下个版本就会解决。

你可以修改一下资源，同时修改java，然后再试试看。

**Comment by lomanyong** [comment]
@demoface 还有问题可以加下我们的技术交流群，可以在群里直接提问

![](http://ww3.sinaimg.cn/large/006tKfTcgw1f7bt5m9yrij30ny0zkdgp.jpg)
