### ISSUE TITLE
command 'python' not found

### ISSUE THREAD

**Issue by bluceshang** [alibaba/freeline#580]
Freeline Plugin: command 'python' not found. 

这是为什么，我能查看我的python 
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

可是一直提示找不到python命令，我重启AS，重启电脑还是一直报这个错误。

**Comment by lomanyong** [comment]
@bluceshang Python 需要配置到环境变量中，确认配置了吗？这是本地环境的问题...通常重启 AS 或者电脑都可以搞定。
