### ISSUE TITLE
停在那不动了。

### ISSUE THREAD

**Issue by shizhongyu** [alibaba/freeline#581]
C:\Work\tulipsport\android\client>python freeline.py -f -d
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=True, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.2
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: C:\Work\tulipsport\android\client\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 281000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save appguide module file stat
[DEBUG] [generate_file_stat_task] save map module file stat
[DEBUG] [generate_file_stat_task] save wearlib module file stat
[DEBUG] [generate_file_stat_task] save util module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.7s

**Comment by lomanyong** [comment]
@shizhongyu 手动执行`gradlew initFreeline -Pmirror`，八成卡在下载 gradle.zip 上了...
