### ISSUE TITLE
第二次编译时出错

### ISSUE THREAD

**Issue by yangwuan55** [alibaba/freeline#586]
![image](https://cloud.githubusercontent.com/assets/5218120/21758859/a68ef3a2-d67a-11e6-8ca2-45ce12bf06fe.png)
![image](https://cloud.githubusercontent.com/assets/5218120/21758903/e3c5ab4e-d67a-11e6-8dbc-0dad558d37ab.png)

请问这是什么情况啊。。。每次编译都是这个情况，重新编译才行。

**Comment by lomanyong** [comment]
@yangwuan55 参考 #539
