### ISSUE TITLE
mac构建成功git提交给其它windons环境的同事报错

### ISSUE THREAD

**Issue by lishensan** [alibaba/freeline#59]
<img width="381" alt="qq20160831-0 2x" src="https://cloud.githubusercontent.com/assets/3710982/18120371/cbe81e76-6f91-11e6-9d74-ec13400f9f31.png">

**Comment by lomanyong** [comment]
最后review了一下，还是每个人单独`initFreeline`，或者由windows的同学`initFreeline`后提交git仓库，就可以避免这个问题了。
