### ISSUE TITLE
运行起来并没有那么快啊

### ISSUE THREAD

**Issue by Aplombs** [alibaba/freeline#591]
我的项目大概1.1G左右,之前编译需要5分钟,现在用Freeline还是5分钟,而且没做任何修改的哦!

**Comment by lomanyong** [comment]
@Aplombs 1.1G的项目也不大...麻烦带上日志...不然无法分析问题...

**Comment by Aplombs** [comment]
日志那么多！怎么带上
            在2017年01月09日 17:41，Yong 写道:@Aplombs 1.1G的项目也不大...麻烦带上日志...不然无法分析问题...

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alibaba/freeline","title":"alibaba/freeline","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alibaba/freeline"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lomanyong in #591: @Aplombs 1.1G的项目也不大...麻烦带上日志...不然无法分析问题..."}],"action":{"name":"View Issue","url":"https://github.com/alibaba/freeline/issues/591#issuecomment-271243010"}}}

**Comment by lomanyong** [comment]
@Aplombs 你要是觉得日志太多，执行`python freeline.py -d > freeline_build.log`，把`freeline_build.log`这个文件传上来就行。

**Comment by Aplombs** [comment]
[freeline_build.txt](https://github.com/alibaba/freeline/files/693311/freeline_build.txt)

**Comment by lomanyong** [comment]
@Aplombs 你修改个文件再执行看看...刚才那个就是空跑。。没有什么特别的内容...

**Comment by Aplombs** [comment]
耗时7分48秒 只添加了3行代码
[freeline_build.txt](https://github.com/alibaba/freeline/files/693348/freeline_build.txt)

**Comment by Aplombs** [comment]
为什么空跑就耗时那么长时间呢?正常来说不应该没修过代码应该更快吗?

**Comment by lomanyong** [comment]
@Aplombs 你刚才空跑耗时1s...没有那么多时间...

**Comment by Aplombs** [comment]
我从开始点击按钮开始秒表 到运行到手机 耗时5分左右;那你的计算方式是什么 指的是你们内部计算的时间?

**Comment by lomanyong** [comment]
@Aplombs 你发的日志里的时间：

````
[DEBUG] [task_engine] it takes task engine 0.78s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.5s
[DEBUG] Task engine running time: 0.8s
[DEBUG] Total time: 1.3s
[DEBUG] --------------------------------------------------------
````

只有 1.3s，你可以自己下载日志文件看下...

按理说你执行完那个命令应该也只有 1.3s，你还做了其他额外的操作了吗？

**Comment by Aplombs** [comment]
我不清楚你们日志的时间是怎么算的,这只是日志显示的时间,但是运行编译不关心日志的时间,都是看运行到设备上的那一刻具体用多少时间的
没有做其他任何操作

**Comment by lomanyong** [comment]
@Aplombs 如果你只是执行了`python freeline.py -d > freeline_build.log`这个命令的话，按照你的日志，应该是 1.3s 就执行完了。你说的编译了五分钟，应该是这条命令之外的其他的操作执行的。
