### ISSUE TITLE
自定义资源文件目录，不刷新R文件，报错

### ISSUE THREAD

**Issue by xyzmst** [alibaba/freeline#592]
资源文件，并没有用默认的目录，而是自定义的目录

sourceSets {
        main {
            res.srcDirs = [
                    'src/main/res/layouts/expl',
                    'src/main/res/layouts/photoalbum',
                    'src/main/res/layouts/myfavorities'
         ]
    }
}
这样布局文件修改后，应该是不会刷新布局文件目录，程序会报找不到id
android.content.res.Resources$NotFoundException
请问 我该如何修改

**Comment by lomanyong** [comment]
@xyzmst 到原本的 issue 来讨论吧..
