### ISSUE TITLE
Could not find method freeline() for arguments 

### ISSUE THREAD

**Issue by shizhongyu** [alibaba/freeline#597]
Error:(134, 0) 

- 

1. Could not find method freeline() for arguments 

[build_c8flc486xljmb25rm90s8dkej$_run_closure3$_closure14@6fabad4f] on object of type com.android.build.gradle.AppExtension.
<a href="openFile:C:\MyWork\tulipsport\android\client\app\build.gradle">Open File</a>

**Comment by lomanyong** [comment]
apply plugin "com.antfortune.freeline"

**Comment by shizhongyu** [comment]
apply from: '../base.gradle'
apply plugin: 'com.antfortune.freeline' 我添加这句了。

**Comment by shizhongyu** [comment]
有demo 吗？
git clone git@github.com:alibaba/freeline.git
cd freeline/sample
./gradlew initFreeline
python freeline.py 
我获取代码，它提示我没有权限，太小白了，问的我都不好意思了，我想是不是有demo， 我照着demo整整。

**Comment by aadhk** [comment]
我有相同的問題，解決了嗎？
