### ISSUE TITLE
Freeline增加对AOP的支持

### ISSUE THREAD

**Issue by gdky005** [alibaba/freeline#60]
后面能不能添加 一些 AOP 相关的东西？ 我们只需要在配置文件里面写上需要修改的东西，当在构建的时候，把某部分内容直接替换或者修改

**Comment by TangXiaoLv** [comment]
@gdky005 AOP你得用aspectJ

**Comment by lomanyong** [comment]
@gdky005 最近思考了一下 AOP 的使用场景，经常是需要 hook 整个 app 的许多 class 的，所以不是特别适合使用在 freeline 这样的增量编译工具上。如果需要修改或者新增 aop 的话，最好的方法还是全量编译，这个 issue 就先 close 了。目前来讲，应该还是会暂时不做 AOP 支持了。

**Comment by gdky005** [comment]
@lomanyong  Ok .
