### ISSUE TITLE
新增的drawable加载失败

### ISSUE THREAD

**Issue by TOPWARNING** [alibaba/freeline#601]
- bug还原：
`imageview起初展示某个drawable A，然后res里新增一个drawable B，让该imageview加载并展示drawable B，增量编译之后imageview展示的仍然是drawable A`

**Comment by lomanyong** [comment]
@TOPWARNING 最好能够提供可以复现的sample代码...否则我这里也无法复现的话也没办法修复...

**Comment by liuwons** [comment]
我在`strings.xml`里修改了字符串内容，加载后也不能显示修改

**Comment by lomanyong** [comment]
@liuwons 尽可能能够给出可以复现的工程...否则对解决问题没有什么帮助...
