### ISSUE TITLE
AndroidStudio 2.2.1 全量编译安装apk文件到小米note1时候提示AndroidManifest.xml:2: error: Error parsing XML: unbound prefix

### ISSUE THREAD

**Issue by TangoHanks** [alibaba/freeline#602]
AndroidManifest.xml:2: error: Error parsing XML: unbound prefix

但是，ank可以成功安装，并且增量编译可以生效；

虽然问题不大，但是总觉得有坑，麻烦有人知道的可以分享一下解决方案；

**Comment by lomanyong** [comment]
@TangoHanks 有具体的完整日志吗？
