### ISSUE TITLE
freeline一直停留在 Gradle build task is running, please wait a minute...执行gradlew initFreeline -Pmirror也没有用

### ISSUE THREAD

**Issue by ZJUHeDQ** [alibaba/freeline#604]

**Comment by lomanyong** [comment]
@ZJUHeDQ 卡在下载 gradle.zip 这里了，请查询已有的 issue 再提问，下载速度过慢

**Comment by ZJUHeDQ** [comment]
查阅了其他的issue，执行下面命令后报错
$ gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace
./gradlew.bat: line 1: @if: command not found
./gradlew.bat: line 2: @rem: command not found
./gradlew.bat: line 3: @rem: command not found
./gradlew.bat: line 4: @rem: command not found
./gradlew.bat: line 5: @rem: command not found
./gradlew.bat: line 6: @rem: command not found
./gradlew.bat: line 8: @rem: command not found
./gradlew.bat: line 88: unexpected EOF while looking for matching `"'
./gradlew.bat: line 91: syntax error: unexpected end of file

**Comment by ZJUHeDQ** [comment]
执行了   gradlew assembleDebug -P freelineBuild=true --stacktrace
一直卡在：Building 97% > :app:transformClassesWithDexForDebug
