### ISSUE TITLE
新加一个module后，无法检测到新module导致无法增量编译

### ISSUE THREAD

**Issue by shuifengYu** [alibaba/freeline#605]
我新加了一个[webview] module,但是以下日志没有扫描这个新模块

[INFO] preparing for tasks...
[-][connect_device_task] finished. in 0.1s
[-][gradle_aapt_task] finished. in 0.0s
[-][mupdf] finished. in 0.0s
[-][nimuikit] finished. in 0.0s
[-][materialpickers] finished. in 0.0s
[-][expandablerecyclerview] finished. in 0.0s
[-][tool] finished. in 0.0s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] finished. in 0.0s
[-][clean_cache_task] finished. in 0.0s
[-][update_stat_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@shuifengYu 使用的是 0.8.4 版本吗？可以看下工程目录下的`freeline_project_description`文件是否包含这个新增的目录？

**Comment by shuifengYu** [comment]
都包含了的
----------------------
{
    "android_gradle_plugin_version": "2.1.3",
    "apk_path": "/Users/coder_yu/workspace/platform/tool/build/outputs/apk/tool-debug-3.2.8.apk",
    "auto_dependency": true,
    "build_cache_dir": "/Users/coder_yu/workspace/platform/tool/build/freeline",
    "build_directory": "/Users/coder_yu/workspace/platform/tool/build",
    "build_script": "./gradlew :tool:assembleDebug",
    "build_script_work_directory": "",
    "build_tools_directory": "/Users/coder_yu/Library/Android/sdk/build-tools/23.0.3",
    "build_tools_version": "23.0.3",
    "compile_sdk_directory": "/Users/coder_yu/Library/Android/sdk/platforms/android-23",
    "compile_sdk_version": "android-23",
    "databinding": [
        
    ],
    "databinding_modules": [
        
    ],
    "debug_package": "com.abc360.tool",
    "exclude_dep_res_paths": [
        
    ],
    "extra_dep_res_paths": [
        
    ],
    "freeline_cache_dir": "/Users/coder_yu/workspace/platform",
    "freeline_gradle_plugin_version": "0.8.4",
    "java_home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home",
    "launcher": "com.abc360.tool.activity.SplashActivity",
    "main_assets_directory": [
        "/Users/coder_yu/workspace/platform/tool/src/debug/assets",
        "/Users/coder_yu/workspace/platform/tool/src/main/assets"
    ],
    "main_jniLibs_directory": [
        "/Users/coder_yu/workspace/platform/tool/src/debug/jniLibs",
        "/Users/coder_yu/workspace/platform/tool/libs"
    ],
    "main_jni_directory": [
        "/Users/coder_yu/workspace/platform/tool/src/debug/jni",
        "/Users/coder_yu/workspace/platform/tool/src/main/jni"
    ],
    "main_manifest_path": "/Users/coder_yu/workspace/platform/tool/src/main/AndroidManifest.xml",
    "main_project_dir": "tool",
    "main_project_name": "tool",
    "main_r_path": "/Users/coder_yu/workspace/platform/tool/build/generated/source/r/debug/R.java",
    "main_res_directory": [
        "/Users/coder_yu/workspace/platform/tool/src/debug/res",
        "/Users/coder_yu/workspace/platform/tool/src/main/res"
    ],
    "main_src_directory": [
        "/Users/coder_yu/workspace/platform/tool/src/debug/java",
        "/Users/coder_yu/workspace/platform/tool/src/main/java"
    ],
    "module_dependencies": {
        "expandablerecyclerview": [
            
        ],
        "materialpickers": [
            
        ],
        "mupdf": [
            
        ],
        "nimuikit": [
            
        ],
        "tool": [
            "mupdf",
            "nimuikit",
            "materialpickers",
            "expandablerecyclerview",
            "webview"
        ],
        "webview": [
            
        ]
    },
    "modules": [
        {
            "name": "tool",
            "path": "/Users/coder_yu/workspace/platform/tool"
        },
        {
            "name": "mupdf",
            "path": "/Users/coder_yu/workspace/platform/mupdf"
        },
        {
            "name": "nimuikit",
            "path": "/Users/coder_yu/workspace/platform/nimuikit"
        },
        {
            "name": "materialpickers",
            "path": "/Users/coder_yu/workspace/platform/materialpickers"
        },
        {
            "name": "expandablerecyclerview",
            "path": "/Users/coder_yu/workspace/platform/expandablerecyclerview"
        },
        {
            "name": "webview",
            "path": "/Users/coder_yu/workspace/platform/webview"
        }
    ],
    "package": "com.abc360.tool",
    "product_flavor": "",
    "project_source_sets": {
        "expandablerecyclerview": {
            "main_assets_directory": [
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/release/assets",
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/main/assets"
            ],
            "main_jniLibs_directory": [
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/release/jniLibs",
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/main/jniLibs"
            ],
            "main_jni_directory": [
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/release/jni",
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/main/jni"
            ],
            "main_manifest_path": "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/main/AndroidManifest.xml",
            "main_res_directory": [
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/release/res",
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/main/res"
            ],
            "main_src_directory": [
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/release/java",
                "/Users/coder_yu/workspace/platform/expandablerecyclerview/src/main/java"
            ]
        },
        "materialpickers": {
            "main_assets_directory": [
                "/Users/coder_yu/workspace/platform/materialpickers/src/release/assets",
                "/Users/coder_yu/workspace/platform/materialpickers/src/main/assets"
            ],
            "main_jniLibs_directory": [
                "/Users/coder_yu/workspace/platform/materialpickers/src/release/jniLibs",
                "/Users/coder_yu/workspace/platform/materialpickers/src/main/jniLibs"
            ],
            "main_jni_directory": [
                "/Users/coder_yu/workspace/platform/materialpickers/src/release/jni",
                "/Users/coder_yu/workspace/platform/materialpickers/src/main/jni"
            ],
            "main_manifest_path": "/Users/coder_yu/workspace/platform/materialpickers/src/main/AndroidManifest.xml",
            "main_res_directory": [
                "/Users/coder_yu/workspace/platform/materialpickers/src/release/res",
                "/Users/coder_yu/workspace/platform/materialpickers/src/main/res"
            ],
            "main_src_directory": [
                "/Users/coder_yu/workspace/platform/materialpickers/src/release/java",
                "/Users/coder_yu/workspace/platform/materialpickers/src/main/java"
            ]
        },
        "mupdf": {
            "main_assets_directory": [
                "/Users/coder_yu/workspace/platform/mupdf/src/release/assets",
                "/Users/coder_yu/workspace/platform/mupdf/src/main/assets"
            ],
            "main_jniLibs_directory": [
                "/Users/coder_yu/workspace/platform/mupdf/src/release/jniLibs",
                "/Users/coder_yu/workspace/platform/mupdf/src/main/jniLibs"
            ],
            "main_jni_directory": [
                "/Users/coder_yu/workspace/platform/mupdf/src/release/jni",
                "/Users/coder_yu/workspace/platform/mupdf/src/main/jni"
            ],
            "main_manifest_path": "/Users/coder_yu/workspace/platform/mupdf/src/main/AndroidManifest.xml",
            "main_res_directory": [
                "/Users/coder_yu/workspace/platform/mupdf/src/release/res",
                "/Users/coder_yu/workspace/platform/mupdf/src/main/res"
            ],
            "main_src_directory": [
                "/Users/coder_yu/workspace/platform/mupdf/src/release/java",
                "/Users/coder_yu/workspace/platform/mupdf/src/main/java"
            ]
        },
        "nimuikit": {
            "main_assets_directory": [
                "/Users/coder_yu/workspace/platform/nimuikit/src/release/assets",
                "/Users/coder_yu/workspace/platform/nimuikit/assets"
            ],
            "main_jniLibs_directory": [
                "/Users/coder_yu/workspace/platform/nimuikit/src/release/jniLibs",
                "/Users/coder_yu/workspace/platform/nimuikit/libs",
                "/Users/coder_yu/workspace/platform/nimuikit/libs-sdk"
            ],
            "main_jni_directory": [
                "/Users/coder_yu/workspace/platform/nimuikit/src/release/jni",
                "/Users/coder_yu/workspace/platform/nimuikit/src/main/jni"
            ],
            "main_manifest_path": "/Users/coder_yu/workspace/platform/nimuikit/AndroidManifest.xml",
            "main_res_directory": [
                "/Users/coder_yu/workspace/platform/nimuikit/src/release/res",
                "/Users/coder_yu/workspace/platform/nimuikit/res",
                "/Users/coder_yu/workspace/platform/nimuikit/res-ptr"
            ],
            "main_src_directory": [
                "/Users/coder_yu/workspace/platform/nimuikit/src/release/java",
                "/Users/coder_yu/workspace/platform/nimuikit/src"
            ]
        },
        "tool": {
            "main_assets_directory": [
                "/Users/coder_yu/workspace/platform/tool/src/debug/assets",
                "/Users/coder_yu/workspace/platform/tool/src/main/assets"
            ],
            "main_jniLibs_directory": [
                "/Users/coder_yu/workspace/platform/tool/src/debug/jniLibs",
                "/Users/coder_yu/workspace/platform/tool/libs"
            ],
            "main_jni_directory": [
                "/Users/coder_yu/workspace/platform/tool/src/debug/jni",
                "/Users/coder_yu/workspace/platform/tool/src/main/jni"
            ],
            "main_manifest_path": "/Users/coder_yu/workspace/platform/tool/src/main/AndroidManifest.xml",
            "main_res_directory": [
                "/Users/coder_yu/workspace/platform/tool/src/debug/res",
                "/Users/coder_yu/workspace/platform/tool/src/main/res"
            ],
            "main_src_directory": [
                "/Users/coder_yu/workspace/platform/tool/src/debug/java",
                "/Users/coder_yu/workspace/platform/tool/src/main/java"
            ]
        },
        "webview": {
            "main_assets_directory": [
                "/Users/coder_yu/workspace/platform/webview/src/release/assets",
                "/Users/coder_yu/workspace/platform/webview/src/main/assets"
            ],
            "main_jniLibs_directory": [
                "/Users/coder_yu/workspace/platform/webview/src/release/jniLibs",
                "/Users/coder_yu/workspace/platform/webview/src/main/jniLibs"
            ],
            "main_jni_directory": [
                "/Users/coder_yu/workspace/platform/webview/src/release/jni",
                "/Users/coder_yu/workspace/platform/webview/src/main/jni"
            ],
            "main_manifest_path": "/Users/coder_yu/workspace/platform/webview/src/main/AndroidManifest.xml",
            "main_res_directory": [
                "/Users/coder_yu/workspace/platform/webview/src/release/res",
                "/Users/coder_yu/workspace/platform/webview/src/main/res"
            ],
            "main_src_directory": [
                "/Users/coder_yu/workspace/platform/webview/src/release/java",
                "/Users/coder_yu/workspace/platform/webview/src/main/java"
            ]
        }
    },
    "project_type": "gradle",
    "root_dir": "/Users/coder_yu/workspace/platform",
    "sdk_directory": "/Users/coder_yu/Library/Android/sdk",
    "use_jdk8": false
}

**Comment by lomanyong** [comment]
@shuifengYu 看了一下应该没有太大的问题，可以全量后使用`python freeline.py -d`从日志确认下扫描的情况。
