### ISSUE TITLE
"declares your JAVA_HOME"的问题，别忙着close

### ISSUE THREAD

**Issue by zengyongchang** [alibaba/freeline#608]
虽然和#91 的问题一样，但是那里的回答没解决我的问题。freeline.py -f可以生效，但是紧接着python freeline.py就报错。-f是全量编译，耗时等不起。
工程就是个win7下的hello-world。

![x2](https://cloud.githubusercontent.com/assets/23071263/21880245/cb96514e-d8d8-11e6-9696-50997d3d90a0.png)

报错：
[DEBUG] [ERROR] Builder.get_javac() return None.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
JAVA_HOME not found in env.
[ERROR] --------------------------------------------------------
[ERROR] Please declares your JAVA_HOME to system env!
[ERROR] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zengyongchang 使用的是 freeline 的哪个版本？如果是 0.8.4 的话，看下工程目录下的`freeline_project_description.json`文件里的`java_home`字段是否正确

**Comment by zengyongchang** [comment]
@lomanyong 是v0.8.4
json那行改成 "java_home": "C:\\Program Files\\Java\\jdk1.8.0_20", 
就好使了。
原来是C:\\Program Files\\Java，不过initFreeline的时候不知是怎么推断了，那个目录下有jdk和jre
