### ISSUE TITLE
 [install_apk_task] install_apk_task start to run after waiting 103.9s

### ISSUE THREAD

**Issue by johnx4** [alibaba/freeline#61]
修改代码后等待更新时间较长，其中该任务耗时最多

**Comment by johnx4** [comment]
[gradle_clean_build_task] gradle_clean_build_task finish in 98.3s

**Comment by lomanyong** [comment]
@johnx4 看样子没有进入增量编译，一直在走全量的流程。手机上是否安装了多个依赖freeline的app呢？比如也安装了freeline的sample工程，如果有的话，可以卸载掉，然后再试试看.

**Comment by johnx4** [comment]
@lomanyong 并没有安装其他freeline的app

**Comment by lomanyong** [comment]
@johnx4 可以发下详细的日志，`python freeline.py -d`，方便我们分析一下为什么每次都会走全量的流程，而不走增量
