### ISSUE TITLE
adb连接好，执行freeline，adb会断开，sync_task失败

### ISSUE THREAD

**Issue by zhangw** [alibaba/freeline#611]
设备是天猫魔盒，使用Wi-Fi连接adb shell后，运行freeline，重试多次，一直是下面的报错。
[DEBUG] [main] main finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 1.4s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy /Users/vincent/tmp/tvtaobao/main/build/freeline/update/dex/classes.dex to /Users/vincent/tmp/tvtaobao/main/build/freeline/freeline-dexes/merged.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] try to connect device 3 times...
[DEBUG] [sync_client] wake up Service: /Users/vincent/Downloads/android-sdk/platform-tools/adb shell am startservice -n com.yunos.tvtaobao/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 4 times...
[DEBUG] [sync_client] wake up Service: /Users/vincent/Downloads/android-sdk/platform-tools/adb shell am startservice -n com.yunos.tvtaobao/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 5 times...
[DEBUG] [sync_client] wake up Service: /Users/vincent/Downloads/android-sdk/platform-tools/adb shell am startservice -n com.yunos.tvtaobao/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 6 times...
[DEBUG] [sync_client] wake up Service: /Users/vincent/Downloads/android-sdk/platform-tools/adb shell am startservice -n com.yunos.tvtaobao/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 7 times...
[DEBUG] [sync_client] wake up Service: /Users/vincent/Downloads/android-sdk/platform-tools/adb shell am startservice -n com.yunos.tvtaobao/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 8 times...
[DEBUG] [sync_client] wake up Service: /Users/vincent/Downloads/android-sdk/platform-tools/adb shell am startservice -n com.yunos.tvtaobao/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 9 times...
[DEBUG] [sync_client] wake up Service: /Users/vincent/Downloads/android-sdk/platform-tools/adb shell am startservice -n com.yunos.tvtaobao/com.antfortune.freeline.FreelineService -e wakeup marker
[DEBUG] [sync_client] try to connect device 10 times...
[DEBUG] [sync_client] No device's connection found
[DEBUG] [connect_device_task] connect_device_task finish in 4.4s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 4.3s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 4.3s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 3.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 4.38s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
	Use `adb devices` to check your device connection
[ERROR] --------------------------------------------------------
[ERROR] No device's connection found
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 5.4s
[DEBUG] Task engine running time: 4.4s
[DEBUG] Total time: 9.7s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zhangw 目前还没有支持wifi连接设备...
