### ISSUE TITLE
增量编译报full resource pack not found:  base-res.so

### ISSUE THREAD

**Issue by YouZiQian** [alibaba/freeline#613]
以下是全量编译时的log
`[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=True, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.4
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.4
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-assets/apktime
[DEBUG] new clean build flag value: 773295
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [generate_file_stat_task] save mvp module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.0s
[DEBUG] [read_project_info_task] read_project_info_task finish in 6.6s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 6.6s
[DEBUG] [gradle_clean_build_task] ./gradlew :app:assembleDebug -P freelineBuild=true --stacktrace
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 28.2s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 34.9s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 34.9s
[DEBUG] [install_apk_task] check device' connection...
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline_annotation_info.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/jar_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/public_keeper.xml
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/stat_cache.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/app/assets_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/app/resources_dependencies.json
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-assets/apktime
[DEBUG] [clean_all_cache_task] ignore remove: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/tocar/resources_dependencies.json
[DEBUG] [clean_all_cache_task] clean_all_cache_task finish in 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 34.9s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 34.9s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 28.2s
[DEBUG] [append_file_stat_task] generate_file_stat_task in append mode
[DEBUG] collecting project info, please wait a while...
[DEBUG] [generate_apt_files_task] start generate apt files stat...
[DEBUG] collecting project info, please wait a while...
[DEBUG] [append_file_stat_task] no new modules found.
[DEBUG] [append_file_stat_task] append_file_stat_task finish in 0.0s
[DEBUG] [build_base_resource_task] /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/public_keeper.xml exists, move to dst: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml
[DEBUG] [install_apk_task] start to install apk to device: /Library/Android/sdk/platform-tools/adb install -r /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/outputs/apk/MoCar_build7_1.0.0 alpha_20170113.apk
[DEBUG] [generate_project_info_task] generate_project_info_task finish in 0.0s
[DEBUG] [generate_apt_files_task] save apt files cache to path: /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/apt_files_stat_cache.json
[DEBUG] [generate_apt_files_task] generate_apt_files_task finish in 0.0s
[DEBUG] [build_base_resource_task] generating ids.xml from public.xml...
[DEBUG] [databinding_processor] java -jar freeline/release-tools/databinding-cli8.jar -p com.chonghot.tocar -i /Users/yons/Desktop/AndroidStudioProjects/tocar/app/src/main/res -o /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-databinding/app/04e8359fb33f0ec1ccd428df963f5c22/res -d /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-databinding/merged_layoutinfo -c /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-databinding/app/04e8359fb33f0ec1ccd428df963f5c22/java -l false -v 15 -s /Library/Android/sdk
[DEBUG] [build_base_resource_task] build_base_resource_task finish in 0.2s
[DEBUG] [install_apk_task] start to launch application com.chonghot.tocar/com.chonghot.tocar.contract.presenter.start.LoginActivity
[DEBUG] [install_apk_task] /Library/Android/sdk/platform-tools/adb shell am start -n com.chonghot.tocar/com.chonghot.tocar.contract.presenter.start.LoginActivity
[DEBUG] [install_apk_task] install_apk_task finish in 12.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 47.27s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

process databinding error: Source '/Users/yons/Desktop/AndroidStudioProjects/tocar/app/src/main/res/android/databinding' exists but is a directory

[ERROR] --------------------------------------------------------
[ERROR] process module databinding failed: java -jar freeline/release-tools/databinding-cli8.jar -p com.chonghot.tocar -i /Users/yons/Desktop/AndroidStudioProjects/tocar/app/src/main/res -o /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-databinding/app/04e8359fb33f0ec1ccd428df963f5c22/res -d /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-databinding/merged_layoutinfo -c /Users/yons/Desktop/AndroidStudioProjects/tocar/app/build/freeline/freeline-databinding/app/04e8359fb33f0ec1ccd428df963f5c22/java -l false -v 15 -s /Library/Android/sdk
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 47.3s
[DEBUG] Total time: 47.5s
[DEBUG] --------------------------------------------------------
`

**Comment by lomanyong** [comment]
@YouZiQian 类似 #594 的问题，正在解决中
