### ISSUE TITLE
请教 Terminal 执行 >python freeline.py -f 报错

### ISSUE THREAD

**Issue by lvwenbo0107** [alibaba/freeline#614]
Terminal 执行 >python freeline.py -f 报错
ERROR:
E:\Android\CustomVIew>python freeline.py -f
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "E:\Android\CustomVIew\freeline_core\dispatcher.py", line 8, in <module>
    from command import AbstractCommand
ImportError: No module named 'command'
请问为啥？

**Comment by lomanyong** [comment]
@lvwenbo0107 请使用 Python 2.7

**Comment by javalue** [comment]
我的已经是2.7了还报这样的错
`Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
ImportError: No module named freeline_core.dispatcher
`

**Comment by Vander-liu** [comment]
我也是,求助..我还在本地下载了新的环境 2.7.14 还是不行.

**Comment by Vander-liu** [comment]
@lomanyong  朋友,求助.
