### ISSUE TITLE
0.8.4  修改任意资源文件后，增量运行失败，必须要全量运行

### ISSUE THREAD

**Issue by OoadaioO** [alibaba/freeline#615]
如题

**Comment by lomanyong** [comment]
@OoadaioO 请贴出日志

**Comment by javaczhang** [comment]
[freelineRes.txt](https://github.com/alibaba/freeline/files/705973/freelineRes.txt)
也碰到同样的错误，但修改java文件增量编译没问题，尝试以前用过的办法：每次修改资源文件就在java文件里加个空格 这次也没用了，compileSdkVersion 25    buildToolsVersion '25.0.2'
期待解答

**Comment by lomanyong** [comment]
@javaczhang #539 可以解决你的问题

**Comment by OoadaioO** [comment]
更新到0.8.5突然好了
