### ISSUE TITLE
执行freeline报错不存在

### ISSUE THREAD

**Issue by adminLiu-s** [alibaba/freeline#617]
Traceback (most recent call last):
  File "freeline.py", line 1, in <module>
    freeline/freeline.py
NameError: name 'freeline' is not defined

**Comment by lomanyong** [comment]
@adminLiu-s 重新`gradlew initFreeline -Pmirror`一下...

**Comment by adminLiu-s** [comment]
都试过了...还是一样的


Old file /Users/liujun/work/dandan/data/Dandan2016/freeline_project_description.json removed.
Save to /Users/liujun/work/dandan/data/Dandan2016/freeline_project_description.json

BUILD SUCCESSFUL

Total time: 1 mins 47.614 secs
LJDMacBook-Pro:Dandan2016 liujun$ python freeline.py
Traceback (most recent call last):
  File "freeline.py", line 1, in <module>
    freeline/freeline.py
NameError: name 'freeline' is not defined

**Comment by lomanyong** [comment]
@adminLiu-s 文件是否存在？是否使用Python3？

**Comment by adminLiu-s** [comment]
![image](https://cloud.githubusercontent.com/assets/11938143/21969098/54e1c37a-dbd6-11e6-9676-2310df6e5506.png)
![image](https://cloud.githubusercontent.com/assets/11938143/21969114/67a2ccf2-dbd6-11e6-8ca0-74d692dc1aa0.png)

**Comment by lomanyong** [comment]
@adminLiu-s 有两个目录`freeline`和`freeline_core`，删掉外面的那个`freeline_core`

**Comment by adminLiu-s** [comment]
![image](https://cloud.githubusercontent.com/assets/11938143/21969277/0ae16f3a-dbd8-11e6-9ec5-b5ddcced4a38.png)
还是一样.....

**Comment by lomanyong** [comment]
@adminLiu-s 发现问题了。执行下面两个命令：

````
rm freeline.py
ln -s freeline/freeline.py freeline.py
````

**Comment by adminLiu-s** [comment]
解决了.....这只能执行里面的freeline.py?

**Comment by lomanyong** [comment]
@adminLiu-s 是你的 Mac 被识别成了 Windows 了，才出现这样的问题...现在应该都正常了。
