### ISSUE TITLE
checkBeforeCleanBuild失败－（StackOverflowError）

### ISSUE THREAD

**Issue by logwee** [alibaba/freeline#620]
checkBeforeCleanBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkBeforeCleanBuild'.
> java.lang.StackOverflowError (no error message)

**Comment by lomanyong** [comment]
@logwee app中是否有依赖循环引用的情况？应该是这个原因导致的。

**Comment by logwee** [comment]
谢谢～～～
@lomanyong 直接assembleDebug是没有问题的，如果有循环引用应该在config阶段就报错才对吧？

**Comment by lomanyong** [comment]
@logwee 本身 gradle 的依赖逻辑自己解决了这个问题...不过 freeline 在扫描模块间依赖的时候没有做这个处理...你也是第一个碰见的。。我们看下后面是否可以加上循环引用的判断吧...

**Comment by logwee** [comment]
@lomanyong 我们有50个子工程，请问有什么好办法找出其中的问题
谢谢～

**Comment by lomanyong** [comment]
@logwee 执行`./gradlew :{your-main-module-name}:dependencies`，会有依赖的结构...你可以先自己判断看看..

**Comment by logwee** [comment]
@lomanyong  谢谢

**Comment by logwee** [comment]
找到原因了，是因为在两个目录下存在同名的子工程
