### ISSUE TITLE
unicodeEncodeError 

### ISSUE THREAD

**Issue by shiyingyan** [alibaba/freeline#623]
![image](https://cloud.githubusercontent.com/assets/8131314/22009873/cc76c31e-dcc0-11e6-9a85-7960b452e5bf.png)
安装完成，点击freeline图标，提示这个错误。看了网上大家说的，有点云里雾里，，仍然不明白如何解决！麻烦请帮忙，谢谢。

**Comment by lomanyong** [comment]
@shiyingyan 路径不要包含中文

**Comment by shiyingyan** [comment]
@lomanyong  您好，不好意思 。路径中并不包含中文 ！
