### ISSUE TITLE
retrolambda支持问题

### ISSUE THREAD

**Issue by ifjgm005** [alibaba/freeline#626]
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > java.util.NoSuchElementException (no error message)
   > Cannot change dependencies of configuration ':app:retrolambdaConfig' after it has been resolved.

**Comment by lomanyong** [comment]
@ifjgm005 这错误信息跟 freeline 没有关系吧？

**Comment by ifjgm005** [comment]
不依赖retrolambda，就可以的。

**Comment by ifjgm005** [comment]
而且不用Freeline 可以正常编译安装

**Comment by ifjgm005** [comment]
能帮忙看下吗？

**Comment by lomanyong** [comment]
@ifjgm005 Google it，这个是你本地自身配置存在问题。retrolambada 是测过的，可以兼容。

**Comment by ifjgm005** [comment]
当我未添加retrolambada 时可以使用Freeline正常编译。
当我添加retrolambada 后，使用AS也能正常编译并运行。可是用Freeline 就出错，确定和Freeline 没有关系吗？

**Comment by ifjgm005** [comment]
这个问题，我找到解决办法了。这里记录下，防止其他同学也掉这个坑。本质上是retrolambada 和Freeline 兼容问题。可能Freeline测试的时候只测了最新版本。当我把retrolambada 升级到最新版本。该问题就解决了，但我用的3.2也不是很古老。

**Comment by lomanyong** [comment]
@ifjgm005 thanks

**Comment by sixgodIT** [comment]
@lomanyong 
我项目中也遇到同样的问题，不过与retrolambda和freeline版本都无关。
retrolambda 3.2.5  
freeline 0.8.5
在集成时 
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.antfortune.freeline'

retrolambda要在freeline上面，顺序颠倒就会报上面的错误。

**Comment by lomanyong** [comment]
@sixgodIT 这是必然的哈~会涉及到插件的执行顺序问题~
