### ISSUE TITLE
WindowsError:[Error 2]这是什么错误

### ISSUE THREAD

**Issue by zhaoqingli** [alibaba/freeline#627]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=True, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.5
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.5
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\work\jdStock_Android\JdJrProject\JdStock\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 175000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save JdStock module file stat
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save JdOpenAccount module file stat
[DEBUG] [generate_file_stat_task] save JdTrade module file stat
[DEBUG] [generate_file_stat_task] save JdFrame module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.2s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\work\jdStock_Android\JdJrProject\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\work\jdStock_Android\JdJrProject\freeline_core\gradle_clean_build.py", line 75, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "D:\work\jdStock_Android\JdJrProject\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] 

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.1s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.3s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zhaoqingli 你估计配置了 buildScript，指令了linux下的工具，而不是windows的gradlew.bat

**Comment by zhaoqingli** [comment]
你好，你说的配置了buildScript，具体指什么？

**Comment by zhaoqingli** [comment]
我配置了gradle环境，用的gradle命令，Android studio默认的gradlew命令不能用

**Comment by lomanyong** [comment]
@zhaoqingli 请查看 freeline 的 wiki：https://github.com/alibaba/freeline/wiki/Freeline-DSL-References#string-buildscript ，自己配置即可以不使用 freeline 自动提供的 assemble 命令

**Comment by shenquan** [comment]
我的也同样出现这种情况，没有解决。。
