### ISSUE TITLE
一直在循环，不往下执行

### ISSUE THREAD

**Issue by hunter0147** [alibaba/freeline#63]
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [sync_client] apktime path: D:\4.5\ebuyandroid_V4.5\suningEBuy\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 255000
[DEBUG] [sync_client] try to connectbb device 1 times...
[DEBUG] [sync_client] apktime path: D:\4.5\ebuyandroid_V4.5\suningEBuy\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 255000
[DEBUG] [sync_client] try to connectbb device 2 times...

**Comment by lomanyong** [comment]
@hunter0147 application类是否添加了`FreelineCore.init(this);`呢？

**Comment by hunter0147** [comment]
加了额

**Comment by charvenhe** [comment]
@hunter0147 进我们官方群，我们跟进下

**Comment by lomanyong** [comment]
@hunter0147 可以看下logcat中，是否有freeline相关的日志，以及freeline的socket是否正常启动了..。看样子是socket没连接上

**Comment by hunter0147** [comment]
09-01 09:45:10.861 9317-9317/? I/Freeline: freeline start initial process...
09-01 09:45:10.861 9317-9317/? I/Freeline: freeline init application
09-01 09:45:10.863 9317-9317/? I/Freeline: start to inject dex...
09-01 09:45:10.863 9317-9317/? I/Freeline: start to inject resources...
09-01 09:45:10.864 9317-9317/? I/Freeline: dynamicInfoSp: {}
09-01 09:45:10.864 9317-9317/? I/Freeline: resMap: {}
09-01 09:45:10.864 9317-9317/? I/Freeline: start to load hackload.dex...
09-01 09:45:10.865 9317-9317/? I/Freeline: copy hackload dex from assets success
09-01 09:45:10.866 9317-9317/? I/Freeline.hackDex: /data/data/com.suning.mobile.ebuy/cache/hack/hackload.dex dex length: 848
09-01 09:45:10.866 9317-9317/? I/Freeline.hackDex: /data/data/com.suning.mobile.ebuy/cache/hack/opt opt length: 4096
09-01 09:45:10.925 9317-9317/? I/Freeline.hackDex: after opt, dex len:848; opt len:4096
09-01 09:45:10.925 9317-9317/? I/Freeline: load hackload，dex size:848
09-01 09:45:10.925 9317-9317/? I/Freeline: freeline init server
09-01 09:45:10.947 883-1904/system_process I/ActivityManager: Start proc 9405:com.suning.mobile.ebuy:freeline/u0a174 for service com.suning.mobile.ebuy/com.antfortune.freeline.FreelineService
09-01 09:45:11.024 9405-9405/? I/Freeline: freeline start initial process...
09-01 09:45:11.494 9405-9405/? D/Freeline.LongLinkServer: Freeline.increment server running on port 41128
09-01 09:45:11.495 9405-9405/? I/Freeline.Service: onStartCommand Received start id 1, intent: Intent { cmp=com.suning.mobile.ebuy/com.antfortune.freeline.FreelineService }
09-01 09:45:11.636 9405-9405/? I/Freeline.Service$Inner: onStartCommand Received start id 1, intent: Intent { cmp=com.suning.mobile.ebuy/com.antfortune.freeline.FreelineService$InnerService }
09-01 09:45:11.956 9578-9578/com.suning.mobile.ebuy:remote I/Freeline: freeline start initial process...
09-01 09:45:15.044 9818-9818/? I/Freeline: freeline start initial process...
09-01 09:45:37.706 10330-10330/? I/Freeline: freeline start initial process...
这是用py freeline.py -f 安装后的log 然后我改了代码 用py freeline.py就一直循环在那边了

**Comment by lomanyong** [comment]
@hunter0147 换台手机或者换成模拟器还是会出现一样的情况吗？

**Comment by charvenhe** [comment]
@hunter0147 估计是部分手机上的兼容性问题，我们正在解决，预计下个迭代加上

**Comment by hunter0147** [comment]
import urllib2
        request = urllib2.Request(url)
        response = urllib2.urlopen(request)
        result = response.read().decode('utf-8').strip()
把请求改成这样可以运行了，但是补丁没起效果

**Comment by hunter0147** [comment]
有时sync不对也会连不上

**Comment by hunter0147** [comment]
搞错了，和urllib2没关系 还是我本地环境的问题，fiddler打开的时候就可以连接上。。。

**Comment by charvenhe** [comment]
@hunter0147，你这边能正常增量了吗

**Comment by hunter0147** [comment]
搞错了，和urllib2没关系 还是我本地环境的问题，fiddler打开的时候就可以连接上。。。

**Comment by hunter0147** [comment]
搞错了，和urllib2没关系 还是我本地环境的问题，fiddler打开的时候就可以连接上。。。

**Comment by hunter0147** [comment]
09-05 17:22:58.991 5227-5421/com.suning.mobile.ebuy:freeline D/Freeline.PushDex: dex file received (0 bytes) rename rst :true
09-05 17:22:58.991 5227-5421/com.suning.mobile.ebuy:freeline D/Freeline.PushDex: /data/data/com.suning.mobile.ebuy/cache/temp/dynamic.apk
增量还不行，看log收到的补丁文件大小为0

**Comment by hunter0147** [comment]
现在可以了 原来是浏览器设置了代理

**Comment by charvenhe** [comment]
@hunter0147 dex为0的问题也解决了吗？

**Comment by hunter0147** [comment]
嗯 是我这边代码改错了 没有传body

**Comment by charvenhe** [comment]
@hunter0147 资源和代码增量都搞定了吗？

**Comment by lomanyong** [comment]
@hunter0147 所以最后的解决方案是你那边有修改过curl的代码 + 关掉代理吗？

**Comment by hunter0147** [comment]
代码没问题 是我这边代理的问题

**Comment by charvenhe** [comment]
@hunter0147 可以在你们日常多使用，有问题的话上来反馈
