### ISSUE TITLE
可否支持本地已有gradle

### ISSUE THREAD

**Issue by LichFaker** [alibaba/freeline#630]
项目中一直使用已下载的Gradle 3.1，再接入FreeLine后编译提示`错误: 找不到或无法加载主类 org.gradle.wrapper.GradleWrapperMain`，可否将脚本中的`./gradlew`改成可修改或可配置的，这样我可以直接将其替换使用本地`gradle`了

**Comment by lomanyong** [comment]
@LichFaker 原本就是可配置的...请参考下说明文档：https://www.freelinebuild.com/docs/zh_cn/

**Comment by LichFaker** [comment]
@lomanyong 修改为
```
freeline {
        buildScript "gradle assembleDebug"
 }
```
使用force提示`freeline failed when read project info with script: ./gradlew -q checkBeforeCleanBuild
`，不使用则提示` Please make sure your application is properly running in your device.`

**Comment by qinhehu** [comment]
@LichFaker 解决了么

**Comment by LichFaker** [comment]
@qinhehu 不好意思，当时是解决了的， 但没及时更新记录。 目前由于代理的问题，已经切换到buck了

**Comment by zpetter** [comment]
是因为开了代理是吗

**Comment by LichFaker** [comment]
@zpetter 不是，通过文档可以配置解决。
代理问题是指：使用freeline需要关闭代理，最终放弃了 :)
