### ISSUE TITLE
一直卡在：Building 97% > :app:transformClassesWithDexForDebug

### ISSUE THREAD

**Issue by ZJUHeDQ** [alibaba/freeline#631]
执行了 gradlew assembleDebug -P freelineBuild=true --stacktrace
一直卡在：Building 97% > :app:transformClassesWithDexForDebug

**Comment by lomanyong** [comment]
@ZJUHeDQ 这个task没有freeline相关的处理...

**Comment by ZJUHeDQ** [comment]
请问这个有可能会是什么原因呢？

**Comment by lomanyong** [comment]
@ZJUHeDQ 这个地方只是在处理 class 转 dex，除非你的工程很大，耗时会比较久，一般不会耗时很久。

**Comment by ZJUHeDQ** [comment]
已经卡了半个多小时了，试了好多次都是这样。用自带的gradle编译就没问题。

**Comment by lomanyong** [comment]
@ZJUHeDQ 手动执行编译命令，看下卡在哪里...`gradlew :app:assembleDebug -PfreelineBuild=true --debug`

**Comment by ZJUHeDQ** [comment]
11:53:13.373 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
11:53:13.373 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:53:13.373 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
11:53:13.374 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
一直在重复上面的日志
> Building 96% > :app:transformClassesWithDexForDebug

**Comment by MrWarm01** [comment]
你好，我目前也遇到这样的问题，请问你是怎么解决的呢？
