### ISSUE TITLE
windows上面为什么代码改变了之后，编译后没有看到效果，另外在一些子模块里面改代码，检测不到代码有更改。

### ISSUE THREAD

**Issue by geakw** [alibaba/freeline#632]

**Comment by lomanyong** [comment]
@geakw 没有日志没有具体工程结构，你让别人怎么帮你分析...

**Comment by geakw** [comment]
子模块的改变检测不到的原因找到了，修改了项目gradle的依赖写法
原来是是这样写的 compile  'rootDir : lib-name'，改成compile project(':lib-name')就可以了。还有个问题是在application类中更改代码后，增量编译无效，只能全编么？

**Comment by lomanyong** [comment]
@geakw 目前暂时不支持 Application 动态修改了，容易引起问题...
