### ISSUE TITLE
执行完./gradlew initFreeline 一直停在Building 0%

### ISSUE THREAD

**Issue by adugmcool** [alibaba/freeline#633]
<img width="1361" alt="3a80b139-ef88-4e51-b497-ffc29852d2aa" src="https://cloud.githubusercontent.com/assets/8541697/22141668/147d6c0c-df2e-11e6-8541-ce9189de6252.png">

**Comment by lomanyong** [comment]
@adugmcool execute: `./gradlew initFreeline -Pmirror`.

Please READ THE DOCUMENT before summit an issue.
