### ISSUE TITLE
增量编译 报找不到符号

### ISSUE THREAD

**Issue by d342784178** [alibaba/freeline#635]
增量编译 报找不到符号 freeline版本是0.8.4 使用as插件方式 build.gradle一点没改
jar_dependencies.json 内有内容
[log.txt](https://github.com/alibaba/freeline/files/725781/log.txt)

**Comment by d342784178** [comment]
build.gradle已经照着readme改了 记错了

**Comment by lomanyong** [comment]
@d342784178 `/Users/mic/android-sdk-macosx/platforms/android-23/android.jar`，这个文件存在吗？

**Comment by d342784178** [comment]
没有android-23 只有android-6.0诶 
这要怎么改?

**Comment by d342784178** [comment]
没有android-23 只有android-6.0诶 
这要怎么改?

**Comment by d342784178** [comment]
手动改freeline_project_description.json能行吗

**Comment by lomanyong** [comment]
@d342784178 你也可以复制android-6.0文件夹，然后改名成`android-23`试试看。改freeline-project-description也是可行的..但是可能有问题...

**Comment by d342784178** [comment]
手动改了freeline_project_description.json 可以了 速度很快
不过全量编译后又得手动改一遍
有没有一劳永逸的方法呢

**Comment by lomanyong** [comment]
@d342784178 尝试一下上面说的，复制一下文件夹然后重命名看看

**Comment by d342784178** [comment]
好像可以
不过有了新问题 full resource pack not found: /Users/mic/AndroidStudioProjects/MyApplication/app/build/freeline/base-res.so

目录下的确没有这个文件

**Comment by lomanyong** [comment]
@d342784178 你全量编译的时候应该就出错了，最后的日志是资源编译出错的输出，你可以具体看下

**Comment by d342784178** [comment]
可以了 万分感谢

**Comment by d342784178** [comment]
又有新问题了...
有时候增量编译的时候 会一直connect service 还失败 只能重新全量编译
还有一点就是全量编译的时候cpu只用到50%不到 有办法能提高利用率吗?

**Comment by lomanyong** [comment]
@d342784178 全量编译的时候本质上是调用 gradle 的编译命令，你可以自行配置 gradle 的参数或者配置来提速。

connect service 失败原因挺多的额，可以参考已有的 issue，以及这个问题跟你本身的环境关系比较大。
