### ISSUE TITLE
ModuleNotFoundError: No module named 'command'

### ISSUE THREAD

**Issue by tonychang84** [alibaba/freeline#636]
python freeline.py
Traceback (most recent call last):
  File "freeline.py", line 7, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "C:\android\xxx\freeline_core\dispatcher.py", line 8, in <module>
    from command import AbstractCommand
ModuleNotFoundError: No module named 'command'

[http://r.chaoxin.com/a81259c/2017-01-24_15/b8f17/8f6bd/1485243040_138675_2448_3264.jpg](url)

**Comment by lomanyong** [comment]
@tonychang84 请使用 Python 2.7+ 版本

**Comment by franklifeisnow** [comment]
我的Python版本 3.6
出现同样的问题
