### ISSUE TITLE
Task 'initFreeline' not found in root project 'xxx'.

### ISSUE THREAD

**Issue by strongmanb** [alibaba/freeline#638]
现在执行gradlew initFreeline就报：Task 'initFreeline' not found in root project 'xxx'.

执行python freeline.py -f也报错：freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild

有解决办法吗？

**Comment by lomanyong** [comment]
@strongmanb 这个问题基本都是你本身配置的问题...确认下是否正确地`apply plugin: "com.antfortune.freeline"`
