### ISSUE TITLE
多进程访问需要增量编译两次才生效

### ISSUE THREAD

**Issue by ysbing** [alibaba/freeline#641]
在第二个进程中，使用增量编译，需要编译两次，才能有变化，还有的时候，会出现CPU类型不匹配的问题。

**Comment by lomanyong** [comment]
@ysbing 目前还没有对多进程增量编译有很好的支持。CPU 类型不匹配的问题，同时修改的 so 文件尽量不要携带不匹配的 so 文件...可以避免这个问题...
