### ISSUE TITLE
freeline插件版本问题

### ISSUE THREAD

**Issue by chk007** [alibaba/freeline#647]
Error:Execution failed for task ':initFreeline'.
> Your local freeline version 0.0.0 is lower than the lastest release version 0.8.5. Please update the freeline version in build.gradle. If you still want the specific version of freeline, you can execute the initial command with the extra parameter `-PfreelineVersion={your-wanted-version}`. eg: `gradlew initFreeline -PfreelineVersion=0.0.0`

1）Linux + Android Studio 2.2 : 在Setting->Plugin中添加Freeline插件;
2) 通过自动提示在gradle脚本中添加依赖;
3) 安装完成后，首次重启使用没有问题，再次重启AS之后，再次通过工具栏的Freeline ICON编译，出现以上错误。

**Comment by liuwons** [comment]
可以在`gradle.properties`里添加`freelineVersion=0.8.5`来解决
