### ISSUE TITLE
修改资源后使用getIdentifier 获取不到id

### ISSUE THREAD

**Issue by criswonder** [alibaba/freeline#653]
如下代码获取的resId，修改资源后增量编译获取为空
```java
int resId = view.getContext().getResources().
                        getIdentifier("activity_main","layout",view.getContext().getPackageName());

```
 
重现步骤：
1. 运行freeline.py, 在打开的app中点击右下角的邮件icon可以看到resId是有值的
2. 修改activity_main.xml line24 为content_main2
3. 命令行运行./freeline.py 
4. 重复步骤1发现resId为空

造成此问题的可疑点：
gradle文件中applicationId为"com.taobao.hongyun.androidtestgarage.change"，而AndroidManifest.xml中为"com.taobao.hongyun.androidtestgarage"

附上项目文件[AndroidTestGarage_freeline1.zip](https://github.com/alibaba/freeline/files/770540/AndroidTestGarage_freeline1.zip)

**Comment by lomanyong** [comment]
@criswonder 暂时的解决方法：让applicationId与manifest中的id一致，这个问题后期会解决~
