### ISSUE TITLE
运行报错 It's not an android Gradle project Currently?

### ISSUE THREAD

**Issue by gunC** [alibaba/freeline#655]
使用 `python freeline.py`命令可以正常运行,但是使用插件则运行报错.
```
 It's not an android Gradle project Currently?
```
![error](https://cloud.githubusercontent.com/assets/1253658/22916914/a86f50dc-f2bc-11e6-9c29-b4e2eeba533c.jpg)

运行环境:
AndroidStudio 2.3 Canary 3
Freeline 0.8.5
android gradle plugin 2.2.3
gradle 3.2

使用版本:
Freeline Plugin 1.1.3

**Comment by lomanyong** [comment]
@gunC 插件判断没有build.gradle文件...能贴一下工程文件结构？

**Comment by gunC** [comment]
![er](https://cloud.githubusercontent.com/assets/1253658/22956862/88259ad6-f35f-11e6-8211-6300f6bf9766.jpg)

**Comment by gunC** [comment]
结构是正常目录结构...

**Comment by lomanyong** [comment]
@gunC 可以提供一个可以复现问题的sample工程吗？

也可以暂时使用命令行先编译着...

**Comment by xuchenchen** [comment]
我也是提示这个，希望尽快给予解决谢谢

**Comment by YanHuiLi** [comment]
我也遇到这个问题了，我给你提供一个吧
@lomanyong [这个项目](https://github.com/YanHuiLi/FirstCodeAndroid/tree/master/Chapter10/ServiceTest)

**Comment by dhhAndroid** [comment]
我的项目也是这样,之前一直好好的,最近才出现这样,不知道怎么解决

**Comment by dhhAndroid** [comment]
Freeline插件我设置了快捷键,我就强制一直按快捷键,好像好了..................

**Comment by ZhaoKaiQiang** [comment]
先用Gradle同步一下，再试试？

**Comment by lvtanxi** [comment]
最后怎么解决的呀？？？我今天又遇见了It's not an Android Gradle project Currently?

**Comment by hiperioncn** [comment]
我也遇到了相同问题，好像就是升级了gradle后，使用的com.android.tools.build:gradle:3.0.1和gradle-4.2.1-all.zip

**Comment by hiperioncn** [comment]
请问这个有解决方案吗？

**Comment by lvtanxi** [comment]
@lomanyong 没有，freeline在as3.x版本上很多问题。我现在时不时就用不了
