### ISSUE TITLE
 [get] Can't get http://static.freelinebuild.com/freeline/0.8.5/all/freeline.zip 有什么好办法可以正常走过这一步，一直都失败。

### ISSUE THREAD

**Issue by Misayanice** [alibaba/freeline#656]
[get] Can't get http://static.freelinebuild.com/freeline/0.8.5/all/freeline.zip 有什么好办法可以正常走过这一步，一直都失败。

**Comment by Misayanice** [comment]
:initFreeline FAILED
FAILURE: Build failed with an exception.

**Comment by lomanyong** [comment]
@Misayanice 这种都是网络问题呀。。。

请参考：https://www.freelinebuild.com/docs/zh_cn/#Gradle%20Task%3A%20initFreeline
