### ISSUE TITLE
网络被墙，依赖源码编译

### ISSUE THREAD

**Issue by aa5279aa** [alibaba/freeline#66]
首次使用的时候，由于网络被墙，把依赖都指向本地。
但是gradle plugin中initFreeline的时候有一项是下载freeline_code.zip到本地，如果失败则进程终止，这一点感觉体验不太好。
所以我修改了gradle工程下的一些代码，优先判断本地是否存在freeline_code.zip包，如果有则优先使用本地的，从而解决了这个问题。
也希望你们能在新版本中解决这个问题，谢谢。
下面是我自己写的一个配置流程，希望能够帮助到有着类似遭遇的人。
http://blog.csdn.net/rzleilei/article/details/52402484

**Comment by charvenhe** [comment]
@aa5279aa 十分感谢你的梳理，windows更新之前的确存在问题，首次网络问题我们后续也会进行优化
