### ISSUE TITLE
python freeline.py -f 报windowsError error2错误

### ISSUE THREAD

**Issue by shenquan** [alibaba/freeline#663]
[https://github.com/alibaba/freeline/issues/70]
python freeline.py -f 报windowsError error2错误，按照你原来在别人问题中的回答去做，不行呀，麻烦帮忙看下，有没有微信群发一下加下群聊，谢谢啦

**Comment by lomanyong** [comment]
@shenquan 请贴出完整的日志呀...才能判断什么问题...

**Comment by shenquan** [comment]
@lomanyong  完整日志如下
C:\sqhanwork2017\XXX\android_2>python freeline.py -f
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanB
uild=True, debug=False, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.1.0
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.5
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.5.1702161520
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: C:\sqhanwork2017\XXX\android_2\XXX\build\f
reeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 193000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiti
ng 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after wai
ting 0.0s
[DEBUG] [generate_file_stat_task] save XXX module file stat
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after wai
ting 0.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0
.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after wai
ting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run aft
er waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after w
aiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting
 0.0s
[DEBUG] [generate_file_stat_task] save XXX module file stat
[DEBUG] [generate_file_stat_task] save XXX module file stat
[DEBUG] [generate_file_stat_task] save XXX module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 1.3s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 1.33s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "C:\sqhanwork2017\XXX\android_2\freeline_core\task.py", line 123, in ex
ecute
    self.task.execute()
  File "C:\sqhanwork2017\XXX\android_2\freeline_core\gradle_clean_build.py", l
ine 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "C:\sqhanwork2017\XXX\android_2\freeline_core\utils.py", line 28, in ce
xec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 1.3s
[DEBUG] Total time: 1.6s
[DEBUG] --------------------------------------------------------

**Comment by shenquan** [comment]
@lomanyong 请问方便加个微信吗:）， 我微信号：hanshenquan1991

**Comment by shenquan** [comment]
@lomanyong  我这边发现0.8.5出这个问题，0.8.3没有这个问题。

**Comment by Dragon-Boat** [comment]
出现类似错误，日志除了文件地址不一样外，其他一致。
出错的情况是：之前正常，再移动了Android Studio的sdk路径后，报错。删除重新安装无效。

**Comment by lomanyong** [comment]
@shenquan @Dragon-Boat `gradlew.bat`这个文件你们系统上无法直接执行吗？

**Comment by Dragon-Boat** [comment]
@lomanyong 可以执行。
再freeline窗口直接执行，提示build successful

**Comment by shenquan** [comment]
@lomanyong 可以执行，同上。

**Comment by Dragon-Boat** [comment]
@lomanyong 在一个简单项目中尝试，该项目之前处于0.8.4版本，运行正常；
修改gradle依赖版本同步后，使用gradlew initFreeline -Pmirror更新到0.8.5，出现freeline.zip is not zip file类似的提示，到文件目录发现freeline.zip只有1kb，遂删除重新运行更新，成功下载0.8.5，继而无法正常运行，日志同上，报错【WindowsError: [Error 2]】。

PS：利用-PfreelineVersion{}似乎不能降级？

**Comment by shenquan** [comment]
@Dragon-Boat 好像可以降级的，命令：gradlew initFreeline -PfreelineVersion=0.8.3

**Comment by Dragon-Boat** [comment]
@shenquan 感谢，之前参数多加了{}。。。
@lomanyong 降级之后正常

**Comment by shenquan** [comment]
@Dragon-Boat 不客气

**Comment by shenquan** [comment]
@lomanyong  注：我出现这个问题之前也修改了SDK路径，现在使用0.8.3版本，没有问题

**Comment by lomanyong** [comment]
@shenquan 从报错的地方来看版本之间应该没有差异...我得找个 windows 机器试下...

**Comment by shenquan** [comment]
@lomanyong 若目前出现这种错误情况人数极少，可以暂时不用修复此问题，可能与具体环境配置有关。

**Comment by lomanyong** [comment]
@shenquan 0.8.6 应该修复这个问题了...有的 windows 机器上必须得 gradlew.bat 才能识别命令...

**Comment by shenquan** [comment]
@lomanyong OK，等我忙完最近的任务过段时间再试一下，多谢，辛苦了：）

**Comment by BLiYing** [comment]
降级到0.8.3我还是报这个错.......................并且可以执行gradlew assembleDebug -PfreelineBuild=true --stacktrace，编译成功。但是python freeline.py就是通不过。

**Comment by BLiYing** [comment]
我自己的sdk出了点问题（电脑系统引起），然后重装系统，好了哈哈。最新版0.8.6也没问题。

**Comment by BLiYing** [comment]
?
