### ISSUE TITLE
style文件的name属性含有.符号会报symbol not defined错误

### ISSUE THREAD

**Issue by androidfans** [alibaba/freeline#665]
看了下源码 .  public.xml是从R.java 文件生成的.  AAPT打包R.java的时候把name属性中的 . 点符号替换成了 _ .  这个时候根据public回头在资源文件里面找的时候就找不到了.

请问这个问题已知吗.

**Comment by lomanyong** [comment]
@androidfans 现在的public.xml应该是aapt生成的，而不是手动拼接的了... not defined 的资源只有那几个吗？其他的都没问题？

**Comment by androidfans** [comment]
是的.  之前以为是res路径的问题.  后来发现所有报错资源的name里面都带点.

**Comment by lomanyong** [comment]
@androidfans 麻烦提供可以一个可以复现问题的工程？我们复现看看,

**Comment by androidfans** [comment]
应该是前面调用AAPT失败了, 然后调用了  generate_public_files_by_r() .   调用AAPT失败的原因我再查一下吧,没有看到相关日志.

**Comment by androidfans** [comment]
换到sample里面把索引改成带点.的  生成的publicxml里面没有改成_下划线.  应该是我们自己项目的问题.

**Comment by androidfans** [comment]
查到原因了.  我们的工程使用ant编译.  插件中给AAPT增加参数的设置不生效.  手动在ant脚本中添加AAPT参数后已解决
