### ISSUE TITLE
command 'python' not found

### ISSUE THREAD

**Issue by walkinthecold** [alibaba/freeline#668]
python环境变量已经配置好了，电脑也重启过。在windows下面，python可以用。如下图，
![image](https://cloud.githubusercontent.com/assets/14848767/23089627/04b551d6-f5c7-11e6-8bfd-79e5111de99f.png)

但是在Androidstudio使用freeline就提示command 'python' not found。有人知道这个问题这么解吗?
Androidstudio版本2.2.2，python版本2.7.

**Comment by lomanyong** [comment]
@walkinthecold Google for it. 你也可以直接通过命令行来编译
