### ISSUE TITLE
File "C:\Users\wangdong\Desktop\4.1.2\freeline_core\task.py", line 123, in execute self.task.execute()

### ISSUE THREAD

**Issue by Mr-dolen** [alibaba/freeline#669]
alse)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.2
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.5
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.5.1702161520
[DEBUG] [WARNING] some important file missed, a clean build will be automatically executed.
[DEBUG] collecting project info, please wait a while...
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: C:\Users\wangdongliang\Desktop\4.1.2\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 54000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [task_engine] depth: 4, task: [generate_apt_files_task]
[DEBUG] [task_engine] depth: 4, task: [append_file_stat_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save app module file stat
[DEBUG] [read_project_info_task] read_project_info_task finish in 0.0s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 0.0s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 0.0s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 0.0s
[DEBUG] [generate_apt_files_task] generate_apt_files_task start to run after waiting 0.0s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 0.0s
[DEBUG] [append_file_stat_task] append_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] save photopicker module file stat
[DEBUG] [generate_file_stat_task] save ptr-lib module file stat
[DEBUG] [generate_file_stat_task] save lib module file stat
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.22s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\wangdong\Desktop\4.1.2\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "C:\Users\wangdong\Desktop\4.1.2\freeline_core\gradle_clean_build.py", line 74, in execute
    output, err, code = cexec(command.split(' '), callback=None)
  File "C:\Users\wangdong\Desktop\4.1.2\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "C:\Users\wangdong\python\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\wangdong\python\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.5s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@Mr-dolen 可以尝试一下 0.8.6 看下是否解决了这个问题

**Comment by Mr-dolen** [comment]
0.8.6已解决，非常感谢
