### ISSUE TITLE
配置freeline后发生module变更导致file not found的问题

### ISSUE THREAD

**Issue by Muyangmin** [alibaba/freeline#67]
这是一个实际应用场景：
开发人员在git(hg, etc)的分支A上配置了freeline并成功运行。  此时突然有一个紧急bug要在分支B上修复。开发人员切换到了B分支。
```
A的工程结构包含module `app`, `lib`, `player`  
B的工程结构只包含module `app`, `lib`。
```
即切换分支后，工程比上次运行freeline时少了一个module。此时执行freeline，会报出相关的build.gradle文件找不到的错误。

建议Freeline在每次运行时**检查一下工程结构**，如果发生了module的增删，那么**重新执行配置过程**，这样就可以避免这种错误的出现。

**Comment by lomanyong** [comment]
@Muyangmin 多谢提议~这是一个被遗漏的case阿...我们尽快支持这个case
