### ISSUE TITLE
ART上 offset的问题.  变量没问题,  但是删除方法仍然有问题.

### ISSUE THREAD

**Issue by androidfans** [alibaba/freeline#671]
public class ArtTest{

    public String getStr1() {
        return "getStr1";
    }
    

    public String getStr2() {
        return "getStr2";
    }

    public String getStr3() {
        return "getStr3";
    }
}

假设如下调用 print  artTest.getStr2(). 删除getStr1()方法后, 打印出来的就是getStr3

**Comment by androidfans** [comment]
增加方法同样

**Comment by lomanyong** [comment]
@androidfans 麻烦给下使用的设备以及系统版本。测试的类不是抽象类？

**Comment by androidfans** [comment]
非抽象类.
三星 S7edge 
Android6.0.1

**Comment by lomanyong** [comment]
@androidfans 在所有的设备以及任何类做同样的操作都会出现问题吗？

**Comment by androidfans** [comment]
ART设备上测试 都会这样,  删除某方法的上面一个方法,  该方法调用就会偏移

**Comment by lomanyong** [comment]
@androidfans 我这边测试倒是没有类似的情况，以前的经验下应该只在特定的类会出现，不会所有的类都无法修改，麻烦贴一下错误的堆栈吧...

**Comment by androidfans** [comment]
并没有报错, 哪来的堆栈.  复现方法是全量编译  
ArtTest artTest = new ArtTest(); 
Toast.makeText(this, artTest.getStr2(), Toast.LENGTH_LONG).show();输出getStr2

然后删除ArtTest的getStr1()方法.增量编译,  这时候输出的就是getStr3

在sample中复现成功 0.8.6版本

**Comment by lomanyong** [comment]
@androidfans 我检查一下

**Comment by androidfans** [comment]
查了一下,  这个问题本质上是art模式中,在转成oat文件的时候.  会生成oat exec段.  oat exec段中,对方法调用的索引已经写死了偏移地址.  也就是说,  上述例子中,需要把调用到ArtTest的类也重新打包编译上传更新才可以触发重新转OAT的操作,从而更新调用者的方法地址指针.

这个问题本质上是代码更新方案的缺陷

**Comment by lomanyong** [comment]
@androidfans 增量编译打包依赖类的问题在开发中，之前是为了解决抽象类问题而做的。不过还有点问题，之后的版本会 release 出来，应该可以优化这个问题。

**Comment by androidfans** [comment]
请问思路是在全量编译完成后, 记录依赖关系,  然后增量的时候找到相关的依赖关系,打包进dex吗.

这种情况下如果改了某个非常基础的类, 可能dex就非常大了.

**Comment by lomanyong** [comment]
@androidfans 类似的，目前freeline对于超过20个类的修改会自动进行全量。不过这个问题也不是完全必现的，可以参考 #593 这个 issue。
