### ISSUE TITLE
设备经常连接不上

### ISSUE THREAD

**Issue by 17043983** [alibaba/freeline#672]
[+][connect_device_task] running... in 31.8s
[-][gradle_aapt_task] finished. in 0.0s
[-][androidcommon] finished. in 0.0s
[-][moduledebug] finished. in 0.0s
[-][androidkugou] finished. in 2.0s
[-][merge_dex_task] finished. in 0.0s

经常在第一步好事过长，期间没有动过手机，不知道为什么会连接不上

**Comment by lomanyong** [comment]
@17043983 换条数据线？

**Comment by 17043983** [comment]
全量编译是没有问题的，只有增量变异的时候有问题。当连不上的时候，adb devices，设备是链接上的

**Comment by lomanyong** [comment]
@17043983 `python freeline.py -d`看下吧，之前也有人提过类似的问题，有的人换了数据线就好了

**Comment by 17043983** [comment]
试过两条线，还没有解决，明天我换一条线试试
