### ISSUE TITLE
kotlin不支持呀，大哥，这个现在用的人很多呀，挺好用的

### ISSUE THREAD

**Issue by s949492225** [alibaba/freeline#674]
kotlin不支持呀，大哥，kotlin现在用的人很多呀，挺好用的，希望能够加入kotlin的支持，很好奇有些库本身就是kotlin写的，不支持话可能会出现很多预料之外的结果，求支持

**Comment by lomanyong** [comment]
@s949492225 kotlin 与 jack 的支持在调研中，可行的话会在 0.9.0 加入支持
