### ISSUE TITLE
commond python not found

### ISSUE THREAD

**Issue by yatou252303** [alibaba/freeline#675]
![image](https://cloud.githubusercontent.com/assets/7346792/23295062/89a58f8c-faa9-11e6-83d7-1b4ea23d41b9.png)

**Comment by yatou252303** [comment]
店家 Freeline 图标进行运行，报python not found,是否需要安装python环境

**Comment by yatou252303** [comment]
点击

**Comment by lomanyong** [comment]
@yatou252303 请先安装python...
