### ISSUE TITLE
设置启动页Activity的主题属性，增量编译后不生效

### ISSUE THREAD

**Issue by hjm1fb** [alibaba/freeline#683]
我对启动页设置了白色背景色
`<style name="SplashActivityTheme" parent="@android:style/Theme.Black.NoTitleBar.Fullscreen">
        <item name="android:background">@color/white</item>
    </style>`
但是点击Run Freeline后重新启动APP ，启动页仍然是默认的黑色。需要重新全编译。

**Comment by lomanyong** [comment]
@hjm1fb 有的主题是无法在运行期生效的，应该是已知问题...
