### ISSUE TITLE
 No device's connection found

### ISSUE THREAD

**Issue by luziming** [alibaba/freeline#686]
我的模拟器是开着的,但是每次编译完后就提示这个错,而且模拟器也会断开
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Use `adb devices` to check your device connection
[ERROR] --------------------------------------------------------
[ERROR] No device's connection found
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 5.4s
[DEBUG] Task engine running time: 98.0s
[DEBUG] Total time: 103.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@luziming 有可能是模拟器的adb与sdk的adb工具冲突了，可以查找一下`genymotion adb`如何进行修改，配置为系统的adb工具应该就可以解决你的问题了
