### ISSUE TITLE
Freeline.increment server is already running

### ISSUE THREAD

**Issue by xiaoshubin** [alibaba/freeline#699]
![image](https://cloud.githubusercontent.com/assets/12315781/23640818/e9b9b202-032a-11e7-97a6-f35454453b1e.png)
并且全量编译也不shuo说找不到main
![image](https://cloud.githubusercontent.com/assets/12315781/23640868/1685f502-032b-11e7-9973-e79561688f83.png)

**Comment by lomanyong** [comment]
@xiaoshubin 把目录下freeline相关的文件都删掉，重新`initFreeline`一下
