### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by tianyutingxy** [alibaba/freeline#7]
[gradle_clean_build_task] 
这个task有优化空间吗，或需要额外配置么。
每次运行freeline.py，这个task要花去3min左右的时间。

**Comment by lomanyong** [comment]
@tianyutingxy freeline运行是有两个过程的。第一次会先执行一次全量编译，就是[gradle_clean_build_task] 这个流程，做初始化准备。然后再运行的话，每次都会是增量的，时间基本都在几秒。如果有修改Manifest或者build.gradle，freeline运行时就会自动再执行一次全量编译[gradle_clean_build_task]

**Comment by charvenhe** [comment]
@tianyutingxy 
gradle_clean_build_task 实际是调用Freeline 里面的DSL build_script 配置的命令，调用你们工程原来的指令进行打全量包，默认是./gradlew assembleDebug 

这几种情况会触发gradle_clean_build_task
1.加了 ”-f“ 参数
2.build.gradle 变化
3.Manifest 变化
4.更换经过增量后，更换了其他手机 ，导致了基线对齐失败
