### ISSUE TITLE
windows上有报这个错误

### ISSUE THREAD

**Issue by zhoujianhanyu** [alibaba/freeline#70]
Traceback (most recent call last):
  File "D:\Android\asworkspace\xxxx\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\Android\asworkspace\xxxx\freeline_core\gradle_clean_build.py", line 104, in execute
    output, err, code = cexec(self._config['build_script'].split(' '), callback=None, cwd=cwd)
  File "D:\Android\asworkspace\xxxx\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "D:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2]

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zhoujianhanyu hello，想问下你用的freeline的版本是多少的？以及你是否定义buildScript字段，使用了linux系统的命令，才导致这个问题呢？

**Comment by zhoujianhanyu** [comment]
freeline的版本是0.5.5。在build.gradle配置了multiDex，没有定义buildScript，其它都是跟sample一样。在Mac上可以，window上就不行。

**Comment by zhoujianhanyu** [comment]
@lomanyong freeline的版本是0.5.5，在build.gradle上配置了multiDex，没有定义buildScript字段。除了引用第三方插件外，其它的配置都跟sample一样。

**Comment by lomanyong** [comment]
@zhoujianhanyu 可以麻烦贴下完整的日志吗？报这个错的完整的日志..

**Comment by zhoujianhanyu** [comment]
@lomanyong D:\Android\asworkspace\xxxxxxxx>python freeline.py
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=False, init=False, version=False)
[DEBUG] final apk not found, need a clean build.
[DEBUG] collecting project info, please wait a while...
[DEBUG] update apk time path: D:\Android\asworkspace\xxxxxxxxxx\app\build\freeline\freeline-assets\apktime
[DEBUG] new clean build flag value: 598000
[DEBUG] [task_engine] depth: 1, task: [read_project_info_task]
[DEBUG] [task_engine] depth: 1, task: [generate_file_stat_task]
[DEBUG] [task_engine] depth: 2, task: [gradle_clean_build_task]
[DEBUG] [task_engine] depth: 3, task: [clean_all_cache_task]
[DEBUG] [task_engine] depth: 3, task: [install_apk_task]
[DEBUG] [task_engine] depth: 4, task: [build_base_resource_task]
[DEBUG] [task_engine] depth: 4, task: [generate_project_info_task]
[DEBUG] [read_project_info_task] read_project_info_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task start to run after waiting 0.0s
[DEBUG] [generate_file_stat_task] generate_file_stat_task finish in 0.2s
[DEBUG] [read_project_info_task] read_project_info_task finish in 8.3s
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task start to run after waiting 8.3s
[DEBUG] [gradle_clean_build_task] gradle.bat assembleDevelopDebug
[DEBUG] [gradle_clean_build_task] Gradle build task is running, please wait a minute...
[DEBUG] [gradle_clean_build_task] gradle_clean_build_task finish in 0.0s
[DEBUG] [clean_all_cache_task] clean_all_cache_task start to run after waiting 8.3s
[DEBUG] [install_apk_task] install_apk_task start to run after waiting 8.3s
[DEBUG] [build_base_resource_task] build_base_resource_task start to run after waiting 8.3s
[DEBUG] [generate_project_info_task] generate_project_info_task start to run after waiting 8.1s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 8.26s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Traceback (most recent call last):
  File "D:\Android\asworkspace\xxxxxxxxx\freeline_core\task.py", line 123, in execute
    self.task.execute()
  File "D:\Android\asworkspace\xxxxxxxxx\freeline_core\gradle_clean_build.py", line 104, in execute
    output, err, code = cexec(self._config['build_script'].split(' '), callback=None, cwd=cwd)
  File "D:\Android\asworkspace\xxxxxxxxxx\freeline_core\utils.py", line 28, in cexec
    p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env, cwd=cwd)
  File "D:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2]

[ERROR] --------------------------------------------------------
[ERROR] unexpected exception within task
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 8.3s
[DEBUG] Total time: 8.5s
[DEBUG] --------------------------------------------------------

**Comment by zhoujianhanyu** [comment]
@lomanyong 换成0.6.0后错误信息不一样了。D:\Android\asworkspace\xxxxxx\app\src\main\res\values\styles.xml:19: error: Error: No resource found that matches the given name: attr 'windowActionBar'.

D:\Android\asworkspace\xxxxxxxxx\app\src\main\res\values\styles.xml:18: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.


[ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline\release-tools\FreelineAapt.exe package -f -I D:\Android\sdk\platforms\android-23\android.jar -M 
D:\Android\asworkspace\xxxxxxx\app\build\intermediates\manifests\full\develop\debug\AndroidManifest.xml -S D:\Android\asworkspace\xxxxxxxx\app\src\main\res -S D:\Android\asworkspace\xxxxxxx\app\build\freeline\app\backup\res -A 
D:\Android\asworkspace\xxxxxxxxx\app\build\freeline\freeline-assets -A D:\Android\asworkspace\xxxxxxxx\app\src\main\assets -m -J 
D:\Android\asworkspace\xxxxxx\app\build\freeline\app\backup --auto-add-overlay -F D:\Android\asworkspace\xxxxxx\app\build\freeline\base-res.so --debug-mode --resoucres-md5-cache-path 
D:\Android\asworkspace\xxxxxx\app\build\freeline\arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.*
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 40.3s
[DEBUG] Total time: 40.6s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@zhoujianhanyu 可以麻烦截下`styles.xml`这个文件相关的报错位置的代码吗？以及，这段报错log可以贴详细点，方便我们分析哈~

**Comment by zhoujianhanyu** [comment]
@lomanyong 
    <style name="Theme.AppCompat.Light.NoActionBar.FullScreen" parent="@style/Theme.AppCompat.Light">
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
    </style>

貌似是appcompat这个库的资源加载出错，但编译安装成功。即使不改代码，每次都会重新编译。

**Comment by charvenhe** [comment]
@zhoujianhanyu 收到，可以暂时先用0.55 版本，我们先进行排查

**Comment by charvenhe** [comment]
@zhoujianhanyu 最新0.6.2试试看解决了没

**Comment by charvenhe** [comment]
@zhoujianhanyu 问题解决了么？没有的话加我们微信群我们单独跟进看看
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)

**Comment by zhoujianhanyu** [comment]
@lomanyong 现在可以用了，多谢你们哈！windows平台不是经常用，还没发现什么问题。mac平台上修改次数多了，有时候会没效果，还碰过一次ui都错乱了。重新强制全部编译才ok。

**Comment by charvenhe** [comment]
@zhoujianhanyu 没效果可能是Application类引用的问题，我们下个迭代会加入这个优化，UI错乱的下次保留下错乱的日志发出来我们定位下

**Comment by zhoujianhanyu** [comment]
@charvenhe 好的，辛苦了各位大神。

**Comment by shenquan** [comment]
@zhoujianhanyu 请问一下你怎么解决的呀

**Comment by zhoujianhanyu** [comment]
@shenquan 年前我在Windows上用0.7.0/0.7.2版本可以。不知道最新版本行不行。你试一下如果最新版本不行就往后一个个版本试试。我的项目不管是mac还是Windows用0.8.4版本是不行的，但0.8.5是可以。

**Comment by shenquan** [comment]
@zhoujianhanyu  谢谢啊  请问你加群了吗  把我拉进去我的微信号:hanshenquan1991

**Comment by shenquan** [comment]
@zhoujianhanyu 我们加个微信吧：）

**Comment by shenquan** [comment]
@zhoujianhanyu  我这边发现0.8.5出这个问题，0.8.3没有这个问题。
