### ISSUE TITLE
Apt1.8似乎和freeline不兼容

### ISSUE THREAD

**Issue by hiperioncn** [alibaba/freeline#703]
当我使用freeline时，无法引入apt1.8, 1.6版本可以正常编译。
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
Gradle sync时报如图错误：
<img width="433" alt="apt-error" src="https://cloud.githubusercontent.com/assets/6045710/23696843/67431e70-0420-11e7-873e-000f6f371970.png">

**Comment by lomanyong** [comment]
@hiperioncn 貌似没有遇见过这个问题，确认是 freeline 导致的吗？

目前 android 也已经原生支持了 apt 了，不使用 android-apt 这个库也可以的

**Comment by hiperioncn** [comment]
只注释掉freeline 的plugin就可正常编译apt1.8，工程其它文件一点没改。
//apply plugin: 'com.antfortune.freeline'
