### ISSUE TITLE
慎重选择freeline

### ISSUE THREAD

**Issue by hanshengjian** [alibaba/freeline#706]
和instant run 做了比较，增量编译速度反而instant run快，全量编译的速度占优，优势将近2倍左右。因为加入包依赖，加入插件依赖，要在application中加入FreelinCore.init(this),入侵了代码。综上，instant run在速度上不占劣势，而且没有侵入代码，还是选择instant run比较明智。而且freeline还有个bug，启动app的时候，并没有查找配置文件，仅将MainActivity.java作为入口，但很多都有以WelocomeActivity或者其他作为入口，越过welcomeActivity,直接进入MainActivity,肯定不对。

**Comment by lomanyong** [comment]
@hanshengjian 对于一些简单的工程 Freeline 对比其他的加速编译工具没有太多明显的优势。更多的优势在于企业级的复杂架构工程，尤其是数十个 module 的工程混合开发的情况，freeline 的优势还是很明显的。Android 要解决这个问题还得等到 android gradle plugin 2.5 正式 release，目前还在 preview 阶段，最快也得数个月之后才会发布，到时可以看下具体的效果。

侵入性的问题，默认情况下是无侵入的（跟 Instant Run 的实现一样），同时也提供了 no-op 依赖。

至于 bug 的问题，默认读取了第一个 Launcher Activity。

**Comment by xlg** [comment]
freeline已经用很久了，但是现在痛苦感很强。因为项目很大，改动个别文件和代码，会发现根本没有跑上去，只能删了程序重新跑一遍，一天要遇到好几次。

**Comment by lomanyong** [comment]
@xlg 可以把你遇见的具体case邮件给我吗？可能是某些改动踩到坑了
