### ISSUE TITLE
连接不上设备

### ISSUE THREAD

**Issue by bright999** [alibaba/freeline#71]
我按照github的教程一步步走下去，在project根目录执行python freeline.py -f 命令，结果报SyntaxError: encoding problem: utf8错误，我的python版本是Python 3.5.2,项目根目录下的freeline.py内容是:
#!/usr/bin/python
# -*- coding:utf8 -*-
from argparse import ArgumentParser

from freeline_core.dispatcher import Dispatcher
from freeline_core.init import init
....

如果我去掉# -*- coding:utf8 -*-那句去掉后再执行python freeline.py -f 命令就报另外一个错误：
 File "freeline.py", line 4, in <module>
    from freeline_core.dispatcher import Dispatcher
  File "D:\projectName\freeline_core\__init__.py", line 1, in <module>
    import build_commands
ImportError: No module named 'build_commands'

但是我查看了D:\projectName\freeline_core\__init__.py文件
import build_commands
import builder
import command
import dispatcher
import exceptions
import task
import tracing
import utils
在D:\projectName\freeline_core下有build_commands.py，内容为
# -*- coding:utf8 -*-
from command import AbstractBuildCommand, MacroCommand

class CleanBuildCommand(AbstractBuildCommand):
    def __init__(self, builder):
        AbstractBuildCommand.__init__(self, builder, command_name='clean_build')
        self._setup()

    def execute(self):
        map(lambda command: command.execute(), self.command_list)

    def _setup(self):
        self.add_command(CheckBulidEnvironmentCommand(self._builder))
        self.add_command(FindDependenciesOfTasksCommand(self._builder))
        self.add_command(GenerateSortedBuildTasksCommand(self._builder))
        self.add_command(UpdateApkCreatedTimeCommand(self._builder))
        self.add_command(ExecuteCleanBuildCommand(self._builder))
...
我对python不是很懂，有什么可以配合组织来解决此问题的，请支声

**Comment by charvenhe** [comment]
@bright999，freeline不支持3.0的python,可以换成2.7试试

**Comment by bright999** [comment]
非常不错，我已经可以跑起来了，但我试改了一下java代码，然后使用python freeline.py命令运行程序，结果却没有把java改动的那部分更新到手机里，而使用python freeline.py -f却可以，有点不太明白，这是否问题？

**Comment by lomanyong** [comment]
@bright999 java不生效的时候有具体的日志可以贴出来看看嘛？`python freeline.py -d`可以看到具体的日志...

**Comment by bright999** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False)
[DEBUG] [scan_changed_files_command] find D:\projectname\projectname_android_1.0\res\layout\splash.xml has modification.
[DEBUG] [scan_changed_files_command] find D:\projectname\projectname_android_1.0\src\com\projectname\android\member\activities\WelcomeActivity.java has modification.
[DEBUG] find HuanXinLibRes has 0 java files modified.
[DEBUG] find projectname_android_1.0 has 1 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1472809088.6015687,
        "is_root_config_changed": false
    },
    "projects": {
        "HuanXinLibRes": {
            "src": [],
            "assets": [],
            "res": [],
            "manifest": [],
            "libs": [],
            "config": []
        },
        "projectname_android_1.0": {
            "src": [
                "D:\\projectname\\projectname_android_1.0\\src\\com\\projectname\\android\\member\\activities\\WelcomeActivity.java"
            ],
            "assets": [],
            "res": [
                "D:\\projectname\\projectname_android_1.0\\res\\layout\\splash.xml"
            ],
            "manifest": [],
            "libs": [],
            "config": []
        }
    }
}
[DEBUG] [gradle_inc_builder] find projectname_android_1.0 modules have res changed
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [HuanXinLibRes]
[DEBUG] [task_engine] depth: 2, task: [projectname_android_1.0]
[DEBUG] [task_engine] depth: 4, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 6, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 7, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 8, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [projectname_android_1.0_inc_invoker] find projectname_android_1.0 has resource files modification.
[DEBUG] [sync_client] apktime path: D:\projectname\projectname_android_1.0\build\freeline\freeline-assets\apktime
[DEBUG] [gradle_aapt_task] start to execute aapt command...
[DEBUG] [sync_client] your local sync value is: 377000
[DEBUG] [tracing] generate_id_keeper_files: 0.999927520752ms
[DEBUG] [projectname_android_1.0_inc_invoker] find relative path: res\layout\splash.xml
[DEBUG] [projectname_android_1.0_inc_invoker] find relative path: res\values\freeline_id_keeper_public.xml
[DEBUG] [projectname_android_1.0_inc_invoker] find relative path: res\values\freeline_id_keeper_ids.xml
[DEBUG] [projectname_android_1.0_inc_invoker] aapt exec: freeline\release-tools\FreelineAapt.exe package -f -I C:\android\sdk\platforms\android-22\android.jar -M D:\projectname\projectname_android_1.0\build\intermediates\manifests\fu
ll\brand\debug\AndroidManifest.xml -S D:\projectname\projectname_android_1.0\res -S D:\projectname\HuanXinLibRes\res -S D:\projectname\projectname_android_1.0\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\res -S D:\mama
100\projectname_android_1.0\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.5.5\res -S D:\projectname\projectname_android_1.0\build\generated\res\rs\brand\debug -S D:\projectname\projectname_android_1.0\build\freeline\ma
ma100_android_1.0\backup\res -A D:\projectname\projectname_android_1.0\build\freeline\freeline-assets -A D:\projectname\projectname_android_1.0\assets --custom-package com.projectname.android.member -m -J D:\projectname\projectname_android_1.0\b
uild\freeline\projectname_android_1.0\backup --auto-add-overlay -P D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\res\values\freeline_id_keeper_public.xml -F D:\projectname\projectname_android_1.0\build\
freeline\projectname_android_1.0\respack\projectname_android_1.0.pack --debug-mode --auto-add-overlay --ignore-assets public_id.xml:public.xml:*.bak:.*
[DEBUG] [projectname_android_1.0_inc_invoker] aapt use time: 8115.00000954ms
[DEBUG] [projectname_android_1.0_inc_invoker] merged_changed_list:
[DEBUG] [projectname_android_1.0_inc_invoker] [u'res/layout/splash.xml', u'res/values/freeline_id_keeper_public.xml', u'res/values/freeline_id_keeper_ids.xml']
[DEBUG] [tracing] run_incremental_aapt_task: 8520.99990845ms
[DEBUG] [projectname_android_1.0_inc_invoker] modify D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\com\projectname\android\member\R.java
[DEBUG] [projectname_android_1.0_inc_invoker] avoid windows unicode error for D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\com\projectname\android\member\R.java
[DEBUG] [projectname_android_1.0_inc_invoker] copy D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\com\projectname\android\member\R.java to D:\projectname\projectname_android_1.0\build\freeline\freeline-backu
p-r\com\projectname\android\member\R.java
[DEBUG] [projectname_android_1.0_inc_invoker] modify D:\projectname\projectname_android_1.0\build\freeline\freeline-backup-r\com\projectname\android\member\R.java
[DEBUG] [tracing] check_other_modules_resources: 15.0001049042ms
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 8.5s
[DEBUG] [HuanXinLibRes] HuanXinLibRes start to run after waiting 8.5s
[DEBUG] [projectname_android_1.0] projectname_android_1.0 start to run after waiting 8.5s
[DEBUG] [HuanXinLibRes_inc_invoker] HuanXinLibRes old R.java path: D:\projectname\HuanXinLibRes\build\generated\source\r\androidTest\debug\com\bs\R.java
[DEBUG] [HuanXinLibRes_inc_invoker] HuanXinLibRes new R.java path: None
[DEBUG] [projectname_android_1.0_inc_invoker] projectname_android_1.0 old R.java path: D:\projectname\projectname_android_1.0\build\generated\source\r\brand\debug\com\projectname\android\member\R.java
[DEBUG] [projectname_android_1.0_inc_invoker] projectname_android_1.0 new R.java path: D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\com\projectname\android\member\R.java
[DEBUG] [HuanXinLibRes_inc_invoker] src changed files:
[DEBUG] [HuanXinLibRes_inc_invoker] []
[DEBUG] [HuanXinLibRes_inc_invoker] HuanXinLibRes project has no change, need not go ahead
[DEBUG] [HuanXinLibRes_inc_invoker] HuanXinLibRes code only change R.java, need not go ahead
[DEBUG] [HuanXinLibRes_inc_javac_compile] no need to execute
[DEBUG] [HuanXinLibRes_inc_dex_compile] no need to execute
[DEBUG] [HuanXinLibRes] HuanXinLibRes finish in 0.0s
[DEBUG] [projectname_android_1.0_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [projectname_android_1.0_inc_invoker] src changed files:
[DEBUG] [projectname_android_1.0_inc_invoker] [u'D:\\projectname\\projectname_android_1.0\\src\\com\\projectname\\android\\member\\activities\\WelcomeActivity.java', u'D:\\projectname\\projectname_android_1.0\\build\\freeline\\projectname_android_
1.0\\backup\\com\\projectname\\android\\member\\R.java']
[DEBUG] [projectname_android_1.0_inc_invoker] find R.java modified in src list
[DEBUG] [projectname_android_1.0_inc_javac_compile] start to execute javac command...
[DEBUG] [projectname_android_1.0_inc_invoker] avoid windows unicode error for D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\com\projectname\android\member\R.java
[DEBUG] [projectname_android_1.0_inc_invoker] javac exec: C:\Program Files\Java\jdk1.8.0_101\bin\javac.exe -target 1.7 -source 1.7 -encoding UTF-8 -g -cp D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\cla
sses;D:\projectname\projectname_android_1.0\build\intermediates\classes\brand\debug;C:\android\sdk\platforms\android-22\android.jar;D:\projectname\projectname_android_1.0\libs\android_api_3.7.0.8.jar;D:\projectname\projectname_android_1.0\libs
\locSDK_3.3.jar;D:\projectname\projectname_android_1.0\libs\alipaySDK-20150610.jar;D:\projectname\projectname_android_1.0\libs\patcher.jar;D:\projectname\projectname_android_1.0\libs\UPPayAssistEx.jar;D:\projectname\projectname_android_1.0\libs\baid
umapapi_v3_4_0.jar;D:\projectname\projectname_android_1.0\libs\zbar.jar;D:\projectname\projectname_android_1.0\libs\GetuiSDK2.9.0.0.jar;D:\projectname\projectname_android_1.0\libs\libammsdk.jar;D:\projectname\projectname_android_1.0\libs\umeng-analy
tics-v5.5.3.jar;D:\projectname\projectname_android_1.0\libs\apache-mime4j-0.5.jar;D:\projectname\projectname_android_1.0\libs\open_sdk_r4346_lite.jar;D:\projectname\projectname_android_1.0\libs\gson-2.1.jar;D:\projectname\projectname_android_1.0\lib
s\commons-codec.jar;D:\projectname\projectname_android_1.0\libs\UPPayPluginExStd.jar;D:\projectname\projectname_android_1.0\libs\httpmime-4.0-beta2.jar;D:\projectname\projectname_android_1.0\build\intermediates\exploded-aar\com.antfortune.free
line\runtime\0.5.5\jars\classes.jar;D:\projectname\projectname_android_1.0\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\jars\classes.jar;D:\projectname\projectname_android_1.0\build\intermediates\exploded-aar\mama1
00\HuanXinLibRes\unspecified\jars\classes.jar;D:\projectname\projectname_android_1.0\build\intermediates\exploded-aar\projectname\HuanXinLibRes\unspecified\jars\libs\android-support-v4.jar;D:\projectname\projectname_android_1.0\build\interme
diates\exploded-aar\projectname\HuanXinLibRes\unspecified\jars\libs\chatlib.jar;D:\projectname\projectname_android_1.0\build\intermediates\exploded-aar\projectname\HuanXinLibRes\unspecified\jars\libs\easemobchat_2.2.9.jar D:\projectname\mama10
0_android_1.0\src\com\projectname\android\member\activities\WelcomeActivity.java D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\com\projectname\android\member\R.java -d D:\projectname\projectname_android_1.0
\build\freeline\projectname_android_1.0\classes
[DEBUG] [projectname_android_1.0_inc_invoker] copy D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\backup\com\projectname\android\member\R.java to D:\projectname\projectname_android_1.0\build\generated\source\r\bran
d\debug\com\projectname\android\member\R.java
[DEBUG] [projectname_android_1.0_inc_dex_compile] start to execute dex command...
[DEBUG] [projectname_android_1.0_inc_invoker] dex exec: C:\android\sdk\build-tools\22.0.1\dx.bat --dex --output=D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\dex\projectname_android_1.0.dex D:\projectname\mama
100_android_1.0\build\freeline\projectname_android_1.0\classes
[DEBUG] [sync_client] apktime path: D:\projectname\projectname_android_1.0\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 377000
[DEBUG] [projectname_android_1.0] projectname_android_1.0 finish in 3.1s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 11.6s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy D:\projectname\projectname_android_1.0\build\freeline\projectname_android_1.0\dex\projectname_android_1.0.dex to D:\projectname\projectname_android_1.0\build\freeline\increment.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 12.3s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 12.3s
[DEBUG] [sync_client] HuanXinLibRes has no need to sync inc res pack.
[DEBUG] [sync_client] start to sync projectname_android_1.0 incremental res pack...
[DEBUG] [sync_client] projectname_android_1.0 pack size: 6443kb
[DEBUG] [sync_client] pushres: http://127.0.0.1:41128/pushResource?mode=full&bundleId=base-res
[DEBUG] [sync_client] sync projectname_android_1.0 incremental res pack finished
[DEBUG] [sync_client] start to sync incremental dex...
[DEBUG] [sync_client] pushdex: http://127.0.0.1:41128/pushDex
[DEBUG] [sync_client] start to sync close longlink...
[DEBUG] [sync_client] closeLongLink: http://127.0.0.1:41128/closeLongLink?no&lastSync=1
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 1.8s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 5.5s
[DEBUG] [clean_cache_task] refresh projectname_android_1.0 ids.xml
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 5.5s
[DEBUG] [update_stat_task] refresh D:\projectname\projectname_android_1.0\src\com\projectname\android\member\activities\WelcomeActivity.java stat
[DEBUG] [update_stat_task] refresh D:\projectname\projectname_android_1.0\res\layout\splash.xml stat
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 14.17s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 14.2s
[DEBUG] Total time: 14.5s
[DEBUG] --------------------------------------------------------


我在WelcomeActivity文件中增加了提示代码，结果却不提示，如果python freeline.py -f就会提示，您看还有什么需要我这边配合的

**Comment by charvenhe** [comment]
@bright999 FreelineCore.init的代码你是哪里调用的，是否在Application有引用到这个类呢

**Comment by bright999** [comment]
@charvenhe FreelineCore.init在Application中的onCreate()调用，在Application有用到WelcomeActivity，不过在FreelineCore.init之后的异常情况下

**Comment by charvenhe** [comment]
@bright999 是类的加载时序，你试试对非Appliction引用到的类进行修改试试，这个问题我们后面会进行优化

**Comment by bright999** [comment]
@charvenhe  还有我刚刚python freeline.py命令时[DEBUG] [sync_client] try to connect device 18 times...
[DEBUG] [sync_client] apktime path: D:\projectname\projectname_android_1.0\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 377001
[DEBUG] [sync_client] try to connect device 19 times...
[DEBUG] [sync_client] apktime path: D:\projectname\projectname_android_1.0\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 377001
[DEBUG] [sync_client] try to connect device 20 times...
[DEBUG] [sync_client] apktime path: D:\projectname\projectname_android_1.0\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 377001
出现这个问题，而我使用android studio run运行就不会，所以反馈给组织

**Comment by charvenhe** [comment]
@bright999 ，连接不上的问题我们正在定位，方便的话可以进我们微信群，我们专门跟进

**Comment by lomanyong** [comment]
@bright999 可以把runtime改为这个版本：`compile 'com.antfortune.freeline:runtime:0.6.0.1609051840'`，试试看是否可以稳定连接上app。

**Comment by bright999** [comment]
@charvenhe  @lomanyong  logcat窗口一直会提示如下错误：
09-08 19:10:56.070 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.DisplayImageOptions.<init>
09-08 19:10:56.070 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.display.RoundedBitmapDisplayer.<init>
09-08 19:10:56.070 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.display.RoundedBitmapDisplayer.<init>
09-08 19:10:56.070 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.memory.impl.FuzzyKeyMemoryCache.<init>
09-08 19:10:56.070 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder.<init>
09-08 19:10:56.075 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.utils.MemoryCacheUtils.<init>
09-08 19:10:56.075 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.assist.QueueProcessingType.<init>
09-08 19:10:56.075 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.utils.MemoryCacheUtils$1.<init>
09-08 19:10:56.075 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.memory.impl.LruMemoryCache.<init>
09-08 19:10:56.075 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.download.BaseImageDownloader.<init>
09-08 19:10:56.075 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.download.BaseImageDownloader.<init>
09-08 19:10:56.075 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.utils.L.<init>
09-08 19:10:56.080 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.naming.HashCodeFileNameGenerator.<init>
09-08 19:10:56.080 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.assist.deque.LIFOLinkedBlockingDeque.<init>
09-08 19:10:56.080 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.decode.BaseImageDecoder.<init>
09-08 19:10:56.080 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.assist.deque.LinkedBlockingDeque.<init>
09-08 19:10:56.080 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.assist.deque.LinkedBlockingDeque.<init>
09-08 19:10:56.080 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.assist.deque.LinkedBlockingDeque.<init>
09-08 19:10:56.080 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.ImageLoaderConfiguration.<init>
09-08 19:10:56.080 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.ImageLoaderConfiguration.<init>
09-08 19:10:56.085 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.ImageLoaderConfiguration$NetworkDeniedImageDownloader.<init>
09-08 19:10:56.085 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.ImageLoaderConfiguration$SlowNetworkImageDownloader.<init>
09-08 19:10:56.085 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.DefaultConfigurationFactory$DefaultThreadFactory.<init>
09-08 19:10:56.085 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.core.ImageLoaderEngine.<init>
09-08 19:10:56.085 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.utils.StorageUtils.<init>
09-08 19:10:56.085 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.projectname.android.member.util.StorageUtils.<init>
09-08 19:10:56.090 2984-3543/? E/PowerManagerService: Exception when search wack lock :java.lang.IllegalArgumentException: Wake lock not active
09-08 19:10:56.100 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiskCache.<init>
09-08 19:10:56.100 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiskCache.<init>
09-08 19:10:56.100 15564-15630/com.projectname.android.member E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.projectname.android.member.util.DesUtils.<init>
09-08 19:10:56.100 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.<init>
09-08 19:10:56.110 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache$2.<init>
09-08 19:10:56.110 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache$1.<init>
09-08 19:10:56.110 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.StrictLineReader.<init>
09-08 19:10:56.115 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.StrictLineReader.<init>
09-08 19:10:56.115 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.Util.<init>
09-08 19:10:56.115 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache$Entry.<init>
09-08 19:10:56.115 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache$Entry.<init>
09-08 19:10:56.115 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache$Editor.<init>
09-08 19:10:56.120 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache$Editor.<init>
09-08 19:10:56.130 15623-15658/com.projectname.android.member:freeline E/dalvikvm: Could not find class 'com.micro.freeline.hackload.ClassVerifier', referenced from method com.nostra13.universalimageloader.cache.disc.impl.ext.StrictLineReader$1.<init>
我把这种情况反馈给组织

**Comment by lomanyong** [comment]
@bright999 这个问题我们晚上发版就会解决~

**Comment by bright999** [comment]
@lomanyong 收到，感谢你们的付出和努力！！！

**Comment by lomanyong** [comment]
@bright999 你那边连接不上的问题目前如何了呢？

**Comment by charvenhe** [comment]
@bright999 尝试更新0.6.1版本看看是否已经解决

**Comment by charvenhe** [comment]
@bright999 ，连接不上的问题加我们微信群我们单独跟进看看
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)

**Comment by charvenhe** [comment]
0.7已经进行专门处理，后续有类似问题移步这里讨论 #152
