### ISSUE TITLE
怎么才能卸载freeline

### ISSUE THREAD

**Issue by huangbom** [alibaba/freeline#714]
你好，我要删除freeline，是把freeline这几个文件删除就可以了吗

![6 44 09](https://cloud.githubusercontent.com/assets/23350159/23851136/4ed27718-081d-11e7-9baa-6ac51b3a183e.png)

**Comment by lomanyong** [comment]
@huangbom 删除这几个文件，以及在build.gradle中添加的相关依赖即可
