### ISSUE TITLE
真机没有问题，但是用模拟器一运行就就断开连接

### ISSUE THREAD

**Issue by sdfdzx** [alibaba/freeline#716]
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Use `adb devices` to check your device connection
[ERROR] --------------------------------------------------------
[ERROR] No device's connection found

还有一个问题，插件装不上
![default](https://cloud.githubusercontent.com/assets/20917145/23892162/7418e81a-08d4-11e7-9100-22f106ade67f.png)

**Comment by lomanyong** [comment]
@sdfdzx 插件安装不上请确认是否是网络问题...

模拟器和真机不能同时连接...
