### ISSUE TITLE
莫名的经常丢失R文件

### ISSUE THREAD

**Issue by AceInAndroid** [alibaba/freeline#718]
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.antfortune.freeline:gradle:0.8.6'

没有错误日志,R文件经常丢失,很奇怪,自从升级到新版的gradle
classpath 'com.android.tools.build:gradle:2.3.0'

就开始出现这个问题

也许这不是一条有建设性的意见,但是还是十分想解决

**Comment by lomanyong** [comment]
@AceInAndroid 指的是什么丢失？什么表现呢？

**Comment by AceInAndroid** [comment]
用freeline编译的时候 项目的R.java文件经常找不到，比如说 R.layout.activity_my_points 资源文件就找不到了。普通编译没问题

**Comment by AceInAndroid** [comment]
必须重新build

**Comment by lomanyong** [comment]
@AceInAndroid 应该是指在 IDE 里 R.java 文件没有找到吧？还是编译的时候报错了？

**Comment by AceInAndroid** [comment]
用freeline编译完成后 ，IDE 里 R.java 文件就找不到了 ，R.java 找不到了还是可以用freeline编译

**Comment by lomanyong** [comment]
@AceInAndroid 工程有什么特殊的配置吗？这个类似的问题在挺早之前解决过，解决的是某些特殊配置导致的，之前是不同的library flavor的原因...

**Comment by LZHIQI** [comment]
我也出先这个东西了

**Comment by LZHIQI** [comment]
刷新下gradle路径就好了，但是多个步骤，真的很不爽

**Comment by AceInAndroid** [comment]
我发现是因为我另外配置gradle 造成的  现在改成默认的 ok了

**Comment by bbssyyuui** [comment]
我也遇到这个问题，解决的同学给下解决方案呗。。

**Comment by bbssyyuui** [comment]
有人说是因为Android Studio 2.3的兼容问题，我用的是2.3

**Comment by CoderWuao** [comment]
我也是这个问题,今天才更新到2.3,使用freeline编译之后,所有引用R文件的地方就找不到包了

**Comment by loody** [comment]
同上

**Comment by marnon7** [comment]
同上 2.3

**Comment by Pr-Jiang** [comment]
2.3.3  所以 ，现在又解决办法吗？

**Comment by kowk** [comment]
楼主 求解决方案啊

**Comment by ChangSpring** [comment]
Android Studio 2.3.3 版本  freeline编译出现R文件丢失  Android studio run R文件就有了  怎么搞....

**Comment by ChangSpring** [comment]
@AceInAndroid 你是gradle哪个地方配置出了问题呢 求解
