### ISSUE TITLE
declared here is not defined.   design 资源问题

### ISSUE THREAD

**Issue by sqc0720** [alibaba/freeline#719]
compile 'com.android.support:design:25.2.0'
freeline 0.8.6
看到你们在0.8.5 的版本已经 close 了之前的issue  为什么我还会出现
E:\New Work\Kdkj_cpa\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1260: error: Public symbol drawable/avd_hide_password_1 declared here is not defined.
E:\New Work\Kdkj_cpa\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1262: error: Public symbol drawable/avd_hide_password_2 declared here is not defined.
E:\New Work\Kdkj_cpa\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1264: error: Public symbol drawable/avd_hide_password_3 declared here is not defined.
E:\New Work\Kdkj_cpa\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1266: error: Public symbol drawable/avd_show_password_1 declared here is not defined.
E:\New Work\Kdkj_cpa\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1268: error: Public symbol drawable/avd_show_password_2 declared here is not defined.
E:\New Work\Kdkj_cpa\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1270: error: Public symbol drawable/avd_show_password_3 declared here is not defined.

**Comment by lomanyong** [comment]
@sqc0720 windows暂时未能支持，windows的aapt有点问题，会再重新打包解决

**Comment by simpleton** [comment]
@lomanyong 想请教造成这个issue的原因是什么呢？多谢了。

**Comment by tangchiech** [comment]
使用0.8.7，同样会出现类似问题

**Comment by Febare** [comment]
使用0.8.7，同样会出现类似问题

**Comment by ixueming** [comment]
使用0.8.8 同样会出现类似问题
