### ISSUE TITLE
修改布局文件增量没有效果

### ISSUE THREAD

**Issue by chen2991101** [alibaba/freeline#720]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.3.0
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.6
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.6
[DEBUG] [scan_changed_files_command] find /Users/hao/dev/android/workspace/android_driver/personal/src/main/res/layout/per_item_truck.xml has modification.
[DEBUG] find personal has 0 java files modified.
[DEBUG] find app has 0 java files modified.
[DEBUG] find api has 0 java files modified.
[DEBUG] find utils has 0 java files modified.
[DEBUG] find business has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "stat_md5": {},
    "build_info": {
        "last_clean_build_time": 1489493632.0,
        "is_root_config_changed": false
    },
    "projects": {
        "personal": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [
                "/Users/hao/dev/android/workspace/android_driver/personal/src/main/res/layout/per_item_truck.xml"
            ],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "app": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "api": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "utils": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        },
        "business": {
            "src": [],
            "so": [],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [gradle_inc_builder] find personal modules have res changed
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [api]
[DEBUG] [task_engine] depth: 3, task: [utils]
[DEBUG] [task_engine] depth: 4, task: [business]
[DEBUG] [task_engine] depth: 4, task: [personal]
[DEBUG] [task_engine] depth: 6, task: [app]
[DEBUG] [task_engine] depth: 7, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 9, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 10, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 11, task: [update_stat_task]
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [app_inc_invoker] find app has resource files modification.
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] start to execute aapt command...
[DEBUG] [sync_client] apktime path: /Users/hao/dev/android/workspace/android_driver/app/build/freeline/freeline-assets/apktime
[DEBUG] [tracing] generate_id_keeper_files: 0.316143035889ms
[DEBUG] [tracing] incremental_databinding_process: 0.053882598877ms
[DEBUG] [sync_client] your local sync value is: 838904
[DEBUG] [sync_client] your local uuid value is: 838901
[DEBUG] [app_inc_invoker] find relative path: res/layout/per_item_truck.xml
[DEBUG] [app_inc_invoker] find relative path: res/values/freeline_id_keeper_public.xml
[DEBUG] [app_inc_invoker] find relative path: res/values/freeline_id_keeper_ids.xml
[DEBUG] [app_inc_invoker] aapt exec: freeline/release-tools/FreelineAapt package -f -I /Users/hao/Library/Android/sdk/platforms/android-25/android.jar -M /Users/hao/dev/android/workspace/android_driver/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/hao/dev/android/workspace/android_driver/app/src/main/res -S /Users/hao/.android/build-cache/88c9708e554858c0e6dc4e0707cf3b8884b4cbf3/output/res -S /Users/hao/.android/build-cache/81c8b73f3e0d2c437353b7b5ef89c6a053ff0f52/output/res -S /Users/hao/dev/android/workspace/android_driver/business/build/intermediates/bundles/default/res -S /Users/hao/.android/build-cache/dfeb779a2bf01a83a0ecbaf3150472c1ec179c55/output/res -S /Users/hao/dev/android/workspace/android_driver/app/build/generated/res/rs/debug -S /Users/hao/.android/build-cache/840ffe3c1e4b05a2abc2d4832822a632beb184d2/output/res -S /Users/hao/dev/android/workspace/android_driver/api/build/intermediates/bundles/default/res -S /Users/hao/.android/build-cache/dbd588a202d1b1039774083c7cb3cc7278dd2a27/output/res -S /Users/hao/.android/build-cache/d2b5fe00b824721e26e2349a19767bd2cb0019ca/output/res -S /Users/hao/.android/build-cache/cab0d8076900fa5b7af0f05f53ac326314705090/output/res -S /Users/hao/.android/build-cache/101ae264894748da228f1f7312b3400c7d44a113/output/res -S /Users/hao/.android/build-cache/d133fb6861d858259888277e8c0dee554073b132/output/res -S /Users/hao/dev/android/workspace/android_driver/utils/build/intermediates/bundles/default/res -S /Users/hao/.android/build-cache/f5ade23dfb515dfa2ab63beb41d5eef6813f6b45/output/res -S /Users/hao/.android/build-cache/37b5d08e80e6502edf86132e107c8fd7edbb9046/output/res -S /Users/hao/.android/build-cache/df7af6bf8db01f8a32e96b89301452fbe7e85d55/output/res -S /Users/hao/.android/build-cache/8f7c48487eaad1600f08c8e4f549a5eb07e8b7d8/output/res -S /Users/hao/.android/build-cache/51375439558f6926062e80fca5e2e936d3af9894/output/res -S /Users/hao/.android/build-cache/ad50d5033c9890c3bfc4acd6f99c3a72556844f6/output/res -S /Users/hao/.android/build-cache/25a1084fdd1b42083170647a2db899f7f800a453/output/res -S /Users/hao/dev/android/workspace/android_driver/app/build/generated/res/resValues/debug -S /Users/hao/.android/build-cache/907db5dfa19021c124eacb3ec3a7ed56ac2a03d8/output/res -S /Users/hao/dev/android/workspace/android_driver/personal/build/intermediates/bundles/default/res -S /Users/hao/.android/build-cache/ea3a1af76022f68512ee79af590245d0e23e223a/output/res -S /Users/hao/.android/build-cache/79edcc6969b7957e67e295625cbef6ee9a0bafe6/output/res -S /Users/hao/.android/build-cache/95d837e6b5b78d3b7de7616233c02320b2447bdc/output/res -S /Users/hao/.android/build-cache/33f9b43ec2f2224c951bea8829f396cc34a133a6/output/res -S /Users/hao/.android/build-cache/51358a42abbd0f5c1c9ef65e72a036eb1176fb5b/output/res -S /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/backup/res -A /Users/hao/dev/android/workspace/android_driver/app/build/freeline/freeline-assets -A /Users/hao/dev/android/workspace/android_driver/app/src/main/assets -A /Users/hao/.android/build-cache/79edcc6969b7957e67e295625cbef6ee9a0bafe6/output/assets -A /Users/hao/.android/build-cache/33f9b43ec2f2224c951bea8829f396cc34a133a6/output/assets -A /Users/hao/.android/build-cache/907db5dfa19021c124eacb3ec3a7ed56ac2a03d8/output/assets -A /Users/hao/.android/build-cache/d2b5fe00b824721e26e2349a19767bd2cb0019ca/output/assets -A /Users/hao/.android/build-cache/ea3a1af76022f68512ee79af590245d0e23e223a/output/assets -A /Users/hao/.android/build-cache/81c8b73f3e0d2c437353b7b5ef89c6a053ff0f52/output/assets -A /Users/hao/dev/android/workspace/android_driver/business/build/intermediates/bundles/default/assets -A /Users/hao/.android/build-cache/dfeb779a2bf01a83a0ecbaf3150472c1ec179c55/output/assets -A /Users/hao/.android/build-cache/cab0d8076900fa5b7af0f05f53ac326314705090/output/assets -A /Users/hao/dev/android/workspace/android_driver/app/build/generated/assets/shaders/debug -A /Users/hao/.android/build-cache/51358a42abbd0f5c1c9ef65e72a036eb1176fb5b/output/assets -A /Users/hao/.android/build-cache/51375439558f6926062e80fca5e2e936d3af9894/output/assets -A /Users/hao/.android/build-cache/88c9708e554858c0e6dc4e0707cf3b8884b4cbf3/output/assets -A /Users/hao/.android/build-cache/840ffe3c1e4b05a2abc2d4832822a632beb184d2/output/assets -A /Users/hao/.android/build-cache/dbd588a202d1b1039774083c7cb3cc7278dd2a27/output/assets -A /Users/hao/.android/build-cache/101ae264894748da228f1f7312b3400c7d44a113/output/assets -A /Users/hao/dev/android/workspace/android_driver/api/build/intermediates/bundles/default/assets -A /Users/hao/.android/build-cache/ad50d5033c9890c3bfc4acd6f99c3a72556844f6/output/assets -A /Users/hao/dev/android/workspace/android_driver/utils/build/intermediates/bundles/default/assets -A /Users/hao/.android/build-cache/df7af6bf8db01f8a32e96b89301452fbe7e85d55/output/assets -A /Users/hao/dev/android/workspace/android_driver/personal/build/intermediates/bundles/default/assets -A /Users/hao/.android/build-cache/25a1084fdd1b42083170647a2db899f7f800a453/output/assets -A /Users/hao/.android/build-cache/8f7c48487eaad1600f08c8e4f549a5eb07e8b7d8/output/assets -A /Users/hao/.android/build-cache/37b5d08e80e6502edf86132e107c8fd7edbb9046/output/assets -A /Users/hao/.android/build-cache/d133fb6861d858259888277e8c0dee554073b132/output/assets -A /Users/hao/.android/build-cache/95d837e6b5b78d3b7de7616233c02320b2447bdc/output/assets -A /Users/hao/.android/build-cache/f5ade23dfb515dfa2ab63beb41d5eef6813f6b45/output/assets --custom-package com.jiajiabao.ucar -m -J /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/backup --auto-add-overlay -P /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/backup/res/values/freeline_id_keeper_public.xml -F /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/respack/app.pack --debug-mode --auto-add-overlay --no-version-vectors --buildIncrement res/layout/per_item_truck.xml:res/values/freeline_id_keeper_public.xml:res/values/freeline_id_keeper_ids.xml --resoucres-md5-cache-path /Users/hao/dev/android/workspace/android_driver/app/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.* --ignore-ids avd_hide_password_1:avd_hide_password_2:avd_hide_password_3:avd_show_password_1:avd_show_password_2:avd_show_password_3
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.1s
[DEBUG] [app_inc_invoker] aapt use time: 391.431093216ms
[DEBUG] [app_inc_invoker] merged_changed_list:
[DEBUG] [app_inc_invoker] [u'res/layout/per_item_truck.xml', u'res/values/freeline_id_keeper_public.xml', u'res/values/freeline_id_keeper_ids.xml']
[DEBUG] [tracing] run_incremental_aapt_task: 403.959035873ms
[DEBUG] [app_inc_invoker] modify /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/backup/com/jiajiabao/ucar/R.java
[DEBUG] [app_inc_invoker] copy /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/backup/com/jiajiabao/ucar/R.java to /Users/hao/dev/android/workspace/android_driver/app/build/freeline/freeline-backup-r/com/jiajiabao/ucar/R.java
[DEBUG] [app_inc_invoker] modify /Users/hao/dev/android/workspace/android_driver/app/build/freeline/freeline-backup-r/com/jiajiabao/ucar/personal/R.java
[DEBUG] [tracing] check_other_modules_resources: 7.37714767456ms
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.4s
[DEBUG] [api] api start to run after waiting 0.4s
[DEBUG] [api_inc_invoker] api old R.java path: /Users/hao/dev/android/workspace/android_driver/api/build/generated/source/r/androidTest/debug/com/jiajiabao/api/R.java
[DEBUG] [api_inc_invoker] api new R.java path: None
[DEBUG] [api_inc_invoker] src changed files:
[DEBUG] [api_inc_invoker] []
[DEBUG] [api_inc_invoker] api project has no change, need not go ahead
[DEBUG] [api_inc_invoker] api code only change R.java, need not go ahead
[DEBUG] [api_inc_javac_compile] no need to execute
[DEBUG] [api_inc_dex_compile] no need to execute
[DEBUG] [api] api finish in 0.0s
[DEBUG] [utils] utils start to run after waiting 0.4s
[DEBUG] [utils_inc_invoker] utils old R.java path: /Users/hao/dev/android/workspace/android_driver/utils/build/generated/source/r/androidTest/debug/com/jiajiabao/ucar/utils/R.java
[DEBUG] [utils_inc_invoker] utils new R.java path: None
[DEBUG] [utils_inc_invoker] src changed files:
[DEBUG] [utils_inc_invoker] []
[DEBUG] [utils_inc_invoker] utils project has no change, need not go ahead
[DEBUG] [utils_inc_invoker] utils code only change R.java, need not go ahead
[DEBUG] [utils_inc_javac_compile] no need to execute
[DEBUG] [utils_inc_dex_compile] no need to execute
[DEBUG] [utils] utils finish in 0.0s
[DEBUG] [personal] personal start to run after waiting 0.4s
[DEBUG] [business] business start to run after waiting 0.4s
[DEBUG] [personal_inc_invoker] personal old R.java path: /Users/hao/dev/android/workspace/android_driver/personal/build/generated/source/r/androidTest/debug/com/jiajiabao/ucar/personal/R.java
[DEBUG] [business_inc_invoker] business old R.java path: /Users/hao/dev/android/workspace/android_driver/business/build/generated/source/r/androidTest/debug/com/jiajiabao/ucar/business/R.java
[DEBUG] [personal_inc_invoker] personal new R.java path: None
[DEBUG] [business_inc_invoker] business new R.java path: None
[DEBUG] [personal_inc_invoker] src changed files:
[DEBUG] [personal_inc_invoker] []
[DEBUG] [personal_inc_invoker] personal project has no change, need not go ahead
[DEBUG] [personal_inc_invoker] personal code only change R.java, need not go ahead
[DEBUG] [personal_inc_javac_compile] no need to execute
[DEBUG] [personal_inc_dex_compile] no need to execute
[DEBUG] [personal] personal finish in 0.0s
[DEBUG] [business_inc_invoker] src changed files:
[DEBUG] [business_inc_invoker] []
[DEBUG] [business_inc_invoker] business project has no change, need not go ahead
[DEBUG] [business_inc_invoker] business code only change R.java, need not go ahead
[DEBUG] [business_inc_javac_compile] no need to execute
[DEBUG] [business_inc_dex_compile] no need to execute
[DEBUG] [business] business finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.3s
[DEBUG] [app_inc_invoker] app old R.java path: /Users/hao/dev/android/workspace/android_driver/app/build/generated/source/r/debug/com/jiajiabao/ucar/R.java
[DEBUG] [app_inc_invoker] app new R.java path: /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/backup/com/jiajiabao/ucar/R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'/Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/backup/com/jiajiabao/ucar/R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.0s
[DEBUG] [sync_client] personal has no need to sync inc res pack.
[DEBUG] [sync_client] checkresource: http://127.0.0.1:41128/checkResource
[DEBUG] [sync_client] base resource exists, there is no need to sync full resource pack
[DEBUG] [sync_client] start to sync app incremental res pack...
[DEBUG] [sync_client] app pack size: 5kb
[DEBUG] [sync_client] pushres: http://127.0.0.1:41128/pushResource?mode=increment&bundleId=base-res
[DEBUG] [sync_client] sync app incremental res pack finished
[DEBUG] [sync_client] api has no need to sync inc res pack.
[DEBUG] [sync_client] utils has no need to sync inc res pack.
[DEBUG] [sync_client] business has no need to sync inc res pack.
[DEBUG] [sync_client] no incremental dexes in /Users/hao/dev/android/workspace/android_driver/app/build/freeline/freeline-dexes
[DEBUG] [sync_client] start to sync close longlink...
[DEBUG] [sync_client] closeLongLink: http://127.0.0.1:41128/closeLongLink?no&lastSync=4
[DEBUG] [gradle_sync_task] gradle_sync_task finish in 0.1s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.1s
[DEBUG] [clean_cache_task] remove cache: /Users/hao/dev/android/workspace/android_driver/app/build/freeline/app/respack/app.rflag
[DEBUG] [clean_cache_task] refresh app ids.xml
[DEBUG] [clean_cache_task] clean_cache_task finish in 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.1s
[DEBUG] [update_stat_task] refresh /Users/hao/dev/android/workspace/android_driver/personal/src/main/res/layout/per_item_truck.xml stat
[DEBUG] [update_stat_task] refresh /Users/hao/dev/android/workspace/android_driver/personal/src/main/res/layout/per_item_truck.xml stat
[DEBUG] [update_stat_task] update_stat_task finish in 0.0s
[DEBUG] [task_engine] it takes task engine 0.58s to execute tasks.
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.6s
[DEBUG] Total time: 0.8s
[DEBUG] --------------------------------------------------------

**Comment by chen2991101** [comment]
![image](https://cloud.githubusercontent.com/assets/6636901/23903664/40f71e12-0900-11e7-92a2-a2e181f79ce4.png)
这个可以
![image](https://cloud.githubusercontent.com/assets/6636901/23903716/6f9c7f96-0900-11e7-92b5-219b78ef3765.png)
这个就不行了

**Comment by chen2991101** [comment]
@lomanyong 没有报错，也没有效果

**Comment by lomanyong** [comment]
@chen2991101 这个情况最好是提供相关的可以复现的工程，问题的原因应该是在工程的某些case上，而不是通用的情况...

**Comment by HakuLess** [comment]
公司项目，不方便提供源码，最近升级了下2.3 buildtools也用25.0.0，然后freeline对resource就无效了.. java代码倒是还都正常... 我再看看可能是啥原因吧~

**Comment by chen2991101** [comment]
@HakuLess 我的情况跟你一样

**Comment by lomanyong** [comment]
@HakuLess @chen2991101 可能是升级到 2.3 android gradle plugin 的缘故，明天我再具体排查一下

**Comment by HakuLess** [comment]
![image](https://cloud.githubusercontent.com/assets/6925363/24099353/a428e90e-0da9-11e7-90fc-8cc6c290586d.png)
https://developer.android.com/studio/build/build-cache.html#clear_the_build_cache
目测是2.3.0增加了什么aar打包缓存的东西，因此application 主module的修改能够生效，而library引入的子module修改无法生效，每次都-f才会好使
暂时把gradle降回到2.2.3，恢复正常

**Comment by lomanyong** [comment]
@HakuLess 恩，是 BuildCache 的原因，你也可以暂时配置关闭 BuildCache 来正常使用，解决方案我这边正在处理...

**Comment by luoGit** [comment]
其他的都还好，我也碰到这个情况，特意跑来issue，希望可以对这个进行处理下，修改了布局文件，就需要clean project 重新运行，又回到最初的起点，记忆中你青涩的脸。。。。

**Comment by lomanyong** [comment]
@luoGit 0.8.7已经解决这个问题了...

**Comment by luoGit** [comment]
好像没有解决啊，我升到0.8.7了，但是还是提示需要clean build

**Comment by HakuLess** [comment]
@luoGit 应该不是一个case，这个case的效果是 改xml或java会走增量编译，1、2s就重新启动Activity，只是xml的修改没有效果，资源修改还是增量编译之前，java代码正常，你可以查下其他的issuue
