### ISSUE TITLE
全量编译成功，增量编译失败，求解决方法

### ISSUE THREAD

**Issue by xingyuetianyu** [alibaba/freeline#721]
运行条件：
1.手机上无apk
2.没有开代理
3.执行 python freeline.py -f 成功
但是之后编译执行 python freeline.py 就出现 Freeline server in app "package name" not found. Please make sure your application is properly running in your device. 这样的问题。
排除：手机连接无问题；
4.＃152 解决方法测试无法解决；
5.重启无法解决。 
6. 日志中没有Freeline.increment server running on port xxx

日志
[DEBUG] [xxinc_dex_compile] start to execute dex command...
[DEBUG] [xx_inc_invoker] dex exec: D:\android\sdk\build-tools\24.0.0\dx.bat --dex --multi-dex --output=D:\xx\build\freeline\
xx\dex D:\xx\build\freeline\xx\classes
[DEBUG] [xx] xx finish in 4.4s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 4.5s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy xx\build\freeline\xx\dex\classes.dex to D:\xx\build\freeline\freeline-dexes\merged.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] wake up Service: D:\android\sdk\platform-tools\adb.exe shell am startservice -n xx/com.antfortune.freeline.FreelineService
[DEBUG] [sync_client] try to connect device 1 times...
[DEBUG] [sync_client] wake up Service: D:\android\sdk\platform-tools\adb.exe shell am startservice -n xx/com.antfortune.freeline.FreelineService -e wakeup marker
...
[DEBUG] [sync_client] try to connect device 10 times...
[DEBUG] [sync_client] Freeline server in app xx not found. Please make sure your application is properly running in your device.
[DEBUG] [connect_device_task] connect_device_task finish in 80.5s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 80.5s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 80.5s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 80.5s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 80.53s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.
        More about this can see: https://github.com/alibaba/freeline/issues/152
[ERROR] --------------------------------------------------------
[ERROR] Freeline server in app xx not found. Please make sure your application is properly running in your device.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.8s
[DEBUG] Task engine running time: 80.5s
[DEBUG] Total time: 81.3s
[DEBUG] --------------------------------------------------------

单独执行
1. $ adb shell am startservice -n xx/com.antfortune.freeline.FreelineService
 -e wakeup marker
Starting service: Intent { cmp=xx/com.antfortune.freeline.FreelineService (has extras) }

2. $ adb shell am startservice -n xx/com.antfortune.freeline.FreelineService
 -e wakeup marker
Starting service: Intent { cmp=xx/com.antfortune.freeline.FreelineService (has extras) }

3. $ adb forward tcp:41128 tcp:41128
    没有值输出

4.$ curl -v 127.0.0.1:41128/checkSync?sync=1\&uuid=22
* About to connect() to 127.0.0.1 port 41128 (#0)
*   Trying 127.0.0.1...
* Adding handle: conn: 0x2ac2e20
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x2ac2e20) send_pipe: 1, recv_pipe: 0
* Connected to 127.0.0.1 (127.0.0.1) port 41128 (#0)
> GET /checkSync?sync=1&uuid=22 HTTP/1.1
> User-Agent: curl/7.30.0
> Host: 127.0.0.1:41128
> Accept: */*
>
* Recv failure: Connection was aborted
* Closing connection 0
curl: (56) Recv failure: Connection was aborted

**Comment by xingyuetianyu** [comment]
从android studio 中 File->Settings->plugins->搜索Freeline，安装后，重启AS ，执行 python freeline.py -f 就报org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':xx'，求解决方法

**Comment by xingyuetianyu** [comment]
152 解决方法测试无法解决；
同时求下微信号，之前看到的微信号，已经过期了，希望可以发个最新的，谢谢

**Comment by lomanyong** [comment]
@xingyuetianyu 可以看下是否存在android logcat的crash日志...有可能是runtime crash了

**Comment by charvenhe** [comment]
重复问题，与731相同
