### ISSUE TITLE
当工程引入QQ浏览器x5内核的jar包的时候编译失败，100%必现

### ISSUE THREAD

**Issue by wanyt** [alibaba/freeline#722]
工程引入QQ浏览器x5内核的jar包的时候使用原声的没有问题，但是使用Freeline的时候报错：

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: 

这个遇到过吗？

这是QQ浏览器的官网：http://x5.tencent.com/tbs/index.html

**Comment by lomanyong** [comment]
@wanyt 这个倒是没有测试过，是否可以提供一个可以复现问题的sample工程呢？

**Comment by wanyt** [comment]
是我工程的问题，麻烦了。
