### ISSUE TITLE
public static final String的常量修改内容无效？

### ISSUE THREAD

**Issue by iceknc** [alibaba/freeline#723]
public static final String的常量增加没问题，但是增加了之后再修改常量的内容，再部署apk，常量内容还是修改前的值。
重新插拔一下数据线再部署，修改的常量才会生效果。

**Comment by lomanyong** [comment]
@iceknc 修改常量必须连同引用类一起修改才能立即生效

**Comment by iceknc** [comment]
对类的成员变量的修改不属于修改了引用类吗？

**Comment by lomanyong** [comment]
@iceknc 比如某个Activity类也修改了，需要连同这个类一起加入编译才行
