### ISSUE TITLE
Incremental javac compile failed

### ISSUE THREAD

**Issue by dss886** [alibaba/freeline#733]
修改了一个工具类中的方法可见性，由private到public。
增量编译时出现错误：访问了private的方法，目测是没有识别到修改了方法可见性？

[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

警告: [options] 未与 -source 1.7 一起设置引导类路径
/Users/xxx/xxxx.java:130: 错误: methodA(int,int)可以在xxUtils中访问private
        color = xxUtils.methodA(color, 0);
                                ^
1 个错误
1 个警告

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 2.4s
[DEBUG] Total time: 2.7s
[DEBUG] --------------------------------------------------------

**Comment by dss886** [comment]
补充：xxUtils和调用的代码不在一个Module内

**Comment by lomanyong** [comment]
@dss886 这种问题最好可以提供可以复现的demo，或者sample代码...否则难以判断问题所在..
