### ISSUE TITLE
Gradle sync failed: Could not find method freeline() for arguments 

### ISSUE THREAD

**Issue by chiyan171** [alibaba/freeline#734]
Gradle sync failed: Could not find method freeline() for arguments [build_coavhh268nadbhqha7dg9o5od$_run_closure3$_closure15@7c5565be] on project ':pdf' of type org.gradle.api.Project.
			Consult IDE log for more details (Help | Show Log)

gradle中有配置：
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.antfortune.freeline:gradle:0.8.6'
    }

apply plugin: 'com.antfortune.freeline'

freeline {
        hack true
        productFlavor 'Test'
    }

可是 freeline这个方法找不到。何解，求帮助！

**Comment by lomanyong** [comment]
@chiyan171 请参考demo，在相应的位置添加freeline的配置...
