### ISSUE TITLE
Freeline Gradle Plugin Version: 0.0.0

### ISSUE THREAD

**Issue by tommyfeng** [alibaba/freeline#735]
![qq 20170322140428](https://cloud.githubusercontent.com/assets/20334082/24184385/a4df5a1c-0f08-11e7-9d1f-3ef90f091989.png)

请问这是什么原因，要如何解决。。。

**Comment by lomanyong** [comment]
@tommyfeng 这个应该没有太大的影响...后面会fix这个问题..
