### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by happy15** [alibaba/freeline#74]
坚果（5.1.1），红米note2（5.0.2），魅蓝note2（5.1），修改layout之后运行python freeline.py出现ExceptionInInitializerError，几乎必先。而修改java代码，还没碰到过。

**Comment by happy15** [comment]
也容易出现binary inflate error。

**Comment by lomanyong** [comment]
@happy15 有具体的crash stacktrace堆栈日志吗？

**Comment by happy15** [comment]
崩的时候全部都是我们自己的类内容。另外，昨天在instant run时也发现了一次exceptionininitializererror。这个信息有用么？

**Comment by lomanyong** [comment]
`exceptionininitializererror `这个问题，如果Instant-Run与Freeline都会出现的话，可能跟你们app在进行一些初始化的时候有关。你们是否有修改或者hack过resource loader之类的东西呢？

以及修改layout是指修改属性，还是增加id，或者随便修改就增量都会报错呢？

**Comment by lomanyong** [comment]
@happy15 hello，最近有再使用freeline或者instant-run的时候可以再关注一下`ExceptionInInitializerError `这个问题，注意一下堆栈。应该有比较大的可能性跟你们的app的初始化的一些操作相关的

**Comment by happy15** [comment]
OK，有新发现会回复。
