### ISSUE TITLE
java.net.UnknownHostException: static.freelinebuild.com

### ISSUE THREAD

**Issue by zhongzilu** [alibaba/freeline#743]
系统环境：Ubuntu 16.04LTS
Python Version: 2.7.12
Freeline Version: 0.8.7

问题描述：
在命令行中执行`./gradlew initFreeline -Pmirror`时失败了，提示一下信息

```bash
Execution failed for task ':initFreeline'.
> java.net.UnknownHostException: static.freelinebuild.com
```

**Comment by lomanyong** [comment]
@zhongzilu 网络问题...可以尝试浏览器访问试试看

**Comment by zhongzilu** [comment]
我访问了，结果如下：

> {"error":"Document not found"}
