### ISSUE TITLE
incremental res build failed.

### ISSUE THREAD

**Issue by Henry-Ti** [alibaba/freeline#747]
[我改变xml文件里的一个文字出现资源编译失败，java文件改变是没有问题的。麻烦告知原因

[ERROR] --------------------------------------------------------
Freeline trace:: makeFileResources all resource. Time Elapsed: 0.013000 ms
Freeline trace:: compile values. Time Elapsed: 0.180000 ms
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.001000 ms

gChangeList = res/layout/activity_main.xml:res/values/freeline_id_keeper_public.xml:res/values/freeline_id_keeper_ids.xml
-resoucres-md5-cache-path = E:\AS_WORK_SPACE\TTYUN\app\build\freeline\arsc_cache.dat
warning: overwriting 'E:\AS_WORK_SPACE\TTYUN\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.8.7\assets\apktime' with 'E:\AS_WORK_SPACE\TTYUN\app\build\freelin
e\freeline-assets\apktime'
E:\AS_WORK_SPACE\TTYUN\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1601: error: Public symbol drawable/avd_hide_password_1 declared here is not defined.
E:\AS_WORK_SPACE\TTYUN\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1603: error: Public symbol drawable/avd_hide_password_2 declared here is not defined.
E:\AS_WORK_SPACE\TTYUN\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1605: error: Public symbol drawable/avd_hide_password_3 declared here is not defined.
E:\AS_WORK_SPACE\TTYUN\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1607: error: Public symbol drawable/avd_show_password_1 declared here is not defined.
E:\AS_WORK_SPACE\TTYUN\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1609: error: Public symbol drawable/avd_show_password_2 declared here is not defined.
E:\AS_WORK_SPACE\TTYUN\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:1611: error: Public symbol drawable/avd_show_password_3 declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.6s
[DEBUG] Total time: 0.8s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@Henry-Ti 降级support-design包的版本即可，windows目前还未修复这个bug，在linux/mac上已支持

**Comment by Caij** [comment]
同样的问题  。最高版本多少 ？
