### ISSUE TITLE
freeline不支持vector

### ISSUE THREAD

**Issue by asdfcjf** [alibaba/freeline#748]
增量编译vector崩溃

**Comment by lomanyong** [comment]
@asdfcjf 使用的是哪个版本的freeline？之前有类似的issue，已经fix。最好能够提供相关的demo，以便复现问题

**Comment by Demarcia-cn** [comment]
v0.8.7,通过第一种方式（添加插件）集成，报上述错误，如：
“\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:2821: error: Public symbol drawable/avd_show_password_3 declared here is not defined.”

**Comment by lomanyong** [comment]
@Demarcia-cn 恩，已知的问题，windows暂时还未解决...
