### ISSUE TITLE
删除XML中的一部分代码出错

### ISSUE THREAD

**Issue by happyxinxin99** [alibaba/freeline#751]
警告: [options] 未与 -source 1.7 一起设置引导类路径
asworkspace/student_haibian_online/app/src/main/java/com/tal/app/seaside/util/TimeUtil.java:3: 错误: 无法访问R
import com.tal.app.seaside.R;
                          ^
  错误的类文件: asworkspace/student_haibian_online/SplashActivity/build/intermediates/classes/debug/com/tal/app/seaside/R.class
    类文件包含错误的类: com.tbruyelle.rxpermissions.R
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by lomanyong** [comment]
@happyxinxin99 不支持删除资源id，这个已在README说明
