### ISSUE TITLE
App有多个进程 代码改了后不生效。

### ISSUE THREAD

**Issue by Caij** [alibaba/freeline#753]
非主进程修改代码后  代码不生效。

**Comment by lomanyong** [comment]
@Caij 目前不支持非主进程代码修改

**Comment by Caij** [comment]
@lomanyong   后面可能支持吗？

**Comment by Caij** [comment]
@lomanyong  即使是5.1手机上， 如果采用多进程  也需要加下面这个， 否则非主线程进程会出现java.lang.ClassCastException: com.antfortune.freeline.FreelineApplication cannot be cast to 这个异常 请问这个能解决吗  不想在代码里面加上FreelineCore的代码。


freeline {
    applicationProxy false
}

public class YourApplication extends Application {

    public onCreate() {
         super.onCreate();
         FreelineCore.init(this);
    }
}

**Comment by Smarking** [comment]
@Caij  问题解决了么？有同样的需求

**Comment by Caij** [comment]
@Smarking   freeline 不支持多进程 没办法的  我现在已经不用这个了。

**Comment by Smarking** [comment]
@Caij 那你改用什么方案了？其实把热修复引入到Freeline，Freeline也是可以支持多进程的吧，打算用这个办法改造Freeline，有啥建议么  @Caij @lomanyong

**Comment by Caij** [comment]
@Smarking  如果是针对多进程没必要，子进程多数是做后台消息服务的，改动不较少。 我主要是因为freeline经常不生效的问题 经常要全量编译  而且针对window的support lib也有限制。

**Comment by Smarking** [comment]
我这边的业务特点正好是，Service进程重，UI进程轻的项目。
