### ISSUE TITLE
突然之间增量编译不起作用了

### ISSUE THREAD

**Issue by huangying812** [alibaba/freeline#756]
每次都是全量编译，哪怕不改代码，都会重新全量编译的。就从昨天开始的，之前一直没问题。
没修改任何代码，执行一次freeline，log如下：

[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, version=False, wait=False)
[DEBUG] [dispatcher] *** Android Gradle Plugin Version: 2.2.3
[DEBUG] [dispatcher] *** Freeline Gradle Plugin Version: 0.8.7
[DEBUG] [dispatcher] *** Freeline Python Version: v0.8.7
[DEBUG] find UmengSdkLib has 0 java files modified.
[DEBUG] find LocateProcess has 0 java files modified.
[DEBUG] find app has 0 java files modified.
[DEBUG] find ListViewLib has 0 java files modified.
[DEBUG] find TbuluToolsLib has 0 java files modified.
[DEBUG] find GlobalLib has 0 java files modified.
[DEBUG] find sharesdk has 0 java files modified.
[DEBUG] find TcpLib has 0 java files modified.
[DEBUG] find StepCounter has 0 java files modified.
[DEBUG] find flowlayout-lib has 0 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "stat_md5": {},
    "build_info": {
	"last_clean_build_time": 1491875285.1543245,
	"is_root_config_changed": false
    },
    "projects": {
	"UmengSdkLib": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"LocateProcess": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"app": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"ListViewLib": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"TbuluToolsLib": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"GlobalLib": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"sharesdk": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"TcpLib": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"StepCounter": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	},
	"flowlayout-lib": {
	    "src": [],
	    "so": [],
	    "assets": [],
	    "libs": [],
	    "res": [],
	    "config": [],
	    "cpp": [],
	    "manifest": []
	}
    }
}
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [UmengSdkLib]
[DEBUG] [task_engine] depth: 2, task: [LocateProcess]
[DEBUG] [task_engine] depth: 2, task: [ListViewLib]
[DEBUG] [task_engine] depth: 2, task: [TbuluToolsLib]
[DEBUG] [task_engine] depth: 2, task: [GlobalLib]
[DEBUG] [task_engine] depth: 2, task: [flowlayout-lib]
[DEBUG] [task_engine] depth: 2, task: [sharesdk]
[DEBUG] [task_engine] depth: 2, task: [TcpLib]
[DEBUG] [task_engine] depth: 2, task: [StepCounter]
[DEBUG] [task_engine] depth: 11, task: [app]
[DEBUG] [task_engine] depth: 12, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 14, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 15, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 16, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [sync_client] apktime path: I:\tbuluwc\trunk_studio\app\build\freeline\freeline-assets\apktime
[DEBUG] [TbuluToolsLib] TbuluToolsLib start to run after waiting 0.0s
[DEBUG] [UmengSdkLib] UmengSdkLib start to run after waiting 0.0s
[DEBUG] [ListViewLib] ListViewLib start to run after waiting 0.0s
[DEBUG] [LocateProcess] LocateProcess start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 47000
[DEBUG] [GlobalLib] GlobalLib start to run after waiting 0.0s
[DEBUG] [sync_client] your local uuid value is: 47000
[DEBUG] [UmengSdkLib_inc_invoker] UmengSdkLib old R.java path: I:\tbuluwc\trunk_studio\UmengSdkLib\build\generated\source\r\androidTest\debug\com\umeng_social_sdk_res_li
b\R.java
[DEBUG] [TbuluToolsLib_inc_invoker] TbuluToolsLib old R.java path: I:\tbuluwc\trunk_studio\TbuluToolsLib\build\generated\source\r\androidTest\debug\com\lolaage\tbulu\too
ls\libs\R.java
[DEBUG] [UmengSdkLib_inc_invoker] UmengSdkLib new R.java path: None
[DEBUG] [ListViewLib_inc_invoker] ListViewLib old R.java path: I:\tbuluwc\trunk_studio\ListViewLib\build\generated\source\r\androidTest\debug\com\lolaage\tbulu\tools\lis
tview\R.java
[DEBUG] [TbuluToolsLib_inc_invoker] TbuluToolsLib new R.java path: None
[DEBUG] [LocateProcess_inc_invoker] LocateProcess old R.java path: I:\tbuluwc\trunk_studio\LocateProcess\build\generated\source\r\androidTest\debug\com\lolaage\tbulu\too
ls\locateprocess\R.java
[DEBUG] [UmengSdkLib_inc_invoker] src changed files:
[DEBUG] [ListViewLib_inc_invoker] ListViewLib new R.java path: None
[DEBUG] [UmengSdkLib_inc_invoker] []
[DEBUG] [TbuluToolsLib_inc_invoker] src changed files:
[DEBUG] [UmengSdkLib_inc_invoker] UmengSdkLib project has no change, need not go ahead
[DEBUG] [TbuluToolsLib_inc_invoker] []
[DEBUG] [ListViewLib_inc_invoker] src changed files:
[DEBUG] [UmengSdkLib_inc_invoker] UmengSdkLib code only change R.java, need not go ahead
[DEBUG] [LocateProcess_inc_invoker] LocateProcess new R.java path: None
[DEBUG] [TbuluToolsLib_inc_invoker] TbuluToolsLib project has no change, need not go ahead
[DEBUG] [ListViewLib_inc_invoker] []
[DEBUG] [UmengSdkLib_inc_javac_compile] no need to execute
[DEBUG] [TbuluToolsLib_inc_invoker] TbuluToolsLib code only change R.java, need not go ahead
[DEBUG] [GlobalLib_inc_invoker] GlobalLib old R.java path: I:\tbuluwc\trunk_studio\GlobalLib\build\generated\source\r\androidTest\debug\com\lolaage\globallib\R.java
[DEBUG] [ListViewLib_inc_invoker] ListViewLib project has no change, need not go ahead
[DEBUG] [LocateProcess_inc_invoker] src changed files:
[DEBUG] [TbuluToolsLib_inc_javac_compile] no need to execute
[DEBUG] [ListViewLib_inc_invoker] ListViewLib code only change R.java, need not go ahead
[DEBUG] [LocateProcess_inc_invoker] []
[DEBUG] [UmengSdkLib_inc_dex_compile] no need to execute
[DEBUG] [ListViewLib_inc_javac_compile] no need to execute
[DEBUG] [LocateProcess_inc_invoker] LocateProcess project has no change, need not go ahead
[DEBUG] [GlobalLib_inc_invoker] GlobalLib new R.java path: None
[DEBUG] [UmengSdkLib] UmengSdkLib finish in 0.0s
[DEBUG] [TbuluToolsLib_inc_dex_compile] no need to execute
[DEBUG] [LocateProcess_inc_invoker] LocateProcess code only change R.java, need not go ahead
[DEBUG] [TbuluToolsLib] TbuluToolsLib finish in 0.0s
[DEBUG] [LocateProcess_inc_javac_compile] no need to execute
[DEBUG] [ListViewLib_inc_dex_compile] no need to execute
[DEBUG] [flowlayout-lib] flowlayout-lib start to run after waiting 0.0s
[DEBUG] [ListViewLib] ListViewLib finish in 0.0s
[DEBUG] [sharesdk] sharesdk start to run after waiting 0.0s
[DEBUG] [GlobalLib_inc_invoker] src changed files:
[DEBUG] [LocateProcess_inc_dex_compile] no need to execute
[DEBUG] [GlobalLib_inc_invoker] []
[DEBUG] [TcpLib] TcpLib start to run after waiting 0.0s
[DEBUG] [LocateProcess] LocateProcess finish in 0.0s
[DEBUG] [GlobalLib_inc_invoker] GlobalLib project has no change, need not go ahead
[DEBUG] [GlobalLib_inc_invoker] GlobalLib code only change R.java, need not go ahead
[DEBUG] [StepCounter] StepCounter start to run after waiting 0.0s
[DEBUG] [GlobalLib_inc_javac_compile] no need to execute
[DEBUG] [GlobalLib_inc_dex_compile] no need to execute
[DEBUG] [GlobalLib] GlobalLib finish in 0.0s
[DEBUG] [sharesdk_inc_invoker] sharesdk old R.java path: I:\tbuluwc\trunk_studio\sharesdk\build\generated\source\r\androidTest\debug\cn\sharesdk\R.java
[DEBUG] [flowlayout-lib_inc_invoker] flowlayout-lib old R.java path: I:\tbuluwc\trunk_studio\flowlayout-lib\build\generated\source\r\androidTest\debug\com\zhy\view\flowl
ayout\R.java
[DEBUG] [TcpLib_inc_invoker] TcpLib old R.java path: I:\tbuluwc\trunk_studio\TcpLib\build\generated\source\r\androidTest\debug\com\lolaage\android\R.java
[DEBUG] [sharesdk_inc_invoker] sharesdk new R.java path: None
[DEBUG] [flowlayout-lib_inc_invoker] flowlayout-lib new R.java path: None
[DEBUG] [TcpLib_inc_invoker] TcpLib new R.java path: None
[DEBUG] [sharesdk_inc_invoker] src changed files:
[DEBUG] [flowlayout-lib_inc_invoker] src changed files:
[DEBUG] [StepCounter_inc_invoker] StepCounter old R.java path: I:\tbuluwc\trunk_studio\StepCounter\build\generated\source\r\androidTest\debug\com\lolaage\tbulu\tools\ste
pcounter\R.java
[DEBUG] [sharesdk_inc_invoker] []
[DEBUG] [TcpLib_inc_invoker] src changed files:
[DEBUG] [flowlayout-lib_inc_invoker] []
[DEBUG] [sharesdk_inc_invoker] sharesdk project has no change, need not go ahead
[DEBUG] [TcpLib_inc_invoker] []
[DEBUG] [flowlayout-lib_inc_invoker] flowlayout-lib project has no change, need not go ahead
[DEBUG] [sharesdk_inc_invoker] sharesdk code only change R.java, need not go ahead
[DEBUG] [TcpLib_inc_invoker] TcpLib project has no change, need not go ahead
[DEBUG] [flowlayout-lib_inc_invoker] flowlayout-lib code only change R.java, need not go ahead
[DEBUG] [StepCounter_inc_invoker] StepCounter new R.java path: None
[DEBUG] [sharesdk_inc_javac_compile] no need to execute
[DEBUG] [TcpLib_inc_invoker] TcpLib code only change R.java, need not go ahead
[DEBUG] [flowlayout-lib_inc_javac_compile] no need to execute
[DEBUG] [TcpLib_inc_javac_compile] no need to execute
[DEBUG] [StepCounter_inc_invoker] src changed files:
[DEBUG] [sharesdk_inc_dex_compile] no need to execute
[DEBUG] [StepCounter_inc_invoker] []
[DEBUG] [flowlayout-lib_inc_dex_compile] no need to execute
[DEBUG] [sharesdk] sharesdk finish in 0.0s
[DEBUG] [StepCounter_inc_invoker] StepCounter project has no change, need not go ahead
[DEBUG] [TcpLib_inc_dex_compile] no need to execute
[DEBUG] [flowlayout-lib] flowlayout-lib finish in 0.0s
[DEBUG] [StepCounter_inc_invoker] StepCounter code only change R.java, need not go ahead
[DEBUG] [TcpLib] TcpLib finish in 0.0s
[DEBUG] [StepCounter_inc_javac_compile] no need to execute
[DEBUG] [StepCounter_inc_dex_compile] no need to execute
[DEBUG] [StepCounter] StepCounter finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [app_inc_invoker] app old R.java path: I:\tbuluwc\trunk_studio\app\build\generated\source\r\debug\com\lolaage\tbulu\tools\R.java
[DEBUG] [app_inc_invoker] app new R.java path: I:\tbuluwc\trunk_studio\app\build\freeline\app\backup\com\lolaage\tbulu\tools\R.java
[DEBUG] avoid windows unicode error for I:\tbuluwc\trunk_studio\app\build\freeline\app\backup\com\lolaage\tbulu\tools\R.java
[DEBUG] [sync_client] server result is 0
[DEBUG] [sync_client] check sync value failed, maybe you need a clean build.
[DEBUG] [connect_device_task] connect_device_task finish in 0.1s
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'I:\\tbuluwc\\trunk_studio\\app\\build\\freeline\\app\\backup\\com\\lolaage\\tbulu\\tools\\R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_invoker] app code only change R.java, need not go ahead
[DEBUG] [app_inc_javac_compile] no need to execute
[DEBUG] [app_inc_dex_compile] no need to execute
[DEBUG] [app] app finish in 0.1s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.1s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.1s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.1s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.1s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 0.1s to execute tasks.
[DEBUG] [WARNING] check sync status failed, a clean build will be automatically executed.

**Comment by lomanyong** [comment]
@huangying812 卸载一下手机的apk，再重新安装试试看

**Comment by huangying812** [comment]
@lomanyong 好吧，居然神奇的好了
