### ISSUE TITLE
android studio 2.4支持java8问题

### ISSUE THREAD

**Issue by linwoain** [alibaba/freeline#760]
现在用的2.4的预览版即将支持java8(非jack方式)
https://developer.android.com/studio/preview/features/java8-support.html
代码中使用java8，全量编译正常，增量的时候会指定使用1.7是否可以设置成参数控制呢？

**Comment by lomanyong** [comment]
@linwoain 2.4 gradle plugin 的兼容问题近期会发布版本来修复~

目前可以暂时降级来支持
