### ISSUE TITLE
A problem occurred evaluating project ':app'. > java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : U

### ISSUE THREAD

**Issue by xiaoconggithup** [alibaba/freeline#764]
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : U

**Comment by lomanyong** [comment]
@xiaoconggithup 已有类似issue，android gradle plugin版本问题...可以自行查询解决
