### ISSUE TITLE
android freeline plugin提示not installFreeLine错误，命令行可以正常跑起freeline

### ISSUE THREAD

**Issue by mianamiana** [alibaba/freeline#765]
![image](https://cloud.githubusercontent.com/assets/14850433/25080867/7822653e-2379-11e7-83b2-f53aae6f14ac.png)
是这样的，为了统一管理dependencies，下面这段我并没有放在rootproject下，
```
 classpath 'com.antfortune.freeline:gradle:0.8.7'
```
我将其放在自建的dependencies.gralde里，并在rootproject中
```
apply from 'dependencies.gralde'
```

一切倒腾完后，我通过命令行跑freeline没有问题，用插件跑会出现上图的情况

附上我的临时解决方案：
![image](https://cloud.githubusercontent.com/assets/14850433/25174257/58b18868-2529-11e7-9394-db3e7eab0c90.png)

**Comment by lomanyong** [comment]
@mianamiana 插件的问题导致的，插件的读取方式用正则来匹配，没有考虑使用这种额外依赖的问题，暂时延后修复这个问题...
