### ISSUE TITLE
Freeline 第二次编译就报错

### ISSUE THREAD

**Issue by xufan** [alibaba/freeline#771]
``` java
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
```

**Comment by lomanyong** [comment]
@xufan 使用了Java8来编译吗？

**Comment by xufan** [comment]
项目的JDK使用的1.8 是studio内置jdk

**Comment by zhaoch2014** [comment]
那这个到底能不能用用1.8进行编译啊

**Comment by zlmerry** [comment]
@lomanyong 我的项目也是用java8编译的（Java8不管是studio带的，还是系统的java8）,都会报楼主的问题； 再附一下：
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

**Comment by zhaoch2014** [comment]
可以用命令行试一下
http://www.jianshu.com/p/9e30be2c63f7
python freeline.py -f

**Comment by zlmerry** [comment]
@zhouxinyu 
python freeline.py -f 这是强制全量编译，且不管是全量还是增量编辑，我仔细查看了console的log，都有输出上面的报错内容，且最后输入日志标识是error，不过最后的app也启动起来了。很诡异，输出error，也能运行起来，但就是这样的；
当时第一次全量编译失败启动后，我修改代码，增量编译，会报相同的错误，但是这次就运行不起来了。

**Comment by lomanyong** [comment]
@xufan 是否是2.4的Android Studio？目前还不支持最新的java8特性

**Comment by xufan** [comment]
2.3.1的studio

**Comment by Comoko** [comment]
这个问题我这边也出现了，经过排查 发现 是由于电脑上同时安装了java 1.8 和1.7导致的，彻底卸载一个可以解决

**Comment by javalue** [comment]
所以呢？到底能支持java8吗？
