### ISSUE TITLE
xml文件改动会报错，是不是兼容databinding有问题

### ISSUE THREAD

**Issue by Licardo** [alibaba/freeline#775]
/Users/zhanghao/AndroidStudioProjects/background-rest_phone/app/build/freeline/freeline-databinding/app/d376d2c26d3e9c3ed1a1786ad3d7c107/java/android/databinding/layouts/DataBindingInfo.java:5: error: cannot find symbol
@BindingBuildInfo(buildId="1485a7d0-6b36-45c2-9ca2-64546d2b584b", modulePackage="zmsoft.rest.phone", sdkRoot="/Users/zhanghao/Library/Android/sdk",layoutInfoDir="/Users/zhanghao/AndroidStudioProjects/background-rest_phone/app/build/freeline/freeline-databinding/merged_layoutinfo",exportClassListTo="",isLibrary=false,minSdk=16,enableDebugLogs=true,printEncodedError=true)
                                                                                ^
  symbol:   method modulePackage()
  location: @interface BindingBuildInfo

**Comment by Licardo** [comment]
@mazhao @huacnlee @fsword

**Comment by zhaoshuyu** [comment]
我是通过注释掉文件gradle_inc_build.py中的
# if 'apt' in self._changed_files:
        # for fpath in self._changed_files['apt']:
        # f fpath.endswith('DataBindingInfo.java'):
        # return True
这几行，暂时把这个问题绕过的，修改databind相关的xml和类没有问题，同问作者这个问题是怎么回事？

**Comment by lomanyong** [comment]
@Licardo @zhaoshuyu DataBinding的支持确实有问题，暂时会deplay对这个特性的支持
