### ISSUE TITLE
修改一个java 类中环境配置文件，编译之后没有改变

### ISSUE THREAD

**Issue by justingboy** [alibaba/freeline#776]
public static final String TEST_URL="www.baidu.com";
//  public static final String TEST_URL="www.youdao.com";

这个请求的地址在其他文件使用， 无论注释掉哪一个，再编译，运行发现调用的地址还是之前的，
必须进行全量编译才能改变，请问有什么解决方法吗?

**Comment by lomanyong** [comment]
@justingboy 必须连同引用类一起编译才能生效，这个是已知问题
