### ISSUE TITLE
使用freeline异常

### ISSUE THREAD

**Issue by heheLT** [alibaba/freeline#777]
1.run freeline出现“Freeline Plugin: Execute task initFreeline and download freeline dependencies...“异常
2.然后执行 ./gradlew initFreeline，出现以下问题：
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hehelt/study/person/code/androidCode/demo/FreeLineDemo/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

**Comment by zhaoch2014** [comment]
这个init一下就好了，gradlew initFreeline -Pmirror

**Comment by lomanyong** [comment]
@heheLT 可以搜下已有的issue，gradle plugin版本不正确
