### ISSUE TITLE
只要在gradle中apply freeline plugin，即使使用默认打包方式也会影响app性能

### ISSUE THREAD

**Issue by geeksammao** [alibaba/freeline#778]
在线上打debug包时没有使用freeline的脚本，之后发现游戏帧率变得很差，注释掉gradle中apply freeline plugin才恢复正常。
反编译有问题的包，发现确实引入了freeline相关的类。现在只能在gradle中设置开关，在测游戏相关时关掉freeline。

**Comment by lomanyong** [comment]
@geeksammao clean后重新编译应该不会有问题，正常打包，没有加入特定的参数的话，不会对app造成影响的
