### ISSUE TITLE
【兼容性】res下layout资源修改后无法正常增量编译

### ISSUE THREAD

**Issue by aoldcat** [alibaba/freeline#78]
我们的项目为了避免每个页面中出现公共组件，定义了一个ids.xml存储控件ID 公共组件定义格式为@id/xxx，发现layout中存在这样的组件名称定义那么使用freeline无法正常的增量编译这个资源文件。

**Comment by charvenhe** [comment]
不能增量的具体表现是没有生效吗？

**Comment by aoldcat** [comment]
@charvenhe 是的 屏幕闪一下 UI修改的文字之类的都无法生效

**Comment by charvenhe** [comment]
这个case我们这边没复现，具体我们晚点联系你联调

**Comment by charvenhe** [comment]
@aoldcat 问题解决了吗

加我们微信群我们单独跟进看看
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f7qxaz4slbj20ny0zk0tm.jpg)

**Comment by lomanyong** [comment]
@aoldcat 可以升级`0.7.1`看看是否还有同样的问题~
