### ISSUE TITLE
Freeline DSL References, 配置property “buildScript” 为非Debug，编译不通过

### ISSUE THREAD

**Issue by biyeshengplay** [alibaba/freeline#789]
环境：MAC
设置如下：
freeline {
        //buildScript "gradlew assembleDebug" //编译成功
        buildScript "gradlew assembleRelease" //编译失败
    }

当buildScript设置为Release或其他时，python freeline.py -f编译不通过，但是最终的release apk生成了

日志如下：
[ERROR] --------------------------------------------------------
			[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/alvinlee/software/android-sdk-macosx/platforms/android-23/android.jar -M /Users/AndroidCode/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/AndroidCode/res -S /Users/AndroidCode/ToggleButtonLib/build/generated/res/resValues/release -S /Users/AndroidCode/JazzyListViewLib/build/generated/res/resValues/release -S /Users/AndroidCode/ToggleButtonLib/build/generated/res/rs/release -S /Users/AndroidCode/JazzyListViewLib/build/generated/res/rs/release -S /Users/AndroidCode/build/freeline/AndroidCode/backup/res -A /Users/AndroidCode/build/freeline/freeline-assets -A /Users/AndroidCode/assets -m -J /Users/AndroidCode/build/freeline/AndroidCode/backup --auto-add-overlay -F /Users/AndroidCode/build/freeline/base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path /Users/AndroidCode/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.* --ignore-ids avd_hide_password_1:avd_hide_password_2:avd_hide_password_3:avd_show_password_1:avd_show_password_2:avd_show_password_3
[ERROR] --------------------------------------------------------

**Comment by biyeshengplay** [comment]
项目没有使用productFlavors

**Comment by lomanyong** [comment]
@biyeshengplay freeline不支持release的buildType的，目前只支持debug的。
