### ISSUE TITLE
修改xml文件增量编译就出错 incremental res build failed

### ISSUE THREAD

**Issue by Heart2009** [alibaba/freeline#793]
首次全量编译
-ignore-ids = avd_hide_password_1:avd_hide_password_2:avd_hide_password_3:avd_show_password_1:avd_show_password_2:avd_show_password_3
Freeline trace:: custom package NULL
warning: overwriting '/Users/Chu/.android/build-cache/d330ae76293e8e9499dd6d866cfe12dc067cb1d3/output/assets/apktime' with '/Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/freeline-assets/apktime'
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
/Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/newapp/backup/AndroidManifest.xml:2: error: Error parsing XML: unbound prefix

[ERROR] --------------------------------------------------------
[ERROR] build base resources failed with: freeline/release-tools/FreelineAapt package -f -I /Users/Chu/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-25/android.jar -M /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/newapp/backup/AndroidManifest.xml -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/src/main/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/AlibaichuanIM/build/generated/res/resValues/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/common/src/main/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/pulltorefresh/src/main/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/richeditor/src/main/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/statistics/build/generated/res/resValues/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/app/src/main/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/sharesdk/build/generated/res/rs/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/richeditor/build/generated/res/rs/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/pulltorefresh/build/generated/res/resValues/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/common/build/generated/res/resValues/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/statistics/src/main/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/AlibaichuanIM/build/generated/res/rs/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/generated/res/rs/talicai_test/debug -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/common/build/generated/res/rs/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/sharesdk/src/main/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/richeditor/build/generated/res/resValues/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/sharesdk/build/generated/res/resValues/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/statistics/build/generated/res/rs/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/pulltorefresh/build/generated/res/rs/release -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/AlibaichuanIM/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/generated/res/resValues/talicai_test/debug -S /Users/Chu/.android/build-cache/95105cc3ff0ff847d2a3b75e325a0da1e558e05f/output/res -S /Users/Chu/.android/build-cache/c1d52f632a9b2fe869590914176c88af41c46780/output/res -S /Users/Chu/.android/build-cache/094037b67edb3a035ac93e447cc01015ae93ab35/output/res -S /Users/Chu/.android/build-cache/01fa06c41e7f802c10cde9be5fbd28479825a490/output/res -S /Users/Chu/.android/build-cache/d2620445e6fa6a98d5075e12c6c6b20ce34ed718/output/res -S /Users/Chu/.android/build-cache/e1b48edd9f0a2d5d1e8050c5c209781ecb1b5410/output/res -S /Users/Chu/.android/build-cache/342b9403628f3826b18b71cc34ef1b81aa180fa6/output/res -S /Users/Chu/.android/build-cache/8de18800a8809d27a790bdd87aaedcd724c5b927/output/res -S /Users/Chu/.android/build-cache/288db8316073fd999fa9b32884c91d30e92d8514/output/res -S /Users/Chu/.android/build-cache/a4eac02aff8961a4b2e5f50cfe17f6455dbfc7c2/output/res -S /Users/Chu/.android/build-cache/8ab8263afa48480aa86f1c64f09402a0afb379d0/output/res -S /Users/Chu/.android/build-cache/bf1c5c1092901f2b732d533b7466e9e807f50cc6/output/res -S /Users/Chu/.android/build-cache/76dd465a1075e62ed01562b02273c213150db572/output/res -S /Users/Chu/.android/build-cache/a894e3a67af344e2ba350a50ee36518a31804045/output/res -S /Users/Chu/.android/build-cache/1afd8a4a34ff8096f5a53219681caad887cc9bf8/output/res -S /Users/Chu/.android/build-cache/b2be0da24bf8b333272e4633842c90ae72986496/output/res -S /Users/Chu/.android/build-cache/7477ba70b62872c28fdd8c461b20440fd18a08bb/output/res -S /Users/Chu/.android/build-cache/fdf904ae6c606e5789617197a601e443a3d150fd/output/res -S /Users/Chu/.android/build-cache/a365f6a1bc664e501c778bf772f040dd0a11d016/output/res -S /Users/Chu/.android/build-cache/32778d8418dc5c08b6de92a77699eadadcd792c1/output/res -S /Users/Chu/.android/build-cache/3909c06fdf77a999851c53bfc42ffecbb6e8ecc7/output/res -S /Users/Chu/.android/build-cache/7f6b9782f6774816d2e6dd349e4658fcf66dcc65/output/res -S /Users/Chu/.android/build-cache/1774519c44cab7e5d033cfc569df5b877b21ff6a/output/res -S /Users/Chu/.android/build-cache/372da6bec14715f3efc9690c6cd8e4fdee7c0d47/output/res -S /Users/Chu/.android/build-cache/c921793bf5e336a1f27bfd86230f525c8afca513/output/res -S /Users/Chu/.android/build-cache/9c201402ef3a5b7f91b40e27dee86fa239ceac04/output/res -S /Users/Chu/.android/build-cache/db701c941e56973a462cc12011a369a2506c1077/output/res -S /Users/Chu/.android/build-cache/2a19ba7d5b8e6f7d9a02823a79b25cb8461792b1/output/res -S /Users/Chu/.android/build-cache/387c8ca4aed2e3cf81cce54ee84224f9f5978347/output/res -S /Users/Chu/.android/build-cache/3c815baf18c6c52d25a597dced1127b727794330/output/res -S /Users/Chu/.android/build-cache/aeaf3ad0bd5ea346c4e847ae5c3f472a27339884/output/res -S /Users/Chu/.android/build-cache/aa0190d00068040f44377c31ba3bb50ad687cee6/output/res -S /Users/Chu/.android/build-cache/e120349e4cb265699199e0c78fa89730bd661b7d/output/res -S /Users/Chu/.android/build-cache/cbec4122a354ea4ce9545a5017c89a260fbe005b/output/res -S /Users/Chu/.android/build-cache/bbac0f26272becf649dfb34f178007f7d78e1d9d/output/res -S /Users/Chu/.android/build-cache/ebdc765d8d8975f7749b7de81205068225196b81/output/res -S /Users/Chu/.android/build-cache/13e9eb9e71575f6c2594c4e207f0a79f83e7bfd2/output/res -S /Users/Chu/.android/build-cache/037a859528d44ea2c1b28a21d64dff5e325b279d/output/res -S /Users/Chu/.android/build-cache/21401485fcb46bb607d1bebdf8fe2e733c24e715/output/res -S /Users/Chu/.android/build-cache/d7d060fd8e9ae6f92dd2bdac4eb95401499d6bf2/output/res -S /Users/Chu/.android/build-cache/3681c3df9e92a1f5474b5758cfc1eca1ce876d8a/output/res -S /Users/Chu/.android/build-cache/e741c87a0eb69a2bc69c2b7a221db217419300aa/output/res -S /Users/Chu/.android/build-cache/879f3e677740f51d4feb836ac1e1f33c027c20a0/output/res -S /Users/Chu/.android/build-cache/b646baddf6de9342f01555d78c9284de902d72fd/output/res -S /Users/Chu/.android/build-cache/1c8183c660304c06040c3e7ec73fbf9dcbb6d083/output/res -S /Users/Chu/.android/build-cache/9d8240b0b646cef7c919b1578c62cbab624ca1f6/output/res -S /Users/Chu/.android/build-cache/0817eddfbee7165fea59ec018bb69e795bbc07bf/output/res -S /Users/Chu/.android/build-cache/d73cbd6be813620bb6c0c34f24169264aa872edc/output/res -S /Users/Chu/.android/build-cache/6a586f7bdf9b1b43742f42f97a5e2de6ac145db7/output/res -S /Users/Chu/.android/build-cache/d330ae76293e8e9499dd6d866cfe12dc067cb1d3/output/res -S /Users/Chu/.android/build-cache/9e3e2e138f40e4a466c7fc212e7aef5fd66f2509/output/res -S /Users/Chu/.android/build-cache/6c08ebf06310bb177dbe8d8b86fe9bcb685fde41/output/res -S /Users/Chu/.android/build-cache/531f33b0653e50b1bc0d35e9fa8d056a20c9102e/output/res -S /Users/Chu/.android/build-cache/43266d613eaebd50dc04c48512b2cb23721ba1a9/output/res -S /Users/Chu/.android/build-cache/3d63331ac9586763d83f50208bbaf2c97f1881ab/output/res -S /Users/Chu/.android/build-cache/922b0915f3ab162acd873a8c18c65138ed246465/output/res -S /Users/Chu/.android/build-cache/e6878aabaf19cfe233b64fb624d6a64b0c399db3/output/res -S /Users/Chu/.android/build-cache/b25947dc65c80904d1d756e9f20e356577cbaa62/output/res -S /Users/Chu/.android/build-cache/3420dad41c37a498b67e4847f5ce5210acdf725b/output/res -S /Users/Chu/.android/build-cache/378ee9796f599587b7fcb379167f508ccad1d4e0/output/res -S /Users/Chu/.android/build-cache/ec34e056acda08e749fb721e7a2e65117afd8f05/output/res -S /Users/Chu/.android/build-cache/ca270118c667518ca171638aa53c2393a94d2a4d/output/res -S /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/newapp/backup/res -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/freeline-assets -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/statistics/build/generated/assets/shaders/release -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/AlibaichuanIM/build/generated/assets/shaders/release -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/app/src/main/assets -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/pulltorefresh/build/generated/assets/shaders/release -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/sharesdk/build/generated/assets/shaders/release -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/generated/assets/shaders/talicai_test/debug -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/richeditor/src/main/assets -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/common/build/generated/assets/shaders/release -A /Users/Chu/Documents/workspace/project/Talicai_Studio_/richeditor/build/generated/assets/shaders/release -A /Users/Chu/.android/build-cache/95105cc3ff0ff847d2a3b75e325a0da1e558e05f/output/assets -A /Users/Chu/.android/build-cache/c1d52f632a9b2fe869590914176c88af41c46780/output/assets -A /Users/Chu/.android/build-cache/094037b67edb3a035ac93e447cc01015ae93ab35/output/assets -A /Users/Chu/.android/build-cache/01fa06c41e7f802c10cde9be5fbd28479825a490/output/assets -A /Users/Chu/.android/build-cache/d2620445e6fa6a98d5075e12c6c6b20ce34ed718/output/assets -A /Users/Chu/.android/build-cache/e1b48edd9f0a2d5d1e8050c5c209781ecb1b5410/output/assets -A /Users/Chu/.android/build-cache/342b9403628f3826b18b71cc34ef1b81aa180fa6/output/assets -A /Users/Chu/.android/build-cache/8de18800a8809d27a790bdd87aaedcd724c5b927/output/assets -A /Users/Chu/.android/build-cache/288db8316073fd999fa9b32884c91d30e92d8514/output/assets -A /Users/Chu/.android/build-cache/a4eac02aff8961a4b2e5f50cfe17f6455dbfc7c2/output/assets -A /Users/Chu/.android/build-cache/8ab8263afa48480aa86f1c64f09402a0afb379d0/output/assets -A /Users/Chu/.android/build-cache/bf1c5c1092901f2b732d533b7466e9e807f50cc6/output/assets -A /Users/Chu/.android/build-cache/76dd465a1075e62ed01562b02273c213150db572/output/assets -A /Users/Chu/.android/build-cache/a894e3a67af344e2ba350a50ee36518a31804045/output/assets -A /Users/Chu/.android/build-cache/1afd8a4a34ff8096f5a53219681caad887cc9bf8/output/assets -A /Users/Chu/.android/build-cache/b2be0da24bf8b333272e4633842c90ae72986496/output/assets -A /Users/Chu/.android/build-cache/7477ba70b62872c28fdd8c461b20440fd18a08bb/output/assets -A /Users/Chu/.android/build-cache/fdf904ae6c606e5789617197a601e443a3d150fd/output/assets -A /Users/Chu/.android/build-cache/a365f6a1bc664e501c778bf772f040dd0a11d016/output/assets -A /Users/Chu/.android/build-cache/32778d8418dc5c08b6de92a77699eadadcd792c1/output/assets -A /Users/Chu/.android/build-cache/3909c06fdf77a999851c53bfc42ffecbb6e8ecc7/output/assets -A /Users/Chu/.android/build-cache/7f6b9782f6774816d2e6dd349e4658fcf66dcc65/output/assets -A /Users/Chu/.android/build-cache/1774519c44cab7e5d033cfc569df5b877b21ff6a/output/assets -A /Users/Chu/.android/build-cache/372da6bec14715f3efc9690c6cd8e4fdee7c0d47/output/assets -A /Users/Chu/.android/build-cache/c921793bf5e336a1f27bfd86230f525c8afca513/output/assets -A /Users/Chu/.android/build-cache/9c201402ef3a5b7f91b40e27dee86fa239ceac04/output/assets -A /Users/Chu/.android/build-cache/db701c941e56973a462cc12011a369a2506c1077/output/assets -A /Users/Chu/.android/build-cache/2a19ba7d5b8e6f7d9a02823a79b25cb8461792b1/output/assets -A /Users/Chu/.android/build-cache/387c8ca4aed2e3cf81cce54ee84224f9f5978347/output/assets -A /Users/Chu/.android/build-cache/3c815baf18c6c52d25a597dced1127b727794330/output/assets -A /Users/Chu/.android/build-cache/aeaf3ad0bd5ea346c4e847ae5c3f472a27339884/output/assets -A /Users/Chu/.android/build-cache/aa0190d00068040f44377c31ba3bb50ad687cee6/output/assets -A /Users/Chu/.android/build-cache/e120349e4cb265699199e0c78fa89730bd661b7d/output/assets -A /Users/Chu/.android/build-cache/cbec4122a354ea4ce9545a5017c89a260fbe005b/output/assets -A /Users/Chu/.android/build-cache/bbac0f26272becf649dfb34f178007f7d78e1d9d/output/assets -A /Users/Chu/.android/build-cache/ebdc765d8d8975f7749b7de81205068225196b81/output/assets -A /Users/Chu/.android/build-cache/13e9eb9e71575f6c2594c4e207f0a79f83e7bfd2/output/assets -A /Users/Chu/.android/build-cache/037a859528d44ea2c1b28a21d64dff5e325b279d/output/assets -A /Users/Chu/.android/build-cache/21401485fcb46bb607d1bebdf8fe2e733c24e715/output/assets -A /Users/Chu/.android/build-cache/d7d060fd8e9ae6f92dd2bdac4eb95401499d6bf2/output/assets -A /Users/Chu/.android/build-cache/3681c3df9e92a1f5474b5758cfc1eca1ce876d8a/output/assets -A /Users/Chu/.android/build-cache/e741c87a0eb69a2bc69c2b7a221db217419300aa/output/assets -A /Users/Chu/.android/build-cache/879f3e677740f51d4feb836ac1e1f33c027c20a0/output/assets -A /Users/Chu/.android/build-cache/b646baddf6de9342f01555d78c9284de902d72fd/output/assets -A /Users/Chu/.android/build-cache/1c8183c660304c06040c3e7ec73fbf9dcbb6d083/output/assets -A /Users/Chu/.android/build-cache/9d8240b0b646cef7c919b1578c62cbab624ca1f6/output/assets -A /Users/Chu/.android/build-cache/0817eddfbee7165fea59ec018bb69e795bbc07bf/output/assets -A /Users/Chu/.android/build-cache/d73cbd6be813620bb6c0c34f24169264aa872edc/output/assets -A /Users/Chu/.android/build-cache/6a586f7bdf9b1b43742f42f97a5e2de6ac145db7/output/assets -A /Users/Chu/.android/build-cache/d330ae76293e8e9499dd6d866cfe12dc067cb1d3/output/assets -A /Users/Chu/.android/build-cache/9e3e2e138f40e4a466c7fc212e7aef5fd66f2509/output/assets -A /Users/Chu/.android/build-cache/6c08ebf06310bb177dbe8d8b86fe9bcb685fde41/output/assets -A /Users/Chu/.android/build-cache/531f33b0653e50b1bc0d35e9fa8d056a20c9102e/output/assets -A /Users/Chu/.android/build-cache/43266d613eaebd50dc04c48512b2cb23721ba1a9/output/assets -A /Users/Chu/.android/build-cache/3d63331ac9586763d83f50208bbaf2c97f1881ab/output/assets -A /Users/Chu/.android/build-cache/922b0915f3ab162acd873a8c18c65138ed246465/output/assets -A /Users/Chu/.android/build-cache/e6878aabaf19cfe233b64fb624d6a64b0c399db3/output/assets -A /Users/Chu/.android/build-cache/b25947dc65c80904d1d756e9f20e356577cbaa62/output/assets -A /Users/Chu/.android/build-cache/3420dad41c37a498b67e4847f5ce5210acdf725b/output/assets -A /Users/Chu/.android/build-cache/378ee9796f599587b7fcb379167f508ccad1d4e0/output/assets -A /Users/Chu/.android/build-cache/ec34e056acda08e749fb721e7a2e65117afd8f05/output/assets -A /Users/Chu/.android/build-cache/ca270118c667518ca171638aa53c2393a94d2a4d/output/assets -m -J /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/newapp/backup --auto-add-overlay -F /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/base-res.so --debug-mode --no-version-vectors --resoucres-md5-cache-path /Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/arsc_cache.dat --ignore-assets public_id.xml:public.xml:*.bak:.* --ignore-ids avd_hide_password_1:avd_hide_password_2:avd_hide_password_3:avd_show_password_1:avd_show_password_2:avd_show_password_3
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s

修改xml布局文件后增量编译出错：
gChangeList = res/layout/activity_trading_detail.xml:res/values/freeline_id_keeper_public.xml:res/values/freeline_id_keeper_ids.xml
-ignore-ids = avd_hide_password_1:avd_hide_password_2:avd_hide_password_3:avd_show_password_1:avd_show_password_2:avd_show_password_3
Freeline trace:: skip data process
warning: overwriting '/Users/Chu/.android/build-cache/d330ae76293e8e9499dd6d866cfe12dc067cb1d3/output/assets/apktime' with '/Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/freeline-assets/apktime'
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '.*')
/Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/newapp/backup/AndroidManifest.xml:2: error: Error parsing XML: unbound prefix

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.3s
[DEBUG] Total time: 0.5s

**Comment by weixiao666** [comment]
同样的问题啊，求解

**Comment by lomanyong** [comment]
`/Users/Chu/Documents/workspace/project/Talicai_Studio_/newapp/build/freeline/newapp/backup/AndroidManifest.xml:2: error: Error parsing XML: unbound prefix`这个文件存在问题，可以clean后重新编译试试看

**Comment by weixiao666** [comment]
我的是修改类文件的时候没问题，修改xml文件只能全量更新，增量更新的时候就还是报这个错

**Comment by biyeshengplay** [comment]
我也遇到了同样的问题。
项目内给不同的buildtype配置了不同的applicationIdSuffix，而freeline包名默认取的是applicationId，这种情况下一修改布局文件就会报AndroidManifest.xml:2: error: Error parsing XML: unbound prefix。

解决办法：
使用Freeline DSL配置packageName为相应的applicationIdSuffix

**Comment by biyeshengplay** [comment]
@lomanyong @weixiao666 @Heart2009
