### ISSUE TITLE
[特性请求] 绝对路径->相对路径

### ISSUE THREAD

**Issue by XieEDeHeiShou** [alibaba/freeline#796]
我注意到项目根目录下的这个文件: freeline_project_description.json 中的内容是以绝对路径进行数据存储的.
会不会导致同一个项目在不同pc下进行增量编译时出现异常呢?
还是说换了PC后再次init就行了呢?
![tim 20170518174440](https://cloud.githubusercontent.com/assets/16363180/26196504/b74ba6a4-3bf1-11e7-9acf-9a94bf53a8fa.png)

**Comment by yrom** [comment]
这个json文件不应该加入版本控制，而是在各自开发环境初始化，如同 *.iml 一样
