### ISSUE TITLE
Error:Execution failed for task ':initFreeline'.

### ISSUE THREAD

**Issue by rmtic** [alibaba/freeline#797]
怎么解决
Error:Execution failed for task ':initFreeline'.
> Can't get http://static.freelinebuild.com/freeline/0.8.7/all/freeline.zip to /Users/Sam/MyDemo/freeline.zip.tmp

**Comment by lomanyong** [comment]
@rmtic 简单的方式，就是手动下载下来，然后通过`--freelineLocal`参数来使用本地的zip包

**Comment by spiritedRunning** [comment]
@lomanyong 请问这个--freelineLocal 具体是怎么使用的，命令格式是怎么样的？

**Comment by rmtic** [comment]
把freeline.zip下载，拷贝到目录下，如果是在mac系统上，在终端执行安装本地freeline的命令。就可以

**Comment by spiritedRunning** [comment]
@rmtic 安装本地freeline的命令是什么呢？ 其实我想问这个，Mac下

**Comment by tangchiech** [comment]
gradlew initFreeline -PfreelineLocal="your-local-freeline-path"
