### ISSUE TITLE
mergeProductionDebugAssets  提示下面的这个加到哪里啊

### ISSUE THREAD

**Issue by certhon** [alibaba/freeline#798]
Execution failed for task ':mergeProductionDebugAssets'.
> /Users/top/CODE/AllModule/TheStore-main/build/intermediates/assets/debug/apktime file not found. 
  Missing the `productFlavor` configuration?
  You can try to add `productFlavor` to freeline DSL, for example: 
  
    freeline { 
        hack true 
        productFlavor 'your-flavor' 
    }
  
  Then re-run `python freeline.py` again.

![image](https://cloud.githubusercontent.com/assets/17233918/26275407/2462701e-3d92-11e7-8be6-ee6198e03b22.png)

**Comment by lomanyong** [comment]
@certhon 这个是需要你配置`productFlavor`的，是会自动进行添加
