### ISSUE TITLE
找不到id

### ISSUE THREAD

**Issue by certhon** [alibaba/freeline#799]
Error:(2, 1) A problem occurred evaluating project ':TheStore-main'.
> Plugin with id 'com.antfortune.freeline' not found.

![image](https://cloud.githubusercontent.com/assets/17233918/26277271/cba531b6-3db7-11e7-8dc9-40840a851592.png)

**Comment by yrom** [comment]
你没有把freeline 加到 buildscript 下面的 classpath 里
