### ISSUE TITLE
一加手机存在增量资源导致crash的兼容性问题

### ISSUE THREAD

**Issue by HachikoDream** [alibaba/freeline#8]
当xml布局文件存在变更时，比如修改一个TextView的text属性，运行python freeline.py将直接导致程序崩溃，是目前的版本还不支持对xml布局文件的修改么？

**Comment by lomanyong** [comment]
@HachikoDream xml修改是支持的，甚至id的增加也是支持的。可以问一下crash具体的stacktrace是什么样的吗？

**Comment by HachikoDream** [comment]
08-22 15:59:00.863 27708-27708/w.dd.transitionlearn I/Freeline.Receiver: receive action type: 3
08-22 15:59:00.864 27708-27708/w.dd.transitionlearn D/Freeline.Receiver: destPath :/data/user/0/w.dd.transitionlearn/cache/temp/base-res.jar
08-22 15:59:00.864 27708-27708/w.dd.transitionlearn I/Freeline: apply res :{base-res=/data/user/0/w.dd.transitionlearn/cache/temp/base-res.jar}
08-22 15:59:00.864 27708-27708/w.dd.transitionlearn I/Freeline: dynamicInfoSp: {base-res.key=/data/user/0/w.dd.transitionlearn/cache/temp/base-res.jar, dynamicTime=1471852740864}
08-22 15:59:00.865 27708-27708/w.dd.transitionlearn I/Freeline: resMap: {base-res.key=/data/user/0/w.dd.transitionlearn/cache/temp/base-res.jar}
08-22 15:59:00.865 27708-27708/w.dd.transitionlearn I/Freeline.GradleDynamic: dynamicResPath: /data/user/0/w.dd.transitionlearn/cache/temp/base-res.jar
08-22 15:59:00.871 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010804d3 (t=7 e=1235) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080012 (t=7 e=18) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010806f9 (t=7 e=1785) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010806ff (t=7 e=1791) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010806fc (t=7 e=1788) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080253 (t=7 e=595) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080038 (t=7 e=56) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080012 (t=7 e=18) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080287 (t=7 e=647) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010803c9 (t=7 e=969) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010803c5 (t=7 e=965) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010803e7 (t=7 e=999) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080287 (t=7 e=647) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010805d4 (t=7 e=1492) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010804de (t=7 e=1246) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010804de (t=7 e=1246) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x0108051e (t=7 e=1310) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080027 (t=7 e=39) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010803f0 (t=7 e=1008) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080287 (t=7 e=647) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x0108024f (t=7 e=591) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010803f4 (t=7 e=1012) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010803cf (t=7 e=975) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x010803ec (t=7 e=1004) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080096 (t=7 e=150) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080342 (t=7 e=834) (error -75)
08-22 15:59:00.872 27708-27708/w.dd.transitionlearn W/ResourceType: Failure getting entry for 0x01080346 (t=7 e=838) (error -75)
08-22 15:59:00.874 27708-27708/w.dd.transitionlearn I/Freeline.GradleDynamic: GradleDynamic apply dynamic resource successfully
08-22 15:59:00.893 27708-27708/w.dd.transitionlearn I/Freeline.Receiver: receive action type: 1
08-22 15:59:00.894 27708-27708/w.dd.transitionlearn D/Freeline.ActManager: restartActivity :ComponentInfo{w.dd.transitionlearn/w.dd.transitionlearn.MainActivity}
08-22 15:59:00.895 27708-27708/w.dd.transitionlearn I/cdinfo: onDestroy: MainAct
                                                              
                                                              [ 08-22 15:59:00.898 27708:27708 W/         ]
                                                              Zip: read 4096 failed: Is a directory
08-22 15:59:00.898 27708-27708/w.dd.transitionlearn W/zipro: Error opening archive /data/user/0/w.dd.transitionlearn/cache/temp/base-res.jar: I/O Error
08-22 15:59:00.898 27708-27708/w.dd.transitionlearn D/asset: failed to open Zip archive '/data/user/0/w.dd.transitionlearn/cache/temp/base-res.jar'
08-22 15:59:00.898 27708-27708/w.dd.transitionlearn A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 27708 (transitionlearn)

**Comment by HachikoDream** [comment]
我改了一下TextView中的text的值 还有加了一个gravity属性  都是不行的

**Comment by HachikoDream** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@HachikoDream 目标机器的android版本是多少的呢？

**Comment by HachikoDream** [comment]
机器 一加A0001
系统 cm
Android版本 6.0.1
@lomanyong

**Comment by HachikoDream** [comment]
@lomanyong  应该是我手机环境问题，我新换了一个机器可以正常运行了。不过你看看那段日志能不能帮助你们排查一下问题吧，Andorid多机型适配确实比较烦，加油~ 整体效果很nice

**Comment by lomanyong** [comment]
@HachikoDream 恩，应该是机型的问题。在5.0+的android系统上，资源的读取方式应该是目录的形式。但是看日志把资源读取的方式作为zip来进行了，导致的io error，直接异常挂掉。

**Comment by lomanyong** [comment]
@HachikoDream 整体运行情况有数据吗~希望能够看下前后对比时间，包括资源修改与java文件修改的时间

**Comment by HachikoDream** [comment]
更改资源文件运行时间在 0.7s左右
更改java文件在1.5s左右 非常快了
不过目前是不支持butterknife这种框架的么？
@lomanyong

**Comment by lomanyong** [comment]
@HachikoDream 恩，暂时还不支持。最近会开始着手解决支持注解库的问题，会支持主流的注解库的。

**Comment by HachikoDream** [comment]
@lomanyong 加油

**Comment by lomanyong** [comment]
@HachikoDream 欢迎在你们的项目中使用哈~有任何问题欢迎随时提issue~

**Comment by lomanyong** [comment]
@HachikoDream 可以尝试升级freeline版本到0.5.3，然后看下是否在一加手机上还会有增量资源导致crash的问题。

注意，需要同时修改gradle插件与runtime的版本号，然后重新执行以下`./gradlew initFreeline`，之后便可正常使用。

**Comment by lomanyong** [comment]
@HachikoDream hello，最近有空可以更新一下freeline的版本，试下是否还在一加手机上存在这个问题
