### ISSUE TITLE
jar中图片等资源无法加载

### ISSUE THREAD

**Issue by sanxieryu** [alibaba/freeline#80]
项目中某个第三封jar包 将其用到的图片资源和.class 一起打入了jar包，使用Freeline 无法加载图片，程序崩溃

`    Bitmap var1 = BitmapFactory.decodeStream(var3 = c.class.getResourceAsStream("/picture/" + var0 + ".png"));
`

**Comment by charvenhe** [comment]
@sanxieryu,出错的堆栈麻烦贴下

**Comment by lomanyong** [comment]
@sanxieryu 方便说下使用了哪个第三方jar包吗？以便我们可以复现看看.

**Comment by lomanyong** [comment]
@sanxieryu 类似的问题我这边试图复现过，但是没有出现crash的问题，可以正常加载资源。所以还是需要你那边提供一下使用的jar包是哪个三方库的？

**Comment by zhoujianhanyu** [comment]
@lomanyong window 平台 0.6.0 版本  com.android.support:appcompat-v7的资源加载不了

**Comment by lomanyong** [comment]
@zhoujianhanyu @sanxieryu 最新的`0.7.0`已修复问题，可以更新试试看。
