### ISSUE TITLE
freeline_id_keeper_public is not defined.

### ISSUE THREAD

**Issue by GoOnToDeth** [alibaba/freeline#802]
D:\Zima_Project\ZiHang2.2.3\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:5132: error: Public symbol drawable/avd_hide_password_1 declared here is not defined.

第一次可以运行，第二次改完了代码在运行的时候就报这个错。

**Comment by lomanyong** [comment]
@GoOnToDeth 这个是已知问题，请降低android-design-support包来绕过这个bug，目前仅在windows出现
