### ISSUE TITLE
与Databinding冲突？

### ISSUE THREAD

**Issue by zx810506** [alibaba/freeline#81]
.....exchangeinfo.xml:37: error: Error: No resource type specified (at 'text' with value '@{account}').

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------

**Comment by zx810506** [comment]
看了之前的issue，希望能很快支持Databinding

**Comment by lomanyong** [comment]
@zx810506 恩，对于databinding的编译方案，后期我们会研究一下，后面陆续支持上。
