### ISSUE TITLE
错误: 找不到或无法加载主类 D:.Android.as_cache..gradle

### ISSUE THREAD

**Issue by yry0304** [alibaba/freeline#811]
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

错误: 找不到或无法加载主类 D:.Android.as_cache..gradle

[ERROR] --------------------------------------------------------
[ERROR] freeline failed when read project info with script: gradlew.bat -q checkBeforeCleanBuild
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 0.2s
[DEBUG] Total time: 0.4s
[DEBUG] --------------------------------------------------------

**Comment by lomanyong** [comment]
@yry0304 可以查看已有的issue，看着是本地环境的问题...
