### ISSUE TITLE
avd_show_password_3

### ISSUE THREAD

**Issue by a434413631** [alibaba/freeline#816]
freeline_id_keeper_public.xml:3343: error: Public symbol drawable/avd_hide_password_1 declared here is not defined.

有没有遇到这个错误的

**Comment by ab503044120** [comment]
有

**Comment by lomanyong** [comment]
@a434413631 @ab503044120 目前windows仍然有这个错误，在linux和mac上已经修复...

**Comment by a434413631** [comment]
那怎么办呢。。我记得之前没有这个问题的
