### ISSUE TITLE
gradlew initFreeline 一直卡在Building 0% > :initFreeline，gradlew initFreeline -Pmirror也不行

### ISSUE THREAD

**Issue by dh1021** [alibaba/freeline#817]
![qq 20170606093839](https://cloud.githubusercontent.com/assets/19261002/26810180/a8eee7a6-4a9c-11e7-86dd-ac82ba734af0.png)

**Comment by BolexLiu** [comment]
怎么解决的。我也卡在这里

**Comment by hejie** [comment]
我也是，现在解决了？
