### ISSUE TITLE
资源文件一修改，不能增量编译了，报下面的错误，怎么解决呢

### ISSUE THREAD

**Issue by WelliJohn** [alibaba/freeline#823]
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.7s
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 2.2s
[DEBUG] [librarypublic] librarypublic start to run after waiting 2.2s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.0s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 2.2s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
Freeline trace:: makeFileResources all resource. Time Elapsed: 0.056000 ms
Freeline trace:: compile values. Time Elapsed: 1.224000 ms
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.001000 ms

gChangeList = res/layout/staff_account_fragment.xml:res/values/freeline_id_keeper_public.xml:res/values/freeline_id_keeper_ids.xml
-resoucres-md5-cache-path = D:\work\business\app\build\freeline\arsc_cache.dat
warning: overwriting 'D:\work\business\librarypublic\src\main\assets\iconfont.ttf' with 'D:\work\business\app\src\main\assets\iconfont.ttf'
warning: overwriting 'C:\Users\user\.android\build-cache\c0c72d4b5eaf2a19f030396790f303cc17b8b3ed\output\assets\apktime' with 'D:\work\business\app\build\freeline\f
reeline-assets\apktime'
D:\work\business\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:2946: error: Public symbol drawable/avd_hide_password_1 declared here is not
 defined.
D:\work\business\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:2948: error: Public symbol drawable/avd_hide_password_2 declared here is not
 defined.
D:\work\business\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:2950: error: Public symbol drawable/avd_hide_password_3 declared here is not
 defined.
D:\work\business\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:2952: error: Public symbol drawable/avd_show_password_1 declared here is not
 defined.
D:\work\business\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:2954: error: Public symbol drawable/avd_show_password_2 declared here is not
 defined.
D:\work\business\app\build\freeline\app\backup\res\values\freeline_id_keeper_public.xml:2956: error: Public symbol drawable/avd_show_password_3 declared here is not
 defined.

**Comment by lomanyong** [comment]
@WelliJohn 这个问题在win系统上是已知的，通过降级support-design包的版本可以暂时绕过这个问题。具体可以参考issue #539
