### ISSUE TITLE
第一次能够安装，第二次就一直报这个错，从mac换到window 还是这样子，只有第一次全量编译能够行

### ISSUE THREAD

**Issue by certhon** [alibaba/freeline#824]
Please make sure your application is properly running in your device.
        Check follow steps:
        1. Make sure the versions `python freeline.py -v`, freeline-gradle and freeline-runtime are the same;
        2. Make sure there is no network proxy.

**Comment by lomanyong** [comment]
@certhon 看下logcat，过滤跟freeline相关的日志，然后就可以看到关键的错误信息。根据这个错误信息来搜索一下就能解决你的问题了。

**Comment by certhon** [comment]
VM has multidex support, MultiDex support library is disabled
过滤freeline 就这一个日志
