### ISSUE TITLE
Eclipse工程转AndroidStudio 使用FreeLine加快编译速度

### ISSUE THREAD

**Issue by candledragle** [alibaba/freeline#828]
我的工程的各个module当初都是在Eclipse上开发的各个Library，现在想改造成AndroidStudio的多module的组件化开发，想使用FreeLine加快编译速度，但是按照官方的文档配置后，还是遇到了一些问题
我要问的第一个问题是：
配置了
```
  sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }

        instrumentTest.setRoot('tests')

        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')

    }
```
后FreeLine无法识别工程结构，报的错是，无法找到一个资源和文件，我写了demo将其中的一个改造成AS默认的工程呢个结构，然后使用freeLine编译通过，我想知道FreeLine能兼容从Eclipse转化过来的工程吗，需要我怎样配置，谢谢

**Comment by candledragle** [comment]
@zhuzhaoyuan @JacksonTian @oldratlee @wenshao @lvscar

**Comment by candledragle** [comment]
@lomanyong

**Comment by lomanyong** [comment]
@candledragle 转为as的工程结构时，请保证根module是一个空的module，不包含src等相关的资源，即整个工程的结构类似一个新建的as的工程即可。

Freeline没有添加对eclipse直接转换的工程的支持...
