### ISSUE TITLE
MultiDex: VM has multidex support, MultiDex support library is disabled

### ISSUE THREAD

**Issue by certhon** [alibaba/freeline#829]
Please make sure your application is properly running in your device.
Check follow steps:
1. Make sure the versions python freeline.py -v, freeline-gradle and freeline-runtime are the same;
2. Make sure there is no network proxy.

过滤freeline log:
MultiDex: VM has multidex support, MultiDex support library is disabled

**Comment by certhon** [comment]
![image](https://user-images.githubusercontent.com/17233918/27374961-47519682-56a0-11e7-83df-7e407aaaee3b.png)

**Comment by certhon** [comment]
python freeline.py -v  使用这个命令 查看到的版本和本地一致
在不联网的情况 应该是不存在代理什么的把  也不行

**Comment by lomanyong** [comment]
@certhon 可以看一下logcat里关于freeline的日志输出，就可以定位问题所在了
