### ISSUE TITLE
Freeline开发Android Studio插件

### ISSUE THREAD

**Issue by aa5279aa** [alibaba/freeline#84]
现在每次执行python freeline.py都感觉有点麻烦，所以开发了一个简单的AS插件，点击之后的效果等同于执行命令python freeline.py。
希望后续的版本中能够增加上这个功能。
插件地址：http://download.csdn.net/detail/aa5279aa/9622072

**Comment by charvenhe** [comment]
@aa5279aa 你好，非常赞，方便的话可以给我们提个pr，我们合到主干

**Comment by pengwei1024** [comment]
插件完全看不到日志啊。。。 @aa5279aa

**Comment by aa5279aa** [comment]
Sorry，第一版的话只是为了我本人的本地调试方便。所以对应代码仅仅只是执行了python freeline.py命令，由于增量更新的话只有10秒左右，而不去care输出的结果。
只是一个建议希望以后加上插件功能。
地址：
https://github.com/aa5279aa/xt_freeline_as_plugin
我这周三之前争取开发完带日志功能的plugin，然后到时候看看效果
@pengwei1024

**Comment by lomanyong** [comment]
@aa5279aa 今天还有人提了这个pr #89 ，也可以看下

**Comment by act262** [comment]
OMG竟然重复了。。

**Comment by lomanyong** [comment]
@act262 插件还有很多方面要做的，不只是可以运行python脚本，包括log打印这些其实都要可以的，所以还是有很多的工作可以做的wwww

**Comment by aa5279aa** [comment]
可以开个分支开放权限，到时候一起来做，做好了之后在合并到主分支上。
其实最理想的状态应该是在AS中开一个日志输出台来监控日志。
另外initFreeline其实也可以集成到插件当中，甚至还可以做一个监控本地配置是否正确的操作。
@act262 
@lomanyong

**Comment by lomanyong** [comment]
@aa5279aa @act262 我新开了一个branch，`as_plugin`，添加了一个`android-studio-plugin`的文件夹。之后关于插件的代码都可以先往这个分支上提pr。

关于插件工程的讨论也可以在这个issue中进行。

**Comment by act262** [comment]
good idea

**Comment by c1031612246** [comment]
插件装上之后出现异常
![image](https://cloud.githubusercontent.com/assets/13751034/18300491/1f4ccd04-74fc-11e6-8243-f2ceb9ccba02.png)

**Comment by aa5279aa** [comment]
@act262 
第一版的话想使用java GUI去展示log信息，写了一个大概，自测还行，就是界面难看点，以后再尝试移到Console里面。
@lomanyong 
已经邮件申请开放as_plugin的权限，望审批

**Comment by aa5279aa** [comment]
@c1031612246 
没遇到过这种情况，可以的话邮件联系我。希望能够告诉我一个复现步骤。
5694209@qq.com

**Comment by c1031612246** [comment]
@aa5279aa 我只是在你的github下载的弄过jar文件，导入到as之后就，as重启后出现了这个错误，我点击错误，显示的是这个
![image](https://cloud.githubusercontent.com/assets/13751034/18302582/3810feaa-750b-11e6-8874-460dde899bf9.png)

**Comment by lomanyong** [comment]
@aa5279aa 抱歉回复晚了哈，权限问题没办法把你加入group中，不过你可以把修改后的代码提PR时，提交到freeline的`as_plugin`这个branch。

以及，最好还是能够调用IDEA的API，将freeline的日志输出打入到console之类的窗口中，这样体验会好点~~

**Comment by huangying812** [comment]
如何使用这个as_plugin呢？最好也写一个文档吧，tks

**Comment by lomanyong** [comment]
插件已merge到master分支，`android-studio-plugin`文件夹
