### ISSUE TITLE
不支持新增VectorDrawable的增量编译

### ISSUE THREAD

**Issue by pcyan** [alibaba/freeline#85]
添加新的`VectorDrawable`之后，增量编译可以通过，但是会找不到图片，从而引起崩溃
其实修改或者新增`VectorDrawable`的话是应该触发全量编译的

**Comment by charvenhe** [comment]
@pcyan 指的是xml新增这个还是修改java？

**Comment by pcyan** [comment]
@charvenhe 新增xml文件

**Comment by charvenhe** [comment]
@pcyan 好的，我们先复现看看

**Comment by lomanyong** [comment]
关联commit：
6b25c56
f54cfa4
9ce7684
