### ISSUE TITLE
无法集成freeline

### ISSUE THREAD

**Issue by lijian8742** [alibaba/freeline#853]
Error:A problem occurred configuring root project 'JoyinWiseSeller_three'.
> Could not resolve all dependencies for configuration ':_app.joyinwiseDebugCompile'.
   > Could not find com.antfortune.freeline:runtime:0.8.7.
     Searched in the following locations:
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.pom
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.jar
         https://repo1.maven.org/maven2/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.pom
         https://repo1.maven.org/maven2/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.jar
         file:/Users/lijian/.m2/repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.pom
         file:/Users/lijian/.m2/repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.jar
         file:/Users/lijian/AndroidStudioWorkspace/JoyinWiseSeller_three/libs/runtime-0.8.7.jar
         file:/Users/lijian/AndroidStudioWorkspace/JoyinWiseSeller_three/libs/runtime.jar
         file:/Users/lijian/Library/Android/sdk/extras/android/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.pom
         file:/Users/lijian/Library/Android/sdk/extras/android/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.jar
         file:/Users/lijian/Library/Android/sdk/extras/google/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.pom
         file:/Users/lijian/Library/Android/sdk/extras/google/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.jar
         file:/Users/lijian/Library/Android/sdk/extras/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.pom
         file:/Users/lijian/Library/Android/sdk/extras/m2repository/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.jar
     Required by:
         :JoyinWiseSeller_three:unspecified

**Comment by lijian8742** [comment]
在浏览器里访问：https://repo1.maven.org/maven2/com/antfortune/freeline/runtime/0.8.7/runtime-0.8.7.jar    结果是404

**Comment by YanHuiLi** [comment]
因为freeline 并没有放在maven里面，
你的项目要使用
```java
allprojects {
    repositories {
        jcenter()
    }
}
```
