### ISSUE TITLE
initFreeLine出错

### ISSUE THREAD

**Issue by fenglintianxia6** [alibaba/freeline#86]
FAILURE: Build failed with an exception.

* What went wrong:
Task 'initFreeline' not found in root project 'XXX'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

错误信息如上 执行./gradlew initFreeline 时出错

**Comment by JakeyYe** [comment]
怎么样，有结果了吗，同样BUILD FAILED.

**Comment by fenglintianxia6** [comment]
我好像是有一个配置没有加进去，你仔细对照一下你的gradle和模板吧

**Comment by JakeyYe** [comment]
好，谢谢，我试试。

**Comment by gzpaiwxc** [comment]
一样是遇到Task 'initFreeline' not found in root project ‘XXX’这个错误，为什么没有看到解决的办法呢？

**Comment by lomanyong** [comment]
@gzpaiwxc 百分之九十是你没有添加`apply plugin: "com.antfortune.freeline"`
