### ISSUE TITLE
read_project_info_task] running... in 卡死了

### ISSUE THREAD

**Issue by emile2013** [alibaba/freeline#873]
一直在运行[+][read_project_info_task] running... in  500s； 正常gradle 早编译和安装了；不知道是哪的原因，全量不会有这么久的

**Comment by emile2013** [comment]
另外，在ART 上 删除方法或变量，地址错乱的概率还挺高的

**Comment by lomanyong** [comment]
地址错乱的问题比较经常发生在抽象类和接口的相关修改上，目前还没有解决方案
