### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Resolving configuration 'annotationProcessor' directly is not allowed

### ISSUE THREAD

**Issue by feisher** [alibaba/freeline#874]
[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat :app:assembleDebug -P freelineBuild=true --stacktrace

使用AS的编译安装没有问题，但是使用Freeline就报错，求解决方案(windows 系统)

**Comment by life2015** [comment]
因为你用的是AS3.0吧
那个问题修复后还没有release 换成之前的Android plugin即可

**Comment by lvtanxi** [comment]
那要什么时候才release新版本呢？毕竟as 3.0已经正式上线了

**Comment by life2015** [comment]
已经大概适配了 但是感觉全量速度没有想象中快...

**Comment by lvtanxi** [comment]
好吧。还是希望能尽快出来一个release版本。手残升级了as，项目没有Freeline真心的不习惯。

**Comment by life2015** [comment]
你可以把gradle plugin的版本设置成2.3.3 依然可以运行
` classpath 'com.android.tools.build:gradle:2.3.3'`
