### ISSUE TITLE
全量编译可以进行，增量编译报错

### ISSUE THREAD

**Issue by iwuq** [alibaba/freeline#904]
[DEBUG] [sync_client] server result is 1
[DEBUG] [sync_client] find device port: 41128
[DEBUG] [connect_device_task] connect_device_task finish in 0.2s
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 1.3s
[DEBUG] [libraryrefresh] libraryrefresh start to run after waiting 1.3s
[DEBUG] [coutdowntimelibrary] coutdowntimelibrary start to run after waiting 1.3s
[DEBUG] [library] library start to run after waiting 1.3s
[DEBUG] [PhotoPicker] PhotoPicker start to run after waiting 1.3s
[DEBUG] [libbusiness] libbusiness start to run after waiting 1.1s
[DEBUG] [launchActivity] launchActivity start to run after waiting 0.0s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 0.0s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 0.0s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 0.0s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 0.0s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 1.3s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
nothing matches overlay file com_search01.png, for flavor xhdpi-v4
nothing matches overlay file com_search01_presssed.png, for flavor xhdpi-v4
nothing matches overlay file icon_shop_favorite_selected.png, for flavor
nothing matches overlay file refresh_black.png, for flavor
nothing matches overlay file search_box_background.xml, for flavor
Freeline trace:: makeFileResources all resource. Time Elapsed: 0.062000 ms
Freeline trace:: compile values. Time Elapsed: 0.734000 ms
Freeline trace:: makeFileResources for color and menu. Time Elapsed: 0.000000 ms

gChangeList = res/layout/my_personal.xml:res/values/freeline_id_keeper_public.xml:res/values/freeline_id_keeper_ids.xml
-resoucres-md5-cache-path = D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\arsc_cache.dat
warning: overwriting 'C:\Users\Administrator\.android\build-cache\bbcbe961fe0f281b40fca40edab0189becf7214e\output\assets\apktime' with 'D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\freeline-assets\apktime'
D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\launchActivity\backup\res\values\freeline_id_keeper_public.xml:4765: error: Public symbol drawable/avd_hide_password_1 declared here is not defined.
D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\launchActivity\backup\res\values\freeline_id_keeper_public.xml:4767: error: Public symbol drawable/avd_hide_password_2 declared here is not defined.
D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\launchActivity\backup\res\values\freeline_id_keeper_public.xml:4769: error: Public symbol drawable/avd_hide_password_3 declared here is not defined.
D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\launchActivity\backup\res\values\freeline_id_keeper_public.xml:4771: error: Public symbol drawable/avd_show_password_1 declared here is not defined.
D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\launchActivity\backup\res\values\freeline_id_keeper_public.xml:4773: error: Public symbol drawable/avd_show_password_2 declared here is not defined.
D:\Dev\StudioProjects\yunshang\ysysgo\launchActivity\build\freeline\launchActivity\backup\res\values\freeline_id_keeper_public.xml:4775: error: Public symbol drawable/avd_show_password_3 declared here is not defined.

[ERROR] --------------------------------------------------------
[ERROR] incremental res build failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 1.3s
[DEBUG] Total time: 1.6s
[DEBUG] --------------------------------------------------------

**Comment by shenquan** [comment]
同样~

**Comment by shenquan** [comment]
我也遇到类似的问题，最终发现不是freeline的原因。是自己的代码写错了，查看报错的代码位置，修改自己的代码就行了。

**Comment by shenquan** [comment]
把-v4的去掉，不要使用v4。
