### ISSUE TITLE
拉不到freeline包，导致初始化出错

### ISSUE THREAD

**Issue by gongtingshisi** [alibaba/freeline#913]
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
variant debug is not zh_tw, skip hack process.
variant release is not debug, skip hack process.
:initFreeline
Freeline initial process start...
[NOTE] Download freeline dependency for specific version 0.8.7...
Downloading release pack from http://static.freelinebuild.com/freeline/0.8.7/all/freeline.zip
Please wait a minute...
      [get] Getting: http://static.freelinebuild.com/freeline/0.8.7/all/freeline.zip
      [get] To: /Users/zhangfeng/Work/baikal_dev/baikal/freeline.zip.tmp
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 407 for URL: http://static.freelinebuild.com/freeline/0.8.7/all/freeline.zip
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 407 for URL: http://static.freelinebuild.com/freeline/0.8.7/all/freeline.zip
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 407 for URL: http://static.freelinebuild.com/freeline/0.8.7/all/freeline.zip
      [get] Can't get http://static.freelinebuild.com/freeline/0.8.7/all/freeline.zip to 
:initFreeline FAILED

**Comment by lomanyong** [comment]
@gongtingshisi 文件是存在的，下载也没啥问题，确认一下是否开了代理网络

**Comment by gongtingshisi** [comment]
代理关了，也是不行。需要重启mac吗

**Comment by lomanyong** [comment]
@gongtingshisi 主要是网络问题，你可以直接在浏览器访问一下这个链接试试看

**Comment by gongtingshisi** [comment]
好的，可以了，我关闭了终端重开就可以了。谢谢高效的support。可以关闭了。
