### ISSUE TITLE
android studio 3.0 gradle 3.0 初始化失败 (已解决)

### ISSUE THREAD

**Issue by firsthubgit** [alibaba/freeline#914]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'baihejia-android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
     Required by:
         project :
   > Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
     Required by:
         project : > com.antfortune.freeline:gradle:0.8.8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by act262** [comment]
3.0.0 需要在 repository 中加入 google 源

**Comment by dhhAndroid** [comment]
在项目的gradle.properties文件中加入 android.enableAapt2=false，就可以解决这个问题

**Comment by sksweet** [comment]
这个也碰过，加google（），但是要VPN。要不第一次下不来。。。

**Comment by firsthubgit** [comment]
可以初始化了，加google()  翻墙下就行
