### ISSUE TITLE
连接不上设备

### ISSUE THREAD

**Issue by leehong2005** [alibaba/freeline#93]
第一次运行python freeline.py后，app能正常启动，修改资源文件后，再运行python freeline.py，却报错。

这是第一次运行的结果：
````
➜  tbreader git:(tbreader_6_2_0) ✗ python freeline.py
[WARNING] NoInstallationException occurs, a clean build will be automatically executed.
[-][read_project_info_task] finished. in 10.8s
[-][generate_file_stat_task] finished. in 0.1s
[-][gradle_clean_build_task] finished. in 89.2s
[-][clean_all_cache_task] finished. in 0.0s
[-][install_apk_task] finished. in 10.4s
[-][build_base_resource_task] finished. in 1.5s
[-][generate_project_info_task] finished. in 0.0s
[DEBUG] --------------------------------------------------------
[DEBUG] Prepare tasks time: 13.9s
[DEBUG] Task engine running time: 110.4s
[DEBUG] Total time: 124.3s
[DEBUG] --------------------------------------------------------
````

这是第二次运行的结果：

````
➜  tbreader git:(tbreader_6_2_0) ✗ python freeline.py
[INFO] preparing for tasks...
[-][connect_device_task] failed. in 13.7s
[-][gradle_aapt_task] finished. in 0.5s
[-][AppLibrary] finished. in 0.0s
[-][AthenaSDK] finished. in 0.0s
[-][TBReader] finished. in 0.0s
[-][merge_dex_task] finished. in 0.0s
[-][gradle_sync_task] failed. in 0s
[-][clean_cache_task] failed. in 0s
[-][update_stat_task] failed. in 0s
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
	Please make sure your application is properly running in your device.
	Check follow steps:
	1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package com.tbreader.android is not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.2s
[DEBUG] Task engine running time: 13.7s
[DEBUG] Total time: 14.0s
[DEBUG] --------------------------------------------------------
````

请问这是什么问题呢？ #29

**Comment by charvenhe** [comment]
@leehong2005 看看FreelinCore.init是否有在Application onCreate 第一行加进去

**Comment by danyunliuhen** [comment]
你把APP当前进程杀死，退居后台再run就行了 我也遇到这个问题了

**Comment by charvenhe** [comment]
@leehong2005 com.tbreader.android这个是你们的package名吗

**Comment by danyunliuhen** [comment]
好吧 我仔细测试了下 跟他的问题一样，第二次运行就报包名找不到了 而且中间会
 try to connect device 22 times... 很多次连接设备

**Comment by charvenhe** [comment]
@danyunliuhen 能加个“-d” 然后把连接不上的日志发出来吗

**Comment by danyunliuhen** [comment]
[DEBUG] [dispatcher] command line args: Namespace(all=False, clean=False, cleanBuild=False, debug=True, init=False, version=False)
[DEBUG] [scan_changed_files_command] find G:\AsWork\MiniErp\app\src\main\jniLibs\armeabi-v7a\libminierp.so has modification.
[DEBUG] [scan_changed_files_command] find G:\AsWork\MiniErp\app\src\main\java\fm\fmphoto\FmEngine.java has modification.
[DEBUG] find app has 1 java files modified.
[DEBUG] project just need a incremental build.
[DEBUG] file changed list:
{
    "build_info": {
        "last_clean_build_time": 1473305323.868284,
        "is_root_config_changed": false
    },
    "projects": {
        "app": {
            "src": [
                "G:\\AsWork\\MiniErp\\app\\src\\main\\java\\fm\\fmphoto\\FmEngine.java"
            ],
            "so": [
                "G:\\AsWork\\MiniErp\\app\\src\\main\\jniLibs\\armeabi-v7a\\libminierp.so"
            ],
            "assets": [],
            "libs": [],
            "res": [],
            "config": [],
            "cpp": [],
            "manifest": []
        }
    }
}
[DEBUG] [gradle_inc_builder] append G:\AsWork\MiniErp\app\src\main\jniLibs\armeabi-v7a\libminierp.so to native queue
[DEBUG] [task_engine] depth: 1, task: [connect_device_task]
[DEBUG] [task_engine] depth: 1, task: [gradle_aapt_task]
[DEBUG] [task_engine] depth: 2, task: [app]
[DEBUG] [task_engine] depth: 3, task: [merge_dex_task]
[DEBUG] [task_engine] depth: 5, task: [gradle_sync_task]
[DEBUG] [task_engine] depth: 6, task: [clean_cache_task]
[DEBUG] [task_engine] depth: 7, task: [update_stat_task]
[DEBUG] [connect_device_task] connect_device_task start to run after waiting 0.0s
[DEBUG] [gradle_aapt_task] gradle_aapt_task start to run after waiting 0.0s
[DEBUG] [sync_client] start to connect device...
[DEBUG] [gradle_aapt_task] no need to execute
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [gradle_aapt_task] gradle_aapt_task finish in 0.0s
[DEBUG] [app] app start to run after waiting 0.0s
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [app_inc_invoker] app old R.java path: G:\AsWork\MiniErp\app\build\generated\source\r\debug\com\hhwy\miniErp\R.java
[DEBUG] [app_inc_invoker] app new R.java path: G:\AsWork\MiniErp\app\build\freeline\app\backup\com\hhwy\miniErp\R.java
[DEBUG] [app_inc_invoker] find R.java changed (md5 value is different from origin R.java)
[DEBUG] [app_inc_invoker] src changed files:
[DEBUG] [app_inc_invoker] [u'G:\\AsWork\\MiniErp\\app\\src\\main\\java\\fm\\fmphoto\\FmEngine.java', u'G:\\AsWork\\MiniErp\\app\\build\\freeline\\app\
\backup\\com\\hhwy\\miniErp\\R.java']
[DEBUG] [app_inc_invoker] find R.java modified in src list
[DEBUG] [app_inc_javac_compile] start to execute javac command...
[DEBUG] [app_inc_invoker] avoid windows unicode error for G:\AsWork\MiniErp\app\build\freeline\app\backup\com\hhwy\miniErp\R.java
[DEBUG] [app_inc_invoker] javac exec: D:\jdk1.8\bin\javac.exe -target 1.7 -source 1.7 -encoding UTF-8 -g -cp G:\AsWork\MiniErp\app\build\freeline\app\
classes;G:\AsWork\MiniErp\app\build\intermediates\classes\debug;D:\SDK\platforms\android-24\android.jar;G:\AsWork\MiniErp\app\libs\BaiduLBS_Android.ja
r;G:\AsWork\MiniErp\app\libs\umeng-analytics-v5.4.1.jar;G:\AsWork\MiniErp\app\libs\BaiduTraceSDK_v2_1_12.jar;G:\AsWork\MiniErp\app\libs\libammsdk.jar;
G:\AsWork\MiniErp\app\libs\TalkingData_Analytics_Android_SDK_V2.2.30.jar;G:\AsWork\MiniErp\app\libs\GetuiSDK2.9.0.0.jar;G:\AsWork\MiniErp\app\libs\QtA
ndroidAccessibility-bundled.jar;G:\AsWork\MiniErp\app\libs\QtAndroidBearer-bundled.jar;G:\AsWork\MiniErp\app\libs\xUtils-2.6.8.jar;G:\AsWork\MiniErp\a
pp\libs\myrec.jar;G:\AsWork\MiniErp\app\libs\QtAndroid-bundled.jar;G:\AsWork\MiniErp\app\libs\gson-2.2.1.jar;G:\AsWork\MiniErp\app\libs\QtMultimedia-b
undled.jar;G:\AsWork\MiniErp\app\libs\QtPositioning-bundled.jar;G:\AsWork\MiniErp\app\libs\glide-3.7.0.jar;G:\AsWork\MiniErp\app\libs\picker.jar;G:\As
Work\MiniErp\app\libs\org.apache.http.legacy.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.android.support\support-compat\24.2.0\jars
\libs\internal_impl-24.2.0.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.android.support\support-vector-drawable\24.2.0\jars\classes.
jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.android.support\support-core-ui\24.2.0\jars\libs\internal_impl-24.2.0.jar;G:\AsWork\Min
iErp\app\build\intermediates\exploded-aar\com.android.support\support-fragment\24.2.0\jars\classes.jar;G:\AsWork\MiniErp\app\build\intermediates\explo
ded-aar\com.android.support\support-compat\24.2.0\jars\classes.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.android.support\animated
-vector-drawable\24.2.0\jars\classes.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.android.support\support-fragment\24.2.0\jars\libs\
internal_impl-24.2.0.jar;D:\SDK\extras\android\m2repository\com\android\support\support-annotations\24.2.0\support-annotations-24.2.0.jar;G:\AsWork\Mi
niErp\app\build\intermediates\exploded-aar\com.android.support\support-media-compat\24.2.0\jars\libs\internal_impl-24.2.0.jar;G:\AsWork\MiniErp\app\bu
ild\intermediates\exploded-aar\com.android.support\support-media-compat\24.2.0\jars\classes.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar
\com.android.support\support-core-utils\24.2.0\jars\classes.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.android.support\support-cor
e-utils\24.2.0\jars\libs\internal_impl-24.2.0.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\24.2.0\jars\
classes.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.6.0\jars\classes.jar;G:\AsWork\MiniErp\app\build\
intermediates\exploded-aar\com.android.support\support-core-ui\24.2.0\jars\classes.jar;G:\AsWork\MiniErp\app\build\intermediates\exploded-aar\com.andr
oid.support\support-v4\24.2.0\jars\classes.jar G:\AsWork\MiniErp\app\src\main\java\fm\fmphoto\FmEngine.java G:\AsWork\MiniErp\app\build\freeline\app\b
ackup\com\hhwy\miniErp\R.java -d G:\AsWork\MiniErp\app\build\freeline\app\classes
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [app_inc_invoker] copy G:\AsWork\MiniErp\app\build\freeline\app\backup\com\hhwy\miniErp\R.java to G:\AsWork\MiniErp\app\build\generated\source
\r\debug\com\hhwy\miniErp\R.java
[DEBUG] [app_inc_dex_compile] start to execute dex command...
[DEBUG] [app_inc_invoker] dex exec: D:\SDK\build-tools\24.0.2\dx.bat --dex --output=G:\AsWork\MiniErp\app\build\freeline\app\dex\app.dex G:\AsWork\Min
iErp\app\build\freeline\app\classes
[DEBUG] [sync_client] try to connect device 1 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [app] app finish in 3.4s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 3.4s
[DEBUG] [merge_dex_task] just 1 dex need to sync, copy G:\AsWork\MiniErp\app\build\freeline\app\dex\app.dex to G:\AsWork\MiniErp\app\build\freeline\in
crement.dex
[DEBUG] [merge_dex_task] merge_dex_task finish in 0.0s
[DEBUG] [sync_client] try to connect device 2 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 3 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 4 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 5 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 6 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 7 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 8 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 9 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 10 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 11 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 12 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 13 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 14 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 15 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 16 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 17 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 18 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 19 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 20 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 21 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 22 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 23 times...
[DEBUG] [sync_client] apktime path: G:\AsWork\MiniErp\app\build\freeline\freeline-assets\apktime
[DEBUG] [sync_client] your local sync value is: 175000
[DEBUG] [sync_client] your local uuid value is: b42e511af5a65163884e4edf1fd5f9c8
[DEBUG] [sync_client] try to connect device 24 times...
[DEBUG] [sync_client] package com.hhwy.miniErp not found. Please make sure your application is properly running in your device, freeline will start a
clean build
[DEBUG] [connect_device_task] connect_device_task finish in 23.6s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 23.6s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 23.6s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 23.6s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 23.64s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------
        Please make sure your application is properly running in your device.
        Check follow steps:
        1. If freeline is not added to your app's denpendencies, modifiy your dependency and run `python freeline.py -f`.
[ERROR] --------------------------------------------------------
[ERROR] Package com.hhwy.miniErp is not found.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 23.6s
[DEBUG] Total time: 23.9s
[DEBUG] --------------------------------

**Comment by charvenhe** [comment]
@leehong2005 @danielzhou82 更新到0.6.1版本试试看这个问题是否已经解决

**Comment by leehong2005** [comment]
@charvenhe 可以确认集成方式都是正常的，按照你的文档说明来的。
之前试了一下，是从入门到放弃，对于商业项目我再评估下是否要用起来，不过都是阿里集团的东西，支持~~~

好的，我再试试新版本。

**Comment by charvenhe** [comment]
@leehong2005 可以尝试用最新0.6.3降低了连接不上的概率

**Comment by yinduo527** [comment]
同样遇到此类问题，版本0.6.3，求解决

**Comment by charvenhe** [comment]
@yinduo527 @danielzhou82 

问题都解决了没？没有的话

**Comment by charvenhe** [comment]
0.7已经进行专门处理，后续有类似问题移步这里讨论 #152
