### ISSUE TITLE
代码中使用了https://github.com/evant/android-retrolambda-lombok，修改方法时报错

### ISSUE THREAD

**Issue by chrise-dcq** [alibaba/freeline#94]
报错提示：

警告: [options] 未与 -source 1.7 一起设置引导类路径
 (请使用 -source 8 或更高版本以启用方法引用)
  (请使用 -source 8 或更高版本以启用 lambda 表达式)
2 个错误
1 个警告

**Comment by lomanyong** [comment]
@chrise-dcq freeline暂时不支持lambda哈，预计这个月内会支持。

**Comment by LanderlYoung** [comment]
遇到相同问题，请问这个支持已经可以了吗。需要什么版本的~十分感谢。

**Comment by Yumee** [comment]
加一，freeline 版本  :0.8.4'

**Comment by lomanyong** [comment]
@LanderlYoung @Yumee 报错的具体日志可以贴出来吗？

**Comment by Yumee** [comment]
日志如下
[DEBUG] [app] app finish in 1.7s
[DEBUG] [merge_dex_task] merge_dex_task start to run after waiting 1.7s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 1.7s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 1.7s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 1.7s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 5.51s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

警告: [options] 未与 -source 1.7 一起设置引导类路径                                                                                                                 
D:\WorkSpace\****(类名): 错误: -source 1.7 中不支持 lambda 表达式                     
        NetWorker.work(url, (status, result) -> {}
                                                                                                                   ^
  (请使用 -source 8 或更高版本以启用 lambda 表达式)                                                                                                                 
1 个错误                                                                                                                                                            
1 个警告                                                                                                                                                            

[ERROR] --------------------------------------------------------
[ERROR] incremental javac compile failed.
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.7s
[DEBUG] Task engine running time: 5.5s
[DEBUG] Total time: 6.2s
[DEBUG] --------------------------------------------------------

**Comment by njleonzhang** [comment]
一样的问题，可以解决么？

**Comment by njleonzhang** [comment]
@lomanyong
