### ISSUE TITLE
执行python freeline.py 报错

### ISSUE THREAD

**Issue by qsyj** [alibaba/freeline#95]
执行完gradlew.bat initFreeline成功后执行python freeline.py
报错：
[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat assembleDebug
[ERROR] --------------------------------------------------------

====请问怎么解决？=====

========================
附—我的项目设置：
1:project-level build.gradle 
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.antfortune.freeline:gradle:0.6.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
2：build.gradle（app）
apply plugin: 'com.android.application'
apply plugin: 'com.antfortune.freeline'
android {
    freeline {
        hack true
    }
    compileSdkVersion 23
    buildToolsVersion '23.0.2'
   defaultConfig {
        minSdkVersion 15
        targetSdkVersion 21
       .....
    }
....
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.antfortune.freeline:runtime:0.6.0'
}

3.Application
public void onCreate() {
        if (Config.DEVELOPER_MODE
                && Build.VERSION.SDK_INT >= Build.VERSION_CODES.GINGERBREAD) {
            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectAll().penaltyDialog().build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectAll().penaltyDeath().build());
        }
        super.onCreate();
        FreelineCore.init(this);
}
4.python-2.7.12

**Comment by lomanyong** [comment]
@qsyj 有上面具体的报错信息吗？

**Comment by qsyj** [comment]
@lomanyong 
BUILD FAILED

Total time: 4.193 secs


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeFlavors_userDebugAssets'.
> J:\studioproject\bitbucket\mobilebank\app\build\intermediates\assets\debug\apk
time file not found.
Missing the `productFlavor` configuration?
You can try to add `productFlavor` to freeline DSL, for example:

  freeline {
      hack true
      productFlavor 'your-flavor'
  }

Then re-run `python freeline.py` again.


* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mer
geFlavors_userDebugAssets'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
xecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: J:\studioproject\bitbucket\mobilebank
\app\build\intermediates\assets\debug\apktime file not found.
Missing the `productFlavor` configuration?
You can try to add `productFlavor` to freeline DSL, for example:

  freeline {
      hack true
      productFlavor 'your-flavor'
  }

Then re-run `python freeline.py` again.

        at com.antfortune.freeline.FreelinePlugin$_addFreelineGeneratedFiles_clo
sure4.doCall(FreelinePlugin.groovy:240)
        at com.antfortune.freeline.FreelinePlugin.addFreelineGeneratedFiles(Free
linePlugin.groovy:235)
        at com.antfortune.freeline.FreelinePlugin$_apply_closure3_closure6_closu
re9.doCall(FreelinePlugin.groovy:93)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more


[ERROR] --------------------------------------------------------
[ERROR] build failed with script: gradlew.bat assembleDebug
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 0.3s
[DEBUG] Task engine running time: 6.9s
[DEBUG] Total time: 7.3s
[DEBUG] --------------------------------------------------------

信息是这个 

我找到原因了
把
freeline {
        hack true
    }
--》
freeline {
        hack true
        productFlavor 'flavors_user'
    }

**Comment by lomanyong** [comment]
恩，按照提示解决即可~

**Comment by qsyj** [comment]
@laijiandong  谢谢
