### ISSUE TITLE
build failed with script: ./gradlew assembleDebug

### ISSUE THREAD

**Issue by c1031612246** [alibaba/freeline#97]
![image](https://cloud.githubusercontent.com/assets/13751034/18298005/d4649b00-74e7-11e6-9092-3d559c9008e7.png)
![image](https://cloud.githubusercontent.com/assets/13751034/18298011/e4b555d0-74e7-11e6-807f-a0210de0fec4.png)
![image](https://cloud.githubusercontent.com/assets/13751034/18298015/f0603238-74e7-11e6-90d2-631e819c0209.png)
我这里该怎么填呢

**Comment by lomanyong** [comment]
@c1031612246 你们平时应该有个打包命令，如果你们的flavor是图中的`Defaule`，则如下配置：

````
freeline {
    hack true
    productFlavor "Defaule"
}
````

**Comment by c1031612246** [comment]
@lomanyong 每次运行 python freeline.py后程序就会崩溃，手动打开APP后是修改过的，就是每次都会先崩溃一下 ，在华为荣耀7上运行 python freeline.py命令后app彻底启动不了

**Comment by lomanyong** [comment]
@c1031612246 麻烦贴下crash日志看下吧，以及手机的系统版本是多少的呢？

**Comment by c1031612246** [comment]
@lomanyong 
这个日志的手机是vivox710 anandroid是4.4
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by c1031612246** [comment]
![image](https://cloud.githubusercontent.com/assets/13751034/18300111/d199144e-74f8-11e6-8fe5-496acfa18b9c.png)
![image](https://cloud.githubusercontent.com/assets/13751034/18300112/d3fd6974-74f8-11e6-89e0-9c02f9fc113b.png)

**Comment by lomanyong** [comment]
@c1031612246 暂时先使用5.0+的手机测试吧。我看这个日志，应该是在5.0以下的机型里有兼容性问题，我这里查查看。

**Comment by c1031612246** [comment]
@lomanyong 好的，我先试试其他的机器

**Comment by charvenhe** [comment]
@c1031612246 上面的日志已经在0.6.1解决
