### ISSUE TITLE
get sync ticket failed

### ISSUE THREAD

**Issue by Mayd1e** [alibaba/freeline#977]
[DEBUG] [sync_client] url====http://127.0.0.1:41135/getSyncTicket
[DEBUG] [sync_client] url====http://127.0.0.1:41136/getSyncTicket
[DEBUG] [sync_client] url====http://127.0.0.1:41137/getSyncTicket
[DEBUG] [sync_client] try to connect device 10 times...
[DEBUG] [gradle_check_mobile_change_task] gradle_check_mobile_change_task finish in 130.4s
[DEBUG] [gradle_push_history_inc_task] gradle_push_history_inc_task start to run after waiting 131.7s
[DEBUG] [sync_client] url=============http://127.0.0.1:0/getSyncTicket
[DEBUG] [gradle_push_history_inc_task] gradle_push_history_inc_task finish in 0.0s
[DEBUG] [gradle_sync_task] gradle_sync_task start to run after waiting 131.7s
[DEBUG] [gradle_backup_inc_product_task] gradle_backup_inc_product_task start to run after waiting 131.7s
[DEBUG] [clean_cache_task] clean_cache_task start to run after waiting 131.7s
[DEBUG] [update_stat_task] update_stat_task start to run after waiting 130.4s
[DEBUG] [task_engine] task engine occurs exception, engine will exit.
[DEBUG] [task_engine] it takes task engine 131.71s to execute tasks.
[ERROR] --------------------------------------------------------
[ERROR] Freeline ERROR
[ERROR] --------------------------------------------------------

[ERROR] --------------------------------------------------------
[ERROR] get sync ticket failed
[ERROR] --------------------------------------------------------
[DEBUG] Prepare tasks time: 3.2s
[DEBUG] Task engine running time: 131.7s
[DEBUG] Total time: 135.0s
[DEBUG] --------------------------------------------------------

这是什么问题

**Comment by ThugKd** [comment]
兄弟  你解决了吗？
