### ISSUE TITLE
编译后的APP在Launcher中找不到

### ISSUE THREAD

**Issue by leehong2005** [alibaba/freeline#98]
发现一个问题，Nexus 5上面，在使用freeline编译后，在App列表里面找到我的应用。

之前是没有问题的，就是在昨天使用freeline后就找不到了。我最后把freeline全部去掉，仍然一样。是不是在手机上面启动什么服务之类的？

**Comment by lomanyong** [comment]
@leehong2005 不会吧...freeline没有对这块造成影响的。你可以把app完全卸载了，然后重新安装试试看。

**Comment by leehong2005** [comment]
Sorry，当时试的时候我修改过MainActivity的category，所以从launcher消失了。
不好意思，误会，误会～～
